In [1]:
import ast

In [2]:
import csv

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
import json

In [6]:
cyr = ['а','б','в','г','д','е','ё','ж','з','и','й','к','л','м','н','о','п','р','с','т','у','ф','х','ц','ч','ш','щ','ъ','ы','ь','э','ю','я','ґ','є','ї','ђ','љ','њ','ћ','џ', 'ў','ъ']
lat = ['a','b','v','g','d','e','jo','zh','z','i','j','k','l','m','n','o','p','r','s','t','u','f','h','ts','ch','sh','sczs','','y','','e','ju','ja','g','e','j','dzh','l','n','ch','dzh', 'w','o']
lat2 = ['ch','cz','rz','sz', 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','qu','r','s','t','u','v','w','x', 'y','z','ą', 'ć','ę', 'ł','ń','ó','ś','ź','ż','á','č','ď','é','ě','í','ň','ř', 'š','ť','ú','ů','ý','ž','ä','ľ','ĺ', 'ô', 'ŕ','è']
cyr2 = ['х', 'ч', 'ж', 'ш',  'а','б','ц','д','е','ф','г','х','и','й','к','л','м','н','о','п','кв','р','с','т','у','в','в','кс','ы','з','ом','ч','ен','л','н','у','ш','ж','ж','а','ч','д','э','е','и','н','рж','ш','т','у','у','и','ж','э','л','лл','уо','рр','э']
langss = ['-', 'c', 'c', 'c', 'l', 'l', 'l', 'c', 'l']

# Transliterates text into proper script: 'c' - Cyrillic into Latinic, 'l' - conversely.
def transliterate(sss, l_kind):
  try:
    sss2 = sss.lower()

    if l_kind == 'c':
        l_from, l_to = cyr, lat
    elif l_kind == 'l':
        l_from, l_to = lat2, cyr2
    else:
        return ""
    for c, l in zip(l_from, l_to):
        try:
            sss2 = sss2.replace(c, l)
        except:
            pass
  except:
    pass
  return sss2

In [7]:
# 0.6 changes
phon_corr = {'о':['у'],
             'у':['о'],
             'е':['я', 'и', 'i', 'і'],
             'я':['е'],
             'д':['т'],
             'з':['с', 'ш'],
             'ж':['ш'],
             'к':['г'],
             'т':['д'],
             'с':['з', 'ш'],
             'ш':['ж'],
             'г':['к', 'х'],
             'и':['е'],
             'i': ['е'],
             'і': ['е'],
             'ч': ['ц'],
             'ц': ['ч'],
             'б': ['п'],
             'п': ['б'],
             'х': ['г'],
            }
# 0.5 changes
phon_corr_1 = {'ў':['в'],
               'в':['ў'],
               'й':['ј'],
               'ј':['й'],
               'и':['ј'],
               'ј':['и'],
               'њ':['н'],
               'н':['њ'],
               'љ':['л'],
               'л':['љ'],
               'ш':['щ'],
               'щ':['ш']
              }

# 0.2 changes
phon_corr_2 = {'ё':['е'],
               'е':['ё'],
               'i':['и', 'й'],
               'і': ['и', 'й'],
               'и':['i', 'ї', 'і', 'й'],
               'ї':['и', 'й'],
               'й':['i', 'і', 'ї', 'и'],
              }

# 0.3 changes
phon_corr_3 = {'о':['а'],
               'а':['о', 'я'],
               'я': ['а'],
               'ю': ['у'],
               'у': ['ю'],
               'е':['э'],         
               'ы':['и', 'i', 'і'],
               'и':['ы'],
               'i': ['ы'],
               'і': ['ы']
              }
# 1.2 changes: ћ, ђ and ъ with anything

def next_step_Levenshtein(dists, str1, str2, i, j):
    dists[i, j] = 1000
    v = min(dists[i-1, j-1], dists[i-1, j], dists[i, j-1])

    if str1[i-1] == 'ь' or str2[j-1] == 'ь':
        # "ь" в любой из строк считается за совпадение с чем угодно
        dists[i, j] = v  # Нулевая стоимость
        return
            
    if str1[i-1] == str2[j-1] and dists[i-1, j-1] <= dists[i-1, j] and dists[i-1, j-1] <= dists[i, j-1]:
        # print('+', str1[i-1: i+2], '|', str2[j-1: j+2], v)
        dists[i, j] = v
    else:
        # print('-', str1[i-1: i+2], '|', str2[j-1: j+2], v)
        if i < len(str1) - 1 and j < len(str2) - 1 and (str1[i-1], str1[i]) == (str2[j], str2[j-1]) and dists[i, j] > v + 0.5:
            # print("+")
            dists[i, j] = v + 0.5
        if i < len(str1) - 2 and j < len(str2) - 2 and (str1[i-2], str1[i-1]) == (str2[j-1], str2[j-2]) and dists[i, j] > v + 0.5:
            # print("++")
            dists[i, j] = v + 0.5
        if str1[i-1] in phon_corr.keys() and str2[j-1] in phon_corr[str1[i-1]] and dists[i, j] > v + 0.6:
            dists[i, j] = v + 0.6
        if str1[i-1] in phon_corr_1.keys() and str2[j-1] in phon_corr_1[str1[i-1]] and dists[i, j] > v + 0.5:
            dists[i, j] = v + 0.5
        if str1[i-1] in phon_corr_2.keys() and str2[j-1] in phon_corr_2[str1[i-1]] and dists[i, j] > v + 0.2:
            dists[i, j] = v + 0.2        
        if dists[i, j] > v + 1:
            dists[i, j] = v + 1

def find_path_Levenstein(dists, str1, str2):
    path = [] # [('>', '>', float(dists[len(str1)+1, len(str2)+1]))]
    pos1, pos2 = len(str1), len(str2)
    while pos1 > 0 and pos2 > 0:
        if dists[pos1, pos2] < dists[pos1, pos2+1] and dists[pos1, pos2] < dists[pos1+1, pos2]:
            path.append((str1[pos1-1], str2[pos2-1], float(dists[pos1, pos2])))
            pos1 -= 1
            pos2 -= 1
        elif dists[pos1+1, pos2] <= dists[pos1, pos2] and dists[pos1+1, pos2] <= dists[pos1+1, pos2]:
            path.append(('_', str2[pos2-1], float(dists[pos1, pos2])))
            pos2 -= 1
        else:
            path.append((str1[pos1-1], '_', float(dists[pos1, pos2])))
            pos1 -= 1

    if pos1 != 0:
        while pos1 != 0:
            path.append((str1[pos1-1], '_', float(dists[pos1, 0])))
            pos1 -= 1
    elif pos2 != 0:
        while pos2 != 0:
            path.append(('_', str2[pos2-1], float(dists[0, pos2])))
            pos2 -= 1
    return path

def fast_Levenstein(str1, str2):
    dists = np.zeros((len(str1)+2, len(str2)+2))
    dists[0, :] = np.arange(0, len(str2)+2, 1)
    dists[:, 0] = np.arange(0, len(str1)+2, 1)
    # print(dists)
    for i in range(1, len(str1)+1):
        for j in range(1, len(str2)+1):
            # print(i, j)
            # print(str1[i-1], str2[j-1])
            next_step_Levenshtein(dists, str1, str2, i, j)
            
        dists[i, len(str2)+1] = min(dists[i-1, len(str2)], dists[i-1, len(str2)+1], dists[i, len(str2)]) + 1
        # print(dists)
        
    for j in range(1, len(str2)+1):
        dists[len(str1)+1, j] = min(dists[len(str1), j-1], dists[len(str1), j], dists[len(str1)+1, j-1]) + 1
    dists[len(str1)+1, len(str2)+1] = dists[len(str1), len(str2)]
    # print(dists)
    path = find_path_Levenstein(dists, str1, str2)
    # print(path[::-1])
    return path[::-1][-1][-1]

In [8]:
russian_true = pd.read_csv('complete_morphs/russian_morphs.csv')
answers_true = pd.read_csv('complete_morphs/user_answers_morphs.csv')
ukrainian_true = pd.read_csv('complete_morphs/ukrainian_morphs.csv')
belarus_true = pd.read_csv('complete_morphs/belarus_morphs.csv')
bulgarian_true = pd.read_csv('complete_morphs/bulgarian_morphs.csv')
polish_true = pd.read_csv('complete_morphs/polish_morphs.csv')
czech_true = pd.read_csv('complete_morphs/czech_morphs.csv')
serbian_true = pd.read_csv('complete_morphs/serbian_morphs.csv')
slovak_true = pd.read_csv('complete_morphs/slovak_morphs.csv')
slovene_true = pd.read_csv('complete_morphs/slovene_morphs.csv')

In [9]:
ukrainian_ans = answers_true.loc[answers_true['parallel_lang'] == 'Ukranian']
belarus_ans = answers_true.loc[answers_true['parallel_lang'] == 'Belarussian']
czech_ans = answers_true.loc[answers_true['parallel_lang'] == 'Czech']
polish_ans = answers_true.loc[answers_true['parallel_lang'] == 'Polish']
bulgarian_ans = answers_true.loc[answers_true['parallel_lang'] == 'Bulgarian']
serbian_ans = answers_true.loc[answers_true['parallel_lang'] == 'Serbian']
slovak_ans = answers_true.loc[answers_true['parallel_lang'] == 'Slovak']
slovene_ans = answers_true.loc[answers_true['parallel_lang'] == 'Slovene']
nopar_ans = answers_true.loc[answers_true['parallel_lang'] == 'No Parallel Text']

In [10]:
num_type = {}

for _, row in nopar_ans.iterrows():
    test_id = row['test_id']
    answer_no = row['answer_no']
    correctness = row['correctness']
    code = (int(f'{test_id}{answer_no}'))
    if code not in num_type.keys():
        num_type[code] = {}
    if correctness not in num_type[code].keys():
        num_type[code][correctness] = 1
    else:
        num_type[code][correctness] +=1
for key in num_type:    
    sum_ans = 0
    for num in num_type[key]:
        sum_ans += num_type[key][num]
    if 'incorr' in num_type[key]:
        num_type[key]['mistakes'] = num_type[key]['incorr'] / sum_ans
    else:
        num_type[key]['mistakes'] = 0

for key in num_type:
    num_type[key] = dict(sorted(num_type[key].items(), key=lambda item: item[1], reverse=True))

num_type

{10: {'corr': 19, 'pcorr': 18, 'incorr': 7, 'mistakes': 0.1590909090909091},
 11: {'pcorr': 30, 'corr': 10, 'incorr': 4, 'mistakes': 0.09090909090909091},
 12: {'pcorr': 29, 'corr': 12, 'incorr': 3, 'mistakes': 0.06818181818181818},
 13: {'corr': 35, 'pcorr': 6, 'incorr': 3, 'mistakes': 0.06818181818181818},
 14: {'incorr': 23, 'pcorr': 17, 'corr': 4, 'mistakes': 0.5227272727272727},
 15: {'corr': 24, 'pcorr': 10, 'incorr': 10, 'mistakes': 0.22727272727272727},
 16: {'corr': 34, 'pcorr': 5, 'incorr': 5, 'mistakes': 0.11363636363636363},
 17: {'pcorr': 27, 'corr': 16, 'incorr': 1, 'mistakes': 0.022727272727272728},
 18: {'pcorr': 24, 'incorr': 13, 'corr': 7, 'mistakes': 0.29545454545454547},
 19: {'pcorr': 30, 'corr': 10, 'incorr': 4, 'mistakes': 0.09090909090909091},
 110: {'corr': 26, 'pcorr': 16, 'incorr': 2, 'mistakes': 0.045454545454545456},
 111: {'pcorr': 34, 'incorr': 5, 'corr': 5, 'mistakes': 0.11363636363636363},
 112: {'corr': 34, 'pcorr': 7, 'incorr': 3, 'mistakes': 0.06818181818181818},
 113: {'incorr': 17, 'pcorr': 17, 'corr': 10, 'mistakes': 0.38636363636363635},
 114: {'pcorr': 25, 'corr': 12, 'incorr': 7, 'mistakes': 0.1590909090909091},
 115: {'pcorr': 26, 'corr': 11, 'incorr': 7, 'mistakes': 0.1590909090909091},
 116: {'pcorr': 23, 'incorr': 12, 'corr': 9, 'mistakes': 0.2727272727272727},
 117: {'pcorr': 32, 'corr': 10, 'incorr': 2, 'mistakes': 0.045454545454545456},
 118: {'pcorr': 26, 'incorr': 10, 'corr': 8, 'mistakes': 0.22727272727272727},
 119: {'pcorr': 19, 'corr': 13, 'incorr': 12, 'mistakes': 0.2727272727272727},
 120: {'pcorr': 24, 'incorr': 13, 'corr': 7, 'mistakes': 0.29545454545454547},
 121: {'pcorr': 23, 'incorr': 11, 'corr': 10, 'mistakes': 0.25},
 122: {'pcorr': 33, 'corr': 9, 'incorr': 2, 'mistakes': 0.045454545454545456},
 123: {'pcorr': 25, 'corr': 13, 'incorr': 6, 'mistakes': 0.13636363636363635},
 124: {'pcorr': 21, 'incorr': 16, 'corr': 7, 'mistakes': 0.36363636363636365},
 125: {'corr': 34, 'incorr': 9, 'pcorr': 1, 'mistakes': 0.20454545454545456},
 126: {'pcorr': 18, 'incorr': 15, 'corr': 11, 'mistakes': 0.3409090909090909},
 127: {'incorr': 27, 'pcorr': 9, 'corr': 8, 'mistakes': 0.6136363636363636},
 128: {'corr': 40, 'pcorr': 2, 'incorr': 2, 'mistakes': 0.045454545454545456},
 129: {'incorr': 20, 'pcorr': 18, 'corr': 6, 'mistakes': 0.45454545454545453},
 130: {'incorr': 20, 'pcorr': 18, 'corr': 6, 'mistakes': 0.45454545454545453},
 131: {'pcorr': 20, 'incorr': 17, 'corr': 7, 'mistakes': 0.38636363636363635},
 132: {'pcorr': 31, 'corr': 8, 'incorr': 5, 'mistakes': 0.11363636363636363},
 133: {'corr': 27, 'pcorr': 12, 'incorr': 5, 'mistakes': 0.11363636363636363},
 134: {'corr': 17, 'incorr': 14, 'pcorr': 13, 'mistakes': 0.3181818181818182},
 135: {'incorr': 17, 'pcorr': 15, 'corr': 12, 'mistakes': 0.38636363636363635},
 136: {'pcorr': 25, 'incorr': 13, 'corr': 6, 'mistakes': 0.29545454545454547},
 137: {'pcorr': 28, 'incorr': 8, 'corr': 8, 'mistakes': 0.18181818181818182},
 138: {'corr': 21, 'incorr': 16, 'pcorr': 7, 'mistakes': 0.36363636363636365},
 139: {'incorr': 20, 'pcorr': 17, 'corr': 7, 'mistakes': 0.45454545454545453},
 140: {'corr': 32, 'pcorr': 8, 'incorr': 4, 'mistakes': 0.09090909090909091},
 141: {'corr': 32, 'pcorr': 10, 'incorr': 2, 'mistakes': 0.045454545454545456},
 142: {'corr': 26, 'pcorr': 9, 'incorr': 9, 'mistakes': 0.20454545454545456},
 20: {'pcorr': 25, 'incorr': 13, 'corr': 8, 'mistakes': 0.2826086956521739},
 21: {'corr': 37, 'pcorr': 8, 'incorr': 1, 'mistakes': 0.021739130434782608},
 22: {'pcorr': 40, 'corr': 5, 'incorr': 1, 'mistakes': 0.021739130434782608},
 23: {'pcorr': 34, 'incorr': 7, 'corr': 5, 'mistakes': 0.15217391304347827},
 24: {'pcorr': 37, 'corr': 8, 'incorr': 1, 'mistakes': 0.021739130434782608},
 25: {'pcorr': 27, 'incorr': 14, 'corr': 5, 'mistakes': 0.30434782608695654},
 26: {'pcorr': 28, 'corr': 14, 'incorr': 4, 'mistakes': 0.08695652173913043},
 27: {'pcorr': 36, 'corr': 6, 'incorr': 4, 'mistakes': 0.08695652173913043},
 28: {'pcorr': 22, 'corr': 21, 'incorr': 3, 'mistakes': 0.06521739130434782},
 29: {'pcorr': 36, 'corr': 7, 'incorr': 3, 'mistakes': 0.06521739130434782},
 210: {'corr': 29, 'pcorr': 11, 'incorr': 6, 'mistakes': 0.13043478260869565},
 211: {'pcorr': 19, 'incorr': 14, 'corr': 13, 'mistakes': 0.30434782608695654},
 212: {'pcorr': 30, 'incorr': 10, 'corr': 6, 'mistakes': 0.21739130434782608},
 213: {'pcorr': 28, 'incorr': 10, 'corr': 8, 'mistakes': 0.21739130434782608},
 214: {'corr': 21, 'pcorr': 13, 'incorr': 12, 'mistakes': 0.2608695652173913},
 215: {'pcorr': 32, 'incorr': 8, 'corr': 6, 'mistakes': 0.17391304347826086},
 216: {'pcorr': 36, 'corr': 8, 'incorr': 2, 'mistakes': 0.043478260869565216},
 217: {'pcorr': 22, 'corr': 19, 'incorr': 5, 'mistakes': 0.10869565217391304},
 218: {'pcorr': 33, 'incorr': 10, 'corr': 3, 'mistakes': 0.21739130434782608},
 219: {'pcorr': 30, 'incorr': 11, 'corr': 5, 'mistakes': 0.2391304347826087},
 220: {'corr': 28, 'pcorr': 12, 'incorr': 6, 'mistakes': 0.13043478260869565},
 221: {'pcorr': 36, 'corr': 6, 'incorr': 4, 'mistakes': 0.08695652173913043},
 222: {'corr': 28, 'pcorr': 12, 'incorr': 6, 'mistakes': 0.13043478260869565},
 223: {'corr': 43, 'incorr': 2, 'pcorr': 1, 'mistakes': 0.043478260869565216},
 224: {'corr': 26, 'incorr': 11, 'pcorr': 9, 'mistakes': 0.2391304347826087},
 225: {'corr': 42, 'incorr': 2, 'pcorr': 2, 'mistakes': 0.043478260869565216},
 226: {'pcorr': 22, 'corr': 22, 'incorr': 2, 'mistakes': 0.043478260869565216},
 227: {'pcorr': 36, 'corr': 8, 'incorr': 2, 'mistakes': 0.043478260869565216},
 228: {'incorr': 20, 'pcorr': 17, 'corr': 9, 'mistakes': 0.43478260869565216},
 229: {'pcorr': 28, 'incorr': 11, 'corr': 7, 'mistakes': 0.2391304347826087},
 230: {'pcorr': 22, 'incorr': 16, 'corr': 8, 'mistakes': 0.34782608695652173},
 231: {'pcorr': 29, 'corr': 9, 'incorr': 8, 'mistakes': 0.17391304347826086},
 232: {'corr': 29, 'pcorr': 11, 'incorr': 6, 'mistakes': 0.13043478260869565},
 233: {'corr': 33, 'pcorr': 7, 'incorr': 6, 'mistakes': 0.13043478260869565},
 234: {'corr': 41, 'pcorr': 4, 'incorr': 1, 'mistakes': 0.021739130434782608},
 235: {'pcorr': 30, 'corr': 11, 'incorr': 5, 'mistakes': 0.10869565217391304},
 236: {'pcorr': 29, 'corr': 9, 'incorr': 8, 'mistakes': 0.17391304347826086},
 237: {'pcorr': 24, 'incorr': 15, 'corr': 7, 'mistakes': 0.32608695652173914},
 238: {'corr': 28, 'pcorr': 16, 'incorr': 2, 'mistakes': 0.043478260869565216},
 239: {'pcorr': 36, 'corr': 6, 'incorr': 4, 'mistakes': 0.08695652173913043},
 30: {'pcorr': 22, 'incorr': 12, 'corr': 3, 'mistakes': 0.32432432432432434},
 31: {'pcorr': 22, 'incorr': 12, 'corr': 3, 'mistakes': 0.32432432432432434},
 32: {'pcorr': 34, 'incorr': 3, 'mistakes': 0.08108108108108109},
 33: {'pcorr': 35, 'corr': 1, 'incorr': 1, 'mistakes': 0.02702702702702703},
 34: {'incorr': 16, 'corr': 13, 'pcorr': 8, 'mistakes': 0.43243243243243246},
 35: {'corr': 33, 'pcorr': 4, 'mistakes': 0},
 36: {'pcorr': 23, 'corr': 10, 'incorr': 4, 'mistakes': 0.10810810810810811},
 37: {'pcorr': 33, 'incorr': 3, 'corr': 1, 'mistakes': 0.08108108108108109},
 38: {'corr': 18, 'pcorr': 12, 'incorr': 7, 'mistakes': 0.1891891891891892},
 39: {'pcorr': 25, 'corr': 8, 'incorr': 4, 'mistakes': 0.10810810810810811},
 310: {'corr': 26, 'pcorr': 8, 'incorr': 3, 'mistakes': 0.08108108108108109},
 311: {'corr': 21, 'pcorr': 13, 'incorr': 3, 'mistakes': 0.08108108108108109},
 312: {'pcorr': 24, 'corr': 10, 'incorr': 3, 'mistakes': 0.08108108108108109},
 313: {'pcorr': 23, 'incorr': 9, 'corr': 5, 'mistakes': 0.24324324324324326},
 314: {'pcorr': 29, 'corr': 5, 'incorr': 3, 'mistakes': 0.08108108108108109},
 315: {'corr': 20, 'incorr': 11, 'pcorr': 6, 'mistakes': 0.2972972972972973},
 316: {'pcorr': 19, 'corr': 14, 'incorr': 4, 'mistakes': 0.10810810810810811},
 317: {'incorr': 20, 'pcorr': 11, 'corr': 6, 'mistakes': 0.5405405405405406},
 318: {'pcorr': 16, 'corr': 15, 'incorr': 6, 'mistakes': 0.16216216216216217},
 319: {'pcorr': 20, 'incorr': 10, 'corr': 7, 'mistakes': 0.2702702702702703},
 320: {'corr': 23, 'pcorr': 10, 'incorr': 4, 'mistakes': 0.10810810810810811},
 321: {'corr': 25, 'pcorr': 10, 'incorr': 2, 'mistakes': 0.05405405405405406},
 322: {'pcorr': 21, 'incorr': 10, 'corr': 6, 'mistakes': 0.2702702702702703},
 323: {'pcorr': 19, 'corr': 11, 'incorr': 7, 'mistakes': 0.1891891891891892},
 324: {'pcorr': 24, 'incorr': 8, 'corr': 5, 'mistakes': 0.21621621621621623},
 325: {'corr': 21, 'pcorr': 13, 'incorr': 3, 'mistakes': 0.08108108108108109},
 326: {'pcorr': 26, 'corr': 10, 'incorr': 1, 'mistakes': 0.02702702702702703},
 327: {'corr': 15, 'incorr': 11, 'pcorr': 11, 'mistakes': 0.2972972972972973},
 328: {'incorr': 18, 'pcorr': 17, 'corr': 2, 'mistakes': 0.4864864864864865},
 329: {'corr': 16, 'pcorr': 15, 'incorr': 6, 'mistakes': 0.16216216216216217},
 330: {'corr': 23, 'incorr': 9, 'pcorr': 5, 'mistakes': 0.24324324324324326},
 331: {'pcorr': 20, 'incorr': 13, 'corr': 4, 'mistakes': 0.35135135135135137},
 332: {'corr': 25, 'pcorr': 10, 'incorr': 2, 'mistakes': 0.05405405405405406},
 333: {'corr': 34, 'pcorr': 3, 'mistakes': 0},
 334: {'corr': 35, 'pcorr': 2, 'mistakes': 0},
 40: {'pcorr': 43, 'corr': 21, 'incorr': 2, 'mistakes': 0.030303030303030304},
 41: {'pcorr': 52, 'corr': 10, 'incorr': 4, 'mistakes': 0.06060606060606061},
 42: {'pcorr': 45, 'incorr': 16, 'corr': 5, 'mistakes': 0.24242424242424243},
 43: {'pcorr': 54, 'incorr': 7, 'corr': 5, 'mistakes': 0.10606060606060606},
 44: {'corr': 52, 'incorr': 9, 'pcorr': 5, 'mistakes': 0.13636363636363635},
 45: {'pcorr': 49, 'incorr': 9, 'corr': 8, 'mistakes': 0.13636363636363635},
 46: {'pcorr': 33, 'incorr': 29, 'corr': 4, 'mistakes': 0.4393939393939394},
 47: {'pcorr': 31, 'incorr': 26, 'corr': 9, 'mistakes': 0.3939393939393939},
 48: {'corr': 34, 'pcorr': 25, 'incorr': 7, 'mistakes': 0.10606060606060606},
 49: {'incorr': 24, 'pcorr': 22, 'corr': 20, 'mistakes': 0.36363636363636365},
 410: {'pcorr': 38, 'corr': 15, 'incorr': 13, 'mistakes': 0.19696969696969696},
 411: {'corr': 46, 'incorr': 18, 'pcorr': 2, 'mistakes': 0.2727272727272727},
 412: {'pcorr': 28, 'incorr': 25, 'corr': 13, 'mistakes': 0.3787878787878788},
 413: {'corr': 54, 'pcorr': 7, 'incorr': 5, 'mistakes': 0.07575757575757576},
 414: {'pcorr': 40, 'incorr': 17, 'corr': 9, 'mistakes': 0.25757575757575757},
 415: {'pcorr': 60, 'corr': 4, 'incorr': 2, 'mistakes': 0.030303030303030304},
 416: {'corr': 45, 'incorr': 14, 'pcorr': 7, 'mistakes': 0.21212121212121213},
 417: {'corr': 58, 'pcorr': 5, 'incorr': 3, 'mistakes': 0.045454545454545456},
 418: {'pcorr': 56, 'corr': 8, 'incorr': 2, 'mistakes': 0.030303030303030304},
 419: {'corr': 42, 'pcorr': 21, 'incorr': 3, 'mistakes': 0.045454545454545456},
 420: {'incorr': 29, 'corr': 21, 'pcorr': 16, 'mistakes': 0.4393939393939394},
 421: {'pcorr': 42, 'incorr': 18, 'corr': 6, 'mistakes': 0.2727272727272727},
 422: {'corr': 41, 'pcorr': 22, 'incorr': 3, 'mistakes': 0.045454545454545456},
 423: {'corr': 54, 'pcorr': 7, 'incorr': 5, 'mistakes': 0.07575757575757576},
 424: {'corr': 42, 'incorr': 19, 'pcorr': 5, 'mistakes': 0.2878787878787879},
 425: {'pcorr': 36, 'corr': 18, 'incorr': 12, 'mistakes': 0.18181818181818182},
 426: {'pcorr': 41, 'corr': 16, 'incorr': 9, 'mistakes': 0.13636363636363635},
 427: {'pcorr': 44, 'incorr': 14, 'corr': 8, 'mistakes': 0.21212121212121213},
 428: {'pcorr': 40, 'corr': 20, 'incorr': 6, 'mistakes': 0.09090909090909091},
 429: {'corr': 63, 'incorr': 3, 'mistakes': 0.045454545454545456},
 430: {'pcorr': 59, 'corr': 5, 'incorr': 2, 'mistakes': 0.030303030303030304},
 431: {'corr': 34, 'pcorr': 25, 'incorr': 7, 'mistakes': 0.10606060606060606},
 432: {'pcorr': 47, 'corr': 14, 'incorr': 5, 'mistakes': 0.07575757575757576},
 433: {'pcorr': 53, 'corr': 11, 'incorr': 2, 'mistakes': 0.030303030303030304},
 434: {'corr': 56, 'incorr': 8, 'pcorr': 2, 'mistakes': 0.12121212121212122},
 435: {'corr': 31, 'incorr': 23, 'pcorr': 12, 'mistakes': 0.3484848484848485},
 436: {'pcorr': 45, 'corr': 15, 'incorr': 6, 'mistakes': 0.09090909090909091},
 437: {'corr': 37, 'incorr': 16, 'pcorr': 13, 'mistakes': 0.24242424242424243},
 438: {'pcorr': 40, 'corr': 23, 'incorr': 3, 'mistakes': 0.045454545454545456},
 439: {'corr': 33, 'pcorr': 27, 'incorr': 6, 'mistakes': 0.09090909090909091},
 440: {'corr': 49, 'incorr': 13, 'pcorr': 4, 'mistakes': 0.19696969696969696},
 441: {'pcorr': 41, 'corr': 18, 'incorr': 7, 'mistakes': 0.10606060606060606},
 442: {'incorr': 38, 'corr': 17, 'pcorr': 11, 'mistakes': 0.5757575757575758},
 443: {'pcorr': 31, 'corr': 30, 'incorr': 5, 'mistakes': 0.07575757575757576},
 50: {'corr': 41, 'pcorr': 6, 'mistakes': 0},
 51: {'corr': 47, 'mistakes': 0},
 52: {'pcorr': 40, 'corr': 7, 'mistakes': 0},
 53: {'corr': 44, 'pcorr': 2, 'incorr': 1, 'mistakes': 0.02127659574468085},
 54: {'corr': 46, 'pcorr': 1, 'mistakes': 0},
 55: {'corr': 40, 'incorr': 4, 'pcorr': 3, 'mistakes': 0.0851063829787234},
 56: {'corr': 46, 'pcorr': 1, 'mistakes': 0},
 57: {'corr': 41, 'pcorr': 6, 'mistakes': 0},
 58: {'pcorr': 23, 'incorr': 20, 'corr': 4, 'mistakes': 0.425531914893617},
 59: {'pcorr': 39, 'corr': 6, 'incorr': 2, 'mistakes': 0.0425531914893617},
 510: {'corr': 24, 'pcorr': 13, 'incorr': 10, 'mistakes': 0.2127659574468085},
 511: {'pcorr': 35, 'corr': 8, 'incorr': 4, 'mistakes': 0.0851063829787234},
 512: {'pcorr': 33, 'incorr': 10, 'corr': 4, 'mistakes': 0.2127659574468085},
 513: {'pcorr': 24, 'incorr': 12, 'corr': 11, 'mistakes': 0.2553191489361702},
 514: {'corr': 39, 'incorr': 7, 'pcorr': 1, 'mistakes': 0.14893617021276595},
 515: {'corr': 39, 'pcorr': 5, 'incorr': 3, 'mistakes': 0.06382978723404255},
 516: {'corr': 36, 'pcorr': 8, 'incorr': 3, 'mistakes': 0.06382978723404255},
 517: {'pcorr': 32, 'corr': 12, 'incorr': 3, 'mistakes': 0.06382978723404255},
 518: {'pcorr': 43, 'corr': 3, 'incorr': 1, 'mistakes': 0.02127659574468085},
 519: {'corr': 43, 'pcorr': 2, 'incorr': 2, 'mistakes': 0.0425531914893617},
 520: {'incorr': 28, 'pcorr': 13, 'corr': 6, 'mistakes': 0.5957446808510638},
 521: {'corr': 41, 'incorr': 4, 'pcorr': 2, 'mistakes': 0.0851063829787234},
 522: {'corr': 38, 'pcorr': 7, 'incorr': 2, 'mistakes': 0.0425531914893617},
 523: {'incorr': 23, 'pcorr': 15, 'corr': 9, 'mistakes': 0.48936170212765956},
 524: {'incorr': 19, 'corr': 17, 'pcorr': 11, 'mistakes': 0.40425531914893614},
 525: {'incorr': 21, 'corr': 20, 'pcorr': 6, 'mistakes': 0.44680851063829785},
 526: {'corr': 33, 'incorr': 8, 'pcorr': 6, 'mistakes': 0.1702127659574468},
 527: {'corr': 30, 'incorr': 9, 'pcorr': 8, 'mistakes': 0.19148936170212766},
 528: {'corr': 39, 'pcorr': 4, 'incorr': 4, 'mistakes': 0.0851063829787234},
 529: {'pcorr': 23, 'incorr': 15, 'corr': 9, 'mistakes': 0.3191489361702128},
 530: {'corr': 18, 'incorr': 17, 'pcorr': 12, 'mistakes': 0.3617021276595745},
 531: {'pcorr': 23, 'corr': 20, 'incorr': 4, 'mistakes': 0.0851063829787234},
 532: {'corr': 43, 'incorr': 3, 'pcorr': 1, 'mistakes': 0.06382978723404255},
 533: {'pcorr': 29, 'corr': 15, 'incorr': 3, 'mistakes': 0.06382978723404255},
 534: {'corr': 21, 'pcorr': 19, 'incorr': 7, 'mistakes': 0.14893617021276595},
 535: {'corr': 33, 'pcorr': 13, 'incorr': 1, 'mistakes': 0.02127659574468085},
 536: {'corr': 33, 'pcorr': 11, 'incorr': 3, 'mistakes': 0.06382978723404255},
 60: {'corr': 27, 'pcorr': 16, 'incorr': 1, 'mistakes': 0.022727272727272728},
 61: {'pcorr': 29, 'corr': 11, 'incorr': 4, 'mistakes': 0.09090909090909091},
 62: {'pcorr': 28, 'corr': 12, 'incorr': 4, 'mistakes': 0.09090909090909091},
 63: {'pcorr': 23, 'corr': 21, 'mistakes': 0},
 64: {'corr': 34, 'pcorr': 6, 'incorr': 4, 'mistakes': 0.09090909090909091},
 65: {'pcorr': 26, 'corr': 15, 'incorr': 3, 'mistakes': 0.06818181818181818},
 66: {'pcorr': 28, 'corr': 12, 'incorr': 4, 'mistakes': 0.09090909090909091},
 67: {'pcorr': 26, 'corr': 10, 'incorr': 8, 'mistakes': 0.18181818181818182},
 68: {'corr': 37, 'pcorr': 4, 'incorr': 3, 'mistakes': 0.06818181818181818},
 69: {'corr': 31, 'pcorr': 12, 'incorr': 1, 'mistakes': 0.022727272727272728},
 610: {'corr': 27, 'pcorr': 16, 'incorr': 1, 'mistakes': 0.022727272727272728},
 611: {'pcorr': 28, 'corr': 14, 'incorr': 2, 'mistakes': 0.045454545454545456},
 612: {'corr': 18, 'pcorr': 15, 'incorr': 11, 'mistakes': 0.25},
 613: {'pcorr': 25, 'corr': 14, 'incorr': 5, 'mistakes': 0.11363636363636363},
 614: {'incorr': 28, 'corr': 12, 'pcorr': 4, 'mistakes': 0.6363636363636364},
 615: {'corr': 28, 'pcorr': 10, 'incorr': 6, 'mistakes': 0.13636363636363635},
 616: {'pcorr': 24, 'corr': 17, 'incorr': 3, 'mistakes': 0.06818181818181818},
 617: {'pcorr': 21, 'corr': 20, 'incorr': 3, 'mistakes': 0.06818181818181818},
 618: {'corr': 38, 'incorr': 5, 'pcorr': 1, 'mistakes': 0.11363636363636363},
 619: {'corr': 37, 'pcorr': 5, 'incorr': 2, 'mistakes': 0.045454545454545456},
 620: {'corr': 28, 'pcorr': 11, 'incorr': 5, 'mistakes': 0.11363636363636363},
 621: {'pcorr': 29, 'corr': 11, 'incorr': 4, 'mistakes': 0.09090909090909091},
 622: {'corr': 30, 'incorr': 7, 'pcorr': 7, 'mistakes': 0.1590909090909091},
 623: {'corr': 19, 'pcorr': 17, 'incorr': 8, 'mistakes': 0.18181818181818182},
 624: {'corr': 33, 'incorr': 6, 'pcorr': 5, 'mistakes': 0.13636363636363635},
 625: {'pcorr': 27, 'corr': 15, 'incorr': 2, 'mistakes': 0.045454545454545456},
 626: {'pcorr': 25, 'corr': 11, 'incorr': 8, 'mistakes': 0.18181818181818182},
 627: {'pcorr': 20, 'corr': 20, 'incorr': 4, 'mistakes': 0.09090909090909091},
 628: {'corr': 23, 'pcorr': 17, 'incorr': 4, 'mistakes': 0.09090909090909091},
 629: {'corr': 38, 'incorr': 6, 'mistakes': 0.13636363636363635},
 630: {'corr': 40, 'incorr': 3, 'pcorr': 1, 'mistakes': 0.06818181818181818},
 631: {'corr': 35, 'incorr': 6, 'pcorr': 3, 'mistakes': 0.13636363636363635},
 632: {'pcorr': 20, 'corr': 15, 'incorr': 9, 'mistakes': 0.20454545454545456},
 633: {'corr': 22, 'incorr': 13, 'pcorr': 9, 'mistakes': 0.29545454545454547},
 634: {'corr': 29, 'incorr': 13, 'pcorr': 2, 'mistakes': 0.29545454545454547}}

In [11]:
def cognate_searcher(answer_set, russian_true, language):
    result_dict = {}
    for _, row in answer_set.iterrows():
        test_id = row['test_id']
        answer_no = row['answer_no']
        user_answer = str(row['answer']).lower().strip()
        correctness = row['correctness']
        code_ans = (user_answer, correctness)
        
        correct_row = russian_true[
            (russian_true['test_id'] == test_id) & 
            (russian_true['answer_no'] == answer_no)
        ]
        original_row = language[
            (language['test_id'] == test_id) & 
            (language['answer_no'] == answer_no)
        ]
        
        if not correct_row.empty:
            correct_answer = str(correct_row.iloc[0]['answer']).strip()
            original_answer = str(original_row.iloc[0]['answer']).strip()
            code = (int(f'{test_id}{answer_no}'), correct_answer, original_answer)
            if code not in result_dict.keys():
                result_dict[code] = {}
        if code_ans not in result_dict[code].keys():
            result_dict[code][code_ans] = 1
        else:
            result_dict[code][code_ans] +=1
    
    for key in result_dict:
        result_dict[key] = dict(sorted(result_dict[key].items(), key=lambda item: item[1], reverse=True))

    return result_dict

In [12]:
ukr_cognates = cognate_searcher(ukrainian_ans, russian_true, ukrainian_true)
ukr_cognates

{(10, 'повернулся', 'повернувся'): {('повернулся', 'corr'): 35,
  ('развернулся', 'corr'): 1,
  ('вернулся', 'pcorr'): 1,
  ('пошёл', 'pcorr'): 1},
 (11, 'ступеням', 'сходинок'): {('ступенькам', 'corr'): 6,
  ('nan', 'incorr'): 5,
  ('ступеням', 'corr'): 4,
  ('сходням', 'corr'): 4,
  ('лестнице', 'corr'): 3,
  ('сходинок', 'incorr'): 2,
  ('выходу', 'pcorr'): 2,
  ('сходне', 'pcorr'): 1,
  ('сходу', 'incorr'): 1,
  ('перекрестку', 'pcorr'): 1,
  ('лестницам', 'corr'): 1,
  ('воротам', 'pcorr'): 1,
  ('сходке', 'pcorr'): 1,
  ('колоннам', 'pcorr'): 1,
  ('приступку', 'pcorr'): 1,
  ('входу', 'pcorr'): 1,
  ('середине', 'pcorr'): 1,
  ('дорожкам', 'pcorr'): 1,
  ('пркступникам', 'incorr'): 1},
 (12, 'шашек', 'шашок'): {('шашек', 'corr'): 14,
  ('nan', 'incorr'): 7,
  ('досок', 'pcorr'): 5,
  ('плиток', 'corr'): 5,
  ('шашок', 'corr'): 2,
  ('цветов', 'pcorr'): 1,
  ('плит', 'corr'): 1,
  ('каамней', 'pcorr'): 1,
  ('шапок', 'incorr'): 1,
  ('узоров', 'corr'): 1},
 (13, 'спиною', 'спиною'): {('спиной', 'corr'): 30, ('спиною', 'corr'): 8},
 (14, 'финики', 'фініки'): {('финики', 'corr'): 31,
  ('nan', 'incorr'): 3,
  ('финикийцы', 'incorr'): 1,
  ('камни', 'pcorr'): 1,
  ('финик', 'corr'): 1,
  ('думая', 'incorr'): 1},
 (15, 'чудо', 'диво'): {('чудо', 'corr'): 22,
  ('nan', 'incorr'): 4,
  ('диво', 'corr'): 4,
  ('зрелище', 'pcorr'): 2,
  ('удивительное событие', 'pcorr'): 1,
  ('воочию', 'incorr'): 1,
  ('диво/чудо', 'corr'): 1,
  ('воочию чудо', 'corr'): 1,
  ('воочии', 'incorr'): 1,
  ('невиданное чудо', 'corr'): 1},
 (16, 'вырвался', 'вирвався'): {('вырвался', 'corr'): 33,
  ('выбрался', 'pcorr'): 2,
  ('nan', 'incorr'): 1,
  ('вырываясь', 'pcorr'): 1,
  ('вырывается', 'corr'): 1},
 (17, 'веревки', 'мотузки'): {('веревки', 'corr'): 12,
  ('верёвки', 'corr'): 5,
  ('nan', 'incorr'): 5,
  ('одежду', 'pcorr'): 3,
  ('доспехи', 'pcorr'): 2,
  ('наручники', 'pcorr'): 2,
  ('повязки', 'pcorr'): 2,
  ('шанель', 'pcorr'): 1,
  ('мотузки', 'incorr'): 1,
  ('кандалы', 'pcorr'): 1,
  ('плащ', 'pcorr'): 1,
  ('мутузку', 'incorr'): 1,
  ('лохмотья', 'pcorr'): 1,
  ('оковы', 'pcorr'): 1},
 (18, 'допросе', 'допиті'): {('допросе', 'corr'): 8,
  ('nan', 'incorr'): 8,
  ('допросах', 'corr'): 7,
  ('пытках', 'pcorr'): 3,
  ('сгибах', 'pcorr'): 2,
  ('локтях', 'pcorr'): 2,
  ('плечах', 'incorr'): 1,
  ('добитых', 'incorr'): 1,
  ('запястьях', 'pcorr'): 1,
  ('кистях', 'pcorr'): 1,
  ('суставах', 'pcorr'): 1,
  ('до костей', 'pcorr'): 1,
  ('руках', 'pcorr'): 1,
  ('дабитых', 'incorr'): 1},
 (19, 'сумасшедшей', 'божевільною'): {('nan', 'incorr'): 9,
  ('божественной', 'pcorr'): 7,
  ('сумасшедшей', 'corr'): 5,
  ('блаженной', 'corr'): 3,
  ('глупой', 'corr'): 2,
  ('сумашедшей', 'corr'): 2,
  ('сумасшедшею', 'corr'): 1,
  ('богаславленной', 'pcorr'): 1,
  ('бешеной', 'pcorr'): 1,
  ('блаженною', 'corr'): 1,
  ('божевольной', 'incorr'): 1,
  ('юродивой', 'corr'): 1,
  ('сумашедшой', 'corr'): 1,
  ('болезненной', 'pcorr'): 1,
  ('дурацкой', 'corr'): 1,
  ('безумной', 'corr'): 1},
 (110, 'знал', 'знав'): {('знал', 'corr'): 35,
  ('зная', 'pcorr'): 2,
  ('узнав', 'pcorr'): 1},
 (111, 'ступеням', 'сходинок'): {('ступеням', 'corr'): 8,
  ('nan', 'incorr'): 6,
  ('сходням', 'corr'): 3,
  ('ступенькам', 'corr'): 3,
  ('воротам', 'pcorr'): 2,
  ('лестницам', 'corr'): 2,
  ('выходам', 'pcorr'): 2,
  ('тропам', 'pcorr'): 2,
  ('сходинок', 'incorr'): 1,
  ('помостам', 'pcorr'): 1,
  ('сходам', 'corr'): 1,
  ('перекрёсткам', 'pcorr'): 1,
  ('колоннам', 'pcorr'): 1,
  ('приступкам', 'incorr'): 1,
  ('ступенек', 'corr'): 1,
  ('ступеней', 'corr'): 1,
  ('тропинкам', 'pcorr'): 1,
  ('преступникам', 'incorr'): 1},
 (112, 'дорогу', 'дорогу'): {('дорогу', 'corr'): 36,
  ('заход', 'incorr'): 1,
  ('мероприятие', 'incorr'): 1},
 (113, 'осужденных', 'засуджених'): {('осужденных', 'corr'): 14,
  ('осуждённых', 'corr'): 5,
  ('nan', 'incorr'): 4,
  ('видеть', 'incorr'): 2,
  ('преследователей', 'pcorr'): 2,
  ('видеть осужденных', 'corr'): 2,
  ('подсудимых', 'corr'): 1,
  ('казни осужденных', 'pcorr'): 1,
  ('засуженных', 'pcorr'): 1,
  ('казни', 'pcorr'): 1,
  ('других осужденных', 'corr'): 1,
  ('значит осужденных', 'corr'): 1,
  ('осужденный', 'corr'): 1,
  ('байни осужденных', 'corr'): 1,
  ('виновных', 'corr'): 1},
 (114, 'глашатаев', 'глашатаїв'): {('глашатаев', 'corr'): 28,
  ('глашатых', 'corr'): 5,
  ('глашатая', 'corr'): 2,
  ('вренных', 'incorr'): 1,
  ('хулиганов', 'pcorr'): 1,
  ('глашатаи', 'corr'): 1},
 (115, 'греческом', 'грецькою'): {('греческом', 'corr'): 28,
  ('греческих', 'corr'): 5,
  ('грецком', 'pcorr'): 2,
  ('грецском', 'corr'): 1,
  ('nan', 'incorr'): 1,
  ('греческом наречии', 'corr'): 1},
 (116, 'труба', 'сурма'): {('nan', 'incorr'): 10,
  ('труба', 'corr'): 6,
  ('сурьма', 'incorr'): 6,
  ('сурма', 'incorr'): 5,
  ('толпа', 'pcorr'): 2,
  ('ржание', 'pcorr'): 1,
  ('девушка', 'pcorr'): 1,
  ('свирель', 'pcorr'): 1,
  ('птица', 'pcorr'): 1,
  ('шум', 'pcorr'): 1,
  ('всадница', 'pcorr'): 1,
  ('сурьма которая', 'incorr'): 1,
  ('кутерьма', 'pcorr'): 1,
  ('скрма', 'incorr'): 1},
 (117, 'весело', 'весело'): {('весело', 'corr'): 36,
  ('nan', 'incorr'): 1,
  ('радостно', 'corr'): 1},
 (118, 'мальчишек', 'хлопчиськ'): {('мальчишек', 'corr'): 9,
  ('nan', 'incorr'): 7,
  ('мальчиков', 'corr'): 3,
  ('парней', 'corr'): 3,
  ('птиц', 'pcorr'): 2,
  ('людей', 'pcorr'): 2,
  ('ребятмшек', 'corr'): 1,
  ('пацанов', 'corr'): 1,
  ('юноши', 'corr'): 1,
  ('ржание', 'incorr'): 1,
  ('мальчишки', 'corr'): 1,
  ('ребятишек', 'corr'): 1,
  ('хлопцев', 'corr'): 1,
  ('мальчика', 'corr'): 1,
  ('мальчик/хлопца', 'corr'): 1,
  ('хлопчиков', 'corr'): 1,
  ('ветра', 'pcorr'): 1,
  ('молодцев', 'corr'): 1},
 (119, 'солдат', 'солдат'): {('солдат', 'corr'): 37, ('содат', 'corr'): 1},
 (120, 'значком', 'значком'): {('значком', 'corr'): 33,
  ('знаком', 'corr'): 2,
  ('nan', 'incorr'): 2,
  ('майданом', 'incorr'): 1},
 (121, 'остановились', 'зупинилися'): {('остановились', 'corr'): 15,
  ('nan', 'incorr'): 9,
  ('остановился', 'corr'): 5,
  ('запнулись', 'pcorr'): 3,
  ('замолчали', 'pcorr'): 2,
  ('зупинилися', 'incorr'): 1,
  ('двинулся', 'pcorr'): 1,
  ('спешились', 'pcorr'): 1,
  ('смутились', 'pcorr'): 1},
 (122, 'вылетела', 'вилетіла'): {('вылетела', 'corr'): 23,
  ('nan', 'incorr'): 4,
  ('влетела', 'corr'): 3,
  ('вышла', 'pcorr'): 2,
  ('шла', 'pcorr'): 1,
  ('зашла', 'pcorr'): 1,
  ('вылетел', 'corr'): 1,
  ('влетел', 'corr'): 1,
  ('вылетелп', 'corr'): 1,
  ('прискакала', 'pcorr'): 1},
 (123, 'каменной', 'кам’яним'): {('каменной', 'corr'): 35,
  ('nan', 'incorr'): 2,
  ('каменной стеной', 'corr'): 1},
 (124, 'виноград', 'виноград'): {('виноград', 'corr'): 35,
  ('винограл', 'corr'): 1,
  ('nan', 'incorr'): 1,
  ('салом', 'incorr'): 1},
 (125, 'дорогой', 'шляхом'): {('дорогой', 'corr'): 30,
  ('nan', 'incorr'): 2,
  ('путем', 'corr'): 2,
  ('путём', 'corr'): 1,
  ('шагом', 'incorr'): 1,
  ('тропкой', 'pcorr'): 1,
  ('проскакали', 'incorr'): 1},
 (126, 'мальчик', 'хлопчик'): {('мальчик', 'corr'): 21,
  ('nan', 'incorr'): 7,
  ('ребенок', 'corr'): 2,
  ('хлопчик', 'corr'): 2,
  ('человек', 'incorr'): 1,
  ('хлопец', 'corr'): 1,
  ('пацан', 'corr'): 1,
  ('ребёнок', 'corr'): 1,
  ('юноша', 'corr'): 1,
  ('паренек', 'corr'): 1},
 (127, 'командир', 'командир'): {('командир', 'corr'): 32,
  ('nan', 'incorr'): 3,
  ('комндир', 'corr'): 1,
  ('мальчик', 'pcorr'): 1,
  ('начальник', 'corr'): 1},
 (128, 'выхватил', 'вихопив'): {('выхватил', 'corr'): 23,
  ('вытащил', 'corr'): 7,
  ('вынул', 'corr'): 3,
  ('nan', 'incorr'): 2,
  ('выхватив', 'corr'): 2,
  ('достал', 'corr'): 1},
 (129, 'взмокшая', 'змоклий'): {('взмокшая', 'corr'): 12,
  ('nan', 'incorr'): 8,
  ('мокрая', 'corr'): 5,
  ('промокшая', 'pcorr'): 1,
  ('черная', 'pcorr'): 1,
  ('вспотевшая', 'corr'): 1,
  ('уставшая', 'pcorr'): 1,
  ('замолчала', 'incorr'): 1,
  ('намокшый', 'pcorr'): 1,
  ('клюнула', 'incorr'): 1,
  ('загнанная', 'pcorr'): 1,
  ('заклевала', 'incorr'): 1,
  ('тёмная', 'pcorr'): 1,
  ('взщмокшая', 'corr'): 1,
  ('смоляной', 'pcorr'): 1,
  ('взмокший', 'corr'): 1},
 (130, 'шарахнулась', 'сахнувся'): {('nan', 'incorr'): 6,
  ('взбрыкнув', 'corr'): 2,
  ('скакнула вбок', 'corr'): 2,
  ('повернулась вбок', 'pcorr'): 1,
  ('отошла вбок', 'corr'): 1,
  ('отпрянула вбок', 'corr'): 1,
  ('согнувшись', 'incorr'): 1,
  ('упала на бок', 'pcorr'): 1,
  ('остановилась', 'pcorr'): 1,
  ('скакнула в бок', 'corr'): 1,
  ('накренилась', 'pcorr'): 1,
  ('отпрянула в бок', 'corr'): 1,
  ('повернулась', 'pcorr'): 1,
  ('прыгнул', 'pcorr'): 1,
  ('завалилась на бок', 'pcorr'): 1,
  ('отпрянула', 'corr'): 1,
  ('в бок', 'pcorr'): 1,
  ('шарахнулась', 'corr'): 1,
  ('дернулась', 'corr'): 1,
  ('дёрнулась вбок', 'corr'): 1,
  ('шарахнулась вбок', 'corr'): 1,
  ('шарахнулась в бок', 'corr'): 1,
  ('метнулась вбок', 'corr'): 1,
  ('сдвинувшись вбок', 'pcorr'): 1,
  ('шарахнулся в сторону', 'corr'): 1,
  ('отпрянула в сторону и', 'corr'): 1,
  ('шарахнулась в сторону и', 'corr'): 1,
  ('как бык', 'incorr'): 1,
  ('взбрыкнулп', 'pcorr'): 1,
  ('скаканула вбок', 'corr'): 1,
  ('шарахнулась в сторону', 'corr'): 1},
 (131, 'командир', 'командир'): {('командир', 'corr'): 35,
  ('nan', 'incorr'): 2,
  ('предводитель', 'pcorr'): 1},
 (132, 'шее', 'шиї'): {('шее', 'corr'): 34,
  ('nan', 'incorr'): 2,
  ('шеи', 'corr'): 1,
  ('щее', 'corr'): 1},
 (133, 'полетели', 'полетіли'): {('полетели', 'corr'): 27,
  ('поскакали', 'corr'): 7,
  ('nan', 'incorr'): 2,
  ('плетели', 'corr'): 1,
  ('помчались', 'corr'): 1},
 (134, 'туче', 'хмарі'): {('облаке', 'corr'): 9,
  ('nan', 'incorr'): 9,
  ('клубах', 'corr'): 6,
  ('туче', 'corr'): 3,
  ('поднявшейся', 'pcorr'): 2,
  ('хмурой', 'incorr'): 2,
  ('корявой', 'incorr'): 1,
  ('бурой', 'pcorr'): 1,
  ('кумарной', 'incorr'): 1,
  ('тучи', 'corr'): 1,
  ('серой', 'pcorr'): 1,
  ('дорожной', 'pcorr'): 1,
  ('густой', 'incorr'): 1},
 (135, 'пик', 'списів'): {('копий', 'corr'): 15,
  ('nan', 'incorr'): 9,
  ('копьев', 'corr'): 2,
  ('спиц', 'incorr'): 1,
  ('сосудов', 'pcorr'): 1,
  ('тросточек', 'incorr'): 1,
  ('тростников', 'incorr'): 1,
  ('прутьев', 'pcorr'): 1,
  ('копей', 'corr'): 1,
  ('доспехов', 'incorr'): 1,
  ('перьев', 'incorr'): 1,
  ('пик', 'corr'): 1,
  ('палок', 'pcorr'): 1,
  ('стволов', 'pcorr'): 1,
  ('стрел', 'pcorr'): 1},
 (136, 'весело', 'весело'): {('весело', 'corr'): 28,
  ('nan', 'incorr'): 6,
  ('весёлыми', 'corr'): 2,
  ('особенно', 'incorr'): 1,
  ('широко', 'pcorr'): 1},
 (137, 'сверкающими', 'блискучими'): {('блестящими', 'corr'): 29,
  ('nan', 'incorr'): 5,
  ('сверкающими', 'corr'): 2,
  ('белыми', 'pcorr'): 1,
  ('яркими', 'corr'): 1},
 (138, 'солдат', 'солдат'): {('солдат', 'corr'): 34,
  ('nan', 'incorr'): 3,
  ('солдфат', 'corr'): 1},
 (139, 'трубою', 'сурмою'): {('nan', 'incorr'): 10,
  ('сурьмой', 'incorr'): 7,
  ('сумкой', 'pcorr'): 5,
  ('сурмой', 'incorr'): 3,
  ('трубою', 'corr'): 2,
  ('трубой', 'corr'): 2,
  ('сурьмою', 'incorr'): 2,
  ('труба', 'corr'): 1,
  ('сурьма', 'incorr'): 1,
  ('латами', 'pcorr'): 1,
  ('стрелою', 'pcorr'): 1,
  ('щитом', 'pcorr'): 1,
  ('сумой', 'pcorr'): 1,
  ('броней', 'pcorr'): 1},
 (140, 'морща', 'морщачи'): {('морща', 'corr'): 27,
  ('nan', 'incorr'): 3,
  ('сморщиненых', 'pcorr'): 1,
  ('поморшив', 'corr'): 1,
  ('сморщенно', 'pcorr'): 1,
  ('морщинистое', 'pcorr'): 1,
  ('морщивший', 'corr'): 1,
  ('морщя', 'corr'): 1,
  ('морщы', 'corr'): 1,
  ('кривя', 'corr'): 1},
 (141, 'двинулся', 'рушив'): {('nan', 'incorr'): 7,
  ('двинулся', 'corr'): 6,
  ('пошел', 'corr'): 5,
  ('шел', 'corr'): 3,
  ('пошёл', 'corr'): 3,
  ('скакал', 'pcorr'): 2,
  ('тронулся', 'pcorr'): 2,
  ('морщась', 'incorr'): 1,
  ('рушив', 'incorr'): 1,
  ('побежал', 'pcorr'): 1,
  ('рванул', 'pcorr'): 1,
  ('последовал', 'corr'): 1,
  ('решив напрямик идти', 'incorr'): 1,
  ('поскакал', 'pcorr'): 1,
  ('отошел', 'pcorr'): 1,
  ('шагнул', 'pcorr'): 1,
  ('сносил все', 'pcorr'): 1},
 (142, 'двинулся', 'рушив'): {('nan', 'incorr'): 7,
  ('двинулся', 'corr'): 5,
  ('рушив', 'incorr'): 3,
  ('шел', 'corr'): 3,
  ('скакал', 'pcorr'): 2,
  ('шли', 'corr'): 2,
  ('тронулся', 'corr'): 2,
  ('пошёл', 'corr'): 2,
  ('побежал', 'pcorr'): 1,
  ('рванул', 'pcorr'): 1,
  ('двинулись', 'corr'): 1,
  ('последовал', 'corr'): 1,
  ('пошли', 'corr'): 1,
  ('зачитывая', 'pcorr'): 1,
  ('решив', 'incorr'): 1,
  ('ломая', 'incorr'): 1,
  ('пошел', 'corr'): 1,
  ('шагал', 'corr'): 1,
  ('скакали', 'pcorr'): 1,
  ('неслись', 'pcorr'): 1},
 (20, 'пустому', 'порожнім'): {('пустому', 'corr'): 24,
  ('nan', 'incorr'): 4,
  ('коридору', 'pcorr'): 2,
  ('страшному', 'pcorr'): 1,
  ('порожнему', 'incorr'): 1,
  ('подвалу', 'incorr'): 1,
  ('прежнему', 'pcorr'): 1,
  ('порогу', 'incorr'): 1,
  ('пустым', 'corr'): 1,
  ('темному', 'pcorr'): 1},
 (21, 'коридору', 'коридором'): {('коридору', 'corr'): 33,
  ('корридору', 'corr'): 2,
  ('проходу', 'pcorr'): 1,
  ('зале', 'pcorr'): 1},
 (22, 'здании', 'будівлі'): {('здании', 'corr'): 8,
  ('nan', 'incorr'): 8,
  ('кабинете', 'pcorr'): 6,
  ('месте', 'pcorr'): 3,
  ('помещении', 'pcorr'): 3,
  ('доме', 'corr'): 2,
  ('сумасшедшем доме', 'corr'): 1,
  ('будилвы', 'incorr'): 1,
  ('здание', 'corr'): 1,
  ('бодуаре', 'pcorr'): 1,
  ('будивле', 'incorr'): 1,
  ('строении', 'corr'): 1,
  ('заведении', 'corr'): 1},
 (23, 'стеклянные', 'скляні'): {('стеклянные', 'corr'): 26,
  ('стеклянными', 'corr'): 2,
  ('nan', 'incorr'): 2,
  ('склянки', 'incorr'): 2,
  ('маленькие', 'pcorr'): 1,
  ('скалянки', 'incorr'): 1,
  ('деревянные', 'pcorr'): 1,
  ('складные', 'incorr'): 1,
  ('книжные', 'pcorr'): 1},
 (24, 'инструментами', 'інструментами'): {('инструментами', 'corr'): 32,
  ('ручками', 'pcorr'): 1,
  ('инструментом', 'corr'): 1,
  ('приборами', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('тнструментами', 'corr'): 1},
 (25, 'кресла', 'крісла'): {('кресла', 'corr'): 33,
  ('там', 'incorr'): 1,
  ('стетоскопы', 'pcorr'): 1,
  ('стулья', 'corr'): 1,
  ('другие', 'incorr'): 1},
 (26, 'колпаками', 'ковпаками'): {('колпаками', 'corr'): 28,
  ('колпачками', 'pcorr'): 2,
  ('плафонами', 'corr'): 2,
  ('орнаментами', 'pcorr'): 1,
  ('пипетками', 'incorr'): 1,
  ('калпаками', 'corr'): 1,
  ('диодами', 'pcorr'): 1,
  ('nan', 'incorr'): 1},
 (27, 'провода', 'дроти'): {('nan', 'incorr'): 9,
  ('провода', 'corr'): 7,
  ('лампы', 'pcorr'): 3,
  ('плиты', 'pcorr'): 2,
  ('светильники', 'pcorr'): 2,
  ('маятники', 'pcorr'): 1,
  ('лампочки', 'pcorr'): 1,
  ('печи', 'pcorr'): 1,
  ('трубки', 'pcorr'): 1,
  ('понели', 'pcorr'): 1,
  ('провод', 'corr'): 1,
  ('камины', 'pcorr'): 1,
  ('стержни', 'pcorr'): 1,
  ('приборы', 'pcorr'): 1,
  ('заборы', 'pcorr'): 1,
  ('дрели', 'pcorr'): 1,
  ('розетки', 'pcorr'): 1,
  ('трубы', 'pcorr'): 1,
  ('дротики', 'incorr'): 1},
 (28, 'принялись', 'заходилися'): {('находились', 'pcorr'): 13,
  ('зашли', 'pcorr'): 9,
  ('заходили', 'pcorr'): 4,
  ('принялись', 'corr'): 2,
  ('находилось', 'pcorr'): 2,
  ('стояли', 'pcorr'): 1,
  ('были', 'pcorr'): 1,
  ('пришли', 'pcorr'): 1,
  ('приходили', 'pcorr'): 1,
  ('говорили', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('взялись', 'corr'): 1},
 (29, 'столик', 'столик'): {('столик', 'corr'): 31,
  ('nan', 'incorr'): 2,
  ('стол', 'corr'): 2,
  ('стенку', 'pcorr'): 1,
  ('стеной', 'pcorr'): 1},
 (210, 'обдумывать', 'обдумувати'): {('обдумывать', 'corr'): 33,
  ('занимать', 'pcorr'): 1,
  ('менять', 'pcorr'): 1,
  ('начал обдумывать', 'corr'): 1,
  ('обдумывать0', 'corr'): 1},
 (211, 'соблазнял', 'спокушав'): {('nan', 'incorr'): 8,
  ('соблазнял', 'corr'): 4,
  ('соблазнительный', 'corr'): 2,
  ('искушал', 'corr'): 2,
  ('привлекал', 'corr'): 2,
  ('спокойный', 'incorr'): 2,
  ('быстро', 'incorr'): 2,
  ('обдумав', 'incorr'): 1,
  ('искушаемый', 'pcorr'): 1,
  ('прослушав', 'incorr'): 1,
  ('необычный', 'pcorr'): 1,
  ('соблознял', 'corr'): 1,
  ('разозлился', 'incorr'): 1,
  ('придумав', 'incorr'): 1,
  ('спонтанный', 'incorr'): 1,
  ('решил', 'incorr'): 1,
  ('раздумывал', 'pcorr'): 1,
  ('буйный', 'incorr'): 1,
  ('рисковый', 'pcorr'): 1,
  ('спокойно', 'incorr'): 1,
  ('съев', 'incorr'): 1,
  ('опасный', 'pcorr'): 1},
 (212, 'замысловатые', 'мудровані'): {('мудреные', 'corr'): 9,
  ('мудрёные', 'corr'): 4,
  ('замысловатые', 'corr'): 3,
  ('nan', 'incorr'): 3,
  ('мудренные', 'corr'): 2,
  ('хитрые', 'corr'): 2,
  ('мудрые', 'pcorr'): 2,
  ('замудренные', 'corr'): 1,
  ('сломать', 'pcorr'): 1,
  ('странные', 'pcorr'): 1,
  ('другие', 'pcorr'): 1,
  ('заумные', 'corr'): 1,
  ('стеклянные', 'pcorr'): 1,
  ('разбить', 'pcorr'): 1,
  ('чёртовы', 'pcorr'): 1,
  ('светящиеся', 'pcorr'): 1,
  ('старинные', 'pcorr'): 1,
  ('сложные', 'corr'): 1,
  ('умные', 'pcorr'): 1},
 (213, 'задержан', 'затримали'): {('nan', 'incorr'): 8,
  ('задержан', 'corr'): 7,
  ('задержали', 'corr'): 3,
  ('задержался', 'pcorr'): 3,
  ('был задержан', 'corr'): 2,
  ('схвачен', 'corr'): 1,
  ('пришел', 'pcorr'): 1,
  ('потратил время', 'pcorr'): 1,
  ('приехал', 'pcorr'): 1,
  ('его задержал', 'corr'): 1,
  ('пропущен', 'pcorr'): 1,
  ('работал', 'pcorr'): 1,
  ('заперт', 'pcorr'): 1,
  ('думает', 'pcorr'): 1,
  ('подарил это', 'pcorr'): 1,
  ('заключен', 'corr'): 1,
  ('пойман', 'pcorr'): 1,
  ('его потревожили', 'pcorr'): 1,
  ('пропадали', 'pcorr'): 1},
 (214, 'сегодняшний', 'сьогоднішній'): {('сегодняшний', 'corr'): 29,
  ('сегодня', 'pcorr'): 3,
  ('nan', 'incorr'): 2,
  ('однако', 'incorr'): 1,
  ('сегодяшний', 'corr'): 1,
  ('нынешний', 'corr'): 1},
 (215, 'вчерашнего', 'вчорашнього'): {('вчерашнего', 'corr'): 33,
  ('nan', 'incorr'): 2,
  ('прежнего', 'pcorr'): 1,
  ('предыдущего', 'pcorr'): 1},
 (216, 'сомнительным', 'сумнівним'): {('сомнительным', 'corr'): 24,
  ('nan', 'incorr'): 4,
  ('лучше', 'pcorr'): 1,
  ('отличительным', 'pcorr'): 1,
  ('сомнительныс', 'corr'): 1,
  ('легче', 'pcorr'): 1,
  ('сомнительный', 'corr'): 1,
  ('долгим', 'pcorr'): 1,
  ('нерешительным', 'pcorr'): 1,
  ('скучным', 'pcorr'): 1,
  ('неразумным', 'pcorr'): 1},
 (217, 'сумасшедший', 'божевільний'): {('nan', 'incorr'): 11,
  ('сумасшедший', 'corr'): 7,
  ('больной', 'pcorr'): 6,
  ('человек', 'pcorr'): 2,
  ('сумашедший', 'corr'): 2,
  ('помешанный', 'corr'): 2,
  ('атеист', 'incorr'): 1,
  ('сумасшедший.', 'corr'): 1,
  ('грешник', 'pcorr'): 1,
  ('богослов', 'pcorr'): 1,
  ('псих', 'corr'): 1,
  ('бездомный', 'pcorr'): 1,
  ('безбожник', 'pcorr'): 1},
 (218, 'повествование', 'розповідь'): {('рассказ', 'corr'): 10,
  ('рассказывать', 'pcorr'): 8,
  ('nan', 'incorr'): 4,
  ('исповедь', 'pcorr'): 3,
  ('расспрашивать', 'incorr'): 2,
  ('повествование', 'corr'): 1,
  ('распрашивать', 'incorr'): 1,
  ('проповеди', 'pcorr'): 1,
  ('говорить', 'pcorr'): 1,
  ('спрашивать', 'incorr'): 1,
  ('узновать', 'pcorr'): 1,
  ('разузнавать', 'pcorr'): 1,
  ('разговор', 'pcorr'): 1,
  ('разводить', 'incorr'): 1,
  ('узнать', 'incorr'): 1},
 (219, 'вчерашний', 'вчорашній'): {('вчерашний', 'corr'): 34,
  ('прошлый', 'pcorr'): 1,
  ('его', 'incorr'): 1,
  ('nan', 'incorr'): 1},
 (220, 'извращенно', 'перекручено'): {('nan', 'incorr'): 10,
  ('перекручено', 'incorr'): 4,
  ('превратно', 'corr'): 3,
  ('искаженно', 'corr'): 3,
  ('иначе', 'pcorr'): 3,
  ('перекрученно', 'incorr'): 2,
  ('неправильно', 'corr'): 2,
  ('превратно.', 'corr'): 1,
  ('криво', 'corr'): 1,
  ('двояко', 'pcorr'): 1,
  ('преувеличенно', 'pcorr'): 1,
  ('не так', 'corr'): 1,
  ('попало', 'incorr'): 1,
  ('запутанно', 'pcorr'): 1,
  ('перевёрнуто', 'corr'): 1,
  ('ярко перекручено', 'incorr'): 1,
  ('скучно', 'pcorr'): 1},
 (221, 'замкнуться', 'замкнутися'): {('замкнуться', 'corr'): 28,
  ('остаться', 'pcorr'): 2,
  ('nan', 'incorr'): 2,
  ('закрывшись', 'pcorr'): 1,
  ('быть', 'incorr'): 1,
  ('замкнувшись', 'pcorr'): 1,
  ('уход', 'pcorr'): 1,
  ('закрыться', 'corr'): 1},
 (222, 'осуществить', 'здійснити'): {('избежать', 'pcorr'): 10,
  ('сделать', 'corr'): 7,
  ('nan', 'incorr'): 6,
  ('осуществить', 'corr'): 5,
  ('понять', 'pcorr'): 1,
  ('достигнуть', 'corr'): 1,
  ('подтвердить', 'pcorr'): 1,
  ('достичь', 'corr'): 1,
  ('помочь', 'incorr'): 1,

In [13]:
bel_cognates = cognate_searcher(belarus_ans, russian_true, belarus_true)
bel_cognates

{(10, 'повернулся', 'завярнуўся'): {('развернулся', 'corr'): 17,
  ('повернулся', 'corr'): 10,
  ('обернулся', 'pcorr'): 3,
  ('завернулся', 'incorr'): 2,
  ('оглянулся', 'pcorr'): 2,
  ('завернул', 'pcorr'): 1,
  ('равзвернулся', 'corr'): 1,
  ('завернулся в плащ', 'pcorr'): 1,
  ('отвернулся', 'corr'): 1},
 (11, 'ступеням', 'прыступак'): {('ступеням', 'corr'): 9,
  ('помосту', 'pcorr'): 5,
  ('nan', 'incorr'): 4,
  ('крыльцу', 'pcorr'): 3,
  ('преступнику', 'pcorr'): 3,
  ('приступку', 'pcorr'): 2,
  ('лестнице', 'corr'): 2,
  ('пристани', 'pcorr'): 2,
  ('тупику', 'pcorr'): 1,
  ('причалу', 'pcorr'): 1,
  ('дверям', 'pcorr'): 1,
  ('помосту и ступеням', 'corr'): 1,
  ('воротам', 'pcorr'): 1,
  ('ступенькам', 'corr'): 1,
  ('приступкам', 'incorr'): 1,
  ('обрыву', 'pcorr'): 1},
 (12, 'шашек', 'шашак'): {('шашек', 'corr'): 7,
  ('плиток', 'corr'): 5,
  ('nan', 'incorr'): 3,
  ('досок', 'pcorr'): 3,
  ('деталей', 'pcorr'): 2,
  ('мозаик', 'corr'): 2,
  ('кусочков', 'corr'): 1,
  ('кусочков мозаики', 'corr'): 1,
  ('мазаик', 'pcorr'): 1,
  ('фрагментов мозаики', 'corr'): 1,
  ('квадратов мозаики', 'corr'): 1,
  ('мозаичного', 'pcorr'): 1,
  ('пазлов мазиики', 'corr'): 1,
  ('плит мозаики', 'corr'): 1,
  ('клеток', 'corr'): 1,
  ('плиток мозаики', 'corr'): 1,
  ('камней мозаики', 'corr'): 1,
  ('узоров', 'corr'): 1,
  ('квадратов', 'corr'): 1,
  ('шашек мозаичного', 'corr'): 1,
  ('мазаечного', 'pcorr'): 1,
  ('частей', 'pcorr'): 1},
 (13, 'спиною', 'плячыма'): {('плечами', 'pcorr'): 26,
  ('спиной', 'corr'): 6,
  ('nan', 'incorr'): 1,
  ('за плечами', 'pcorr'): 1,
  ('плечами градом', 'incorr'): 1,
  ('его плечами', 'pcorr'): 1,
  ('плчами', 'pcorr'): 1,
  ('плечами гадом летят', 'pcorr'): 1},
 (14, 'финики', 'фiнiкi'): {('финики', 'corr'): 33,
  ('nan', 'incorr'): 2,
  ('фантики', 'pcorr'): 1,
  ('а также', 'incorr'): 1,
  ('думая', 'incorr'): 1},
 (15, 'чудо', 'дзiва'): {('чудо', 'corr'): 17,
  ('диво', 'corr'): 6,
  ('nan', 'incorr'): 4,
  ('узреть диво', 'corr'): 2,
  ('чиво', 'incorr'): 1,
  ('убийцу', 'pcorr'): 1,
  ('лезут на плечи друг к другу', 'incorr'): 1,
  ('живого', 'incorr'): 1,
  ('жизнь', 'pcorr'): 1,
  ('чужо', 'pcorr'): 1,
  ('увидеть чудо', 'corr'): 1,
  ('и убедиться', 'incorr'): 1,
  ('увидеть диво', 'corr'): 1},
 (16, 'вырвался', 'вырваўся'): {('вырвался', 'corr'): 30,
  ('вырвавшийся', 'corr'): 1,
  ('вывернулся', 'pcorr'): 1,
  ('и вырвался', 'corr'): 1,
  ('вырывался', 'corr'): 1,
  ('вырываясь', 'pcorr'): 1,
  ('вырывается', 'corr'): 1,
  ('nan', 'incorr'): 1,
  ('вырваться', 'corr'): 1},
 (17, 'веревки', 'вяроўкi'): {('веревки', 'corr'): 16,
  ('варежки', 'pcorr'): 4,
  ('оковы', 'pcorr'): 4,
  ('nan', 'incorr'): 3,
  ('верёвки', 'corr'): 3,
  ('кожу', 'pcorr'): 1,
  ('наручники', 'pcorr'): 1,
  ('рубашку', 'pcorr'): 1,
  ('рукава', 'pcorr'): 1,
  ('верёвку', 'corr'): 1,
  ('верев и', 'corr'): 1,
  ('ветровку', 'pcorr'): 1,
  ('штанишки', 'incorr'): 1},
 (18, 'допросе', 'допытах'): {('пытках', 'pcorr'): 18,
  ('допросах', 'corr'): 10,
  ('nan', 'incorr'): 4,
  ('допросе', 'corr'): 2,
  ('запястьях', 'pcorr'): 1,
  ('вытянутых', 'incorr'): 1,
  ('опытах', 'pcorr'): 1,
  ('добрыо', 'incorr'): 1},
 (19, 'сумасшедшей', 'дурною'): {('дурной', 'corr'): 14,
  ('глупой', 'corr'): 11,
  ('nan', 'incorr'): 5,
  ('дурною', 'corr'): 2,
  ('дурной (глупой дурацкой))', 'pcorr'): 1,
  ('злобной', 'pcorr'): 1,
  ('непонимающей', 'pcorr'): 1,
  ('бессмысленной', 'pcorr'): 1,
  ('дружной', 'incorr'): 1,
  ('сумасшедшей', 'corr'): 1},
 (110, 'знал', 'ведаў'): {('знал', 'corr'): 25,
  ('знает', 'corr'): 4,
  ('видел', 'pcorr'): 2,
  ('думает', 'pcorr'): 1,
  ('знал (ведал)', 'corr'): 1,
  ('узнал', 'pcorr'): 1,
  ('налеется', 'pcorr'): 1,
  ('рассказывал', 'pcorr'): 1,
  ('зная', 'pcorr'): 1,
  ('понимал', 'pcorr'): 1},
 (111, 'ступеням', 'прыступак'): {('ступеням', 'corr'): 9,
  ('приступкам', 'incorr'): 7,
  ('nan', 'incorr'): 4,
  ('помостам', 'pcorr'): 3,
  ('преступников', 'pcorr'): 2,
  ('ступенькам', 'corr'): 2,
  ('дверям', 'pcorr'): 2,
  ('воротам', 'pcorr'): 2,
  ('приступкам (лестницам)', 'corr'): 1,
  ('стражам', 'pcorr'): 1,
  ('лестницам', 'corr'): 1,
  ('выступах', 'pcorr'): 1,
  ('ступеней', 'corr'): 1,
  ('обрывам', 'pcorr'): 1,
  ('стенам', 'pcorr'): 1},
 (112, 'дорогу', 'дарогу'): {('дорогу', 'corr'): 37,
  ('дорогу (тропу)', 'corr'): 1},
 (113, 'осужденных', 'асуджаных'): {('отсюда', 'incorr'): 18,
  ('осужденных', 'corr'): 8,
  ('отсюда осужденных', 'corr'): 3,
  ('осуждённых', 'corr'): 3,
  ('отнюдь', 'incorr'): 1,
  ('осужденного', 'corr'): 1,
  ('чувствую что', 'incorr'): 1,
  ('nan', 'incorr'): 1,
  ('отсюда осужленных', 'corr'): 1,
  ('местный суд', 'pcorr'): 1},
 (114, 'глашатаев', 'глашатаяў'): {('глашатаев', 'corr'): 19,
  ('глашатая', 'corr'): 5,
  ('глашатых', 'corr'): 4,
  ('nan', 'incorr'): 3,
  ('глашатай', 'corr'): 1,
  ('осуждённого', 'pcorr'): 1,
  ('также', 'incorr'): 1,
  ('глашатого', 'corr'): 1,
  ('глашатоев', 'corr'): 1,
  ('толпы', 'pcorr'): 1,
  ('гашатых', 'corr'): 1},
 (115, 'греческом', 'грэцкай'): {('греческом', 'corr'): 25,
  ('греческих', 'corr'): 7,
  ('грецком', 'pcorr'): 2,
  ('nan', 'incorr'): 1,
  ('латинских', 'pcorr'): 1,
  ('турецком', 'pcorr'): 1,
  ('грецких', 'pcorr'): 1},
 (116, 'труба', 'трубы'): {('звук трубы', 'corr'): 16,
  ('гул трубы', 'corr'): 10,
  ('труба', 'corr'): 6,
  ('nan', 'incorr'): 2,
  ('гул труб', 'corr'): 1,
  ('гуд трубы', 'corr'): 1,
  ('звук', 'pcorr'): 1,
  ('трубы', 'corr'): 1},
 (117, 'весело', 'весела'): {('весело', 'corr'): 34,
  ('nan', 'incorr'): 2,
  ('коротко', 'pcorr'): 1,
  ('веспло', 'corr'): 1},
 (118, 'мальчишек', 'хлапчукоўскi'): {('nan', 'incorr'): 21,
  ('мальчишек', 'corr'): 3,
  ('идущий', 'pcorr'): 1,
  (', доносящийся', 'incorr'): 1,
  ('сходящий', 'incorr'): 1,
  ('прозвучавший', 'pcorr'): 1,
  ('долетевший', 'pcorr'): 1,
  ('раздавшийся', 'pcorr'): 1,
  ('донлсящийся', 'pcorr'): 1,
  ('крыш', 'pcorr'): 1,
  ('ближайших', 'incorr'): 1,
  ('звучащий', 'pcorr'): 1,
  ('доносящийся', 'pcorr'): 1,
  ('мальчишками', 'corr'): 1,
  ('покрытий', 'pcorr'): 1,
  ('слетевший', 'incorr'): 1},
 (119, 'солдат', 'салдат'): {('солдат', 'corr'): 35,
  ('nan', 'incorr'): 2,
  ('солда', 'corr'): 1},
 (120, 'значком', 'значком'): {('значком', 'corr'): 21,
  ('знаменем', 'pcorr'): 6,
  ('знаком', 'corr'): 5,
  ('флагом', 'pcorr'): 3,
  ('nan', 'incorr'): 2,
  ('зачком', 'corr'): 1},
 (121, 'остановились', 'спынiлiся'): {('nan', 'incorr'): 14,
  ('остановились', 'corr'): 7,
  ('остановился', 'corr'): 3,
  ('спустились', 'pcorr'): 2,
  ('тронулись', 'pcorr'): 2,
  ('спешились', 'pcorr'): 2,
  ('отступил', 'pcorr'): 1,
  ('удалились', 'pcorr'): 1,
  ('развернулись', 'pcorr'): 1,
  ('поднялся', 'pcorr'): 1,
  ('скрылись', 'pcorr'): 1,
  ('встрепенулись', 'pcorr'): 1,
  ('отправились', 'pcorr'): 1,
  ('вырвался', 'pcorr'): 1},
 (122, 'вылетела', 'вылецела'): {('вылетела', 'corr'): 30,
  ('nan', 'incorr'): 3,
  ('вышла', 'pcorr'): 2,
  ('выльется', 'pcorr'): 1,
  ('влетела', 'corr'): 1,
  ('вылетели', 'corr'): 1},
 (123, 'каменной', 'каменнаю'): {('каменной', 'corr'): 34,
  ('nan', 'incorr'): 4},
 (124, 'виноград', 'вiнаград'): {('виноград', 'corr'): 34,
  ('nan', 'incorr'): 3,
  ('виноградники', 'pcorr'): 1},
 (125, 'дорогой', 'дарогаю'): {('дорогой', 'corr'): 29,
  ('дорогою', 'corr'): 4,
  ('nan', 'incorr'): 3,
  ('дороге', 'corr'): 1,
  ('дорогу', 'corr'): 1},
 (126, 'мальчик', 'хлопчык'): {('мальчик', 'corr'): 16,
  ('nan', 'incorr'): 5,
  ('хлопчик', 'corr'): 5,
  ('ребенок', 'corr'): 4,
  ('юноша', 'corr'): 2,
  ('хлопец', 'corr'): 2,
  ('ребёнок', 'corr'): 1,
  ('мальчишка', 'corr'): 1,
  ('мальик', 'corr'): 1,
  ('хлопок', 'incorr'): 1},
 (127, 'командир', 'камандзiр'): {('командир', 'corr'): 30,
  ('nan', 'incorr'): 4,
  ('камандир', 'corr'): 2,
  ('командир/начальник', 'corr'): 1,
  ('властный', 'incorr'): 1},
 (128, 'выхватил', 'выхапiў'): {('выхватил', 'corr'): 23,
  ('вытащил', 'corr'): 5,
  ('nan', 'incorr'): 4,
  ('вынул', 'corr'): 3,
  ('достал', 'corr'): 2,
  ('схватил', 'pcorr'): 1},
 (129, 'взмокшая', 'мокры'): {('мокрая', 'corr'): 29,
  ('nan', 'incorr'): 4,
  ('взмыленная', 'corr'): 2,
  ('каркнула,', 'incorr'): 1,
  ('испугала', 'incorr'): 1,
  ('в пене', 'pcorr'): 1},
 (130, 'шарахнулась', 'шарахнуўся'): {('шарахнулась', 'corr'): 21,
  ('nan', 'incorr'): 5,
  ('шарахнувшись', 'corr'): 2,
  ('устав', 'pcorr'): 2,
  ('успугалась', 'pcorr'): 1,
  ('отшарахнулась', 'corr'): 1,
  ('а та', 'incorr'): 1,
  ('вздрогнула', 'pcorr'): 1,
  ('дернулся', 'corr'): 1,
  ('упала', 'pcorr'): 1,
  ('встрепенулась', 'pcorr'): 1,
  ('отпрыгнула', 'pcorr'): 1},
 (131, 'командир', 'камандзiр'): {('командир', 'corr'): 23,
  ('nan', 'incorr'): 11,
  ('хлестко', 'incorr'): 1,
  ('нагойкою', 'incorr'): 1,
  ('он', 'incorr'): 1,
  ('камандир', 'corr'): 1},
 (132, 'шее', 'шыi'): {('шее', 'corr'): 27,
  ('nan', 'incorr'): 5,
  ('спине', 'pcorr'): 2,
  ('шее (гриве холке)', 'corr'): 1,
  ('шее/холке', 'corr'): 1,
  ('ногам', 'pcorr'): 1,
  ('гриве', 'corr'): 1},
 (133, 'полетели', 'паляцелi'): {('полетели', 'corr'): 19,
  ('nan', 'incorr'): 6,
  ('поскакали', 'corr'): 3,
  ('плелись', 'pcorr'): 3,
  ('выстроились', 'pcorr'): 2,
  ('полтели', 'corr'): 1,
  ('помчались', 'corr'): 1,
  ('полетелт', 'corr'): 1,
  ('маршировали', 'pcorr'): 1,
  ('подпрыгивали', 'pcorr'): 1},
 (134, 'туче', 'хмарах'): {('клубах', 'corr'): 10,
  ('nan', 'incorr'): 9,
  ('тучах', 'corr'): 5,
  ('облаке', 'corr'): 2,
  ('серой', 'pcorr'): 2,
  ('облаках', 'corr'): 2,
  ('хлопьях', 'pcorr'): 1,
  ('бамбуковой', 'incorr'): 1,
  ('пустынной', 'pcorr'): 1,
  ('темной', 'pcorr'): 1,
  ('облако', 'corr'): 1,
  ('полетели', 'corr'): 1,
  ('туче', 'corr'): 1,
  ('столбах', 'pcorr'): 1},
 (135, 'пик', 'пiк'): {('пик', 'corr'): 29,
  ('nan', 'incorr'): 7,
  ('копий', 'corr'): 2},
 (136, 'весело', 'весела'): {('весело', 'corr'): 20,
  ('веселыми', 'corr'): 8,
  ('nan', 'incorr'): 6,
  ('весёлыми', 'corr'): 1,
  ('весёло', 'corr'): 1,
  ('весело/радостно', 'corr'): 1,
  ('белыми', 'pcorr'): 1},
 (137, 'сверкающими', 'зіхатлівымі'): {('белыми', 'pcorr'): 19,
  ('nan', 'incorr'): 10,
  ('белыми сияющими', 'pcorr'): 3,
  ('желтыми', 'pcorr'): 1,
  ('белыми хитрыми', 'pcorr'): 1,
  ('белыми отливающими', 'pcorr'): 1,
  ('оголенными', 'pcorr'): 1,
  ('ослепительными', 'corr'): 1,
  ('золотыми', 'pcorr'): 1},
 (138, 'солдат', 'салдат'): {('солдат', 'corr'): 33, ('nan', 'incorr'): 5},
 (139, 'трубою', 'трубою'): {('трубой', 'corr'): 24,
  ('трубою', 'corr'): 8,
  ('nan', 'incorr'): 5,
  ('с трубой', 'corr'): 1},
 (140, 'морща', 'моршчыўся'): {('морща', 'corr'): 21,
  ('nan', 'incorr'): 6,
  ('морщил', 'corr'): 2,
  ('корча', 'pcorr'): 1,
  ('морщиня', 'corr'): 1,
  ('морщившееся', 'corr'): 1,
  ('мрща', 'corr'): 1,
  ('морщя', 'corr'): 1,
  ('морщась', 'corr'): 1,
  ('морщящий', 'pcorr'): 1,
  ('поморща', 'corr'): 1,
  ('морщилось', 'pcorr'): 1},
 (141, 'двинулся', 'рушыў'): {('nan', 'incorr'): 8,
  ('пошел', 'corr'): 7,
  ('поскакал', 'pcorr'): 5,
  ('двинулся', 'corr'): 4,
  ('пошёл', 'corr'): 3,
  ('шел', 'corr'): 3,
  ('бежал', 'pcorr'): 1,
  ('шагал', 'corr'): 1,
  ('поехал', 'pcorr'): 1,
  ('поскокал', 'pcorr'): 1,
  ('отправился', 'corr'): 1,
  ('помчался', 'pcorr'): 1,
  ('устремился', 'corr'): 1,
  ('направился', 'corr'): 1},
 (142, 'двинулся', 'рушылi'): {('nan', 'incorr'): 7,
  ('пошли', 'corr'): 3,
  ('поскакали', 'pcorr'): 3,
  ('шёл', 'corr'): 2,
  ('последовали', 'corr'): 2,
  ('шли', 'corr'): 2,
  ('мчались', 'pcorr'): 2,
  ('двинулись', 'corr'): 2,
  ('неслись', 'pcorr'): 1,
  ('следовал', 'corr'): 1,
  ('шел', 'corr'): 1,
  ('проследовали', 'corr'): 1,
  ('рванулись', 'pcorr'): 1,
  ('шагали', 'corr'): 1,
  ('прокуратор', 'incorr'): 1,
  ('стояли', 'pcorr'): 1,
  ('пошел', 'corr'): 1,
  ('двинулся', 'corr'): 1,
  ('до ворот сада шли', 'corr'): 1,
  ('скакали', 'pcorr'): 1,
  ('полотцы рушили', 'incorr'): 1,
  ('поехали', 'pcorr'): 1,
  ('устремились', 'corr'): 1},
 (20, 'пустому', 'пустым'): {('пустому', 'corr'): 29,
  ('пустым', 'corr'): 4,
  ('глухому', 'pcorr'): 2,
  ('улице', 'incorr'): 1,
  ('коридору', 'pcorr'): 1,
  ('пустынному', 'corr'): 1},
 (21, 'коридору', 'калiдоры'): {('коридору', 'corr'): 34,
  ('проходу', 'pcorr'): 1,
  ('и глухим коридорам', 'corr'): 1,
  ('корридору', 'corr'): 1,
  ('коридорам', 'corr'): 1},
 (22, 'здании', 'будынку'): {('nan', 'incorr'): 7,
  ('доме', 'corr'): 6,
  ('здании', 'corr'): 5,
  ('помещении', 'pcorr'): 4,
  ('кабинете', 'pcorr'): 2,
  ('месте', 'pcorr'): 2,
  ('строительстве', 'incorr'): 2,
  ('помещению', 'pcorr'): 1,
  ('домом', 'corr'): 1,
  ('будынке', 'incorr'): 1,
  ('бункере', 'pcorr'): 1,
  ('будуаре', 'pcorr'): 1,
  ('диван', 'incorr'): 1,
  ('диваном', 'incorr'): 1,
  ('обставленном', 'incorr'): 1,
  ('дому', 'pcorr'): 1,
  ('квартире', 'pcorr'): 1},
 (23, 'стеклянные', 'шкляныя'): {('стеклянные', 'corr'): 30,
  ('nan', 'incorr'): 4,
  ('школьными', 'incorr'): 1,
  ('маленькие', 'pcorr'): 1,
  ('застекленные', 'corr'): 1,
  ('коробочки', 'incorr'): 1},
 (24, 'инструментами', 'iнструментамi'): {('инструментами', 'corr'): 33,
  ('nan', 'incorr'): 2,
  ('инетсркументами', 'corr'): 1,
  ('аппаратами', 'pcorr'): 1,
  ('ножками', 'pcorr'): 1},
 (25, 'кресла', 'крэслы'): {('кресла', 'corr'): 31,
  ('стулья', 'corr'): 3,
  ('креслы', 'corr'): 2,
  ('выставленны', 'incorr'): 1,
  ('приборы', 'pcorr'): 1},
 (26, 'колпаками', 'каўпакамi'): {('колпаками', 'corr'): 22,
  ('абажурами', 'corr'): 3,
  ('крышками', 'pcorr'): 2,
  ('купайками', 'incorr'): 1,
  ('огоньками', 'pcorr'): 1,
  ('огнями', 'pcorr'): 1,
  ('жидкостями', 'pcorr'): 1,
  ('своей чистотой', 'pcorr'): 1,
  ('эмбрионами', 'incorr'): 1,
  ('упаковками', 'pcorr'): 1,
  ('плафонами', 'corr'): 1,
  ('кнопками', 'pcorr'): 1,
  ('колпоками', 'corr'): 1,
  ('nan', 'incorr'): 1},
 (27, 'провода', 'правады'): {('провода', 'corr'): 32,
  ('приборы', 'pcorr'): 2,
  ('горелки', 'pcorr'): 1,
  ('плитки', 'pcorr'): 1,
  ('угри', 'pcorr'): 1,
  ('nan', 'incorr'): 1},
 (28, 'принялись', 'ўзялiся'): {('взялись', 'corr'): 20,
  ('увязались', 'pcorr'): 5,
  ('находились', 'pcorr'): 2,
  ('ивановича', 'incorr'): 1,
  ('взялись втроём', 'corr'): 1,
  ('сидели', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('были', 'pcorr'): 1,
  ('взялись втроем', 'corr'): 1,
  ('принялись', 'corr'): 1,
  ('уставились', 'pcorr'): 1,
  ('зашли', 'pcorr'): 1,
  ('обнялись', 'pcorr'): 1,
  ('появились', 'pcorr'): 1},
 (29, 'столик', 'столiк'): {('столик', 'corr'): 34,
  ('ширму', 'pcorr'): 2,
  ('стол', 'corr'): 2},
 (210, 'обдумывать', 'думаць'): {('думать про свое', 'corr'): 11,
  ('обдумывать', 'corr'): 10,
  ('думать про своё', 'corr'): 6,
  ('обдумывать свое', 'corr'): 4,
  ('обдумывать своё', 'corr'): 2,
  ('оценивать', 'corr'): 1,
  ('в интересное', 'incorr'): 1,
  ('думать', 'corr'): 1,
  ('думать за свое', 'corr'): 1,
  ('обдумав', 'pcorr'): 1},
 (211, 'соблазнял', 'спакушаў'): {('nan', 'incorr'): 8,
  ('искушал', 'corr'): 7,
  ('соблазнял', 'corr'): 4,
  ('соблазнительный', 'corr'): 4,
  ('спокойный', 'incorr'): 2,
  ('простой', 'pcorr'): 1,
  ('покушай', 'incorr'): 1,
  ('опасный', 'pcorr'): 1,
  ('активный', 'pcorr'): 1,
  ('спокойно', 'incorr'): 1,
  ('смелый', 'pcorr'): 1,
  ('спрашивал', 'pcorr'): 1,
  ('клей', 'incorr'): 1,
  ('вариант', 'incorr'): 1,
  ('легкий', 'pcorr'): 1,
  ('нравился', 'corr'): 1,
  ('странный', 'incorr'): 1,
  ('попробуй', 'pcorr'): 1},
 (212, 'замысловатые', 'мудрагелiстыя'): {('мудреные', 'corr'): 7,
  ('nan', 'incorr'): 6,
  ('причудливые', 'pcorr'): 4,
  ('премудрые', 'corr'): 3,
  ('мудрёные', 'corr'): 2,
  ('мудренные', 'corr'): 2,
  ('мудрые', 'pcorr'): 1,
  ('чудные', 'pcorr'): 1,
  ('странные', 'pcorr'): 1,
  ('кинул', 'incorr'): 1,
  ('премудрёные', 'corr'): 1,
  ('поломать', 'incorr'): 1,
  ('прыгнув', 'incorr'): 1,
  ('заумные', 'corr'): 1,
  ('схватить', 'pcorr'): 1,
  ('хитровыдуманные', 'corr'): 1,
  ('замысловаты', 'corr'): 1,
  ('бпросить', 'pcorr'): 1,
  ('необычные', 'pcorr'): 1,
  ('замысловатые', 'corr'): 1},
 (213, 'задержан', 'трымаюць'): {('задержан', 'corr'): 8,
  ('nan', 'incorr'): 7,
  ('тут', 'incorr'): 3,
  ('находится здесь', 'pcorr'): 3,
  ('пытается', 'pcorr'): 1,
  ('приехал', 'pcorr'): 1,
  ('мается', 'pcorr'): 1,
  ('старался', 'pcorr'): 1,
  ('находится тут', 'pcorr'): 1,
  ('страдает здесь', 'pcorr'): 1,
  ('находится', 'pcorr'): 1,
  ('ушел', 'pcorr'): 1,
  ('теряет время', 'pcorr'): 1,
  ('мучают', 'pcorr'): 1,
  ('находится тутт почем', 'pcorr'): 1,
  ('потратил время', 'pcorr'): 1,
  ('простоял', 'pcorr'): 1,
  ('торчит здесь', 'pcorr'): 1,
  ('держат', 'pcorr'): 1,
  ('тратит время', 'pcorr'): 1,
  ('всё', 'incorr'): 1},
 (214, 'сегодняшний', 'сённяшнi'): {('сегодняшний', 'corr'): 28,
  ('сегодня', 'pcorr'): 4,
  ('сегоднешний', 'corr'): 2,
  ('новый', 'pcorr'): 1,
  ('нынешний', 'corr'): 1,
  ('тот', 'incorr'): 1,
  ('сегоднишний', 'corr'): 1},
 (215, 'вчерашнего', 'ўчарашняга'): {('вчерашнего', 'corr'): 35,
  ('ивановича', 'incorr'): 1,
  ('предыдущего', 'pcorr'): 1,
  ('того', 'incorr'): 1},
 (216, 'сомнительным', 'сумнiцельным'): {('сомнительным', 'corr'): 31,
  ('сумасшедшим', 'pcorr'): 2,
  ('дурацким', 'pcorr'): 1,
  ('вернее', 'pcorr'): 1,
  ('ручкой', 'incorr'): 1,
  ('nan', 'incorr'): 1,
  ('сомнительный', 'corr'): 1},
 (217, 'сумасшедший', "вар'ят"): {('nan', 'incorr'): 14,
  ('сумасшедший', 'corr'): 4,
  ('варяг', 'incorr'): 3,
  ('варвар', 'pcorr'): 2,
  ('человек', 'pcorr'): 2,
  ('сумашедший', 'corr'): 2,
  ('псих', 'corr'): 1,
  ('больной', 'pcorr'): 1,
  ('саморез', 'incorr'): 1,
  ('парень', 'pcorr'): 1,
  ('вор', 'pcorr'): 1,
  ('психопат', 'corr'): 1,
  ('пациент', 'pcorr'): 1,
  ('тип', 'pcorr'): 1,
  ('псих.', 'corr'): 1,
  ('верно', 'incorr'): 1,
  ('борец', 'pcorr'): 1},
 (218, 'повествование', 'расказ'): {('рассказ', 'corr'): 27,
  ('рассказывать', 'pcorr'): 4,
  ('расказ', 'corr'): 2,
  ('разглагольствовать', 'pcorr'): 1,
  ('говорить', 'pcorr'): 1,
  ('гоготать', 'pcorr'): 1,
  ('разговор', 'pcorr'): 1,
  ('nan', 'incorr'): 1},
 (219, 'вчерашний', 'учарашнi'): {('вчерашний', 'corr'): 34,
  ('его', 'incorr'): 1,
  ('предыдущий', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('вчершний', 'corr'): 1},
 (220, 'извращенно', 'наадварот'): {('наоборот', 'corr'): 19,
  ('nan', 'incorr'): 10,
  ('иначе', 'pcorr'): 1,
  ('не так', 'corr'): 1,
  ('бред', 'incorr'): 1,
  ('превратно', 'corr'): 1,
  ('неправильно', 'corr'): 1,
  ('неадекватно', 'pcorr'): 1,
  ('извращенно', 'corr'): 1,
  ('не так.', 'corr'): 1,
  ('привратно', 'corr'): 1},
 (221, 'замкнуться', 'адгарадзiцца'): {('отгородиться', 'pcorr'): 15,
  ('оставаться', 'pcorr'): 6,
  ('остаться', 'pcorr'): 5,
  ('nan', 'incorr'): 2,
  ('отградиться', 'corr'): 1,
  ('пребывать', 'pcorr'): 1,
  ('и остаться', 'pcorr'): 1,
  ('отгородитьсч', 'corr'): 1,
  ('оградится', 'pcorr'): 1,
  ('одгородиться', 'corr'): 1,
  ('путь', 'pcorr'): 1,
  ('ограничиться', 'pcorr'): 1,
  ('находясь', 'pcorr'): 1,
  ('отгородиться', 'corr'): 1},
 (222, 'осуществить', 'ажыццявiць'): {('осуществить', 'corr'): 20,
  ('сделать', 'corr'): 4,
  ('избежать', 'pcorr'): 3,
  ('ему', 'incorr'): 3,
  ('добиться', 'pcorr'): 3,
  ('идея', 'incorr'): 1,
  ('к сожалению', 'incorr'): 1,
  ('nan', 'incorr'): 1,
  ('добится', 'pcorr'): 1,
  ('это оживить', 'incorr'): 1},
 (223, 'вопросов', 'пытанняў'): {('вопросов', 'corr'): 26,
  ('nan', 'incorr'): 5,
  ('скучных', 'incorr'): 1,
  ('вещей', 'pcorr'): 1,
  ('путаниц', 'pcorr'): 1,
  ('испытаний', 'incorr'): 1,
  ('пыток', 'pcorr'): 1,
  ('вопросов.', 'corr'): 1,
  ('понятный', 'incorr'): 1},
 (224, 'выспросили', 'распыталiся'): {('расспросили', 'corr'): 11,
  ('nan', 'incorr'): 4,
  ('выпытали', 'corr'): 4,
  ('спрашивали', 'corr'): 3,
  ('распросили', 'corr'): 2,
  ('выпытывали', 'corr'): 2,
  ('вызнавали', 'corr'): 2,
  ('ивановича', 'incorr'): 1,
  ('было', 'pcorr'): 1,
  ('распуталось', 'pcorr'): 1,
  ('распрашивал', 'corr'): 1,
  ('запел', 'incorr'): 1,
  ('запуталось', 'pcorr'): 1,
  ('рассказал', 'pcorr'): 1,

In [14]:
bg_cognates = cognate_searcher(bulgarian_ans, russian_true, bulgarian_true)
bg_cognates

{(10, 'повернулся', 'обърна'): {('обернулся', 'pcorr'): 12,
  ('повернулся', 'corr'): 12,
  ('развернулся', 'corr'): 3,
  ('оглянулся', 'pcorr'): 2,
  ('встал', 'pcorr'): 2,
  ('nan', 'incorr'): 2,
  ('прошелся туда и обратно по подиуму', 'incorr'): 1,
  ('василий', 'incorr'): 1,
  ('прыгнул с обрыва', 'incorr'): 1,
  ('огляделся', 'pcorr'): 1},
 (11, 'ступеням', 'стъпалата'): {('nan', 'incorr'): 10,
  ('ступеням', 'corr'): 7,
  ('палате', 'incorr'): 4,
  ('дому', 'pcorr'): 3,
  ('площади', 'pcorr'): 2,
  ('като', 'incorr'): 1,
  ('собору', 'pcorr'): 1,
  ('трибуне', 'pcorr'): 1,
  ('толпе', 'pcorr'): 1,
  ('ступени', 'corr'): 1,
  ('ступенькам', 'corr'): 1,
  ('храму', 'pcorr'): 1,
  ('лестнице', 'corr'): 1,
  ('креслу', 'pcorr'): 1,
  ('палатке', 'pcorr'): 1,
  ('бордюру', 'pcorr'): 1},
 (12, 'шашек', 'плочки'): {('плиток', 'corr'): 9,
  ('досок', 'pcorr'): 8,
  ('шашек', 'corr'): 3,
  ('камней', 'pcorr'): 3,
  ('дощечек', 'pcorr'): 3,
  ('шахматных плиток', 'corr'): 2,
  ('nan', 'incorr'): 2,
  ('полос', 'corr'): 1,
  ('плоских камней', 'pcorr'): 1,
  ('плит', 'corr'): 1,
  ('узоров', 'corr'): 1,
  ('шахмат', 'pcorr'): 1,
  ('ковров', 'pcorr'): 1,
  ('листьев', 'pcorr'): 1},
 (13, 'спиною', 'гърба'): {('спиной', 'corr'): 29,
  ('nan', 'incorr'): 2,
  ('спиной сверху подиума градом', 'pcorr'): 1,
  ('за спиною', 'corr'): 1,
  ('проход', 'incorr'): 1,
  ('верх подиума', 'pcorr'): 1,
  ('карта', 'incorr'): 1,
  ('спиною', 'corr'): 1},
 (14, 'финики', 'смокини'): {('nan', 'incorr'): 11,
  ('инжир', 'pcorr'): 5,
  ('финики', 'corr'): 3,
  ('и инжир', 'pcorr'): 2,
  ('и увидел', 'incorr'): 1,
  ('окурки', 'incorr'): 1,
  ('заметил', 'incorr'): 1,
  ('и смоквы', 'incorr'): 1,
  ('и понимал', 'pcorr'): 1,
  ('чувствовал', 'pcorr'): 1,
  ('фрукты', 'pcorr'): 1,
  ('и чувствовал', 'pcorr'): 1,
  ('радуясь', 'incorr'): 1,
  ('сигареты', 'pcorr'): 1,
  ('ветки', 'pcorr'): 1,
  ('надеется', 'incorr'): 1,
  ('и смотрит', 'incorr'): 1,
  ('люди стали собирать монеты', 'incorr'): 1,
  ('понимал', 'pcorr'): 1,
  ('и смокинги', 'incorr'): 1},
 (15, 'чудо', 'чудото'): {('чудо', 'corr'): 24,
  ('это чудо', 'corr'): 4,
  ('nan', 'incorr'): 2,
  ('отчетливо', 'incorr'): 1,
  ('смерть', 'pcorr'): 1,
  ('зрелище', 'pcorr'): 1,
  ('и инжир', 'incorr'): 1,
  ('жизнь', 'pcorr'): 1,
  ('представление', 'pcorr'): 1,
  ('то', 'incorr'): 1},
 (16, 'вырвался', 'изтръгнал'): {('вырвался', 'corr'): 21,
  ('nan', 'incorr'): 3,
  ('увильнул', 'pcorr'): 1,
  ('и вырвался', 'corr'): 1,
  ('выбрался', 'pcorr'): 1,
  ('выкарабкивался', 'corr'): 1,
  ('себя вытащил', 'pcorr'): 1,
  ('и сбежал', 'pcorr'): 1,
  ('питаться', 'incorr'): 1,
  ('ускользнул', 'corr'): 1,
  ('вырывается', 'corr'): 1,
  ('избежал', 'corr'): 1,
  ('вылез', 'pcorr'): 1,
  ('сбежал', 'corr'): 1,
  ('но выбрался', 'pcorr'): 1},
 (17, 'веревки', 'въжетата'): {('веревки', 'corr'): 10,
  ('nan', 'incorr'): 6,
  ('одежду', 'pcorr'): 6,
  ('кожу', 'pcorr'): 2,
  ('наручники', 'pcorr'): 2,
  ('верёвки', 'corr'): 2,
  ('доспехи', 'pcorr'): 2,
  ('веревкм', 'corr'): 1,
  ('вретище', 'pcorr'): 1,
  ('кольчугу', 'pcorr'): 1,
  ('путы', 'corr'): 1,
  ('улыбку', 'pcorr'): 1,
  ('жилет', 'pcorr'): 1,
  ('верёвку', 'corr'): 1},
 (18, 'допросе', 'разпита'): {('nan', 'incorr'): 7,
  ('распятии', 'pcorr'): 6,
  ('допросе', 'corr'): 6,
  ('запястьях', 'pcorr'): 3,
  ('допросах', 'corr'): 3,
  ('пытке', 'corr'): 2,
  ('дыбе руках', 'pcorr'): 1,
  ('изнанку', 'incorr'): 1,
  ('локтях', 'pcorr'): 1,
  ('теле', 'pcorr'): 1,
  ('плечах', 'incorr'): 1,
  ('дыбе', 'pcorr'): 1,
  ('ободранных', 'incorr'): 1,
  ('крапиве на', 'incorr'): 1,
  ('спину', 'incorr'): 1,
  ('обеих', 'incorr'): 1},
 (19, 'сумасшедшей', 'налудничава'): {('nan', 'incorr'): 7,
  ('безумной', 'corr'): 7,
  ('сумасшедшей', 'corr'): 3,
  ('лукавой', 'pcorr'): 2,
  ('лучистой', 'pcorr'): 1,
  ('непонимающей', 'pcorr'): 1,
  ('нарочитой', 'pcorr'): 1,
  ('глупой', 'corr'): 1,
  ('неудачной', 'incorr'): 1,
  ('жалкой', 'pcorr'): 1,
  ('наивной', 'pcorr'): 1,
  ('детской', 'pcorr'): 1,
  ('добродушной', 'pcorr'): 1,
  ('глуповатой', 'pcorr'): 1,
  ('натянутой', 'pcorr'): 1,
  ('дкрацкой', 'pcorr'): 1,
  ('странной', 'pcorr'): 1,
  ('доброй', 'pcorr'): 1,
  ('сумасшедсшей', 'corr'): 1,
  ('хитрой', 'pcorr'): 1,
  ('белоснежной', 'pcorr'): 1,
  ('налюдной', 'incorr'): 1},
 (110, 'знал', 'знаеше'): {('знал', 'corr'): 30,
  ('чувствовал', 'pcorr'): 1,
  ('предполагал', 'pcorr'): 1,
  ('знает', 'corr'): 1,
  ('думал', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('услышал', 'pcorr'): 1,
  ('понял', 'pcorr'): 1},
 (111, 'ступеням', 'стъпала'): {('ступеням', 'corr'): 10,
  ('nan', 'incorr'): 9,
  ('воротам', 'pcorr'): 5,
  ('ступенькам', 'corr'): 2,
  ('спускам', 'pcorr'): 1,
  ('лестницам', 'corr'): 1,
  ('колоннам', 'pcorr'): 1,
  ('воротами', 'pcorr'): 1,
  ('входам', 'pcorr'): 1,
  ('дверям', 'pcorr'): 1,
  ('залам', 'pcorr'): 1,
  ('стенам', 'pcorr'): 1,
  ('выходам', 'pcorr'): 1,
  ('флангам', 'pcorr'): 1,
  ('шпалам', 'pcorr'): 1},
 (112, 'дорогу', 'пътя'): {('дорогу', 'corr'): 28,
  ('тропу', 'pcorr'): 3,
  ('nan', 'incorr'): 2,
  ('плаху', 'pcorr'): 1,
  ('площадь', 'pcorr'): 1,
  ('свободу', 'pcorr'): 1,
  ('пять', 'incorr'): 1},
 (113, 'осужденных', 'осъдените'): {('nan', 'incorr'): 5,
  ('осужденных', 'corr'): 5,
  ('больше', 'incorr'): 4,
  ('осуждённых', 'corr'): 3,
  ('толпу', 'pcorr'): 2,
  ('что', 'incorr'): 1,
  ('его', 'incorr'): 1,
  ('вече', 'incorr'): 1,
  ('конвой', 'pcorr'): 1,
  ('врагов', 'pcorr'): 1,
  ('однако', 'incorr'): 1,
  ('хотя', 'incorr'): 1,
  ('осужденного', 'corr'): 1,
  ('людей', 'pcorr'): 1,
  ('народ', 'pcorr'): 1,
  ('правду', 'pcorr'): 1,
  ('окружающих', 'pcorr'): 1,
  ('отсюда', 'incorr'): 1,
  ('глазами', 'pcorr'): 1,
  ('страх', 'pcorr'): 1,
  ('осуждённого', 'corr'): 1,
  ('теперь', 'incorr'): 1,
  ('ведь', 'incorr'): 1},
 (114, 'глашатаев', 'глашатаите'): {('глашатаев', 'corr'): 18,
  ('nan', 'incorr'): 5,
  ('людей', 'pcorr'): 4,
  ('глашатых', 'corr'): 3,
  ('на плахе', 'pcorr'): 1,
  ('глашатого', 'corr'): 1,
  ('легионеров', 'pcorr'): 1,
  ('страшные вопли', 'incorr'): 1,
  ('глошатая', 'corr'): 1,
  ('глашатая', 'corr'): 1,
  ('галашатаев', 'corr'): 1},
 (115, 'греческом', 'гръцки'): {('греческом', 'corr'): 24,
  ('nan', 'incorr'): 6,
  ('греческих', 'corr'): 2,
  ('грецком', 'pcorr'): 1,
  ('испанском', 'pcorr'): 1,
  ('непонятных', 'pcorr'): 1,
  ('английском', 'pcorr'): 1,
  ('разных', 'pcorr'): 1},
 (116, 'труба', 'тръба'): {('nan', 'incorr'): 9,
  ('труба', 'corr'): 7,
  ('голос', 'pcorr'): 5,
  ('толпа', 'pcorr'): 2,
  ('крик', 'pcorr'): 2,
  ('вой', 'pcorr'): 1,
  ('веселый голос женщины', 'pcorr'): 1,
  ('треск', 'pcorr'): 1,
  ('она замерла', 'incorr'): 1,
  ('громоподобный', 'incorr'): 1,
  ('резкие крики глашатаев', 'pcorr'): 1,
  ('трубы', 'corr'): 1,
  ('женщина', 'pcorr'): 1,
  ('всадница', 'pcorr'): 1,
  ('крики', 'pcorr'): 1,
  ('звук', 'pcorr'): 1,
  ('цокот', 'incorr'): 1},
 (117, 'весело', 'весел'): {('весело', 'corr'): 19,
  ('громко', 'pcorr'): 6,
  ('nan', 'incorr'): 5,
  ('звонко', 'corr'): 3,
  ('требовательно', 'pcorr'): 1,
  ('вопиюще', 'pcorr'): 1,
  ('выглянувшая', 'incorr'): 1,
  ('неразборчиво', 'pcorr'): 1},
 (118, 'мальчишек', 'хлапетата'): {('nan', 'incorr'): 14,
  ('детей', 'corr'): 6,
  ('мальчишек', 'corr'): 2,
  ('доносившийся', 'pcorr'): 2,
  ('ребят', 'corr'): 2,
  ('мальчиков', 'corr'): 1,
  ('на плахе', 'pcorr'): 1,
  ('кнута', 'pcorr'): 1,
  ('доносящийся', 'pcorr'): 1,
  (', доносящийся', 'incorr'): 1,
  ('зевак', 'pcorr'): 1,
  ('хлопанье', 'incorr'): 1,
  ('ветра', 'pcorr'): 1,
  ('птиц', 'pcorr'): 1,
  ('опустившийся', 'incorr'): 1,
  ('и хлопот', 'incorr'): 1},
 (119, 'солдат', 'войникът'): {('воин', 'corr'): 14,
  ('солдат', 'corr'): 11,
  ('nan', 'incorr'): 3,
  ('вождь застонал', 'incorr'): 1,
  ('военачальник', 'pcorr'): 1,
  ('возник', 'incorr'): 1,
  ('пилат', 'pcorr'): 1,
  ('человек', 'pcorr'): 1,
  ('легионер', 'corr'): 1,
  ('он', 'incorr'): 1,
  ('полководец', 'pcorr'): 1,
  ('военный', 'pcorr'): 1},
 (120, 'значком', 'римския орел'): {('римским орлом', 'corr'): 8,
  ('nan', 'incorr'): 7,
  ('значком', 'corr'): 4,
  ('знаменем', 'pcorr'): 3,
  ('орлом', 'corr'): 2,
  ('с римским орлом в руках', 'corr'): 1,
  ('стременом', 'incorr'): 1,
  ('платком', 'pcorr'): 1,
  ('топором', 'pcorr'): 1,
  ('оружием', 'pcorr'): 1,
  ('римскои мечом', 'pcorr'): 1,
  ('знаком римского орла', 'corr'): 1,
  ('своим оружием', 'pcorr'): 1,
  ('штандартом', 'corr'): 1,
  ('жезлом', 'pcorr'): 1,
  ('посохом', 'pcorr'): 1,
  ('римский орлом', 'corr'): 1,
  ('свечкой', 'pcorr'): 1},
 (121, 'остановились', 'спряха'): {('nan', 'incorr'): 12,
  ('остановились', 'corr'): 8,
  ('спрятались', 'incorr'): 7,
  ('отпрянули', 'pcorr'): 2,
  ('стражи', 'incorr'): 1,
  ('испугались', 'pcorr'): 1,
  ('отошли', 'pcorr'): 1,
  ('спросили', 'pcorr'): 1,
  ('ушли', 'pcorr'): 1,
  ('сомкнулись', 'pcorr'): 1,
  ('тронулись', 'pcorr'): 1,
  ('оглянулись', 'pcorr'): 1},
 (122, 'вылетела', 'излетя'): {('вылетела', 'corr'): 8,
  ('влетела', 'corr'): 6,
  ('nan', 'incorr'): 4,
  ('взлетела', 'pcorr'): 2,
  ('залетая', 'incorr'): 2,
  ('взетела', 'pcorr'): 1,
  ('переходя на галоп, влетела', 'corr'): 1,
  ('ринулвсь', 'pcorr'): 1,
  ('влетели', 'corr'): 1,
  ('ворвалась', 'corr'): 1,
  ('галопом', 'incorr'): 1,
  ('прискакала', 'pcorr'): 1,
  ('влетала', 'corr'): 1,
  ('появилась', 'pcorr'): 1,
  ('вышли', 'pcorr'): 1,
  ('выехали', 'pcorr'): 1,
  ('снял', 'incorr'): 1,
  ('выехала', 'pcorr'): 1,
  ('выбежала', 'pcorr'): 1,
  ('вылетел', 'corr'): 1},
 (123, 'каменной', 'каменна'): {('каменной', 'corr'): 26,
  ('nan', 'incorr'): 3,
  ('краем', 'incorr'): 2,
  ('обвитой лозой', 'pcorr'): 1,
  ('красной', 'pcorr'): 1,
  ('обвитой', 'incorr'): 1,
  ('крепостноц', 'pcorr'): 1,
  ('мостовой', 'incorr'): 1,
  ('высокой', 'pcorr'): 1},
 (124, 'виноград', 'лози'): {('виноград', 'corr'): 15,
  ('nan', 'incorr'): 6,
  ('лоза', 'corr'): 4,
  ('путь', 'pcorr'): 2,
  ('плющ', 'pcorr'): 2,
  ('он', 'incorr'): 1,
  ('кровавый шлейф', 'pcorr'): 1,
  ('легкий дымок', 'pcorr'): 1,
  ('мох', 'pcorr'): 1,
  ('бетон', 'incorr'): 1,
  ('виноградная лаза', 'corr'): 1,
  ('туман', 'pcorr'): 1,
  ('край', 'pcorr'): 1},
 (125, 'дорогой', 'път'): {('дорогой', 'corr'): 24,
  ('nan', 'incorr'): 4,
  ('путь', 'corr'): 3,
  ('дороги', 'corr'): 2,
  ('виноград', 'incorr'): 1,
  ('проулок', 'pcorr'): 1,
  ('долиной', 'pcorr'): 1,
  ('пути', 'corr'): 1},
 (126, 'мальчик', 'момче'): {('nan', 'incorr'): 14,
  ('мальчик', 'corr'): 10,
  ('мышь', 'pcorr'): 4,
  ('ребенок', 'corr'): 3,
  ('свирчок', 'pcorr'): 1,
  ('мартышка', 'pcorr'): 1,
  ('ворон', 'pcorr'): 1,
  ('котенок', 'pcorr'): 1,
  ('крупинка', 'pcorr'): 1,
  ('момче', 'incorr'): 1},
 (127, 'командир', 'командир'): {('командир', 'corr'): 27,
  ('nan', 'incorr'): 6,
  ('коммандир', 'corr'): 1,
  ('командующий', 'pcorr'): 1,
  ('высоки', 'incorr'): 1,
  ('прошел', 'incorr'): 1},
 (128, 'выхватил', 'изтегли'): {('выхватил', 'corr'): 9,
  ('вынул', 'corr'): 7,
  ('достал', 'corr'): 6,
  ('вытащил', 'corr'): 6,
  ('извлек', 'corr'): 3,
  ('nan', 'incorr'): 3,
  ('извлёк', 'corr'): 2,
  ('вытянул/достал', 'corr'): 1},
 (129, 'взмокшая', 'запенен'): {('взмыленная', 'corr'): 7,
  ('nan', 'incorr'): 7,
  ('взмокшая', 'corr'): 4,
  ('загнанная', 'pcorr'): 2,
  ('вспененная', 'pcorr'): 2,
  ('запененная', 'incorr'): 1,
  ('в пене', 'pcorr'): 1,
  ('моя', 'incorr'): 1,
  ('подлетела', 'incorr'): 1,
  ('взмыленая', 'corr'): 1,
  ('огромная', 'pcorr'): 1,
  ('злая', 'pcorr'): 1,
  ('замыленная', 'incorr'): 1,
  ('легионерская', 'pcorr'): 1,
  ('и', 'incorr'): 1,
  ('застегнутая', 'incorr'): 1,
  ('уставшая', 'pcorr'): 1,
  ('резвая', 'pcorr'): 1,
  ('вспотевшая', 'corr'): 1,
  ('темная', 'pcorr'): 1},
 (130, 'шарахнулась', 'встрани'): {('nan', 'incorr'): 11,
  ('встала', 'pcorr'): 4,
  ('шарахнулась', 'corr'): 3,
  ('метнулась в сторону', 'corr'): 1,
  ('всбрыкнула и', 'pcorr'): 1,
  ('метнулась прочь и', 'pcorr'): 1,
  ('заржавши', 'pcorr'): 1,
  ('заржала', 'pcorr'): 1,
  ('резко остановилась', 'pcorr'): 1,
  ('его', 'incorr'): 1,
  ('выпрямилась', 'pcorr'): 1,
  ('вскочила', 'pcorr'): 1,
  ('встрепенулась', 'pcorr'): 1,
  ('остановилаь', 'pcorr'): 1,
  ('отпряла', 'corr'): 1,
  ('командира', 'incorr'): 1,
  ('остановившись', 'pcorr'): 1,
  ('резко', 'incorr'): 1,
  ('взяли и', 'incorr'): 1,
  ('посторонилась', 'pcorr'): 1,
  ('остановилась', 'pcorr'): 1,
  ('метнулась', 'pcorr'): 1},
 (131, 'командир', 'командирът'): {('командир', 'corr'): 26,
  ('nan', 'incorr'): 5,
  ('быстро', 'incorr'): 1,
  ('коммандир', 'corr'): 1,
  ('сильно', 'incorr'): 1,
  ('всадник', 'pcorr'): 1,
  ('вдруг', 'incorr'): 1,
  ('он', 'incorr'): 1},
 (132, 'шее', 'врата'): {('шее', 'corr'): 10,
  ('nan', 'incorr'): 8,
  ('крупу', 'pcorr'): 4,
  ('бокам', 'pcorr'): 3,
  ('спине', 'pcorr'): 2,
  ('боку', 'pcorr'): 2,
  ('заднице', 'pcorr'): 1,
  ('вратам', 'incorr'): 1,
  ('голове', 'pcorr'): 1,
  ('плечам', 'pcorr'): 1,
  ('грив', 'corr'): 1,
  ('заду', 'pcorr'): 1,
  ('задней части', 'pcorr'): 1,
  ('попе', 'pcorr'): 1},
 (133, 'полетели', 'полетяха'): {('полетели', 'corr'): 11,
  ('помчались', 'corr'): 3,
  ('nan', 'incorr'): 3,
  ('пролетели', 'corr'): 3,
  ('поскакали', 'corr'): 3,
  ('выстроились', 'pcorr'): 2,
  ('скачут', 'corr'): 2,
  ('скакали', 'corr'): 2,
  ('шли', 'pcorr'): 1,
  ('взлетели', 'pcorr'): 1,
  ('человека', 'incorr'): 1,
  ('пыльные', 'incorr'): 1,
  ('побежали', 'pcorr'): 1,
  ('появились', 'pcorr'): 1,
  ('летели', 'corr'): 1,
  ('проехали', 'pcorr'): 1},
 (134, 'туче', 'облак'): {('облаках', 'corr'): 12,
  ('облаке', 'corr'): 11,
  ('туче', 'corr'): 3,
  ('nan', 'incorr'): 3,
  ('конной', 'incorr'): 1,
  ('грязи', 'pcorr'): 1,
  ('дорожной', 'pcorr'): 1,
  ('клубах', 'corr'): 1,
  ('поднявшейся', 'pcorr'): 1,
  ('тумане', 'pcorr'): 1,
  ('облака', 'corr'): 1,
  ('столбе', 'pcorr'): 1},
 (135, 'пик', 'пики'): {('пик', 'corr'): 19,
  ('nan', 'incorr'): 5,
  ('копий', 'corr'): 3,
  ('палок', 'pcorr'): 2,
  ('лопаток', 'incorr'): 2,
  ('палочек', 'incorr'): 2,
  ('подков', 'incorr'): 1,
  ('пиков', 'corr'): 1,
  ('тапочек', 'incorr'): 1,
  ('лёгких пик', 'corr'): 1},
 (136, 'весело', 'весело'): {('весело', 'corr'): 16,
  ('nan', 'incorr'): 5,
  ('блестящими', 'pcorr'): 3,
  ('извергающимися', 'incorr'): 1,
  ('масками', 'incorr'): 1,
  ('широко', 'pcorr'): 1,
  ('зловеще', 'pcorr'): 1,
  ('веселыми', 'corr'): 1,
  ('блетящими', 'pcorr'): 1,
  ('сжатыми', 'pcorr'): 1,
  ('сильно', 'pcorr'): 1,
  ('злыми', 'pcorr'): 1,
  ('оголенными', 'pcorr'): 1,
  ('радостно', 'corr'): 1,
  ('белыми', 'pcorr'): 1,
  ('злобными', 'pcorr'): 1},
 (137, 'сверкающими', 'блестящи'): {('блестящими', 'corr'): 13,
  ('белыми', 'pcorr'): 7,
  ('nan', 'incorr'): 5,
  ('сверкающими', 'corr'): 4,
  ('по мордовски', 'incorr'): 1,
  ('жёлтыми', 'pcorr'): 1,
  ('светлыми', 'pcorr'): 1,
  ('изголодавшимися', 'pcorr'): 1,
  ('белоснежными', 'pcorr'): 1,
  ('поломанными', 'pcorr'): 1,
  ('коричневыми', 'pcorr'): 1,
  ('желтыми', 'pcorr'): 1},
 (138, 'солдат', 'войник'): {('воин', 'corr'): 17,
  ('солдат', 'corr'): 10,
  ('всадник', 'corr'): 4,
  ('nan', 'incorr'): 2,
  ('вождь', 'pcorr'): 1,
  ('командир', 'pcorr'): 1,
  ('он', 'incorr'): 1,
  ('салдат', 'corr'): 1},
 (139, 'трубою', 'тръба'): {('трубой', 'corr'): 11,
  ('nan', 'incorr'): 9,
  ('трубою', 'corr'): 3,
  ('сумкой', 'pcorr'): 2,
  ('сумко', 'incorr'): 1,
  ('турбиной', 'incorr'): 1,
  ('металический герб', 'incorr'): 1,
  ('трибой', 'incorr'): 1,
  ('тюрбой', 'incorr'): 1,
  ('шарфом', 'pcorr'): 1,
  ('тяжелой ношей', 'pcorr'): 1,
  ('защитой', 'pcorr'): 1,
  ('посохом', 'pcorr'): 1,
  ('накидкой', 'pcorr'): 1,
  ('трубкой', 'pcorr'): 1,
  ('щитом', 'pcorr'): 1},
 (140, 'морща', 'мръщеше'): {('морща', 'corr'): 19,
  ('nan', 'incorr'): 3,
  ('прикрывая', 'pcorr'): 2,
  ('сморщив', 'corr'): 2,
  ('хмурясь', 'corr'): 2,
  ('пряча', 'pcorr'): 1,
  ('нахмурившись', 'corr'): 1,
  ('потирая', 'pcorr'): 1,
  ('морщась', 'corr'): 1,
  ('его', 'incorr'): 1,
  ('хмуря', 'corr'): 1,
  ('наморщив', 'corr'): 1,
  ('кривя', 'corr'): 1,
  ('зажмурив', 'pcorr'): 1},
 (141, 'двинулся', 'продължи'): {('продолжил путь', 'corr'): 9,
  ('пошел', 'corr'): 9,
  ('двинулся', 'corr'): 3,
  ('продолжил', 'pcorr'): 3,
  ('nan', 'incorr'): 2,
  ('пошёл', 'corr'): 2,
  ('устремляясь', 'pcorr'): 1,
  ('ринулся', 'pcorr'): 1,
  ('поспешил', 'pcorr'): 1,
  ('уходил все', 'corr'): 1,
  ('прошёл', 'corr'): 1,
  ('убежал', 'pcorr'): 1,
  ('поехал', 'pcorr'): 1,
  ('шёл', 'corr'): 1,
  ('ускакал', 'pcorr'): 1},
 (142, 'двинулся', 'тръгнаха'): {('шли', 'corr'): 3,
  ('nan', 'incorr'): 3,
  ('отправились', 'pcorr'): 2,
  ('двинулись', 'corr'): 2,
  ('двинулся', 'corr'): 2,
  ('тронулись', 'corr'): 1,
  ('тронулся', 'corr'): 1,
  ('хана', 'incorr'): 1,
  ('пошли', 'corr'): 1,
  ('поскакали', 'pcorr'): 1,
  ('третий', 'incorr'): 1,
  ('следовали', 'corr'): 1,
  ('последовал', 'corr'): 1,
  ('последовали', 'corr'): 1,
  ('пошел', 'corr'): 1,
  ('двигались', 'corr'): 1,
  ('конвой', 'incorr'): 1,
  ('тряслись', 'pcorr'): 1,
  ('прошли', 'corr'): 1,
  ('устремились', 'corr'): 1,
  ('троеца', 'incorr'): 1,
  ('прыгали', 'pcorr'): 1,
  ('свора', 'incorr'): 1,
  ('следом', 'incorr'): 1,
  ('бежит', 'pcorr'): 1,
  ('втроём', 'incorr'): 1,
  ('проследовал', 'corr'): 1,
  ('трусил', 'pcorr'): 1,
  ('следовал', 'corr'): 1,
  ('ускакали', 'pcorr'): 1},
 (20, 'пустому', 'празния'): {('пустому', 'corr'): 10,
  ('nan', 'incorr'): 6,
  ('праздничному', 'incorr'): 3,
  ('коридору', 'pcorr'): 2,
  ('праздному', 'incorr'): 2,
  ('коридру', 'incorr'): 1,
  ('правому', 'pcorr'): 1,
  ('бесшумному', 'pcorr'): 1,
  ('парадная', 'incorr'): 1,
  ('прихожей', 'incorr'): 1,
  ('длинному', 'pcorr'): 1,
  ('красивому', 'pcorr'): 1,
  ('залу', 'incorr'): 1,
  ('парадной', 'incorr'): 1,
  ('темному', 'pcorr'): 1,
  ('большому', 'pcorr'): 1,
  ('празному', 'incorr'): 1,
  ('пустынному', 'corr'): 1,
  ('празднечному', 'incorr'): 1},
 (21, 'коридору', 'коридор'): {('коридору', 'corr'): 32,
  ('nan', 'incorr'): 3,
  ('полу', 'pcorr'): 1,
  ('переходу', 'pcorr'): 1},
 (22, 'здании', 'сграда'): {('помещении', 'pcorr'): 8,
  ('nan', 'incorr'): 6,
  ('здании', 'corr'): 6,
  ('кабинете', 'pcorr'): 4,
  ('доме', 'corr'): 3,
  ('месте', 'pcorr'): 2,
  ('строении', 'corr'): 2,
  ('столе', 'incorr'): 1,
  ('хранилище', 'pcorr'): 1,
  ('комнате', 'pcorr'): 1,
  ('складе', 'pcorr'): 1,
  ('городе', 'pcorr'): 1,
  ('зале', 'pcorr'): 1},
 (23, 'стеклянные', 'стъклени'): {('стеклянные', 'corr'): 30,
  ('nan', 'incorr'): 2,
  ('витринные', 'corr'): 1,
  ('маленькие', 'pcorr'): 1,
  ('застеклённые', 'corr'): 1,
  ('остекленные', 'corr'): 1,
  ('шкафчики', 'incorr'): 1},
 (24, 'инструментами', 'инструменти'): {('инструментами', 'corr'): 33,
  ('nan', 'incorr'): 2,
  ('ручками', 'pcorr'): 1,
  ('предметами', 'pcorr'): 1},
 (25, 'кресла', 'кресла'): {('кресла', 'corr'): 30,
  ('стулья', 'corr'): 3,
  ('люстры', 'pcorr'): 1,
  ('чертежи', 'pcorr'): 1,
  ('диваны', 'pcorr'): 1,
  ('кресла с использованием', 'corr'): 1},
 (26, 'колпаками', 'абажури'): {('абажурами', 'corr'): 29,
  ('абажюрами', 'corr'): 2,
  ('жидкостями', 'pcorr'): 1,
  ('огоньками', 'pcorr'): 1,
  ('плафонами', 'corr'): 1,
  ('абужурами где', 'corr'): 1,
  ('люстры', 'pcorr'): 1,
  ('nan', 'incorr'): 1},
 (27, 'провода', 'жици'): {('nan', 'incorr'): 9,
  ('провода', 'corr'): 7,
  ('щипцы', 'pcorr'): 4,
  ('лампы', 'pcorr'): 4,
  ('зажигалки', 'incorr'): 2,
  ('пассатижи', 'incorr'): 1,
  ('печи', 'pcorr'): 1,
  ('обогреватели', 'pcorr'): 1,
  ('розетки', 'pcorr'): 1,
  ('часы', 'pcorr'): 1,
  ('жицы', 'incorr'): 1,
  ('ножницы', 'pcorr'): 1,
  ('устройства', 'pcorr'): 1,
  ('горелки', 'pcorr'): 1,
  ('щиты', 'pcorr'): 1,
  ('шипцы', 'pcorr'): 1},
 (28, 'принялись', 'заловиха'): {('взялись', 'corr'): 7,
  ('nan', 'incorr'): 5,
  ('находились', 'pcorr'): 3,
  ('принялись', 'corr'): 3,
  ('зашли', 'pcorr'): 3,
  ('ждали', 'pcorr'): 2,
  ('схватились', 'pcorr'): 2,

In [15]:
cz_cognates = cognate_searcher(czech_ans, russian_true, czech_true)
cz_cognates

{(10, 'повернулся', 'otočil'): {('обернулся', 'pcorr'): 8,
  ('развернулся', 'corr'): 5,
  ('отвернулся', 'corr'): 4,
  ('nan', 'incorr'): 3,
  ('замолчал', 'pcorr'): 2,
  ('встал', 'pcorr'): 2,
  ('закончил', 'pcorr'): 2,
  ('посмотрел', 'pcorr'): 1,
  ('повернулся', 'corr'): 1,
  ('покричал', 'pcorr'): 1,
  ('отошёл', 'pcorr'): 1,
  ('повернул', 'corr'): 1,
  ('пригнулся', 'pcorr'): 1,
  ('оглянулся', 'pcorr'): 1,
  ('отскочил', 'pcorr'): 1,
  ('отскочил от края', 'pcorr'): 1,
  ('оточился', 'incorr'): 1,
  ('отошел', 'pcorr'): 1},
 (11, 'ступеням', 'stupňům'): {('ступеням', 'corr'): 24,
  ('ступенькам', 'corr'): 2,
  ('дороге', 'pcorr'): 2,
  ('замку', 'pcorr'): 2,
  ('nan', 'incorr'): 2,
  ('ступенька', 'corr'): 1,
  ('лестнице', 'corr'): 1,
  ('доиу', 'pcorr'): 1,
  ('трибуне', 'pcorr'): 1,
  ('месту', 'pcorr'): 1},
 (12, 'шашек', 'čtverce'): {('nan', 'incorr'): 5,
  ('камней', 'pcorr'): 4,
  ('квадратов', 'corr'): 4,
  ('досок', 'pcorr'): 3,
  ('плиток', 'corr'): 3,
  ('цветов', 'pcorr'): 2,
  ('бревен', 'pcorr'): 1,
  ('монет', 'incorr'): 1,
  ('ковра листьев', 'pcorr'): 1,
  ('листов', 'pcorr'): 1,
  ('квадратиков', 'corr'): 1,
  ('квадратного', 'incorr'): 1,
  ('пятен', 'pcorr'): 1,
  ('зеленого', 'incorr'): 1,
  ('квадротов', 'corr'): 1,
  ('шашек', 'corr'): 1,
  ('ковров', 'pcorr'): 1,
  ('четырёхугольников', 'pcorr'): 1,
  ('листьев из', 'pcorr'): 1,
  ('...', 'incorr'): 1,
  ('ковриков', 'pcorr'): 1,
  ('дощечек', 'pcorr'): 1},
 (13, 'спиною', 'zády'): {('спиной', 'corr'): 32,
  ('трибуной', 'pcorr'): 2,
  ('ухом', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('плечами', 'pcorr'): 1},
 (14, 'финики', 'fíků'): {('nan', 'incorr'): 13,
  ('инжир', 'pcorr'): 4,
  ('цветы', 'pcorr'): 3,
  ('и инжир', 'pcorr'): 2,
  ('фиги', 'pcorr'): 2,
  ('камни', 'pcorr'): 1,
  ('слушая', 'incorr'): 1,
  ('копейки', 'pcorr'): 1,
  ('на арену', 'pcorr'): 1,
  ('фрукты', 'pcorr'): 1,
  ('рычащую и негодующую', 'incorr'): 1,
  ('финики', 'corr'): 1,
  ('странно', 'incorr'): 1,
  ('слышал', 'pcorr'): 1,
  ('позвякивая', 'pcorr'): 1,
  ('по факту', 'incorr'): 1,
  ('украшения', 'pcorr'): 1,
  ('а также', 'incorr'): 1},
 (15, 'чудо', 'zázrak'): {('чудо', 'corr'): 13,
  ('nan', 'incorr'): 6,
  ('воочию', 'incorr'): 3,
  ('то', 'incorr'): 2,
  ('призрак', 'pcorr'): 2,
  ('его', 'incorr'): 2,
  ('закат', 'pcorr'): 1,
  ('волю', 'pcorr'): 1,
  ('властными', 'incorr'): 1,
  ('призрака', 'pcorr'): 1,
  ('индивидуума', 'pcorr'): 1,
  ('чудеса', 'corr'): 1,
  ('пилата', 'pcorr'): 1,
  ('...', 'incorr'): 1,
  ('зазракными', 'incorr'): 1},
 (16, 'вырвался', 'vyvázl'): {('вырвался', 'corr'): 16,
  ('наконец вырвался', 'corr'): 2,
  ('nan', 'incorr'): 2,
  ('но вылез', 'pcorr'): 2,
  ('наконец вылез', 'pcorr'): 1,
  ('вылез', 'pcorr'): 1,
  ('вылезал', 'pcorr'): 1,
  ('выскользнул', 'corr'): 1,
  ('наконец выбрался', 'pcorr'): 1,
  ('сбежал', 'corr'): 1,
  ('выкарабкался', 'pcorr'): 1,
  ('вырванный', 'pcorr'): 1,
  ('вырвется', 'corr'): 1,
  ('а прежде вырвался', 'corr'): 1,
  ('он вырвался', 'corr'): 1,
  ('выбрался', 'pcorr'): 1,
  ('но вырвался', 'corr'): 1,
  ('прежде', 'incorr'): 1,
  ('получил жизнь', 'pcorr'): 1},
 (17, 'веревки', 'pouta'): {('путы', 'corr'): 8,
  ('наручники', 'pcorr'): 7,
  ('nan', 'incorr'): 4,
  ('одежду', 'pcorr'): 4,
  ('верёвки', 'corr'): 3,
  ('путы (веревки)', 'corr'): 1,
  ('покров', 'pcorr'): 1,
  ('пот', 'pcorr'): 1,
  ('одеяния', 'pcorr'): 1,
  ('платье', 'pcorr'): 1,
  ('доспехи', 'pcorr'): 1,
  ('кольчугу', 'pcorr'): 1,
  ('веревки', 'corr'): 1,
  ('рубище', 'pcorr'): 1,
  ('пуанту', 'incorr'): 1,
  ('рубаху', 'pcorr'): 1},
 (18, 'допросе', 'výslechu'): {('nan', 'incorr'): 7,
  ('допросе', 'corr'): 6,
  ('запястьях', 'pcorr'): 5,
  ('виселице', 'pcorr'): 4,
  ('суставах', 'pcorr'): 2,
  ('локтях', 'pcorr'): 2,
  ('больных', 'incorr'): 1,
  ('плечах', 'incorr'): 1,
  ('столе', 'pcorr'): 1,
  ('весу', 'incorr'): 1,
  ('изгибах', 'pcorr'): 1,
  ('своих', 'incorr'): 1,
  ('допросах', 'corr'): 1,
  ('бестных', 'incorr'): 1,
  ('висилице', 'pcorr'): 1,
  ('кресте', 'pcorr'): 1,
  ('дыбах', 'pcorr'): 1},
 (19, 'сумасшедшей', 'pomateným'): {('nan', 'incorr'): 6,
  ('безумной', 'corr'): 4,
  ('помутненной', 'pcorr'): 3,
  ('помутневшей', 'pcorr'): 2,
  ('глупой', 'corr'): 2,
  ('помутнённой', 'pcorr'): 2,
  ('счастливой', 'pcorr'): 2,
  ('помутневший', 'pcorr'): 1,
  ('безмятежной', 'pcorr'): 1,
  ('усмешливой', 'pcorr'): 1,
  ('искренной', 'pcorr'): 1,
  ('болезненной', 'pcorr'): 1,
  ('манящей', 'pcorr'): 1,
  ('мягкой', 'pcorr'): 1,
  ('рассеяной', 'pcorr'): 1,
  ('непонимающей', 'pcorr'): 1,
  ('улыбкой', 'incorr'): 1,
  ('и грустной', 'pcorr'): 1,
  ('светлой', 'pcorr'): 1,
  ('жуткой', 'pcorr'): 1,
  ('загадочной', 'pcorr'): 1,
  ('вымученной', 'pcorr'): 1,
  ('последней', 'pcorr'): 1},
 (110, 'знал', 'věděl'): {('видел', 'pcorr'): 20,
  ('знал', 'corr'): 13,
  ('nan', 'incorr'): 1,
  ('понимал', 'pcorr'): 1,
  ('заметил', 'pcorr'): 1,
  ('меж тем', 'incorr'): 1},
 (111, 'ступеням', 'stupňům'): {('ступеням', 'corr'): 15,
  ('воротам', 'pcorr'): 5,
  ('nan', 'incorr'): 3,
  ('уровням', 'pcorr'): 3,
  ('ступенькам', 'corr'): 2,
  ('стенам', 'pcorr'): 2,
  ('стражам', 'pcorr'): 1,
  ('уровнем', 'incorr'): 1,
  ('столбам', 'pcorr'): 1,
  ('лестницам', 'corr'): 1,
  ('ступеням злодеев', 'corr'): 1,
  ('помостам', 'pcorr'): 1,
  ('крестам', 'pcorr'): 1},
 (112, 'дорогу', 'silnici'): {('дорогу', 'corr'): 20,
  ('nan', 'incorr'): 6,
  ('тропинку', 'pcorr'): 1,
  ('смертную дорогу', 'corr'): 1,
  ('солнце', 'incorr'): 1,
  ('запад', 'incorr'): 1,
  ('выход', 'incorr'): 1,
  ('площадь', 'pcorr'): 1,
  ('дорогу (?)', 'corr'): 1,
  ('улицу', 'corr'): 1,
  ('тропу', 'pcorr'): 1,
  ('симницу', 'incorr'): 1,
  ('владение смерти', 'incorr'): 1},
 (113, 'осужденных', 'odsouzenci'): {('осужденных', 'corr'): 7,
  ('nan', 'incorr'): 6,
  ('осуждённых', 'corr'): 3,
  ('отсюда', 'incorr'): 2,
  ('происхрдящее', 'pcorr'): 1,
  ('его', 'incorr'): 1,
  ('больше', 'incorr'): 1,
  ('людей', 'pcorr'): 1,
  ('но солнце', 'pcorr'): 1,
  ('глазами', 'pcorr'): 1,
  ('другого', 'incorr'): 1,
  ('толпу', 'pcorr'): 1,
  ('заимочек', 'incorr'): 1,
  ('приговорённых', 'corr'): 1,
  ('опасность', 'pcorr'): 1,
  ('узника', 'corr'): 1,
  ('однако', 'incorr'): 1,
  ('...', 'incorr'): 1,
  ('иешуа', 'pcorr'): 1,
  ('заусенцы', 'incorr'): 1,
  ('остального', 'incorr'): 1,
  ('никого', 'incorr'): 1,
  ('остальных', 'pcorr'): 1},
 (114, 'глашатаев', 'vyvolavačů'): {('nan', 'incorr'): 10,
  ('глашатаев', 'corr'): 3,
  ('людей', 'pcorr'): 3,
  ('толпы', 'pcorr'): 2,
  ('страждущих', 'incorr'): 2,
  ('зевак', 'pcorr'): 2,
  ('стражей', 'pcorr'): 1,
  ('глашатых', 'corr'): 1,
  ('заключенных', 'pcorr'): 1,
  ('их', 'incorr'): 1,
  ('палачей', 'pcorr'): 1,
  ('говоривших', 'incorr'): 1,
  ('призывателей', 'pcorr'): 1,
  ('вызывающих', 'incorr'): 1,
  ('выскочек', 'incorr'): 1,
  ('переводчиков / глашатаев', 'corr'): 1,
  ('провокаторов', 'pcorr'): 1,
  ('солдат', 'pcorr'): 1,
  ('попугаев', 'pcorr'): 1,
  ('восторга', 'incorr'): 1,
  ('слов', 'incorr'): 1},
 (115, 'греческом', 'řecky'): {('греческом', 'corr'): 14,
  ('nan', 'incorr'): 7,
  ('других', 'pcorr'): 3,
  ('ржецком', 'incorr'): 3,
  ('ржевском', 'incorr'): 1,
  ('но', 'incorr'): 1,
  ('русском', 'pcorr'): 1,
  ('рижском', 'incorr'): 1,
  ('шумершских', 'pcorr'): 1,
  ('местных', 'pcorr'): 1,
  ('греческий', 'corr'): 1,
  ('грубых', 'pcorr'): 1,
  ('еврейском', 'pcorr'): 1,
  ('иностранных', 'pcorr'): 1},
 (116, 'труба', 'troubení'): {('nan', 'incorr'): 13,
  ('труба', 'corr'): 5,
  ('толпа', 'pcorr'): 3,
  ('кто-то', 'incorr'): 1,
  ('голос', 'pcorr'): 1,
  ('так', 'incorr'): 1,
  ('приближаваяся', 'incorr'): 1,
  ('который', 'incorr'): 1,
  ('шум', 'pcorr'): 1,
  ('гудок', 'pcorr'): 1,
  ('удар', 'pcorr'): 1,
  ('приблизившись', 'incorr'): 1,
  ('ропот', 'pcorr'): 1,
  ('труба (?)', 'corr'): 1,
  ('цокот', 'incorr'): 1,
  ('лошадь', 'pcorr'): 1,
  ('...', 'incorr'): 1,
  ('приближение', 'incorr'): 1,
  ('кавалерия', 'incorr'): 1},
 (117, 'весело', 'veselé'): {('весело', 'corr'): 30,
  ('nan', 'incorr'): 4,
  ('нет', 'incorr'): 1,
  ('пронзительно', 'pcorr'): 1,
  ('кратко', 'pcorr'): 1},
 (118, 'мальчишек', 'chlapců'): {('nan', 'incorr'): 6,
  ('ветра', 'pcorr'): 3,
  ('доносившийся', 'pcorr'): 3,
  ('местных', 'pcorr'): 3,
  ('местных парней', 'corr'): 2,
  ('мальчишек', 'corr'): 2,
  ('местных мальчиков', 'corr'): 2,
  ('местных жителей', 'pcorr'): 2,
  ('местных хлопцев', 'corr'): 1,
  ('да', 'incorr'): 1,
  ('по селу', 'incorr'): 1,
  ('по всей длине улицы', 'pcorr'): 1,
  ('разносящийся', 'incorr'): 1,
  ('свирели', 'pcorr'): 1,
  ('телеги', 'pcorr'): 1,
  ('детей', 'corr'): 1,
  ('местных мальчишек', 'corr'): 1,
  ('местный хлопцев', 'corr'): 1,
  ('проникавший', 'incorr'): 1,
  ('горожан', 'pcorr'): 1,
  ('людей', 'pcorr'): 1,
  ('летевший', 'incorr'): 1},
 (119, 'солдат', 'voják'): {('вожак', 'pcorr'): 10,
  ('солдат', 'corr'): 9,
  ('воин', 'corr'): 7,
  ('nan', 'incorr'): 7,
  ('ладно', 'incorr'): 1,
  ('оратор', 'pcorr'): 1,
  ('предводитель', 'pcorr'): 1,
  ('главарь', 'pcorr'): 1},
 (120, 'значком', 'praporem'): {('знаменем', 'pcorr'): 10,
  ('nan', 'incorr'): 8,
  ('рупором', 'incorr'): 4,
  ('мечом', 'pcorr'): 2,
  ('свитком', 'pcorr'): 2,
  ('прапором?', 'incorr'): 1,
  ('свёртком', 'pcorr'): 1,
  ('нет', 'incorr'): 1,
  ('флагом', 'pcorr'): 1,
  ('струпором', 'incorr'): 1,
  ('рапортом', 'incorr'): 1,
  ('топором', 'pcorr'): 1,
  ('...', 'incorr'): 1,
  ('стягом', 'pcorr'): 1,
  ('копьем', 'pcorr'): 1,
  ('скипетром', 'pcorr'): 1},
 (121, 'остановились', 'zastavili'): {('остановились', 'corr'): 12,
  ('nan', 'incorr'): 11,
  ('заставили', 'incorr'): 2,
  ('ушли', 'pcorr'): 2,
  ('отошли в сторону', 'pcorr'): 1,
  ('увидели это', 'pcorr'): 1,
  ('скакунов', 'incorr'): 1,
  ('его доставили', 'pcorr'): 1,
  ('начали', 'pcorr'): 1,
  ('выстроились', 'pcorr'): 1,
  ('обернулись', 'pcorr'): 1,
  ('замерли', 'pcorr'): 1,
  ('отступили', 'pcorr'): 1,
  ('его обступили', 'pcorr'): 1},
 (122, 'вылетела', 'řítila'): {('nan', 'incorr'): 10,
  ('выскочила', 'corr'): 4,
  ('выходила', 'pcorr'): 3,
  ('выехала', 'pcorr'): 3,
  ('прискакала', 'pcorr'): 2,
  ('вышла', 'pcorr'): 2,
  ('входила', 'pcorr'): 1,
  ('шагала', 'pcorr'): 1,
  ('но', 'incorr'): 1,
  ('побрела', 'pcorr'): 1,
  ('бросилась', 'pcorr'): 1,
  ('планировала выехать', 'pcorr'): 1,
  ('въехала', 'pcorr'): 1,
  ('поскакала', 'pcorr'): 1,
  ('взобралась', 'pcorr'): 1,
  ('вошла', 'pcorr'): 1,
  ('устремилась', 'pcorr'): 1,
  ('ржитила', 'incorr'): 1,
  ('наступила', 'pcorr'): 1},
 (123, 'каменной', 'kamenné'): {('каменной', 'corr'): 25,
  ('nan', 'incorr'): 8,
  ('да', 'incorr'): 1,
  ('рухнувшей', 'pcorr'): 1,
  ('крепостной', 'pcorr'): 1,
  ('крутой', 'pcorr'): 1},
 (124, 'виноград', 'dorazit'): {('nan', 'incorr'): 16,
  ('плющ', 'pcorr'): 3,
  ('виноград', 'corr'): 3,
  ('дым', 'pcorr'): 2,
  ('ведь', 'incorr'): 1,
  ('я', 'incorr'): 1,
  ('цветок', 'pcorr'): 1,
  ('виноградный куст', 'corr'): 1,
  ('ров', 'pcorr'): 1,
  ('красный', 'incorr'): 1,
  ('туман', 'pcorr'): 1,
  ('плющом', 'pcorr'): 1,
  ('мосток', 'pcorr'): 1,
  ('участок', 'incorr'): 1,
  ('мох', 'pcorr'): 1,
  ('...', 'incorr'): 1,
  ('ревень и вдоль которой', 'incorr'): 1},
 (125, 'дорогой', 'cestou'): {('дорогой', 'corr'): 16,
  ('nan', 'incorr'): 10,
  ('путь', 'corr'): 4,
  ('тропой', 'pcorr'): 2,
  ('дорогой можно', 'corr'): 2,
  ('да', 'incorr'): 1,
  ('путем', 'corr'): 1,
  ('...', 'incorr'): 1},
 (126, 'мальчик', 'chlapecké'): {('nan', 'incorr'): 14,
  ('мальчик', 'corr'): 6,
  ('ребенок', 'corr'): 2,
  ('комар', 'pcorr'): 1,
  ('муха', 'pcorr'): 1,
  ('нет', 'incorr'): 1,
  ('муж', 'incorr'): 1,
  ('мышь', 'pcorr'): 1,
  ('хлопец', 'corr'): 1,
  ('стрела', 'pcorr'): 1,
  ('хорек', 'pcorr'): 1,
  ('ребёнок', 'corr'): 1,
  ('карлик', 'pcorr'): 1,
  ('пони', 'pcorr'): 1,
  ('черт', 'pcorr'): 1,
  ('...', 'incorr'): 1,
  ('дитя', 'corr'): 1,
  ('пуля', 'pcorr'): 1},
 (127, 'командир', 'velitel'): {('nan', 'incorr'): 16,
  ('командир', 'corr'): 3,
  ('мужчина', 'pcorr'): 2,
  ('предводитель', 'pcorr'): 2,
  ('что', 'incorr'): 1,
  ('красен', 'incorr'): 1,
  ('плети', 'incorr'): 1,
  ('ведущий', 'pcorr'): 1,
  ('суран', 'incorr'): 1,
  ('по происхождению', 'incorr'): 1,
  ('пилат', 'incorr'): 1,
  ('кучер', 'pcorr'): 1,
  ('летел как стрела', 'incorr'): 1,
  ('человек', 'pcorr'): 1,
  ('...', 'incorr'): 1,
  ('глава', 'pcorr'): 1,
  ('всадник', 'pcorr'): 1,
  ('повелитель кавалерийской', 'incorr'): 1},
 (128, 'выхватил', 'vykřikl'): {('выхватил', 'corr'): 10,
  ('nan', 'incorr'): 8,
  ('вынул', 'corr'): 6,
  ('вытащил', 'corr'): 5,
  ('достал', 'corr'): 3,
  ('как', 'incorr'): 1,
  ('высунул', 'pcorr'): 1,
  ('вырвал', 'pcorr'): 1,
  ('выдернул', 'corr'): 1,
  ('доставал', 'corr'): 1},
 (129, 'взмокшая', 'zpocený'): {('nan', 'incorr'): 16,
  ('потная', 'corr'): 3,
  ('вспотевшая', 'corr'): 2,
  ('вражеская', 'pcorr'): 1,
  ('скорая', 'incorr'): 1,
  ('скаковая', 'pcorr'): 1,
  ('ударила', 'incorr'): 1,
  ('буйная', 'pcorr'): 1,
  ('испуганная', 'pcorr'): 1,
  ('строптивая', 'pcorr'): 1,
  ('быстрая', 'pcorr'): 1,
  ('бешеная', 'pcorr'): 1,
  ('черная', 'pcorr'): 1,
  ('разьяренная', 'pcorr'): 1,
  ('дивная', 'pcorr'): 1,
  ('уставшая', 'pcorr'): 1,
  ('взмыленная', 'corr'): 1,
  ('огромная', 'pcorr'): 1,
  ('его', 'incorr'): 1},
 (130, 'шарахнулась', 'uskočil'): {('nan', 'incorr'): 11,
  ('отскочила в сторону', 'corr'): 6,
  ('бросилась в сторону', 'pcorr'): 3,
  ('всхрипела', 'pcorr'): 1,
  ('странно', 'incorr'): 1,
  ('быстро', 'pcorr'): 1,
  ('запала', 'incorr'): 1,
  ('которая', 'incorr'): 1,
  ('скакнула вбок', 'corr'): 1,
  ('в сторону', 'pcorr'): 1,
  ('отскочила', 'corr'): 1,
  ('заржав', 'pcorr'): 1,
  ('прокуратора', 'incorr'): 1,
  ('отпрыгнула', 'pcorr'): 1,
  ('прискакала', 'pcorr'): 1,
  ('остановившись', 'pcorr'): 1,
  ('скача', 'incorr'): 1,
  ('отскочила в строну', 'corr'): 1,
  ('вскочила', 'pcorr'): 1,
  ('отскочила в сторону и', 'corr'): 1},
 (131, 'командир', 'velitel'): {('nan', 'incorr'): 12,
  ('он', 'incorr'): 4,
  ('командир', 'corr'): 4,
  ('всадник', 'pcorr'): 4,
  ('повелитель', 'pcorr'): 2,
  ('бичем', 'incorr'): 1,
  ('бичевкой', 'incorr'): 1,
  ('ведущий', 'pcorr'): 1,
  ('резко', 'incorr'): 1,
  ('взмахнув', 'incorr'): 1,
  ('кучер', 'pcorr'): 1,
  ('сириец', 'pcorr'): 1,
  ('солдат', 'pcorr'): 1,
  ('велитель', 'incorr'): 1,
  ('наездник', 'pcorr'): 1,
  ('их вожак', 'pcorr'): 1},
 (132, 'шее', 'hřbetě'): {('хребту', 'pcorr'): 14,
  ('спине', 'pcorr'): 11,
  ('nan', 'incorr'): 8,
  ('шее', 'corr'): 1,
  ('крупу', 'pcorr'): 1,
  ('боку', 'pcorr'): 1,
  ('хребту (спине)', 'pcorr'): 1},
 (133, 'полетели', 'hnaly'): {('nan', 'incorr'): 9,
  ('скакали', 'corr'): 6,
  ('шли', 'pcorr'): 3,
  ('мчались', 'corr'): 3,
  ('гнали', 'pcorr'): 3,
  ('погнались', 'pcorr'): 2,
  ('гнались', 'pcorr'): 2,
  ('облаченные в доспехи', 'incorr'): 1,
  ('в облаках', 'incorr'): 1,
  ('поехали', 'pcorr'): 1,
  ('погнали', 'pcorr'): 1,
  ('поскакали', 'corr'): 1,
  ('устремились', 'pcorr'): 1,
  ('солдаты', 'incorr'): 1,
  ('ехали', 'pcorr'): 1,
  ('неслись', 'corr'): 1},
 (134, 'туче', 'oblacích'): {('облаках', 'corr'): 11,
  ('nan', 'incorr'): 10,
  ('клубах', 'corr'): 3,
  ('дорожной', 'pcorr'): 3,
  ('облаке', 'corr'): 2,
  ('густой', 'incorr'): 1,
  ('полной', 'incorr'): 1,
  ('одеждах все в', 'pcorr'): 1,
  ('бамбуковой', 'incorr'): 1,
  ('поднятой', 'incorr'): 1,
  ('клубе', 'corr'): 1,
  ('столбах', 'pcorr'): 1,
  ('поднятой дорожной', 'pcorr'): 1},
 (135, 'пик', 'kopí'): {('копий', 'corr'): 17,
  ('nan', 'incorr'): 10,
  ('копей', 'corr'): 3,
  ('копьев', 'corr'): 2,
  ('стебелт', 'incorr'): 1,
  ('палок', 'pcorr'): 1,
  ('тапочках', 'incorr'): 1,
  ('палочек', 'incorr'): 1,
  ('плетей', 'incorr'): 1},
 (136, 'весело', 'vesele'): {('nan', 'incorr'): 12,
  ('весело', 'corr'): 7,
  ('веселыми', 'corr'): 6,
  ('черными', 'pcorr'): 4,
  ('сильно', 'pcorr'): 2,
  ('турок', 'incorr'): 1,
  ('блестящими', 'pcorr'): 1,
  ('гнилыми', 'pcorr'): 1,
  ('радостно', 'corr'): 1,
  ('злыми', 'pcorr'): 1,
  ('белыми', 'pcorr'): 1},
 (137, 'сверкающими', 'svítivými'): {('nan', 'incorr'): 11,
  ('светлыми', 'pcorr'): 5,
  ('белыми', 'pcorr'): 2,
  ('желтыми', 'pcorr'): 2,
  ('блестящими', 'corr'): 2,
  ('кривыми', 'pcorr'): 2,
  ('сверкающими', 'corr'): 1,
  ('светившими', 'pcorr'): 1,
  ('чистыми', 'pcorr'): 1,
  ('светящимися', 'pcorr'): 1,
  ('редкими', 'pcorr'): 1,
  ('выставленными', 'pcorr'): 1,
  ('блесящими', 'corr'): 1,
  ('пылающими', 'pcorr'): 1,
  ('острыми', 'pcorr'): 1,
  ('сияющими', 'corr'): 1,
  ('выцветвишими', 'pcorr'): 1,
  ('в улыбке', 'incorr'): 1,
  ('стиснутыми', 'pcorr'): 1},
 (138, 'солдат', 'voják'): {('nan', 'incorr'): 9,
  ('солдат', 'corr'): 9,
  ('вожак', 'pcorr'): 7,
  ('воин', 'corr'): 4,
  ('всадник', 'corr'): 3,
  ('командир', 'pcorr'): 1,
  ('быстро', 'incorr'): 1,
  ('конем', 'incorr'): 1,
  ('главарь (вожак)', 'pcorr'): 1,
  ('главарь', 'pcorr'): 1},
 (139, 'трубою', 'trubkou'): {('трубой', 'corr'): 13,
  ('nan', 'incorr'): 10,
  ('трубкой', 'pcorr'): 8,
  ('саблей', 'pcorr'): 2,
  ('трубкой?', 'incorr'): 1,
  ('взгляд', 'incorr'): 1,
  ('мечом', 'pcorr'): 1,
  ('саблею', 'pcorr'): 1},
 (140, 'морща', 'svraštil'): {('nan', 'incorr'): 9,
  ('морща', 'corr'): 8,
  ('кривя', 'corr'): 4,
  ('скривив', 'corr'): 3,
  ('сморщив', 'corr'): 3,
  ('отворачивая', 'pcorr'): 2,
  ('прикрывает', 'pcorr'): 1,
  ('скорчил', 'pcorr'): 1,
  ('закрыв', 'pcorr'): 1,
  ('наморщив', 'corr'): 1,
  ('нахмурив', 'pcorr'): 1,
  ('прикрыв', 'pcorr'): 1,
  ('отвернул', 'incorr'): 1,
  ('ноющее', 'incorr'): 1},
 (141, 'двинулся', 'mířil'): {('nan', 'incorr'): 11,
  ('пошел', 'corr'): 8,
  ('пошёл', 'corr'): 3,
  ('направился', 'corr'): 2,
  ('шел', 'corr'): 2,
  ('снова пошел', 'corr'): 1,
  ('идет', 'corr'): 1,
  ('выскочил', 'pcorr'): 1,
  ('зашагал', 'corr'): 1,
  ('двинулся', 'corr'): 1,
  ('поскакали', 'pcorr'): 1,
  ('идёт', 'corr'): 1,
  ('ехал', 'pcorr'): 1,
  ('поскакал', 'pcorr'): 1,
  ('бежал', 'pcorr'): 1,
  ('отправился', 'corr'): 1},
 (142, 'двинулся', 'mířili'): {('nan', 'incorr'): 10,
  ('шли', 'corr'): 7,
  ('спешили', 'pcorr'): 2,
  ('следовали', 'corr'): 2,
  ('устремились', 'corr'): 1,
  ('арда', 'incorr'): 1,
  ('скакали', 'pcorr'): 1,
  ('находились', 'pcorr'): 1,
  ('мчали', 'pcorr'): 1,
  ('чеканили шаг', 'pcorr'): 1,
  ('направился', 'corr'): 1,
  ('последовали', 'corr'): 1,
  ('пролегал', 'incorr'): 1,
  ('минуя', 'incorr'): 1,
  ('следуют', 'corr'): 1,
  ('ехали', 'pcorr'): 1,
  ('стояли', 'pcorr'): 1,
  ('пошли', 'corr'): 1,
  ('семенили', 'pcorr'): 1,
  ('отправился', 'corr'): 1},
 (20, 'пустому', 'prázdnou'): {('пустому', 'corr'): 14,
  ('тихому', 'pcorr'): 5,
  ('nan', 'incorr'): 3,
  ('праздничному', 'incorr'): 2,
  ('длинному', 'pcorr'): 2,
  ('коридору', 'pcorr'): 2,
  ('праздному', 'incorr'): 2,
  ('лестнице', 'incorr'): 2,
  ('ковру', 'incorr'): 1,
  ('большому', 'pcorr'): 1,
  ('больнице', 'incorr'): 1,
  ('прихожей', 'incorr'): 1,
  ('двору', 'incorr'): 1,
  ('темному', 'pcorr'): 1,
  ('украшенному', 'pcorr'): 1,
  ('широкому', 'pcorr'): 1},
 (21, 'коридору', 'chodbou'): {('коридору', 'corr'): 29,
  ('nan', 'incorr'): 3,
  ('корридору', 'corr'): 2,
  ('ковру', 'pcorr'): 1,
  ('паркету', 'pcorr'): 1,
  ('холлу', 'corr'): 1,
  ('вскоре', 'incorr'): 1,
  ('проходу', 'pcorr'): 1,
  ('пути', 'pcorr'): 1},
 (22, 'здании', 'budovy'): {('кабинете', 'pcorr'): 10,
  ('здании', 'corr'): 9,
  ('месте', 'pcorr'): 5,
  ('доме', 'corr'): 5,
  ('помещении', 'pcorr'): 4,
  ('nan', 'incorr'): 4,
  ('строении', 'corr'): 1,
  ('коридоре', 'pcorr'): 1,
  ('зданием', 'corr'): 1},
 (23, 'стеклянные', 'skleněné'): {('стеклянные', 'corr'): 14,
  ('маленькие', 'pcorr'): 10,
  ('nan', 'incorr'): 7,
  ('небольшие', 'pcorr'): 3,
  ('совместные', 'incorr'): 1,
  ('новые', 'pcorr'): 1,
  ('шкафчики', 'incorr'): 1,
  ('склеенные', 'pcorr'): 1,
  ('столы', 'incorr'): 1,
  ('застеклённые', 'corr'): 1},

In [16]:
pol_cognates = cognate_searcher(polish_ans, russian_true, polish_true)
pol_cognates

{(10, 'повернулся', 'odwrócił'): {('повернулся', 'corr'): 11,
  ('развернулся', 'corr'): 4,
  ('оглянулся', 'pcorr'): 3,
  ('встал', 'pcorr'): 2,
  ('обернулся', 'pcorr'): 2,
  ('отвернулся', 'corr'): 2,
  ('подумал', 'pcorr'): 1,
  ('откинул это', 'incorr'): 1,
  ('взял', 'corr'): 1,
  ('прикрыл глаза', 'pcorr'): 1,
  ('открыл дверь', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('поверил в это', 'incorr'): 1,
  ('одбросил', 'incorr'): 1,
  ('повернулся назад', 'corr'): 1,
  ('одумался', 'incorr'): 1,
  ('оглядел его', 'pcorr'): 1,
  ('вздохнул', 'pcorr'): 1},
 (11, 'ступеням', 'schodów'): {('лестнице', 'corr'): 9,
  ('ступеням', 'corr'): 4,
  ('nan', 'incorr'): 3,
  ('выходу', 'pcorr'): 3,
  ('замку', 'pcorr'): 2,
  ('спуску', 'pcorr'): 1,
  ('дороге', 'pcorr'): 1,
  ('сторону сходней', 'incorr'): 1,
  ('лестнице, спуску', 'corr'): 1,
  ('реке', 'pcorr'): 1,
  ('школе', 'pcorr'): 1,
  ('судам', 'pcorr'): 1,
  ('плахе', 'pcorr'): 1,
  ('обрыву', 'pcorr'): 1,
  ('оврагу', 'pcorr'): 1,
  ('толпе', 'pcorr'): 1,
  ('камню', 'pcorr'): 1,
  ('стороне', 'incorr'): 1,
  ('возвышению', 'pcorr'): 1,
  ('другому берегу', 'pcorr'): 1},
 (12, 'шашек', 'szachownicę'): {('камней', 'pcorr'): 7,
  ('досок', 'pcorr'): 4,
  ('nan', 'incorr'): 4,
  ('листьев', 'pcorr'): 4,
  ('камушков', 'pcorr'): 3,
  ('узоров', 'corr'): 3,
  ('шахматного', 'pcorr'): 2,
  ('плиток', 'corr'): 2,
  ('шашек', 'corr'): 2,
  ('шахмат', 'pcorr'): 1,
  ('пятен', 'pcorr'): 1,
  ('цветов', 'pcorr'): 1,
  ('половиц', 'pcorr'): 1,
  ('перил и', 'pcorr'): 1},
 (13, 'спиною', 'plecami'): {('спиной', 'corr'): 15,
  ('плечами', 'pcorr'): 15,
  ('nan', 'incorr'): 2,
  ('его плечами', 'pcorr'): 2,
  ('террасой', 'pcorr'): 1,
  ('град', 'incorr'): 1},
 (14, 'финики', 'palmowe'): {('nan', 'incorr'): 5,
  ('орешки', 'incorr'): 4,
  ('пальмовые орешки', 'incorr'): 2,
  ('кокосы', 'pcorr'): 2,
  ('пальмовые орехи', 'incorr'): 2,
  ('финики', 'corr'): 2,
  ('пальмовые ветви', 'incorr'): 2,
  ('камни и плевки', 'pcorr'): 1,
  ('настолько громко', 'incorr'): 1,
  ('пальмовые ветки', 'pcorr'): 1,
  ('и орешки пальмовые', 'incorr'): 1,
  ('понял', 'pcorr'): 1,
  ('ощущал', 'incorr'): 1,
  ('драгоценности', 'pcorr'): 1,
  ('финики (пальмовые орехи)', 'corr'): 1,
  ('оливки', 'pcorr'): 1,
  ('серебряники', 'pcorr'): 1,
  ('видел', 'incorr'): 1,
  ('бумажки', 'pcorr'): 1,
  ('конфеты', 'pcorr'): 1,
  ('и оклики', 'pcorr'): 1,
  ('шапки', 'pcorr'): 1,
  ('и пальмовые орехи', 'incorr'): 1,
  ('глядя', 'incorr'): 1},
 (15, 'чудо', 'cud'): {('чудо', 'corr'): 24,
  ('nan', 'incorr'): 3,
  ('воочию', 'incorr'): 1,
  ('то чудо', 'corr'): 1,
  ('на яву', 'incorr'): 1,
  ('картину', 'pcorr'): 1,
  ('невозможное', 'corr'): 1,
  ('человека', 'pcorr'): 1,
  ('властными', 'incorr'): 1,
  ('то', 'incorr'): 1,
  ('это чудо', 'corr'): 1},
 (16, 'вырвался', 'wyrwał'): {('вырвался', 'corr'): 21,
  ('выбрался', 'pcorr'): 3,
  ('nan', 'incorr'): 2,
  ('который вырвался', 'corr'): 2,
  ('вырвал', 'pcorr'): 2,
  ('который вырван', 'pcorr'): 1,
  ('вырвал  рак', 'corr'): 1,
  ('и который вырвал себя', 'corr'): 1,
  ('бежит', 'pcorr'): 1,
  ('и который вырвался', 'corr'): 1,
  ('и который вырвался.', 'corr'): 1},
 (17, 'веревки', 'więzy'): {('кандалы', 'pcorr'): 6,
  ('nan', 'incorr'): 5,
  ('веревки', 'corr'): 5,
  ('оковы', 'pcorr'): 4,
  ('путы', 'corr'): 3,
  ('цепи', 'pcorr'): 2,
  ('узы', 'corr'): 1,
  ('повязки', 'pcorr'): 1,
  ('наручники', 'pcorr'): 1,
  ('вензеля', 'pcorr'): 1,
  ('верёвки', 'corr'): 1,
  ('skórze', 'incorr'): 1,
  ('вены', 'incorr'): 1,
  ('броню', 'pcorr'): 1,
  ('ордена', 'pcorr'): 1,
  ('веревку', 'corr'): 1,
  ('одежду', 'pcorr'): 1},
 (18, 'допросе', 'śledztwa'): {('запястьях', 'pcorr'): 8,
  ('nan', 'incorr'): 7,
  ('допросе', 'corr'): 3,
  ('суставах', 'pcorr'): 2,
  ('время следствия', 'corr'): 2,
  ('следствии', 'corr'): 2,
  ('ранах', 'pcorr'): 1,
  ('допросах', 'corr'): 1,
  ('корню', 'incorr'): 1,
  ('наружу', 'incorr'): 1,
  ('дознании', 'corr'): 1,
  ('совсем', 'incorr'): 1,
  ('изнанку', 'incorr'): 1,
  ('запястиях', 'pcorr'): 1,
  ('чашных', 'incorr'): 1,
  ('сражениях', 'pcorr'): 1,
  ('зад', 'incorr'): 1,
  ('расследованиях', 'corr'): 1},
 (19, 'сумасшедшей', 'obłędnym'): {('бледной', 'pcorr'): 6,
  ('nan', 'incorr'): 3,
  ('безумной', 'corr'): 3,
  ('вымученной', 'pcorr'): 2,
  ('холодной', 'pcorr'): 2,
  ('беззубой', 'pcorr'): 1,
  ('насмешливой', 'pcorr'): 1,
  ('нелепой', 'pcorr'): 1,
  ('заразительной', 'pcorr'): 1,
  ('глупой', 'corr'): 1,
  ('и бессознательной', 'pcorr'): 1,
  ('ленивой', 'pcorr'): 1,
  ('ледяной', 'pcorr'): 1,
  ('широкой', 'pcorr'): 1,
  ('обалделой', 'corr'): 1,
  ('дурацкой', 'corr'): 1,
  ('растерянной (?)', 'pcorr'): 1,
  ('безличной', 'pcorr'): 1,
  ('сумасшедшей ухмылкой', 'corr'): 1,
  ('заразной', 'pcorr'): 1,
  ('сумасшедшей', 'corr'): 1,
  ('слабой', 'pcorr'): 1,
  ('пустой', 'pcorr'): 1,
  ('счастливой', 'pcorr'): 1,
  ('гримасой', 'incorr'): 1},
 (110, 'знал', 'wiedział'): {('видел', 'pcorr'): 14,
  ('знал', 'corr'): 14,
  ('nan', 'incorr'): 2,
  ('увидел', 'pcorr'): 2,
  ('заметил', 'pcorr'): 1,
  ('сказал', 'pcorr'): 1,
  ('понял', 'pcorr'): 1,
  ('взвыл', 'pcorr'): 1},
 (111, 'ступеням', 'schodkom'): {('ступеням', 'corr'): 7,
  ('лестницам', 'corr'): 6,
  ('nan', 'incorr'): 4,
  ('воротам', 'pcorr'): 4,
  ('дверям', 'pcorr'): 2,
  ('выходам', 'pcorr'): 2,
  ('сходкам', 'incorr'): 2,
  ('помостам', 'pcorr'): 1,
  ('сходням', 'corr'): 1,
  ('стенам', 'pcorr'): 1,
  ('телегам', 'pcorr'): 1,
  ('виновых', 'incorr'): 1,
  ('линиям', 'pcorr'): 1,
  ('легионерам', 'pcorr'): 1,
  ('входам', 'pcorr'): 1,
  ('машинам', 'pcorr'): 1},
 (112, 'дорогу', 'drogę'): {('дорогу', 'corr'): 32,
  ('лестницу', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('улицу', 'corr'): 1,
  ('площадь', 'pcorr'): 1},
 (113, 'осужденных', 'skazańców'): {('nan', 'incorr'): 10,
  ('осуждённых', 'corr'): 2,
  ('больше', 'incorr'): 2,
  ('что происходит с тремя', 'incorr'): 1,
  ('конвой', 'pcorr'): 1,
  ('угрозы', 'pcorr'): 1,
  ('остальное', 'pcorr'): 1,
  ('сказал', 'incorr'): 1,
  ('каторжников', 'pcorr'): 1,
  ('советников', 'pcorr'): 1,
  ('осужденных', 'corr'): 1,
  ('грозу', 'pcorr'): 1,
  ('город', 'pcorr'): 1,
  ('но теперь', 'incorr'): 1,
  ('первосвященников', 'pcorr'): 1,
  ('грозу', 'incorr'): 1,
  ('но', 'incorr'): 1,
  ('врагов', 'pcorr'): 1,
  ('обвиняемых', 'corr'): 1,
  ('дальнейшее', 'pcorr'): 1,
  ('хотя', 'incorr'): 1,
  ('связанных', 'pcorr'): 1,
  ('заключенных', 'corr'): 1,
  ('их', 'incorr'): 1,
  ('что было сзади', 'incorr'): 1},
 (114, 'глашатаев', 'heroldów'): {('nan', 'incorr'): 8,
  ('глашатаев', 'corr'): 7,
  ('людей', 'pcorr'): 4,
  ('герольдов', 'corr'): 3,
  ('зрителей', 'pcorr'): 2,
  ('горожан', 'pcorr'): 1,
  ('толпы', 'pcorr'): 1,
  ('переводчиков', 'pcorr'): 1,
  ('глашатая', 'corr'): 1,
  ('толп', 'pcorr'): 1,
  ('солдат', 'pcorr'): 1,
  ('гонцов', 'pcorr'): 1,
  ('надсмоторщиков', 'pcorr'): 1,
  ('колдунов', 'pcorr'): 1,
  ('глашатых', 'corr'): 1,
  ('глашати', 'corr'): 1,
  ('зевак', 'pcorr'): 1},
 (115, 'греческом', 'grecku'): {('греческом', 'corr'): 30,
  ('nan', 'incorr'): 2,
  ('арабском', 'pcorr'): 1,
  ('древних', 'pcorr'): 1,
  ('грецком', 'pcorr'): 1,
  ('жаргоне', 'incorr'): 1},
 (116, 'труба', 'trąbki'): {('труба', 'corr'): 10,
  ('nan', 'incorr'): 8,
  ('женщина', 'pcorr'): 3,
  ('веселый', 'incorr'): 2,
  ('на площадь выбежала женщина', 'incorr'): 1,
  ('голос торговки', 'pcorr'): 1,
  ('девушка', 'pcorr'): 1,
  ('весёлый голос', 'pcorr'): 1,
  ('голос трубы', 'corr'): 1,
  ('трубы', 'corr'): 1,
  ('гул', 'pcorr'): 1,
  ('ржанье', 'pcorr'): 1,
  ('звук повозки', 'pcorr'): 1,
  ('ржач', 'incorr'): 1,
  ('веселым голосом', 'pcorr'): 1,
  ('звук трубы', 'corr'): 1,
  ('гоготанье', 'pcorr'): 1},
 (117, 'весело', 'wesoły'): {('весело', 'corr'): 12,
  ('nan', 'incorr'): 7,
  ('громко', 'pcorr'): 7,
  ('отрывисто', 'pcorr'): 2,
  ('звонко', 'corr'): 1,
  ('требовательно', 'pcorr'): 1,
  ('робко', 'pcorr'): 1,
  ('рвано', 'pcorr'): 1,
  ('труба', 'incorr'): 1,
  ('глухо', 'pcorr'): 1,
  ('голос', 'incorr'): 1,
  ('зычно', 'pcorr'): 1},
 (118, 'мальчишек', 'chłopców'): {('мальчишек', 'corr'): 7,
  ('парней', 'corr'): 5,
  ('мальчиков', 'corr'): 4,
  ('nan', 'incorr'): 4,
  ('юношей', 'corr'): 2,
  ('людей', 'pcorr'): 2,
  ('стрел', 'pcorr'): 1,
  ('двери', 'pcorr'): 1,
  ('кнута', 'pcorr'): 1,
  ('молодёжи', 'pcorr'): 1,
  ('жителей', 'pcorr'): 1,
  ('мужчин', 'pcorr'): 1,
  ('толпы', 'pcorr'): 1,
  ('хлопцов', 'corr'): 1,
  ('хлопцев', 'corr'): 1,
  ('ребят свисавших', 'corr'): 1,
  ('слетавший', 'incorr'): 1,
  ('ветра', 'pcorr'): 1},
 (119, 'солдат', 'żołnierz'): {('солдат', 'corr'): 12,
  ('nan', 'incorr'): 7,
  ('человек', 'pcorr'): 4,
  ('судья', 'pcorr'): 2,
  ('мужчина', 'pcorr'): 2,
  ('всадник', 'pcorr'): 1,
  ('однако', 'incorr'): 1,
  ('уставший солдат', 'corr'): 1,
  ('самый последний', 'incorr'): 1,
  ('местный смотритель', 'pcorr'): 1,
  ('один стражник', 'corr'): 1,
  ('мальчик', 'pcorr'): 1,
  ('воин', 'corr'): 1,
  ('боец', 'corr'): 1},
 (120, 'значком', 'znakiem'): {('знаменем', 'pcorr'): 9,
  ('nan', 'incorr'): 8,
  ('знаком', 'corr'): 6,
  ('свитком', 'pcorr'): 2,
  ('флагом', 'pcorr'): 2,
  ('свертком', 'pcorr'): 2,
  ('значком', 'corr'): 2,
  ('стиснутым знаменем', 'pcorr'): 1,
  ('палкой', 'pcorr'): 1,
  ('кнутом', 'pcorr'): 1,
  ('топором', 'pcorr'): 1,
  ('свистком', 'pcorr'): 1},
 (121, 'остановились', 'przystanęli'): {('остановились', 'corr'): 14,
  ('nan', 'incorr'): 9,
  ('тронулись', 'pcorr'): 2,
  ('обратили на него внимание', 'pcorr'): 1,
  ('пристани', 'incorr'): 1,
  ('привстали', 'incorr'): 1,
  ('замолчали', 'pcorr'): 1,
  ('эскорта', 'incorr'): 1,
  ('замерли', 'pcorr'): 1,
  ('ушли', 'pcorr'): 1,
  ('заорали', 'pcorr'): 1,
  ('оторопели', 'pcorr'): 1,
  ('испугались', 'pcorr'): 1,
  ('принялись за дело', 'pcorr'): 1},
 (122, 'вылетела', 'wypadła'): {('nan', 'incorr'): 6,
  ('вылетела', 'corr'): 4,
  ('выехала', 'pcorr'): 4,
  ('вышла', 'pcorr'): 2,
  ('выбежала', 'pcorr'): 2,
  ('ворвалась', 'corr'): 2,
  ('въехала', 'pcorr'): 2,
  ('въезжала', 'pcorr'): 1,
  ('поскакала', 'pcorr'): 1,
  ('свернула', 'pcorr'): 1,
  ('пришла', 'pcorr'): 1,
  ('заехала', 'pcorr'): 1,
  ('выскочил', 'corr'): 1,
  ('выскочила', 'corr'): 1,
  ('устремилась', 'pcorr'): 1,
  ('оборонилась', 'incorr'): 1,
  ('вышла (?)', 'pcorr'): 1,
  ('побежала', 'pcorr'): 1,
  ('выскакивала', 'corr'): 1,
  ('обходя', 'incorr'): 1,
  ('бегом', 'incorr'): 1},
 (123, 'каменной', 'kamiennych'): {('каменной', 'corr'): 20,
  ('nan', 'incorr'): 8,
  ('оборонительной', 'pcorr'): 2,
  ('обрушенной', 'pcorr'): 2,
  ('огромной', 'pcorr'): 1,
  ('крепостной', 'pcorr'): 1,
  ('главной', 'pcorr'): 1,
  ('левой', 'pcorr'): 1},
 (124, 'виноград', 'winem'): {('nan', 'incorr'): 13,
  ('виноград', 'corr'): 9,
  ('плющ', 'pcorr'): 3,
  ('камень', 'incorr'): 2,
  ('путь', 'pcorr'): 2,
  ('переулок', 'incorr'): 1,
  ('мох', 'pcorr'): 1,
  ('вьюн', 'pcorr'): 1,
  ('дождь', 'pcorr'): 1,
  ('туман', 'pcorr'): 1,
  ('вьюнок', 'pcorr'): 1,
  ('иней', 'incorr'): 1},
 (125, 'дорогой', 'drogą'): {('дорогой', 'corr'): 25,
  ('nan', 'incorr'): 5,
  ('путь', 'corr'): 2,
  ('дороги', 'corr'): 2,
  ('дороге', 'corr'): 1,
  ('было', 'incorr'): 1},
 (126, 'мальчик', 'wyrostek'): {('nan', 'incorr'): 10,
  ('подросток', 'corr'): 6,
  ('мальчик', 'corr'): 4,
  ('росток', 'pcorr'): 4,
  ('аппендикс', 'incorr'): 2,
  ('ребенок', 'corr'): 2,
  ('воробей', 'pcorr'): 1,
  ('ребёнок', 'corr'): 1,
  ('хорёк', 'pcorr'): 1,
  ('выходец из', 'incorr'): 1,
  ('котёнок', 'pcorr'): 1,
  ('карлик', 'pcorr'): 1,
  ('щенок', 'pcorr'): 1,
  ('гном', 'pcorr'): 1},
 (127, 'командир', 'dowódca'): {('nan', 'incorr'): 13,
  ('командир', 'corr'): 7,
  ('предводитель', 'pcorr'): 3,
  ('командующий', 'pcorr'): 2,
  ('всадник', 'pcorr'): 1,
  ('начальник', 'corr'): 1,
  ('сириец командир', 'corr'): 1,
  ('мальчишка', 'pcorr'): 1,
  ('дворца', 'incorr'): 1,
  ('пилат', 'incorr'): 1,
  ('парень', 'pcorr'): 1,
  ('воин', 'pcorr'): 1,
  ('кавалерийский', 'incorr'): 1,
  ('проворный', 'incorr'): 1,
  ('человек', 'pcorr'): 1},
 (128, 'выхватил', 'wyszarpnął'): {('вытащил', 'corr'): 9,
  ('выхватил', 'corr'): 8,
  ('nan', 'incorr'): 7,
  ('вынул', 'corr'): 6,
  ('достал', 'corr'): 4,
  ('выдернул', 'corr'): 1,
  ('обнажил', 'corr'): 1},
 (129, 'взмокшая', 'spieniony'): {('nan', 'incorr'): 13,
  ('вспененная', 'pcorr'): 6,
  ('дикая', 'pcorr'): 3,
  ('испугала', 'incorr'): 1,
  ('взмыленная', 'corr'): 1,
  ('его', 'incorr'): 1,
  ('скаковая', 'pcorr'): 1,
  ('мощная', 'pcorr'): 1,
  ('белая', 'pcorr'): 1,
  ('чёрная', 'pcorr'): 1,
  ('мокрая', 'corr'): 1,
  ('облетела', 'incorr'): 1,
  ('взмокшая', 'corr'): 1,
  ('черная', 'pcorr'): 1,
  ('вспенённая', 'pcorr'): 1,
  ('пенистая', 'pcorr'): 1,
  ('проклятая', 'pcorr'): 1},
 (130, 'шарахнулась', 'uskoczył'): {('вскочила', 'pcorr'): 10,
  ('nan', 'incorr'): 7,
  ('скакнула', 'corr'): 2,
  ('шарахнулась', 'corr'): 2,
  ('быстро', 'pcorr'): 2,
  ('остановилась', 'pcorr'): 2,
  ('с ржанием', 'incorr'): 1,
  ('отскочила', 'corr'): 1,
  ('вскачила', 'pcorr'): 1,
  ('подпрыгнула', 'pcorr'): 1,
  ('разжав', 'incorr'): 1,
  ('ускокав', 'incorr'): 1,
  ('и он', 'incorr'): 1,
  ('ускорилась', 'pcorr'): 1,
  ('скача', 'incorr'): 1,
  ('прыгнула', 'pcorr'): 1,
  ('подскочила', 'pcorr'): 1},
 (131, 'командир', 'dowódca'): {('nan', 'incorr'): 9,
  ('командир', 'corr'): 6,
  ('сириец', 'pcorr'): 2,
  ('сильно', 'incorr'): 2,
  ('хлёстко', 'incorr'): 2,
  ('предводитель', 'pcorr'): 2,
  ('он', 'incorr'): 2,
  ('человек', 'pcorr'): 2,
  ('сильным ударом', 'incorr'): 1,
  ('кротко', 'incorr'): 1,
  ('мальчик', 'pcorr'): 1,
  ('солдат', 'pcorr'): 1,
  ('коротко', 'incorr'): 1,
  ('парень', 'pcorr'): 1,
  ('воин', 'pcorr'): 1,
  ('коротким ударом', 'incorr'): 1,
  ('коротким кнутом', 'incorr'): 1},
 (132, 'шее', 'karku'): {('nan', 'incorr'): 7,
  ('шее', 'corr'): 6,
  ('крупу', 'pcorr'): 6,
  ('спине', 'pcorr'): 5,
  ('холке', 'corr'): 3,
  ('бокам', 'pcorr'): 2,
  ('боку', 'pcorr'): 2,
  ('круглому заду', 'pcorr'): 1,
  ('голове', 'pcorr'): 1,
  ('хребту', 'pcorr'): 1,
  ('бедру', 'pcorr'): 1,
  ('загривку', 'corr'): 1},
 (133, 'полетели', 'przemknęli'): {('nan', 'incorr'): 9,
  ('скакали', 'corr'): 4,
  ('поскакали', 'corr'): 3,
  ('полетели', 'corr'): 2,
  ('ехали', 'pcorr'): 2,
  ('сомкнулись', 'pcorr'): 2,
  ('выстроились', 'pcorr'): 1,
  ('с хмурыми лицами', 'incorr'): 1,
  ('примкнули', 'pcorr'): 1,
  ('мчались', 'corr'): 1,
  ('проносились', 'corr'): 1,
  ('мелькали', 'pcorr'): 1,
  ('выбежали', 'pcorr'): 1,
  ('поскакали (?)', 'corr'): 1,
  ('хмурые', 'incorr'): 1,
  ('побежали', 'pcorr'): 1,
  ('проскакали', 'corr'): 1,
  ('устремились', 'pcorr'): 1,
  ('поехали', 'pcorr'): 1,
  ('стояли', 'pcorr'): 1},
 (134, 'туче', 'chmurach'): {('nan', 'incorr'): 10,
  ('клубах', 'corr'): 5,
  ('облаках', 'corr'): 4,
  ('грязной', 'incorr'): 4,
  ('дорожной', 'pcorr'): 3,
  ('облаке', 'corr'): 3,
  ('туче', 'corr'): 2,
  ('облаке поднятой', 'corr'): 1,
  ('одежде', 'pcorr'): 1,
  ('тёмной', 'pcorr'): 1,
  ('тучах', 'corr'): 1,
  ('грязи', 'pcorr'): 1},
 (135, 'пик', 'dzid'): {('nan', 'incorr'): 9,
  ('копий', 'corr'): 7,
  ('палок', 'pcorr'): 5,
  ('копьев', 'corr'): 3,
  ('пик', 'corr'): 2,
  ('палочек', 'incorr'): 2,
  ('шляп', 'pcorr'): 1,
  ('штор', 'incorr'): 1,
  ('шапок', 'pcorr'): 1,
  ('кнутов', 'pcorr'): 1,
  ('хлыстов', 'pcorr'): 1,
  ('сапог', 'incorr'): 1,
  ('зарослей', 'incorr'): 1,
  ('стрел', 'pcorr'): 1},
 (136, 'весело', 'wesoło'): {('весело', 'corr'): 12,
  ('nan', 'incorr'): 11,
  ('белыми', 'pcorr'): 2,
  ('лицами', 'incorr'): 2,
  ('злобно', 'pcorr'): 2,
  ('неестественно', 'pcorr'): 1,
  ('взглядами', 'incorr'): 1,
  ('веселыми', 'corr'): 1,
  ('пастью', 'incorr'): 1,
  ('улыбающимися', 'incorr'): 1,
  ('огромными', 'pcorr'): 1,
  ('смуглыми', 'pcorr'): 1},
 (137, 'сверкающими', 'połyskliwych'): {('nan', 'incorr'): 16,
  ('белыми', 'pcorr'): 10,
  ('выщербленными', 'pcorr'): 1,
  ('грязными', 'pcorr'): 1,
  ('стёсанными', 'pcorr'): 1,
  ('специально заточенными', 'pcorr'): 1,
  ('кривыми', 'pcorr'): 1,
  ('блестящими', 'corr'): 1,
  ('серыми', 'pcorr'): 1,
  ('сверкающими', 'corr'): 1,
  ('зазубренными', 'pcorr'): 1,
  ('ужасными', 'pcorr'): 1},
 (138, 'солдат', 'żołnierz'): {('nan', 'incorr'): 11,
  ('солдат', 'corr'): 11,
  ('всадник', 'corr'): 3,
  ('воин', 'corr'): 2,
  ('сириец', 'pcorr'): 1,
  ('остаток армии', 'pcorr'): 1,
  ('последний', 'incorr'): 1,
  ('мальчик', 'pcorr'): 1,
  ('вождь', 'pcorr'): 1,
  ('отставший солдат', 'corr'): 1,
  ('мужчина', 'pcorr'): 1,
  ('человек', 'pcorr'): 1,
  ('мулат', 'pcorr'): 1},
 (139, 'трубою', 'trąbka'): {('трубой', 'corr'): 14,
  ('nan', 'incorr'): 9,
  ('трубою', 'corr'): 2,
  ('металлической бляхой', 'pcorr'): 1,
  ('бронёй', 'pcorr'): 1,
  ('палкой', 'incorr'): 1,
  ('алебардой', 'pcorr'): 1,
  ('загорелой', 'incorr'): 1,
  ('алое', 'incorr'): 1,
  ('трубкой', 'pcorr'): 1,
  ('кнутом', 'pcorr'): 1,
  ('защитой', 'pcorr'): 1,
  ('саблей', 'pcorr'): 1,
  ('с колчаном', 'pcorr'): 1},
 (140, 'морща', 'krzywiąc'): {('морща', 'corr'): 8,
  ('nan', 'incorr'): 8,
  ('сморщив', 'corr'): 4,
  ('кривя', 'corr'): 3,
  ('прикрыв', 'pcorr'): 2,
  ('скривив', 'corr'): 2,
  ('хмуря', 'corr'): 2,
  ('отстранив', 'pcorr'): 1,
  ('пряча', 'pcorr'): 1,
  ('потирая', 'pcorr'): 1,
  ('вытирая', 'pcorr'): 1,
  ('отклоняя', 'pcorr'): 1,
  ('прикрывая', 'pcorr'): 1,
  ('нахмуренное', 'pcorr'): 1},
 (141, 'двинулся', 'ruszył'): {('nan', 'incorr'): 8,
  ('пошел', 'corr'): 7,
  ('двинулся', 'corr'): 4,
  ('поскакал', 'pcorr'): 3,
  ('пошёл', 'corr'): 2,
  ('направился', 'corr'): 2,
  ('скакал', 'pcorr'): 2,
  ('ступил', 'pcorr'): 1,
  ('поплелся', 'corr'): 1,
  ('с недовольствием шёл', 'corr'): 1,
  ('шел', 'corr'): 1,
  ('поехал', 'pcorr'): 1,
  ('ехал', 'pcorr'): 1,
  ('помчался', 'pcorr'): 1,
  ('поспешил', 'pcorr'): 1},
 (142, 'двинулся', 'szli'): {('шли', 'corr'): 14,
  ('nan', 'incorr'): 6,
  ('шел', 'corr'): 2,
  ('двинулся', 'corr'): 2,
  ('устремился', 'corr'): 1,
  ('стража', 'incorr'): 1,
  ('ехали', 'pcorr'): 1,
  ('в сопровождение', 'incorr'): 1,
  ('мчались', 'pcorr'): 1,
  ('дворцовый', 'incorr'): 1,
  ('солдаты', 'incorr'): 1,
  ('бросились', 'pcorr'): 1,
  ('тронулся', 'corr'): 1,
  ('его', 'incorr'): 1,
  ('весь', 'incorr'): 1,
  ('гнался', 'pcorr'): 1},
 (20, 'пустому', 'pustym'): {('пустому', 'corr'): 30,
  ('пустым', 'corr'): 3,
  ('коридору', 'pcorr'): 2,
  ('nan', 'incorr'): 1,
  ('темному', 'pcorr'): 1,
  ('тихому', 'pcorr'): 1,
  ('пустым комнатам', 'corr'): 1,
  ('корридору', 'pcorr'): 1,
  ('этажу', 'incorr'): 1,
  ('глухому', 'pcorr'): 1,
  ('пустым коридорам', 'corr'): 1,
  ('вымершему', 'pcorr'): 1},
 (21, 'коридору', 'korytarzem'): {('коридору', 'corr'): 29,
  ('корридору', 'corr'): 4,
  ('этажу', 'pcorr'): 3,
  ('полу', 'pcorr'): 2,
  ('коридорам', 'corr'): 2,
  ('nan', 'incorr'): 1,
  ('ковру', 'pcorr'): 1,
  ('корридорам', 'corr'): 1,
  ('кабинету', 'pcorr'): 1},
 (22, 'здании', 'budynku'): {('здании', 'corr'): 14,
  ('помещении', 'pcorr'): 9,
  ('кабинете', 'pcorr'): 7,
  ('nan', 'incorr'): 6,
  ('доме', 'corr'): 4,
  ('бункере', 'pcorr'): 1,
  ('кабинетен', 'pcorr'): 1,
  ('здании,  разу же подумал', 'corr'): 1,
  ('будильнике', 'incorr'): 1},
 (23, 'стеклянные', 'przeszklone'): {('nan', 'incorr'): 13,
  ('небольшие', 'pcorr'): 6,
  ('стеклянные', 'corr'): 4,
  ('маленькие', 'pcorr'): 4,
  ('застекленные', 'corr'): 3,
  ('застеклённые', 'corr'): 2,
  ('полный', 'pcorr'): 1,
  ('кривые', 'pcorr'): 1,
  ('стулья', 'incorr'): 1,
  ('висели', 'incorr'): 1,
  ('стеклянными', 'corr'): 1,
  ('столовые', 'pcorr'): 1,
  ('остеклённые', 'corr'): 1,
  ('железные', 'pcorr'): 1,
  ('полные', 'pcorr'): 1,
  ('кухонные', 'pcorr'): 1,
  ('стеллажи', 'incorr'): 1,
  ('низкие', 'pcorr'): 1},
 (24, 'инструментами', 'narzędzi'): {('инструментами', 'corr'): 12,
  ('ручками', 'pcorr'): 9,
  ('nan', 'incorr'): 9,
  ('ножками', 'pcorr'): 3,
  ('ножницами', 'pcorr'): 2,
  ('поверхностями', 'pcorr'): 2,

In [17]:
sn_cognates = cognate_searcher(slovene_ans, russian_true, slovene_true)
sn_cognates

{(10, 'повернулся', 'zasukal'): {('повернулся', 'corr'): 10,
  ('nan', 'incorr'): 7,
  ('заскучал', 'pcorr'): 4,
  ('развернулся', 'corr'): 3,
  ('повернул', 'corr'): 1,
  ('подумал', 'pcorr'): 1,
  ('понял', 'incorr'): 1,
  ('замолчал', 'pcorr'): 1,
  ('увидел', 'pcorr'): 1,
  ('встал', 'pcorr'): 1,
  ('вышел', 'pcorr'): 1,
  ('посмотрел', 'pcorr'): 1,
  ('задумался', 'pcorr'): 1,
  ('павернулся', 'corr'): 1,
  ('сказал', 'incorr'): 1,
  ('постоял', 'pcorr'): 1,
  ('застукал', 'incorr'): 1},
 (11, 'ступеням', 'stopnicam'): {('лестнице', 'corr'): 12,
  ('ступеням', 'corr'): 8,
  ('nan', 'incorr'): 4,
  ('ступенькам', 'corr'): 2,
  ('воротам', 'pcorr'): 2,
  ('дворцу', 'pcorr'): 2,
  ('горе', 'pcorr'): 1,
  ('сходням', 'corr'): 1,
  ('себе', 'incorr'): 1,
  ('гостям', 'pcorr'): 1,
  ('стенам', 'pcorr'): 1,
  ('нему', 'incorr'): 1,
  ('стопницам', 'incorr'): 1},
 (12, 'шашек', 'ploščic'): {('квадратов', 'corr'): 10,
  ('плиток', 'corr'): 5,
  ('узоров', 'corr'): 4,
  ('nan', 'incorr'): 3,
  ('шашек', 'corr'): 3,
  ('квадратных', 'pcorr'): 2,
  ('полей', 'corr'): 1,
  ('деревяшек', 'pcorr'): 1,
  ('досок', 'pcorr'): 1,
  ('листьев', 'pcorr'): 1,
  ('квадратиков', 'corr'): 1,
  ('узоров из плиток', 'corr'): 1,
  ('квадратные', 'incorr'): 1,
  ('бревен', 'pcorr'): 1,
  ('квадратов узора', 'corr'): 1,
  ('цветов', 'pcorr'): 1},
 (13, 'спиною', 'hrbtom'): {('спиной', 'corr'): 27,
  ('плечами', 'pcorr'): 2,
  ('хребтом', 'pcorr'): 2,
  ('nan', 'incorr'): 2,
  ('его спиной', 'corr'): 1,
  ('спиною', 'corr'): 1,
  ('ним', 'incorr'): 1,
  ('нет', 'incorr'): 1},
 (14, 'финики', 'dateljnov'): {('nan', 'incorr'): 16,
  ('финики', 'corr'): 8,
  ('dateljnov', 'incorr'): 1,
  ('и финики', 'corr'): 1,
  ('сокровища', 'pcorr'): 1,
  ('знал', 'incorr'): 1,
  ('падают на землю', 'incorr'): 1,
  ('серебро', 'pcorr'): 1,
  ('кольца', 'pcorr'): 1,
  ('лучше тем', 'incorr'): 1,
  ('навзничь', 'incorr'): 1,
  ('медного', 'incorr'): 1,
  ('лезвия на хребте', 'incorr'): 1,
  ('что', 'incorr'): 1,
  ('камни', 'pcorr'): 1},
 (15, 'чудо', 'čudo'): {('чудо', 'corr'): 30,
  ('nan', 'incorr'): 2,
  ('видели', 'incorr'): 1,
  ('это', 'incorr'): 1,
  ('казнь', 'pcorr'): 1,
  ('войну', 'pcorr'): 1,
  ('всё то', 'incorr'): 1},
 (16, 'вырвался', 'iztrga'): {('вырвался', 'corr'): 11,
  ('вырывается', 'corr'): 8,
  ('nan', 'incorr'): 4,
  ('выбрался', 'pcorr'): 3,
  ('вырван', 'pcorr'): 2,
  ('этого периода!', 'incorr'): 1,
  ('сбежал', 'corr'): 1,
  ('берет', 'pcorr'): 1,
  ('ушёл', 'pcorr'): 1,
  ('ушел', 'pcorr'): 1,
  ('изтрга', 'incorr'): 1,
  ('вовсе не', 'incorr'): 1,
  ('вырывался', 'corr'): 1,
  ('спасается', 'corr'): 1},
 (17, 'веревки', 'vezi'): {('веревки', 'corr'): 7,
  ('одежду', 'pcorr'): 5,
  ('путы', 'corr'): 4,
  ('nan', 'incorr'): 4,
  ('связки', 'pcorr'): 3,
  ('доспехи', 'pcorr'): 2,
  ('оковы', 'pcorr'): 2,
  ('повязки', 'pcorr'): 1,
  ('кожу', 'pcorr'): 1,
  ('кандалы', 'pcorr'): 1,
  ('шаль', 'pcorr'): 1,
  ('веревку', 'corr'): 1,
  ('куртку', 'pcorr'): 1,
  ('вещи', 'incorr'): 1,
  ('при не желании', 'incorr'): 1,
  ('воз', 'incorr'): 1,
  ('шлем', 'pcorr'): 1},
 (18, 'допросе', 'zasliševanjem'): {('запястьях', 'pcorr'): 13,
  ('допросе', 'corr'): 11,
  ('nan', 'incorr'): 3,
  ('допросах', 'corr'): 2,
  ('запястях', 'pcorr'): 1,
  ('ногах', 'pcorr'): 1,
  ('израненных', 'incorr'): 1,
  ('ружу', 'incorr'): 1,
  ('мускулистых', 'incorr'): 1,
  ('на допросе', 'corr'): 1,
  ('спине', 'pcorr'): 1,
  ('запчстьях', 'pcorr'): 1},
 (19, 'сумасшедшей', 'norim'): {('nan', 'incorr'): 11,
  ('сумасшедшей', 'corr'): 8,
  ('безумной', 'corr'): 3,
  ('сумашедшей', 'corr'): 3,
  ('глупой', 'corr'): 3,
  ('насмешливой', 'pcorr'): 2,
  ('своей', 'pcorr'): 2,
  ('натянутой', 'pcorr'): 1,
  ('естественной', 'pcorr'): 1,
  ('нервной', 'pcorr'): 1,
  ('нормальной', 'pcorr'): 1,
  ('насмешкой', 'incorr'): 1},
 (110, 'знал', 'vedel'): {('видел', 'pcorr'): 15,
  ('знал', 'corr'): 14,
  ('nan', 'incorr'): 2,
  ('к тому времени', 'incorr'): 1,
  ('понял', 'pcorr'): 1,
  ('уверен', 'pcorr'): 1,
  ('ждал', 'pcorr'): 1,
  ('не знал', 'corr'): 1,
  ('страж', 'incorr'): 1},
 (111, 'ступеням', 'stopnicam'): {('ступеням', 'corr'): 14,
  ('nan', 'incorr'): 5,
  ('лестницам', 'corr'): 4,
  ('воротам', 'pcorr'): 4,
  ('дверям', 'pcorr'): 3,
  ('ступенькам', 'corr'): 1,
  ('тратуарам', 'pcorr'): 1,
  ('стенам', 'pcorr'): 1,
  ('колоннам', 'pcorr'): 1,
  ('мостам', 'pcorr'): 1,
  ('местам', 'incorr'): 1,
  ('столбам', 'pcorr'): 1},
 (112, 'дорогу', 'cesto'): {('дорогу', 'corr'): 26,
  ('улицу', 'corr'): 2,
  ('nan', 'incorr'): 2,
  ('на запад', 'incorr'): 1,
  ('лестницу', 'pcorr'): 1,
  ('казнь', 'pcorr'): 1,
  ('запад', 'incorr'): 1,
  ('тропу', 'pcorr'): 1,
  ('место', 'incorr'): 1,
  ('гору голгофу', 'pcorr'): 1},
 (113, 'осужденных', 'obsojencev'): {('осужденных', 'corr'): 10,
  ('nan', 'incorr'): 7,
  ('больше', 'incorr'): 6,
  ('море', 'pcorr'): 3,
  ('осуждённых', 'corr'): 2,
  ('толпу', 'pcorr'): 2,
  ('смерть', 'incorr'): 1,
  ('оборванцев', 'pcorr'): 1,
  ('назад', 'incorr'): 1,
  ('море людей', 'pcorr'): 1,
  ('однако', 'incorr'): 1,
  ('никакой угрозы', 'pcorr'): 1,
  ('остальное', 'pcorr'): 1},
 (114, 'глашатаев', 'izklicevalcev'): {('глашатаев', 'corr'): 10,
  ('nan', 'incorr'): 9,
  ('звонивших', 'pcorr'): 5,
  ('изкличевальцев', 'incorr'): 2,
  ('звонящих', 'pcorr'): 1,
  ('ругательств', 'pcorr'): 1,
  ('переводчиков', 'pcorr'): 1,
  ('солдат', 'pcorr'): 1,
  ('людей', 'pcorr'): 1,
  ('зрителей', 'pcorr'): 1,
  ('раненных', 'pcorr'): 1,
  ('иностранцев', 'pcorr'): 1,
  ('жертв', 'pcorr'): 1,
  ('поокурора', 'pcorr'): 1,
  ('глашаев', 'corr'): 1},
 (115, 'греческом', 'grščini'): {('греческом', 'corr'): 21,
  ('nan', 'incorr'): 5,
  ('греческих', 'corr'): 3,
  ('иностранных', 'pcorr'): 2,
  ('арамейских', 'pcorr'): 1,
  ('латинском', 'pcorr'): 1,
  ('египетском', 'pcorr'): 1,
  ('разных', 'pcorr'): 1,
  ('городском', 'pcorr'): 1,
  ('других', 'pcorr'): 1},
 (116, 'труба', 'trobento'): {('nan', 'incorr'): 13,
  ('труба', 'corr'): 8,
  ('треск', 'pcorr'): 2,
  ('труб', 'corr'): 2,
  ('трубу', 'corr'): 1,
  ('свист', 'pcorr'): 1,
  ('конница', 'pcorr'): 1,
  ('колесница', 'pcorr'): 1,
  ('рёв', 'pcorr'): 1,
  ('трубы', 'corr'): 1,
  ('гул', 'pcorr'): 1,
  ('ржание', 'pcorr'): 1,
  ('рожком', 'corr'): 1,
  ('звук трубы', 'corr'): 1,
  ('шум', 'pcorr'): 1,
  ('крик', 'pcorr'): 1},
 (117, 'весело', 'veselo'): {('весело', 'corr'): 29,
  ('nan', 'incorr'): 4,
  ('неистово', 'pcorr'): 1,
  ('громко', 'pcorr'): 1,
  ('робко', 'pcorr'): 1,
  ('оглушающе', 'pcorr'): 1},
 (118, 'мальчишек', 'paglavcev'): {('nan', 'incorr'): 12,
  ('головастиков', 'incorr'): 5,
  ('мальчишек', 'corr'): 4,
  ('людей', 'pcorr'): 2,
  ('голов', 'pcorr'): 1,
  ('стрел', 'pcorr'): 1,
  ('наездников', 'pcorr'): 1,
  ('толпы', 'pcorr'): 1,
  ('смотрящих', 'pcorr'): 1,
  ('стрелы', 'pcorr'): 1,
  ('дрели', 'incorr'): 1,
  ('зачинщиков', 'pcorr'): 1,
  ('караульных', 'pcorr'): 1,
  ('жителей', 'pcorr'): 1,
  ('паглавцев', 'incorr'): 1,
  ('мальчиков', 'corr'): 1,
  ('хищных', 'incorr'): 1,
  ('ветра', 'pcorr'): 1},
 (119, 'солдат', 'vojak'): {('вожак', 'pcorr'): 15,
  ('солдат', 'corr'): 14,
  ('воин', 'corr'): 3,
  ('монах', 'pcorr'): 1,
  ('вомн', 'corr'): 1,
  ('предводитель', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('всадник', 'pcorr'): 1},
 (120, 'значком', 'znamenjem'): {('знаменем', 'pcorr'): 19,
  ('знаком', 'corr'): 4,
  ('божьим знаменем', 'corr'): 3,
  ('значком', 'corr'): 3,
  ('боевым знаком', 'corr'): 2,
  ('nan', 'incorr'): 2,
  ('свечой', 'pcorr'): 1,
  ('прокуратор', 'incorr'): 1,
  ('спицей', 'incorr'): 1,
  ('ломом', 'pcorr'): 1},
 (121, 'остановились', 'ustavili'): {('остановились', 'corr'): 18,
  ('nan', 'incorr'): 5,
  ('поставили', 'incorr'): 2,
  ('остановился', 'corr'): 1,
  ('охраны', 'incorr'): 1,
  ('короля', 'incorr'): 1,
  ('встали', 'corr'): 1,
  ('устава', 'incorr'): 1,
  ('стояли', 'corr'): 1,
  ('установили', 'incorr'): 1,
  ('стража', 'incorr'): 1,
  ('ушел', 'pcorr'): 1,
  ('отправились', 'pcorr'): 1,
  ('стражи', 'incorr'): 1,
  ('обернулисиь', 'pcorr'): 1},
 (122, 'вылетела', 'pridrvela'): {('бросилась', 'pcorr'): 7,
  ('помчалась', 'corr'): 3,
  ('nan', 'incorr'): 3,
  ('прискакала', 'pcorr'): 3,
  ('выехала', 'pcorr'): 3,
  ('пришла', 'pcorr'): 2,
  ('вылетела', 'corr'): 2,
  ('привела', 'pcorr'): 2,
  ('прибыла', 'pcorr'): 2,
  ('выскочила', 'corr'): 1,
  ('волков', 'incorr'): 1,
  ('приехала', 'pcorr'): 1,
  ('вышла', 'pcorr'): 1,
  ('где', 'incorr'): 1,
  ('вела процессию', 'pcorr'): 1,
  ('вылетел', 'corr'): 1,
  ('шла', 'pcorr'): 1,
  ('поскакала', 'pcorr'): 1,
  ('ворвалась', 'corr'): 1},
 (123, 'каменной', 'kamnitnim'): {('каменной', 'corr'): 32,
  ('nan', 'incorr'): 2,
  ('городской', 'pcorr'): 1,
  ('каменистой', 'pcorr'): 1,
  ('толстой', 'pcorr'): 1},
 (124, 'виноград', 'vinsko'): {('виноград', 'corr'): 14,
  ('nan', 'incorr'): 7,
  ('туман', 'pcorr'): 3,
  ('путь', 'pcorr'): 2,
  ('виноградник', 'pcorr'): 1,
  ('лоза', 'corr'): 1,
  ('песок', 'pcorr'): 1,
  ('винноградный лист', 'corr'): 1,
  ('тракт', 'pcorr'): 1,
  ('плющ', 'pcorr'): 1,
  ('лозой', 'corr'): 1,
  ('стлался', 'incorr'): 1,
  ('виноградная лоза', 'corr'): 1,
  ('кавалерия', 'incorr'): 1,
  ('конь', 'incorr'): 1},
 (125, 'дорогой', 'poti'): {('дорогой', 'corr'): 23,
  ('путь', 'corr'): 4,
  ('nan', 'incorr'): 3,
  ('дороге', 'corr'): 3,
  ('путем', 'corr'): 1,
  ('путём', 'corr'): 1,
  ('до голгофы', 'pcorr'): 1,
  ('мимо', 'incorr'): 1},
 (126, 'мальчик', 'deček'): {('мальчик', 'corr'): 13,
  ('кот', 'pcorr'): 8,
  ('nan', 'incorr'): 6,
  ('сириец', 'pcorr'): 3,
  ('воробей', 'pcorr'): 1,
  ('чёрт', 'pcorr'): 1,
  ('мальчишка', 'corr'): 1,
  ('ребёнок', 'corr'): 1,
  ('как мальчик', 'corr'): 1,
  ('ночь', 'incorr'): 1,
  ('дитя', 'corr'): 1},
 (127, 'командир', 'poveljnik'): {('nan', 'incorr'): 14,
  ('командир', 'corr'): 8,
  ('встретился', 'incorr'): 2,
  ('черный', 'incorr'): 1,
  ('кавалериец', 'pcorr'): 1,
  ('пришёл', 'incorr'): 1,
  ('предводитель', 'pcorr'): 1,
  ('пилат', 'incorr'): 1,
  ('в миру', 'incorr'): 1,
  ('прискакал', 'incorr'): 1,
  ('встретившийся с пиратом', 'incorr'): 1,
  ('прибежал', 'incorr'): 1,
  ('той', 'incorr'): 1,
  ('смуглый', 'incorr'): 1,
  ('пришел', 'incorr'): 1,
  ('кот', 'incorr'): 1},
 (128, 'выхватил', 'izdrl'): {('вытащил', 'corr'): 12,
  ('достал', 'corr'): 7,
  ('вынул', 'corr'): 5,
  ('извлек', 'corr'): 3,
  ('nan', 'incorr'): 3,
  ('выхватил', 'corr'): 3,
  ('выдернул', 'corr'): 2,
  ('извлёк', 'corr'): 1,
  ('закричал', 'incorr'): 1},
 (129, 'взмокшая', 'premočeni'): {('nan', 'incorr'): 10,
  ('взмокшая', 'corr'): 5,
  ('черная', 'pcorr'): 3,
  ('промокшая', 'pcorr'): 3,
  ('взмыленная', 'corr'): 2,
  ('уставшая', 'pcorr'): 2,
  ('мокрая', 'corr'): 2,
  ('отскогчила', 'incorr'): 1,
  ('отпрыгнула и', 'incorr'): 1,
  ('дикая', 'pcorr'): 1,
  ('бешеная', 'pcorr'): 1,
  ('отскочила', 'incorr'): 1,
  ('встревоженная', 'pcorr'): 1,
  ('измученная', 'pcorr'): 1,
  ('бешенная', 'pcorr'): 1,
  ('вскочила', 'incorr'): 1,
  ('чёрная', 'pcorr'): 1},
 (130, 'шарахнулась', 'skočil'): {('nan', 'incorr'): 15,
  ('встала', 'pcorr'): 3,
  ('вскочила', 'pcorr'): 3,
  ('шарахнулась', 'corr'): 3,
  ('отскочила', 'corr'): 2,
  ('вскочив', 'incorr'): 1,
  ('брыкнулась', 'pcorr'): 1,
  ('взбрыкнулась', 'corr'): 1,
  ('вдруг', 'incorr'): 1,
  ('взбрыкнула', 'pcorr'): 1,
  ('отскочила в сторону', 'corr'): 1,
  ('вскачила', 'pcorr'): 1,
  ('выбежала', 'pcorr'): 1,
  ('дёрнулась', 'corr'): 1,
  ('вскарабкалась', 'pcorr'): 1,
  ('на ноги', 'incorr'): 1},
 (131, 'командир', 'poveljnik'): {('командир', 'corr'): 14,
  ('nan', 'incorr'): 6,
  ('он', 'incorr'): 4,
  ('всадник', 'pcorr'): 3,
  ('свистнул', 'incorr'): 1,
  ('сириец', 'pcorr'): 1,
  ('указчик', 'incorr'): 1,
  ('предводитель', 'pcorr'): 1,
  ('воин', 'pcorr'): 1,
  ('повелитель', 'pcorr'): 1,
  ('праведник', 'pcorr'): 1,
  ('алы', 'incorr'): 1,
  ('команир', 'corr'): 1,
  ('потиснил', 'incorr'): 1},
 (132, 'шее', 'vratu'): {('шее', 'corr'): 17,
  ('nan', 'incorr'): 6,
  ('крупу', 'pcorr'): 5,
  ('боку', 'pcorr'): 3,
  ('спине', 'pcorr'): 2,
  ('бокам', 'pcorr'): 1,
  ('по шее', 'corr'): 1,
  ('лицу', 'pcorr'): 1,
  ('рту', 'pcorr'): 1},
 (133, 'полетели', 'zdirjali'): {('nan', 'incorr'): 8,
  ('скакали', 'corr'): 7,
  ('его', 'incorr'): 3,
  ('поскакали', 'corr'): 3,
  ('встали', 'pcorr'): 2,
  ('проскакали', 'corr'): 2,
  ('ехали', 'pcorr'): 1,
  ('помчались', 'corr'): 1,
  ('воины', 'incorr'): 1,
  ('полетели', 'corr'): 1,
  ('разгневанные', 'incorr'): 1,
  ('всадники', 'incorr'): 1,
  ('бежали', 'pcorr'): 1,
  ('шли', 'pcorr'): 1,
  ('солдаты', 'incorr'): 1,
  ('вылетели', 'corr'): 1,
  ('стояли', 'pcorr'): 1,
  ('мчались', 'corr'): 1},
 (134, 'туче', 'oblak'): {('облаке', 'corr'): 12,
  ('клубах', 'corr'): 6,
  ('nan', 'incorr'): 5,
  ('облаках', 'corr'): 4,
  ('туче', 'corr'): 3,
  ('в облаках', 'corr'): 2,
  ('доспехах', 'incorr'): 1,
  ('окутанной', 'incorr'): 1,
  ('погонах', 'incorr'): 1,
  ('окутанные', 'incorr'): 1,
  ('невидимой', 'incorr'): 1},
 (135, 'пик', 'sulic'): {('nan', 'incorr'): 13,
  ('копий', 'corr'): 9,
  ('палок', 'pcorr'): 4,
  ('пик', 'corr'): 3,
  ('палиц', 'pcorr'): 1,
  ('наконечников', 'pcorr'): 1,
  ('прутьев', 'pcorr'): 1,
  ('копей', 'corr'): 1,
  ('орудий', 'pcorr'): 1,
  ('попон', 'incorr'): 1,
  ('копьев', 'corr'): 1,
  ('стволов', 'pcorr'): 1},
 (136, 'весело', 'veselo'): {('весело', 'corr'): 11,
  ('nan', 'incorr'): 10,
  ('веселыми', 'corr'): 4,
  ('белыми', 'pcorr'): 1,
  ('острыми', 'pcorr'): 1,
  ('улыбками', 'incorr'): 1,
  ('шрамами', 'incorr'): 1,
  ('озлобленными', 'pcorr'): 1,
  ('зубами', 'incorr'): 1,
  ('злобно', 'pcorr'): 1,
  ('венсело', 'corr'): 1,
  ('тёмными', 'pcorr'): 1,
  ('радостно', 'corr'): 1,
  ('казавшимися', 'incorr'): 1,
  ('коричневыми', 'pcorr'): 1},
 (137, 'сверкающими', 'lesketajočimi'): {('nan', 'incorr'): 15,
  ('сверкающими', 'corr'): 7,
  ('белыми', 'pcorr'): 4,
  ('блестящими', 'corr'): 2,
  ('острыми', 'pcorr'): 2,
  ('гнилыми', 'pcorr'): 1,
  ('желтыми', 'pcorr'): 1,
  ('светящимися', 'pcorr'): 1,
  ('кривыми', 'pcorr'): 1,
  ('заостренными', 'pcorr'): 1,
  ('скрежещущими', 'pcorr'): 1,
  ('лязгающими', 'pcorr'): 1},
 (138, 'солдат', 'vojak'): {('солдат', 'corr'): 13,
  ('вожак', 'pcorr'): 11,
  ('nan', 'incorr'): 5,
  ('всадник', 'corr'): 2,
  ('воин', 'corr'): 2,
  ('на коне', 'pcorr'): 1,
  ('наездник', 'pcorr'): 1,
  ('пилат', 'incorr'): 1,
  ('конь', 'pcorr'): 1},
 (139, 'трубою', 'trobenta'): {('трубой', 'corr'): 11,
  ('nan', 'incorr'): 10,
  ('трубою', 'corr'): 3,
  ('шпагой', 'pcorr'): 1,
  ('плетью', 'pcorr'): 1,
  ('торбой', 'incorr'): 1,
  ('алебардой', 'pcorr'): 1,
  ('меча', 'incorr'): 1,
  ('светящее солнце', 'incorr'): 1,
  ('саблей', 'pcorr'): 1,
  ('красной', 'incorr'): 1,
  ('накидкой', 'pcorr'): 1,
  ('трубы', 'corr'): 1,
  ('мантией', 'pcorr'): 1,
  ('гривой', 'pcorr'): 1,
  ('сумкой', 'pcorr'): 1},
 (140, 'морща', 'namrščil'): {('морща', 'corr'): 8,
  ('нахмурив', 'pcorr'): 7,
  ('nan', 'incorr'): 5,
  ('наморщив', 'corr'): 2,
  ('нахмурил', 'corr'): 2,
  ('хмуря', 'corr'): 2,
  ('корча', 'pcorr'): 1,
  ('нахмурившееся', 'corr'): 1,
  ('сморщив', 'corr'): 1,
  ('cморщив', 'corr'): 1,
  ('прикрывая', 'pcorr'): 1,
  ('скривив', 'corr'): 1,
  ('хмурясь', 'corr'): 1,
  ('наморщил', 'corr'): 1,
  ('нахмуривши', 'corr'): 1,
  ('хмурит', 'pcorr'): 1,
  ('спрятал', 'pcorr'): 1},
 (141, 'двинулся', 'šel'): {('пошел', 'corr'): 8,
  ('шел', 'corr'): 7,
  ('пошёл', 'corr'): 6,
  ('nan', 'incorr'): 5,
  ('двинулся', 'corr'): 3,
  ('шёл', 'corr'): 3,
  ('чуть', 'incorr'): 1,
  ('прошёл', 'corr'): 1,
  ('направился', 'corr'): 1,
  ('идёт', 'corr'): 1,
  ('прикрыл глаза и пошел', 'corr'): 1},
 (142, 'двинулся', 'stopali'): {('шли', 'corr'): 6,
  ('nan', 'incorr'): 4,
  ('стояли', 'pcorr'): 4,
  ('ступали', 'corr'): 3,
  ('двинулся', 'corr'): 3,
  ('топали', 'corr'): 2,
  ('шагали', 'corr'): 2,
  ('следовали', 'corr'): 2,
  ('собака', 'incorr'): 1,
  ('устремился', 'corr'): 1,
  ('стоял', 'pcorr'): 1,
  ('шди', 'corr'): 1,
  ('двигались', 'corr'): 1,
  ('ступал', 'corr'): 1,
  ('писец', 'incorr'): 1,
  ('и весь', 'incorr'): 1,
  ('направились', 'corr'): 1,
  ('стоялиприкрыл', 'pcorr'): 1,
  ('пошел', 'corr'): 1},
 (20, 'пустому', 'praznem'): {('пустому', 'corr'): 15,
  ('гостиной', 'incorr'): 2,
  ('nan', 'incorr'): 2,
  ('праздничному', 'incorr'): 2,
  ('парадному', 'pcorr'): 2,
  ('тихому', 'pcorr'): 2,
  ('длинному', 'pcorr'): 2,
  ('коридору', 'pcorr'): 1,
  ('дворцу', 'incorr'): 1,
  ('красивому', 'pcorr'): 1,
  ('пустынному', 'corr'): 1,
  ('лестнице', 'incorr'): 1,
  ('парадной', 'incorr'): 1,
  ('подвалу', 'incorr'): 1,
  ('зданию', 'incorr'): 1,
  ('дороге', 'incorr'): 1,
  ('узкому', 'pcorr'): 1},
 (21, 'коридору', 'hodniku'): {('коридору', 'corr'): 25,
  ('проходу', 'pcorr'): 6,
  ('nan', 'incorr'): 2,
  ('туалету', 'pcorr'): 1,
  ('коредору', 'corr'): 1,
  ('лесу', 'pcorr'): 1,
  ('ходу', 'corr'): 1},
 (22, 'здании', 'stavbi'): {('здании', 'corr'): 10,
  ('месте', 'pcorr'): 6,
  ('помещении', 'pcorr'): 5,
  ('кабинете', 'pcorr'): 3,
  ('столе', 'incorr'): 2,
  ('доме', 'corr'): 2,
  ('диване', 'pcorr'): 2,
  ('воспринимал', 'incorr'): 1,
  ('комнате', 'pcorr'): 1,
  ('спокойно', 'incorr'): 1,
  ('стремал', 'incorr'): 1,
  ('складе', 'pcorr'): 1,
  ('переживал', 'incorr'): 1,
  ('коридоре', 'pcorr'): 1},
 (23, 'стеклянные', 'zastekljene'): {('застекленные', 'corr'): 18,
  ('застеклённые', 'corr'): 5,
  ('стеклянные', 'corr'): 2,
  ('небольшие', 'pcorr'): 2,
  ('столы', 'incorr'): 2,
  ('тумбочки', 'incorr'): 2,
  ('тумбы', 'incorr'): 1,
  ('не большие', 'incorr'): 1,
  ('стулья', 'incorr'): 1,
  ('не застекленные', 'corr'): 1,
  ('маленькие', 'pcorr'): 1,
  ('кровати', 'incorr'): 1},
 (24, 'инструментами', 'instrumenti'): {('инструментами', 'corr'): 29,
  ('ручками', 'pcorr'): 4,
  ('ложечками', 'pcorr'): 1,
  ('приборами', 'pcorr'): 1,
  ('nan', 'incorr'): 1,
  ('поверхностями', 'pcorr'): 1},
 (25, 'кресла', 'naslanjači'): {('кресла', 'corr'): 10,
  ('изделия', 'pcorr'): 5,
  ('части', 'pcorr'): 2,
  ('приборы', 'pcorr'): 2,
  ('nan', 'incorr'): 2,
  ('вещи', 'pcorr'): 2,
  ('насавлены', 'incorr'): 1,
  ('видны', 'incorr'): 1,
  ('нагромождения', 'pcorr'): 1,
  ('навалены', 'incorr'): 1,
  ('тут', 'incorr'): 1,
  ('насланжича', 'incorr'): 1,
  ('сиденья', 'corr'): 1,
  ('они', 'incorr'): 1,
  ('налажены', 'incorr'): 1,
  ('оборудования', 'pcorr'): 1,
  ('очень', 'incorr'): 1,
  ('инструменты', 'pcorr'): 1,
  ('там', 'incorr'): 1,
  ('станки', 'pcorr'): 1},
 (26, 'колпаками', 'senčniki'): {('огоньками', 'pcorr'): 4,
  ('зонтиками', 'pcorr'): 3,
  ('nan', 'incorr'): 3,
  ('абажурами', 'corr'): 3,
  ('лампочками', 'pcorr'): 2,
  ('свечками', 'pcorr'): 2,
  ('стружками', 'incorr'): 2,
  ('подсвечниками', 'pcorr'): 2,
  ('колпаками', 'corr'): 2,
  ('свечами', 'pcorr'): 1,
  ('стеклами', 'pcorr'): 1,
  ('обожурами', 'corr'): 1,
  ('аьажурами', 'corr'): 1,
  ('ночниками', 'pcorr'): 1,
  ('обажурами', 'corr'): 1,
  ('наконечниками', 'incorr'): 1,
  ('облицованными', 'incorr'): 1,
  ('стёклами', 'pcorr'): 1,
  ('краями', 'pcorr'): 1,
  ('рассеивателями', 'corr'): 1,
  ('шляпами', 'pcorr'): 1,
  ('дырами', 'pcorr'): 1,
  ('надписями', 'pcorr'): 1},
 (27, 'провода', 'napeljave'): {('nan', 'incorr'): 5,
  ('приборы', 'pcorr'): 4,
  ('провода', 'corr'): 4,
  ('установки', 'pcorr'): 4,
  ('нагреватели', 'pcorr'): 3,
  ('плиты', 'pcorr'): 2,
  ('напильники', 'incorr'): 2,
  ('паяльники', 'pcorr'): 1,
  ('инструменты', 'pcorr'): 1,
  ('конфорки', 'pcorr'): 1,
  ('механизмы', 'pcorr'): 1,
  ('иструменты', 'pcorr'): 1,
  ('присполсобления', 'pcorr'): 1,
  ('устройства', 'pcorr'): 1,
  ('приспособления', 'pcorr'): 1,
  ('лампы', 'pcorr'): 1,
  ('чайники', 'pcorr'): 1,
  ('горелки', 'pcorr'): 1,
  ('штуки', 'pcorr'): 1,
  ('наплавы', 'incorr'): 1},
 (28, 'принялись', 'sprejeli'): {('стояли', 'pcorr'): 6,
  ('встретили', 'pcorr'): 4,
  ('принялись', 'corr'): 3,
  ('зашли', 'pcorr'): 3,
  ('ждали', 'pcorr'): 2,

In [18]:
sk_cognates = cognate_searcher(slovak_ans, russian_true, slovak_true)
sk_cognates

{(10, 'повернулся', 'sa obrátil'): {('повернулся', 'corr'): 20,
  ('обернулся', 'pcorr'): 16,
  ('развернулся', 'corr'): 11,
  ('nan', 'incorr'): 3,
  ('обратился', 'incorr'): 2,
  ('повернул', 'corr'): 2,
  ('сообразил', 'incorr'): 2,
  ('осмотрелся', 'incorr'): 2,
  ('оглянулся', 'pcorr'): 1,
  ('обратился к скрещенной трибуне', 'incorr'): 1,
  ('обратил', 'incorr'): 1,
  ('вышел', 'pcorr'): 1,
  ('спустился', 'pcorr'): 1,
  ('повернулся(развернулся)', 'corr'): 1,
  ('заметил', 'incorr'): 1,
  ('посмотрел', 'pcorr'): 1,
  ('повернуля', 'corr'): 1,
  ('взял', 'corr'): 1,
  ('собрался', 'pcorr'): 1},
 (11, 'ступеням', 'schodíkom'): {('ступеням', 'corr'): 15,
  ('nan', 'incorr'): 9,
  ('ступенькам', 'corr'): 5,
  ('лестнице', 'corr'): 5,
  ('спуску', 'pcorr'): 4,
  ('трибуне', 'pcorr'): 4,
  ('воротам', 'pcorr'): 3,
  ('помосту', 'pcorr'): 3,
  ('выходу', 'pcorr'): 2,
  ('писарю', 'pcorr'): 1,
  ('не глядя ни направо ни налево', 'incorr'): 1,
  ('дворцу', 'pcorr'): 1,
  ('сходням', 'corr'): 1,
  ('товарищам', 'pcorr'): 1,
  ('ани', 'incorr'): 1,
  ('ступеньками', 'corr'): 1,
  ('входу', 'pcorr'): 1,
  ('людям', 'pcorr'): 1,
  ('повороту', 'pcorr'): 1,
  ('дому', 'pcorr'): 1,
  ('источнику', 'pcorr'): 1,
  ('ступенямплит', 'corr'): 1,
  ('толпе', 'pcorr'): 1,
  ('горе', 'pcorr'): 1,
  ('берегу', 'pcorr'): 1,
  ('ступенм', 'corr'): 1,
  ('девушке', 'pcorr'): 1,
  ('месту откуда прибыл', 'pcorr'): 1},
 (12, 'шашек', 'dlaždice'): {('плиток', 'corr'): 14,
  ('досок', 'pcorr'): 13,
  ('nan', 'incorr'): 11,
  ('камней', 'pcorr'): 6,
  ('цветов', 'pcorr'): 3,
  ('узоров', 'corr'): 2,
  ('шашек', 'corr'): 2,
  ('плит', 'corr'): 2,
  ('ступеней', 'pcorr'): 1,
  ('пестрого', 'incorr'): 1,
  ('стеклышек', 'pcorr'): 1,
  ('полей', 'corr'): 1,
  ('волокон', 'pcorr'): 1,
  ('мозаик', 'corr'): 1,
  ('листов', 'pcorr'): 1,
  ('камешков', 'corr'): 1,
  ('листьев', 'pcorr'): 1,
  ('лен', 'incorr'): 1,
  ('пестрых плиток', 'corr'): 1,
  ('плитки', 'corr'): 1,
  ('дощечек', 'pcorr'): 1,
  ('луж', 'pcorr'): 1,
  ('ступенек', 'pcorr'): 1,
  ('цветов  были', 'incorr'): 1},
 (13, 'спиною', 'chrbtom'): {('спиной', 'corr'): 54,
  ('nan', 'incorr'): 2,
  ('плечами', 'pcorr'): 2,
  ('спиной сто', 'corr'): 1,
  ('спину', 'corr'): 1,
  ('спиною', 'corr'): 1,
  ('пазухой', 'incorr'): 1,
  ('городом', 'pcorr'): 1,
  ('нашими спинами, как град, падают', 'corr'): 1,
  ('храбрость', 'incorr'): 1,
  ('спинами', 'corr'): 1,
  ('шиворот', 'incorr'): 1,
  ('спиной      видит как', 'corr'): 1,
  ('спиной за', 'corr'): 1},
 (14, 'финики', 'datle'): {('nan', 'incorr'): 20,
  ('финики', 'corr'): 10,
  ('знал', 'incorr'): 3,
  ('также', 'incorr'): 2,
  ('и', 'incorr'): 2,
  ('даже', 'incorr'): 2,
  ('звеня', 'pcorr'): 2,
  ('дальше же', 'incorr'): 1,
  ('далее', 'incorr'): 1,
  ('орехи', 'pcorr'): 1,
  ('до того', 'incorr'): 1,
  ('чувствовал', 'pcorr'): 1,
  ('плоды', 'pcorr'): 1,
  ('учитывая', 'incorr'): 1,
  ('дятлы', 'incorr'): 1,
  ('с трибуны', 'incorr'): 1,
  ('видел', 'incorr'): 1,
  ('представлял', 'incorr'): 1,
  ('заенящие', 'incorr'): 1,
  ('слышал', 'pcorr'): 1,
  ('день', 'incorr'): 1,
  ('так', 'incorr'): 1,
  ('столько много', 'incorr'): 1,
  ('понимая', 'pcorr'): 1,
  ('доволен', 'incorr'): 1,
  ('поэтому', 'incorr'): 1,
  ('дальше', 'incorr'): 1,
  ('а в ревкоме', 'incorr'): 1,
  ('дату', 'incorr'): 1,
  ('затем', 'incorr'): 1,
  ('думая', 'incorr'): 1,
  ('да так', 'incorr'): 1,
  ('и золото', 'pcorr'): 1,
  ('также обратил внимание', 'incorr'): 1,
  ('даты', 'incorr'): 1},
 (15, 'чудо', 'zázrak'): {('чудо', 'corr'): 23,
  ('nan', 'incorr'): 13,
  ('чудотворца', 'pcorr'): 6,
  ('то', 'incorr'): 5,
  ('призрак', 'pcorr'): 3,
  ('увидеть', 'incorr'): 2,
  ('на месте', 'pcorr'): 2,
  ('зрелище', 'pcorr'): 2,
  ('явление', 'pcorr'): 1,
  ('сейчас', 'incorr'): 1,
  ('воочию', 'incorr'): 1,
  ('чуда', 'corr'): 1,
  ('невозможное', 'corr'): 1,
  ('все', 'incorr'): 1,
  ('человека', 'pcorr'): 1,
  ('н', 'incorr'): 1,
  ('видели чудо', 'corr'): 1,
  ('картину', 'pcorr'): 1,
  ('призрака', 'pcorr'): 1,
  ('живого', 'incorr'): 1,
  ('умирающего', 'pcorr'): 1},
 (16, 'вырвался', 'vytrhol'): {('вырвался', 'corr'): 29,
  ('nan', 'incorr'): 9,
  ('ушел', 'pcorr'): 3,
  ('выскользнул', 'corr'): 3,
  ('выбрался', 'pcorr'): 2,
  ('освободился', 'corr'): 2,
  ('вырваться', 'corr'): 1,
  ('вырванный', 'pcorr'): 1,
  ('вырывался', 'corr'): 1,
  ('ускользает', 'corr'): 1,
  ('выбирается', 'pcorr'): 1,
  ('но все же вырвался', 'corr'): 1,
  ('выпохнул', 'incorr'): 1,
  ('вырывается', 'corr'): 1,
  ('вырвавшийся', 'corr'): 1,
  ('но вырвался', 'corr'): 1,
  ('ускользнул', 'corr'): 1,
  ('вернулся', 'pcorr'): 1,
  ('вышел', 'pcorr'): 1,
  ('и вырвался', 'corr'): 1,
  ('и все', 'incorr'): 1,
  ('высвободился', 'corr'): 1,
  ('выскочил', 'pcorr'): 1,
  ('всё же', 'pcorr'): 1,
  ('предстал', 'pcorr'): 1,
  ('дать', 'incorr'): 1,
  ('не выкарабкается', 'pcorr'): 1},
 (17, 'веревки', 'povrazy'): {('веревки', 'corr'): 16,
  ('одежду', 'pcorr'): 9,
  ('повязки', 'pcorr'): 8,
  ('верёвки', 'corr'): 7,
  ('доспехи', 'pcorr'): 6,
  ('оковы', 'pcorr'): 5,
  ('nan', 'incorr'): 4,
  ('кандалы', 'pcorr'): 3,
  ('рубаху', 'pcorr'): 2,
  ('верёвку', 'corr'): 1,
  ('веревки(путы)', 'corr'): 1,
  ('лохмотья', 'pcorr'): 1,
  ('перчатки', 'pcorr'): 1,
  ('веревками', 'corr'): 1,
  ('порезы', 'incorr'): 1,
  ('веревку', 'corr'): 1,
  ('тряпье', 'pcorr'): 1,
  ('латы', 'pcorr'): 1},
 (18, 'допросе', 'výsluchu'): {('допросе', 'corr'): 15,
  ('nan', 'incorr'): 13,
  ('виселице', 'pcorr'): 4,
  ('запястьях', 'pcorr'): 3,
  ('весу', 'incorr'): 3,
  ('изнанку', 'incorr'): 3,
  ('плечах', 'incorr'): 3,
  ('время допроса', 'corr'): 3,
  ('допросах', 'corr'): 2,
  ('пальцах', 'pcorr'): 1,
  ('боли в', 'incorr'): 1,
  ('силу', 'pcorr'): 1,
  ('предплечьях', 'pcorr'): 1,
  ('висилице', 'pcorr'): 1,
  ('ногах', 'pcorr'): 1,
  ('дыбе', 'pcorr'): 1,
  ('раненых', 'pcorr'): 1,
  ('лодыжках', 'pcorr'): 1,
  ('сломанных', 'incorr'): 1,
  ('вытянутых', 'incorr'): 1,
  ('его', 'incorr'): 1,
  ('кресте', 'pcorr'): 1,
  ('столбе', 'pcorr'): 1,
  ('суставах', 'pcorr'): 1,
  ('палке', 'pcorr'): 1,
  ('спину', 'incorr'): 1,
  ('локтях', 'pcorr'): 1,
  ('ногах', 'incorr'): 1,
  ('левую сторону', 'incorr'): 1},
 (19, 'сумасшедшей', 'pomäteným'): {('безумной', 'corr'): 8,
  ('тупой', 'pcorr'): 8,
  ('nan', 'incorr'): 6,
  ('глупой', 'corr'): 6,
  ('сумасшедшей', 'corr'): 5,
  ('злой', 'pcorr'): 4,
  ('кривой', 'pcorr'): 3,
  ('помутнённой', 'pcorr'): 2,
  ('помутневшей', 'pcorr'): 2,
  ('заливистым', 'pcorr'): 1,
  ('отстраненной', 'pcorr'): 1,
  ('детской', 'pcorr'): 1,
  ('безмятежной', 'pcorr'): 1,
  ('тупой и злой', 'pcorr'): 1,
  ('странной', 'pcorr'): 1,
  ('беззубой', 'pcorr'): 1,
  ('смятеннойвидел', 'pcorr'): 1,
  ('помпезной', 'pcorr'): 1,
  ('pcorr', 'pcorr'): 1,
  ('не веселой', 'pcorr'): 1,
  ('помутнённрй', 'pcorr'): 1,
  ('усталой', 'pcorr'): 1,
  ('пустой', 'pcorr'): 1,
  ('тупой безумной', 'corr'): 1,
  ('изможденной', 'pcorr'): 1,
  ('беспамятной', 'pcorr'): 1,
  ('смятенной', 'pcorr'): 1,
  ('затуманенной', 'pcorr'): 1,
  ('глуповатой', 'pcorr'): 1,
  ('растерянной', 'pcorr'): 1,
  ('целеустремленной', 'pcorr'): 1,
  ('блаженной', 'corr'): 1,
  ('мучительной', 'pcorr'): 1,
  ('легкой', 'pcorr'): 1},
 (110, 'знал', 'vedel'): {('видел', 'pcorr'): 33,
  ('знал', 'corr'): 28,
  ('nan', 'incorr'): 2,
  ('увидел', 'pcorr'): 2,
  ('уже знал', 'corr'): 1,
  ('видит', 'pcorr'): 1,
  ('знает', 'corr'): 1,
  ('видел как стражник', 'pcorr'): 1},
 (111, 'ступеням', 'schodíkom'): {('ступеням', 'corr'): 20,
  ('воротам', 'pcorr'): 10,
  ('nan', 'incorr'): 6,
  ('лестницам', 'corr'): 5,
  ('выходам', 'pcorr'): 3,
  ('сходням', 'corr'): 2,
  ('входам', 'pcorr'): 2,
  ('ступенькам', 'corr'): 2,
  ('дверям', 'pcorr'): 2,
  ('стенам', 'pcorr'): 1,
  ('варотам', 'pcorr'): 1,
  ('стражам', 'pcorr'): 1,
  ('проходам', 'pcorr'): 1,
  ('подходам', 'pcorr'): 1,
  ('спускам', 'pcorr'): 1,
  ('лагерям', 'pcorr'): 1,
  ('перилам', 'pcorr'): 1,
  ('сходили', 'incorr'): 1,
  ('сходам', 'corr'): 1,
  ('ступеням (лестницам)', 'corr'): 1,
  ('строям', 'pcorr'): 1,
  ('каторжников', 'pcorr'): 1,
  ('заключенных', 'pcorr'): 1,
  ('леслицам', 'corr'): 1,
  ('пешком', 'incorr'): 1,
  ('мостикам', 'pcorr'): 1},
 (112, 'дорогу', 'cestu'): {('дорогу', 'corr'): 40,
  ('nan', 'incorr'): 8,
  ('лестницу', 'pcorr'): 3,
  ('улицу', 'corr'): 3,
  ('тропу', 'pcorr'): 2,
  ('место', 'incorr'): 2,
  ('запад', 'incorr'): 2,
  ('дороге', 'corr'): 1,
  ('дороге смерти', 'corr'): 1,
  ('тесную дорогу', 'corr'): 1,
  ('смертную тропу', 'pcorr'): 1,
  ('смерть', 'pcorr'): 1,
  ('вела', 'incorr'): 1,
  ('казнь', 'pcorr'): 1,
  ('сторону', 'pcorr'): 1,
  ('дорогуда так', 'corr'): 1},
 (113, 'осужденных', 'odsúdenci'): {('осужденных', 'corr'): 19,
  ('nan', 'incorr'): 7,
  ('осуждённых', 'corr'): 6,
  ('каторжников', 'pcorr'): 6,
  ('заключенных', 'corr'): 3,
  ('отсюда', 'incorr'): 3,
  ('заключённых', 'corr'): 2,
  ('их', 'incorr'): 2,
  ('каторжники', 'pcorr'): 2,
  ('осужденного', 'corr'): 2,
  ('людей', 'pcorr'): 1,
  ('судей', 'pcorr'): 1,
  ('подсудимых', 'corr'): 1,
  ('теперь', 'incorr'): 1,
  ('однако', 'incorr'): 1,
  ('очевидцы?', 'pcorr'): 1,
  ('осужденные уже исчезли из поля видимости', 'corr'): 1,
  ('осуждённого', 'corr'): 1,
  ('поэтому', 'incorr'): 1,
  ('боль', 'pcorr'): 1,
  ('отступили', 'incorr'): 1,
  ('к сожалению', 'incorr'): 1,
  ('кто вокруг', 'incorr'): 1,
  ('одним глазом', 'incorr'): 1,
  ('трибуну за хребтом', 'pcorr'): 1,
  ('успокоился', 'incorr'): 1,
  ('но из за болезни', 'incorr'): 1},
 (114, 'глашатаев', 'vyvolávačov'): {('nan', 'incorr'): 13,
  ('призывателей', 'pcorr'): 10,
  ('людей', 'pcorr'): 9,
  ('глашатаев', 'corr'): 8,
  ('стражников', 'pcorr'): 2,
  ('конвоиров', 'pcorr'): 2,
  ('палачей', 'pcorr'): 2,
  ('которые оплакивали', 'incorr'): 1,
  ('легионеров', 'pcorr'): 1,
  ('мусоров', 'incorr'): 1,
  ('отдельных голосов', 'pcorr'): 1,
  ('толпы', 'pcorr'): 1,
  ('проклятий', 'incorr'): 1,
  ('глашатых', 'corr'): 1,
  ('глашатого', 'corr'): 1,
  ('по амерекански', 'incorr'): 1,
  ('окупантов', 'pcorr'): 1,
  ('звучавшие четко', 'incorr'): 1,
  ('вояк', 'pcorr'): 1,
  ('волков', 'incorr'): 1,
  ('переводчиков', 'pcorr'): 1,
  ('которые', 'incorr'): 1,
  ('жителей', 'pcorr'): 1,
  ('очевидцев', 'pcorr'): 1,
  ('казни', 'incorr'): 1,
  ('хурхае', 'incorr'): 1,
  ('ловцов', 'incorr'): 1,
  ('боли', 'pcorr'): 1,
  ('убейте его', 'incorr'): 1,
  ('арестованных', 'pcorr'): 1},
 (115, 'греческом', 'grécky'): {('греческом', 'corr'): 49,
  ('греческих', 'corr'): 7,
  ('nan', 'incorr'): 5,
  ('грецких', 'pcorr'): 2,
  ('грецком', 'pcorr'): 1,
  ('арамейских', 'pcorr'): 1,
  ('герцек', 'incorr'): 1,
  ('жаргоне', 'incorr'): 1,
  ('греческим', 'corr'): 1,
  ('славянских', 'pcorr'): 1},
 (116, 'труба', 'poľnice'): {('голос', 'pcorr'): 10,
  ('nan', 'incorr'): 8,
  ('труба', 'corr'): 5,
  ('голос горна', 'corr'): 4,
  ('толпа', 'pcorr'): 3,
  ('женщина', 'pcorr'): 2,
  ('голос женщины', 'pcorr'): 2,
  ('глас', 'pcorr'): 2,
  ('грохот', 'pcorr'): 2,
  ('гонец', 'pcorr'): 1,
  ('всадник', 'pcorr'): 1,
  ('горна', 'corr'): 1,
  ('звук горна', 'corr'): 1,
  ('шум толпы', 'pcorr'): 1,
  ('крик людей', 'pcorr'): 1,
  ('голос ...', 'pcorr'): 1,
  ('бег', 'incorr'): 1,
  ('хлыст', 'pcorr'): 1,
  ('трубный звон', 'corr'): 1,
  ('конница', 'pcorr'): 1,
  ('голос девулки которая', 'pcorr'): 1,
  ('кратко', 'incorr'): 1,
  ('баржу', 'incorr'): 1,
  ('горбатый голосо', 'pcorr'): 1,
  ('повозки', 'incorr'): 1,
  ('кто-то', 'incorr'): 1,
  ('горн', 'corr'): 1,
  ('хаос', 'incorr'): 1,
  ('шум', 'pcorr'): 1,
  ('горы', 'pcorr'): 1,
  ('девушка', 'pcorr'): 1,
  ('звук трубы', 'corr'): 1,
  ('голос всадницы', 'pcorr'): 1,
  ('звук конницы', 'pcorr'): 1,
  ('цоканье', 'pcorr'): 1,
  ('голос птицы', 'pcorr'): 1,
  ('горбатый голос', 'pcorr'): 1,
  ('голос пленницы', 'pcorr'): 1,
  ('хлестание', 'incorr'): 1,
  ('ржание', 'pcorr'): 1},
 (117, 'весело', 'veselo'): {('весело', 'corr'): 53,
  ('громко', 'pcorr'): 5,
  ('nan', 'incorr'): 4,
  ('звонко', 'corr'): 1,
  ('задорно', 'corr'): 1,
  ('тихо', 'pcorr'): 1,
  ('хрипло', 'pcorr'): 1,
  ('сильно', 'pcorr'): 1,
  ('резко', 'pcorr'): 1,
  ('аплодировал', 'incorr'): 1},
 (118, 'мальчишек', 'šarvancov'): {('сорванцов', 'corr'): 25,
  ('мальчишек', 'corr'): 8,
  ('nan', 'incorr'): 8,
  ('сарванцов', 'pcorr'): 4,
  ('стычек', 'incorr'): 3,
  ('доносившийся', 'pcorr'): 2,
  ('шарфов', 'incorr'): 1,
  ('шпаны', 'corr'): 1,
  ('жаровонков', 'pcorr'): 1,
  ('обломков, сорванных', 'pcorr'): 1,
  ('крыш', 'pcorr'): 1,
  ('детей', 'corr'): 1,
  ('детворы', 'corr'): 1,
  ('стрелы', 'pcorr'): 1,
  ('людей', 'pcorr'): 1,
  ('этих трех сорванцов', 'corr'): 1,
  ('шарванцов', 'corr'): 1,
  ('скарлатина', 'incorr'): 1,
  ('черепиц', 'pcorr'): 1,
  ('хулиганов', 'pcorr'): 1,
  ('ветра', 'pcorr'): 1,
  ('полный рабочий день', 'incorr'): 1,
  ('осуждённых', 'pcorr'): 1,
  ('группы сорванцов', 'corr'): 1,
  ('и ветер', 'pcorr'): 1},
 (119, 'солдат', 'vojak'): {('солдат', 'corr'): 21,
  ('воин', 'corr'): 15,
  ('вожак', 'pcorr'): 10,
  ('nan', 'incorr'): 7,
  ('главарь', 'pcorr'): 2,
  ('вождь', 'pcorr'): 2,
  ('страж', 'corr'): 1,
  ('глава', 'pcorr'): 1,
  ('прокуратор', 'pcorr'): 1,
  ('pcorr', 'pcorr'): 1,
  ('вояка', 'corr'): 1,
  ('начальник', 'pcorr'): 1,
  ('стражник', 'corr'): 1,
  ('главарь (вожак)', 'pcorr'): 1,
  ('главнокомандующий', 'pcorr'): 1,
  ('пилат', 'pcorr'): 1,
  ('человека', 'pcorr'): 1,
  ('возница', 'pcorr'): 1},
 (120, 'значком', 'zástavkou'): {('nan', 'incorr'): 22,
  ('знаменем', 'pcorr'): 7,
  ('флагом', 'pcorr'): 4,
  ('значком', 'corr'): 4,
  ('флажком', 'pcorr'): 3,
  ('оружием', 'pcorr'): 3,
  ('мечом', 'pcorr'): 2,
  ('свитком', 'pcorr'): 2,
  ('кнутом', 'pcorr'): 2,
  ('посохом', 'pcorr'): 2,
  ('на страже с месом', 'pcorr'): 1,
  ('щитом', 'pcorr'): 1,
  ('свтком', 'pcorr'): 1,
  ('страху', 'incorr'): 1,
  ('вымпелом', 'pcorr'): 1,
  ('махнул флажком', 'pcorr'): 1,
  ('копьём', 'pcorr'): 1,
  ('с мечом', 'pcorr'): 1,
  ('знаменем тревоги', 'pcorr'): 1,
  ('знал', 'pcorr'): 1,
  ('солдат космоса', 'incorr'): 1,
  ('штандартом', 'corr'): 1,
  ('!!!!', 'incorr'): 1,
  ('страхом', 'incorr'): 1,
  ('сжатым платком', 'pcorr'): 1,
  ('знаком', 'corr'): 1,
  ('страха', 'pcorr'): 1,
  ('всеми держащий платок', 'incorr'): 1},
 (121, 'остановились', 'sa zastavili'): {('nan', 'incorr'): 27,
  ('остановились', 'corr'): 21,
  ('остановился', 'corr'): 3,
  ('встали', 'corr'): 2,
  ('стражи', 'incorr'): 2,
  ('дали команду', 'pcorr'): 1,
  ('застыли', 'pcorr'): 1,
  ('остановил', 'corr'): 1,
  ('отдал приказ', 'pcorr'): 1,
  ('залвигались', 'pcorr'): 1,
  ('поднялись', 'pcorr'): 1,
  ('ушли', 'pcorr'): 1,
  ('замерли', 'pcorr'): 1,
  ('заставили', 'incorr'): 1,
  ('убежал', 'pcorr'): 1,
  ('посмотрели на него', 'pcorr'): 1,
  ('покинули его', 'pcorr'): 1,
  ('кричал', 'pcorr'): 1,
  ('отступили', 'pcorr'): 1},
 (122, 'вылетела', 'vyletela'): {('вылетела', 'corr'): 29,
  ('nan', 'incorr'): 8,
  ('выскочила', 'corr'): 6,
  ('выбежала', 'pcorr'): 4,
  ('влетела', 'corr'): 3,
  ('выехала', 'pcorr'): 3,
  ('вышла', 'pcorr'): 3,
  ('вылетел', 'corr'): 2,
  ('трусил', 'pcorr'): 1,
  ('выехал', 'pcorr'): 1,
  ('побежала', 'pcorr'): 1,
  ('влетел', 'corr'): 1,
  ('полетел', 'corr'): 1,
  ('вылетили', 'corr'): 1,
  ('прискакала', 'pcorr'): 1,
  ('скакала', 'corr'): 1,
  ('неслась', 'corr'): 1,
  ('красной', 'incorr'): 1,
  ('выбежала боком', 'pcorr'): 1},
 (123, 'каменной', 'kamennom'): {('каменной', 'corr'): 51,
  ('nan', 'incorr'): 9,
  ('кирпичной', 'corr'): 2,
  ('заросшей', 'pcorr'): 1,
  ('каменной стеной', 'corr'): 1,
  ('каменой', 'corr'): 1,
  ('уличной', 'pcorr'): 1,
  ('отвесной', 'pcorr'): 1,
  ('левой', 'pcorr'): 1,
  ('цокот копыт    стоял под', 'incorr'): 1},
 (124, 'виноград', 'viničom'): {('виноград', 'corr'): 26,
  ('nan', 'incorr'): 17,
  ('плющ', 'pcorr'): 4,
  ('дым', 'pcorr'): 2,
  ('путь', 'pcorr'): 2,
  ('ым', 'pcorr'): 1,
  ('виноградник', 'pcorr'): 1,
  ('виннич', 'incorr'): 1,
  ('вьюн', 'pcorr'): 1,
  ('экипаж', 'incorr'): 1,
  ('по', 'incorr'): 1,
  ('мох', 'pcorr'): 1,
  ('сорняк', 'pcorr'): 1,
  ('поросшей', 'incorr'): 1,
  ('плюш', 'corr'): 1,
  ('вьюнок', 'pcorr'): 1,
  ('заросший', 'incorr'): 1,
  ('накацу', 'incorr'): 1,
  ('голос', 'incorr'): 1,
  ('иней', 'incorr'): 1,
  ('не знаю', 'incorr'): 1,
  ('он', 'incorr'): 1,
  ('один', 'incorr'): 1},
 (125, 'дорогой', 'cestou'): {('дорогой', 'corr'): 43,
  ('nan', 'incorr'): 11,
  ('путь', 'corr'): 6,
  ('дороге', 'corr'): 3,
  ('путем', 'corr'): 1,
  ('дороги', 'corr'): 1,
  ('пытался', 'incorr'): 1,
  ('пути', 'corr'): 1,
  ('достала', 'incorr'): 1,
  ('извилистой', 'incorr'): 1},
 (126, 'мальчик', 'chlapec'): {('мальчик', 'corr'): 29,
  ('nan', 'incorr'): 12,
  ('ребенок', 'corr'): 6,
  ('мальчишка', 'corr'): 4,
  ('хлопец', 'corr'): 3,
  ('ребёнок', 'corr'): 2,
  ('юноша', 'corr'): 1,
  ('дитя', 'corr'): 1,
  ('молодец', 'pcorr'): 1,
  ('дробь', 'pcorr'): 1,
  ('мышь', 'pcorr'): 1,
  ('клоп', 'pcorr'): 1,
  ('гном', 'pcorr'): 1,
  ('холоп', 'incorr'): 1,
  ('бурундук', 'pcorr'): 1,
  ('гномик', 'pcorr'): 1,
  ('тмави', 'incorr'): 1,
  ('парень', 'corr'): 1,
  ('конь', 'pcorr'): 1},
 (127, 'командир', 'veliteľ'): {('nan', 'incorr'): 21,
  ('приехал', 'incorr'): 7,
  ('командир', 'corr'): 7,
  ('пригнал', 'incorr'): 3,
  ('смуглый', 'incorr'): 2,
  ('пронесся', 'incorr'): 2,
  ('прискакал', 'incorr'): 1,
  ('начальник', 'corr'): 1,
  ('кавалер', 'pcorr'): 1,
  ('солдат', 'pcorr'): 1,
  ('предводитель', 'pcorr'): 1,
  ('грязный', 'incorr'): 1,
  ('переехал', 'incorr'): 1,
  ('выехал', 'incorr'): 1,
  ('закричал', 'incorr'): 1,
  ('губы', 'incorr'): 1,
  ('он пронесся', 'incorr'): 1,
  ('воин', 'pcorr'): 1,
  ('накинулся', 'incorr'): 1,
  ('выскочил', 'incorr'): 1,
  ('вылетел', 'incorr'): 1,
  ('примчался', 'incorr'): 1,
  ('хлопец', 'incorr'): 1,
  ('перегнал', 'incorr'): 1,
  ('крошечны', 'incorr'): 1,
  ('вождь', 'incorr'): 1,
  ('кучер', 'pcorr'): 1,
  ('кавалерийской', 'incorr'): 1,
  ('человек', 'pcorr'): 1,
  ('командующий', 'pcorr'): 1,
  ('велител', 'incorr'): 1,
  ('и скакун', 'pcorr'): 1,
  ('выскочил перед', 'incorr'): 1},
 (128, 'выхватил', 'vytasil'): {('вытащил', 'corr'): 41,
  ('nan', 'incorr'): 9,
  ('выхватил', 'corr'): 7,
  ('вынул', 'corr'): 7,
  ('достал', 'corr'): 3,
  ('обнажил', 'corr'): 1,
  ('не знаю', 'incorr'): 1},
 (129, 'взмокшая', 'spotený'): {('nan', 'incorr'): 23,
  ('потная', 'corr'): 11,
  ('вспотевшая', 'corr'): 5,
  ('взмокшая', 'corr'): 4,
  ('резвая', 'pcorr'): 2,
  ('уставшая', 'pcorr'): 2,
  ('попятилась', 'incorr'): 1,
  ('скакун', 'incorr'): 1,
  ('старая', 'pcorr'): 1,
  ('в мыле', 'corr'): 1,
  ('гнедая', 'pcorr'): 1,
  ('армейская', 'pcorr'): 1,
  ('яростная', 'pcorr'): 1,
  ('покрытая потом', 'corr'): 1,
  ('усталая', 'pcorr'): 1,
  ('степная', 'pcorr'): 1,
  ('быстрая', 'pcorr'): 1,
  ('черная', 'pcorr'): 1,
  ('плотная', 'pcorr'): 1,
  ('в пене', 'pcorr'): 1,
  ('молодая', 'pcorr'): 1,
  ('гнядая', 'pcorr'): 1,
  ('мокрая', 'corr'): 1,
  ('цувол', 'incorr'): 1,
  ('клюнула', 'incorr'): 1,
  ('и рябая', 'pcorr'): 1,
  ('взлетели и испугали', 'incorr'): 1,
  ('разъяренная', 'pcorr'): 1},
 (130, 'шарахнулась', 'cúvol'): {('nan', 'incorr'): 24,
  ('заржала', 'pcorr'): 5,
  ('шарахнулась', 'corr'): 4,
  ('откинувшись', 'pcorr'): 2,
  ('встала', 'pcorr'): 2,
  ('попятилась', 'pcorr'): 2,
  ('резко', 'incorr'): 2,
  ('заржав', 'pcorr'): 2,
  ('закричала', 'incorr'): 1,
  ('засопев', 'incorr'): 1,
  ('назад', 'incorr'): 1,
  ('растянулась', 'pcorr'): 1,
  ('становясь', 'pcorr'): 1,
  ('издав вопль', 'pcorr'): 1,
  ('всхрапнула', 'pcorr'): 1,
  ('и', 'incorr'): 1,
  ('взвилась', 'pcorr'): 1,
  ('солдата', 'incorr'): 1,
  ('встав на задние ноги', 'pcorr'): 1,
  ('взбрыкнула', 'pcorr'): 1,
  ('ржанула', 'pcorr'): 1,
  ('попятившись', 'pcorr'): 1,
  ('попятялись', 'pcorr'): 1,
  ('шла', 'pcorr'): 1,
  ('крикнула', 'incorr'): 1,
  ('неожиданно', 'incorr'): 1,

In [19]:
sb_cognates = cognate_searcher(serbian_ans, russian_true, serbian_true)
sb_cognates

{(10, 'повернулся', 'окренуо'): {('повернулся', 'corr'): 9,
  ('оглянулся', 'pcorr'): 9,
  ('обернулся', 'pcorr'): 5,
  ('nan', 'incorr'): 4,
  ('развернулся', 'corr'): 2,
  ('поклонился', 'pcorr'): 1,
  ('повернул', 'corr'): 1,
  ('нагнулся', 'pcorr'): 1,
  ('наклонился', 'pcorr'): 1,
  ('поднялся', 'pcorr'): 1,
  ('окрикнул', 'incorr'): 1,
  ('встал', 'pcorr'): 1,
  ('подумал', 'pcorr'): 1,
  ('повернулся вокруг', 'corr'): 1,
  ('огляделся', 'pcorr'): 1,
  ('онлянулся', 'pcorr'): 1},
 (11, 'ступеням', 'степеницама'): {('лестнице', 'corr'): 13,
  ('ступеням', 'corr'): 6,
  ('платформе', 'pcorr'): 5,
  ('nan', 'incorr'): 5,
  ('помосту', 'pcorr'): 3,
  ('ступенькам', 'corr'): 2,
  ('воротам', 'pcorr'): 2,
  ('плаформе', 'pcorr'): 1,
  ('площади', 'pcorr'): 1,
  ('темницам', 'pcorr'): 1,
  ('деревне', 'pcorr'): 1},
 (12, 'шашек', 'коцака'): {('nan', 'incorr'): 11,
  ('кубиков', 'pcorr'): 5,
  ('досок', 'pcorr'): 4,
  ('камней', 'pcorr'): 4,
  ('плит', 'corr'): 3,
  ('плиток', 'corr'): 3,
  ('цветов', 'pcorr'): 2,
  ('листов', 'pcorr'): 1,
  ('опалубков', 'incorr'): 1,
  ('цветков', 'pcorr'): 1,
  ('камешков', 'corr'): 1,
  ('ступеней', 'pcorr'): 1,
  ('досоксмысл', 'pcorr'): 1,
  ('огней', 'pcorr'): 1,
  ('кубов', 'corr'): 1},
 (13, 'спиною', 'леђа'): {('спиной', 'corr'): 26,
  ('nan', 'incorr'): 7,
  ('плечами', 'pcorr'): 3,
  ('контрольную', 'incorr'): 1,
  ('это', 'incorr'): 1,
  ('балками', 'pcorr'): 1,
  ('смысл', 'incorr'): 1},
 (14, 'финики', 'урме'): {('nan', 'incorr'): 17,
  ('финики', 'corr'): 4,
  ('и урмы', 'incorr'): 2,
  ('деньги', 'pcorr'): 2,
  ('венки', 'pcorr'): 1,
  ('урмы', 'incorr'): 1,
  ('и он видел', 'incorr'): 1,
  ('да', 'incorr'): 1,
  ('помидоры', 'pcorr'): 1,
  ('чувствовал кожей', 'incorr'): 1,
  ('гроши', 'pcorr'): 1,
  ('оружие', 'pcorr'): 1,
  ('шкуры', 'pcorr'): 1,
  ('людей', 'incorr'): 1,
  ('и', 'incorr'): 1,
  ('огня', 'incorr'): 1,
  ('толпа', 'incorr'): 1,
  ('понимал', 'pcorr'): 1,
  ('и даты', 'incorr'): 1},
 (15, 'чудо', 'чудо'): {('чудо', 'corr'): 35,
  ('nan', 'incorr'): 3,
  ('то', 'incorr'): 1,
  ('помилование', 'pcorr'): 1},
 (16, 'вырвался', 'ишчупао'): {('вырвался', 'corr'): 13,
  ('nan', 'incorr'): 6,
  ('выбрался', 'pcorr'): 4,
  ('вырывается', 'corr'): 2,
  ('спасся', 'corr'): 2,
  ('исчез', 'pcorr'): 2,
  ('вышел', 'pcorr'): 1,
  ('ускользает', 'corr'): 1,
  ('выравался', 'corr'): 1,
  ('выскочил', 'pcorr'): 1,
  ('восстал', 'pcorr'): 1,
  ('сбежало', 'corr'): 1,
  ('сбежал', 'corr'): 1,
  ('умрет', 'pcorr'): 1,
  ('избежал', 'corr'): 1,
  ('выпрыгивает', 'pcorr'): 1,
  ('выскользнул', 'corr'): 1},
 (17, 'веревки', 'конопце'): {('веревки', 'corr'): 12,
  ('nan', 'incorr'): 5,
  ('оковы', 'pcorr'): 3,
  ('кандалы', 'pcorr'): 3,
  ('одежду', 'pcorr'): 3,
  ('наручники', 'pcorr'): 2,
  ('веревку', 'corr'): 2,
  ('тулуп', 'pcorr'): 1,
  ('куртку', 'pcorr'): 1,
  ('шляпу', 'pcorr'): 1,
  ('гвозди', 'incorr'): 1,
  ('рубашку', 'pcorr'): 1,
  ('даты', 'incorr'): 1,
  ('сапоги', 'pcorr'): 1,
  ('одежды', 'pcorr'): 1,
  ('накидку', 'pcorr'): 1,
  ('власяницу', 'pcorr'): 1},
 (18, 'допросе', 'саслушања'): {('nan', 'incorr'): 17,
  ('запястьях', 'pcorr'): 4,
  ('плечах', 'incorr'): 2,
  ('его', 'incorr'): 2,
  ('пытках', 'pcorr'): 2,
  ('допросе', 'corr'): 2,
  ('допросах', 'corr'): 1,
  ('слуъ', 'incorr'): 1,
  ('нечистивых', 'incorr'): 1,
  ('вывернутых', 'incorr'): 1,
  ('стол', 'pcorr'): 1,
  ('пальцах', 'pcorr'): 1,
  ('кистях', 'pcorr'): 1,
  ('непослушных', 'incorr'): 1,
  ('суставах', 'pcorr'): 1,
  ('изнанку', 'incorr'): 1,
  ('дыбе', 'pcorr'): 1},
 (19, 'сумасшедшей', 'лудачким'): {('безумной', 'corr'): 5,
  ('nan', 'incorr'): 4,
  ('лучистой', 'pcorr'): 4,
  ('дурацкой', 'corr'): 3,
  ('сумасшедшей', 'corr'): 3,
  ('лучезарной', 'pcorr'): 2,
  ('светлой', 'pcorr'): 2,
  ('глупой', 'corr'): 2,
  ('человеческой', 'pcorr'): 2,
  ('доброй', 'pcorr'): 2,
  ('смазливой', 'pcorr'): 1,
  ('злобной', 'pcorr'): 1,
  ('человеколюбивой', 'pcorr'): 1,
  ('дурацкой', 'pcorr'): 1,
  ('чудной', 'pcorr'): 1,
  ('грустной', 'pcorr'): 1,
  ('детской', 'pcorr'): 1,
  ('своей', 'pcorr'): 1,
  ('широкой', 'pcorr'): 1,
  ('счастливой', 'pcorr'): 1,
  ('лукавой', 'pcorr'): 1},
 (110, 'знал', 'знао'): {('знал', 'corr'): 32,
  ('знает', 'corr'): 3,
  ('nan', 'incorr'): 3,
  ('понимал', 'pcorr'): 1,
  ('зная', 'pcorr'): 1},
 (111, 'ступеням', 'степеницама'): {('лестницам', 'corr'): 12,
  ('ступеням', 'corr'): 10,
  ('воротам', 'pcorr'): 6,
  ('nan', 'incorr'): 4,
  ('ступенькам', 'corr'): 2,
  ('автобусам', 'incorr'): 1,
  ('помостьям', 'incorr'): 1,
  ('столбам у воды', 'pcorr'): 1,
  ('улицам', 'pcorr'): 1,
  ('дорогам', 'pcorr'): 1,
  ('домам', 'pcorr'): 1},
 (112, 'дорогу', 'пут'): {('дорогу', 'corr'): 29,
  ('nan', 'incorr'): 3,
  ('прямую', 'pcorr'): 1,
  ('тропу', 'pcorr'): 1,
  ('дорогу возле воды', 'corr'): 1,
  ('воду', 'incorr'): 1,
  ('запад', 'incorr'): 1,
  ('реку', 'pcorr'): 1,
  ('дороги', 'corr'): 1,
  ('казнь', 'pcorr'): 1},
 (113, 'осужденных', 'осуђенике'): {('осужденных', 'corr'): 9,
  ('больше', 'incorr'): 7,
  ('nan', 'incorr'): 6,
  ('выше', 'incorr'): 4,
  ('ничего', 'incorr'): 3,
  ('это', 'incorr'): 1,
  ('повешения', 'incorr'): 1,
  ('отступников', 'pcorr'): 1,
  ('внизу', 'incorr'): 1,
  ('но', 'incorr'): 1,
  ('его', 'incorr'): 1,
  ('преступника', 'corr'): 1,
  ('тем более', 'incorr'): 1,
  ('дальше', 'incorr'): 1,
  ('осужденного', 'corr'): 1,
  ('казнь', 'pcorr'): 1},
 (114, 'глашатаев', 'телала'): {('nan', 'incorr'): 12,
  ('людей', 'pcorr'): 6,
  ('глашатаев', 'corr'): 4,
  ('толпы', 'pcorr'): 4,
  ('телят', 'pcorr'): 2,
  ('талалий', 'incorr'): 1,
  ('телалий', 'incorr'): 1,
  ('узников', 'pcorr'): 1,
  ('успокоится', 'incorr'): 1,
  ('проклятий', 'incorr'): 1,
  ('которые там повторяли', 'incorr'): 1,
  ('стражников', 'pcorr'): 1,
  ('мужчины', 'pcorr'): 1,
  ('телала', 'incorr'): 1,
  ('народа', 'pcorr'): 1,
  ('солдат', 'pcorr'): 1,
  ('которые повторялись', 'incorr'): 1},
 (115, 'греческом', 'грчком'): {('греческом', 'corr'): 33,
  ('nan', 'incorr'): 4,
  ('грческих', 'corr'): 1,
  ('армянском', 'pcorr'): 1,
  ('еврейском', 'pcorr'): 1},
 (116, 'труба', 'трубе'): {('труба', 'corr'): 11,
  ('звук трубы', 'corr'): 10,
  ('nan', 'incorr'): 5,
  ('трубы', 'corr'): 2,
  ('звук труб', 'corr'): 2,
  ('не спеша', 'incorr'): 1,
  ('приближался', 'incorr'): 1,
  ('крик', 'pcorr'): 1,
  ('запела труба', 'corr'): 1,
  ('так же', 'incorr'): 1,
  ('крики', 'pcorr'): 1,
  ('звук', 'pcorr'): 1,
  ('трубный звук', 'pcorr'): 1,
  ('толпы', 'pcorr'): 1,
  ('крикунья', 'pcorr'): 1},
 (117, 'весело', 'весело'): {('весело', 'corr'): 30,
  ('nan', 'incorr'): 4,
  ('громко', 'pcorr'): 2,
  ('радостно', 'corr'): 2,
  ('радостная', 'incorr'): 1,
  ('тихо', 'pcorr'): 1},
 (118, 'мальчишек', 'дечака'): {('nan', 'incorr'): 11,
  ('мальчика', 'corr'): 4,
  ('ветра', 'pcorr'): 3,
  ('детей', 'corr'): 2,
  ('птиц', 'pcorr'): 2,
  ('дечака', 'incorr'): 2,
  ('дьячка', 'pcorr'): 2,
  ('мальчиков', 'corr'): 1,
  ('доносящийся', 'pcorr'): 1,
  ('трибун', 'pcorr'): 1,
  ('мясника', 'pcorr'): 1,
  ('ребенка', 'corr'): 1,
  ('черта', 'pcorr'): 1,
  ('мальчик', 'corr'): 1,
  ('людей', 'pcorr'): 1,
  ('наездника', 'incorr'): 1,
  ('звучащий', 'pcorr'): 1,
  ('мальчишек', 'corr'): 1,
  ('труб', 'pcorr'): 1,
  ('камней', 'incorr'): 1,
  ('доносившийся', 'pcorr'): 1},
 (119, 'солдат', 'војник'): {('солдат', 'corr'): 11,
  ('воин', 'corr'): 7,
  ('nan', 'incorr'): 6,
  ('возница', 'pcorr'): 2,
  ('всадник', 'pcorr'): 2,
  ('возник', 'incorr'): 2,
  ('военный', 'pcorr'): 2,
  ('военачальник', 'pcorr'): 1,
  ('он', 'incorr'): 1,
  ('солдат стоявший', 'corr'): 1,
  ('палач', 'pcorr'): 1,
  ('проводние', 'pcorr'): 1,
  ('наездник', 'pcorr'): 1,
  ('страж', 'corr'): 1,
  ('извозчик', 'incorr'): 1},
 (120, 'значком', 'барјачетом'): {('nan', 'incorr'): 16,
  ('бархатом', 'incorr'): 4,
  ('флагом', 'pcorr'): 2,
  ('кнутом', 'pcorr'): 1,
  ('плетью', 'pcorr'): 1,
  ('рапортом', 'incorr'): 1,
  ('мной', 'incorr'): 1,
  ('шпагой', 'pcorr'): 1,
  ('стременем', 'incorr'): 1,
  ('оружием', 'pcorr'): 1,
  ('топорищем', 'pcorr'): 1,
  ('чем то', 'incorr'): 1,
  ('знаменем', 'pcorr'): 1,
  ('штандартом', 'corr'): 1,
  ('орудием', 'pcorr'): 1,
  ('копьем', 'pcorr'): 1,
  ('с барачетом', 'incorr'): 1,
  ('щитом', 'pcorr'): 1,
  ('свертком', 'pcorr'): 1,
  ('барачетом', 'incorr'): 1,
  ('ограждением', 'pcorr'): 1},
 (121, 'остановились', 'зауставили'): {('nan', 'incorr'): 14,
  ('остановились', 'corr'): 8,
  ('остановился', 'corr'): 3,
  ('заговорили', 'pcorr'): 2,
  ('проехали', 'pcorr'): 1,
  ('пошел', 'pcorr'): 1,
  ('установилию', 'pcorr'): 1,
  ('полиции', 'incorr'): 1,
  ('остановились.', 'corr'): 1,
  ('лошадей', 'incorr'): 1,
  ('проверили оружие?', 'pcorr'): 1,
  ('смирно', 'incorr'): 1,
  ('встрепенулись', 'pcorr'): 1,
  ('остановили', 'corr'): 1,
  ('ускакали', 'pcorr'): 1,
  ('заствтавали', 'incorr'): 1,
  ('встали', 'corr'): 1},
 (122, 'вылетела', 'излетела'): {('вылетела', 'corr'): 8,
  ('влетела', 'corr'): 6,
  ('nan', 'incorr'): 6,
  ('взлетела', 'pcorr'): 5,
  ('выбежала', 'pcorr'): 2,
  ('выехала', 'pcorr'): 2,
  ('отправилась', 'pcorr'): 1,
  ('выйдя', 'pcorr'): 1,
  ('выбегая', 'incorr'): 1,
  ('выскочила', 'corr'): 1,
  ('побежала', 'pcorr'): 1,
  ('неу', 'incorr'): 1,
  ('влетела', 'pcorr'): 1,
  ('вышла', 'pcorr'): 1,
  ('залетела', 'pcorr'): 1,
  ('на юг', 'incorr'): 1,
  ('мчалась', 'pcorr'): 1},
 (123, 'каменной', 'каменог'): {('каменной', 'corr'): 31,
  ('nan', 'incorr'): 6,
  ('твердой', 'pcorr'): 1,
  ('неу', 'incorr'): 1,
  ('городской', 'pcorr'): 1},
 (124, 'виноград', 'лоза'): {('виноград', 'corr'): 14,
  ('nan', 'incorr'): 9,
  ('лоза', 'corr'): 2,
  ('плющ', 'pcorr'): 2,
  ('сказочная лоха', 'incorr'): 1,
  ('человек', 'pcorr'): 1,
  ('виноградная лоа', 'corr'): 1,
  ('люд', 'incorr'): 1,
  ('виноград? лоза.', 'corr'): 1,
  ('песок', 'pcorr'): 1,
  ('неу', 'incorr'): 1,
  ('лоза виноград', 'corr'): 1,
  ('дым', 'pcorr'): 1,
  ('побег', 'incorr'): 1,
  ('туман', 'pcorr'): 1,
  ('куст лозы', 'corr'): 1,
  ('вьюн', 'pcorr'): 1},
 (125, 'дорогой', 'путем'): {('дорогой', 'corr'): 21,
  ('путем', 'corr'): 6,
  ('nan', 'incorr'): 5,
  ('путь', 'corr'): 3,
  ('дороге', 'corr'): 1,
  ('срок', 'pcorr'): 1,
  ('дорогой, путём', 'corr'): 1,
  ('неу', 'incorr'): 1,
  ('путемди', 'corr'): 1},
 (126, 'мальчик', 'дечак'): {('nan', 'incorr'): 11,
  ('мальчик', 'corr'): 9,
  ('ребенок', 'corr'): 9,
  ('ребёнок', 'corr'): 1,
  ('дьяк', 'pcorr'): 1,
  ('птичка', 'pcorr'): 1,
  ('зуб', 'pcorr'): 1,
  ('черт', 'pcorr'): 1,
  ('парень', 'corr'): 1,
  ('всадник', 'incorr'): 1,
  ('птица', 'pcorr'): 1,
  ('воробей', 'pcorr'): 1,
  ('дьячок', 'pcorr'): 1,
  ('араб', 'incorr'): 1},
 (127, 'командир', 'командир'): {('командир', 'corr'): 31,
  ('nan', 'incorr'): 5,
  ('эль-командир', 'corr'): 1,
  ('серега', 'incorr'): 1,
  ('командир юля', 'corr'): 1,
  ('командующий', 'pcorr'): 1},
 (128, 'выхватил', 'извукао'): {('вытащил', 'corr'): 7,
  ('достал', 'corr'): 7,
  ('извлек', 'corr'): 6,
  ('nan', 'incorr'): 6,
  ('вынул', 'corr'): 5,
  ('извлёк', 'corr'): 4,
  ('выхватил', 'corr'): 2,
  ('и вытащил', 'corr'): 1,
  ('извелк', 'corr'): 1,
  ('вытащил меч', 'corr'): 1},
 (129, 'взмокшая', 'ознојени'): {('nan', 'incorr'): 22,
  ('потная', 'corr'): 2,
  ('уставшая', 'pcorr'): 2,
  ('взмокшая', 'corr'): 1,
  ('озорная', 'pcorr'): 1,
  ('ознойная', 'incorr'): 1,
  ('босая', 'incorr'): 1,
  ('и черная', 'pcorr'): 1,
  ('сердитая', 'pcorr'): 1,
  ('сивая', 'pcorr'): 1,
  ('загнанная', 'pcorr'): 1,
  ('эта', 'incorr'): 1,
  ('мокрая', 'corr'): 1,
  ('бешеная', 'pcorr'): 1,
  ('масти', 'incorr'): 1,
  ('замерзшая', 'pcorr'): 1,
  ('тронула', 'incorr'): 1},
 (130, 'шарахнулась', 'тргнуо'): {('nan', 'incorr'): 17,
  ('дернулась', 'corr'): 5,
  ('тронулась', 'pcorr'): 3,
  ('вздрогнула', 'pcorr'): 2,
  ('дёрнулась', 'corr'): 2,
  ('шарахнулась и', 'corr'): 1,
  ('ржанула', 'pcorr'): 1,
  ('тронувшись', 'pcorr'): 1,
  ('обозлившись', 'incorr'): 1,
  ('примчалась', 'pcorr'): 1,
  ('закричала', 'incorr'): 1,
  ('тронула', 'pcorr'): 1,
  ('заржала', 'pcorr'): 1,
  ('дрогнула', 'pcorr'): 1,
  ('взвизгнула', 'incorr'): 1,
  ('которая', 'incorr'): 1},
 (131, 'командир', 'командир'): {('командир', 'corr'): 29,
  ('nan', 'incorr'): 5,
  ('командар', 'corr'): 1,
  ('помахав', 'incorr'): 1,
  ('рн', 'incorr'): 1,
  ('солдат', 'pcorr'): 1,
  ('он', 'incorr'): 1,
  ('командующий', 'pcorr'): 1},
 (132, 'шее', 'врату'): {('шее', 'corr'): 12,
  ('nan', 'incorr'): 8,
  ('крупу', 'pcorr'): 5,
  ('боку', 'pcorr'): 4,
  ('жопе', 'pcorr'): 2,
  ('бокам', 'pcorr'): 2,
  ('морде', 'pcorr'): 1,
  ('телу', 'pcorr'): 1,
  ('бедру', 'pcorr'): 1,
  ('воротам', 'incorr'): 1,
  ('черепу', 'pcorr'): 1,
  ('голове', 'pcorr'): 1,
  ('спине', 'pcorr'): 1},
 (133, 'полетели', 'пролетели'): {('пролетели', 'corr'): 12,
  ('конные', 'incorr'): 9,
  ('nan', 'incorr'): 4,
  ('проскакали', 'corr'): 3,
  ('полетели', 'corr'): 1,
  ('летели', 'corr'): 1,
  ('поскакали', 'corr'): 1,
  ('пошли', 'pcorr'): 1,
  ('шли', 'pcorr'): 1,
  ('смелые', 'incorr'): 1,
  ('гнались', 'pcorr'): 1,
  ('конница', 'incorr'): 1,
  ('пронеслись', 'corr'): 1,
  ('пролетли', 'corr'): 1,
  ('пробежали', 'pcorr'): 1,
  ('скакали', 'corr'): 1},
 (134, 'туче', 'облаку'): {('облаке', 'corr'): 27,
  ('nan', 'incorr'): 5,
  ('облако', 'corr'): 2,
  ('туче', 'corr'): 1,
  ('облачной', 'incorr'): 1,
  ('вязкой', 'incorr'): 1,
  ('дорожной', 'pcorr'): 1,
  ('клубах', 'corr'): 1,
  ('облаках', 'corr'): 1},
 (135, 'пик', 'копаља'): {('копий', 'corr'): 15,
  ('палок', 'pcorr'): 6,
  ('nan', 'incorr'): 6,
  ('пик', 'corr'): 2,
  ('копей', 'corr'): 2,
  ('копьев', 'corr'): 1,
  ('лопат', 'incorr'): 1,
  ('труб', 'pcorr'): 1,
  ('палочек', 'incorr'): 1,
  ('кистей?', 'incorr'): 1,
  ('одеждах', 'incorr'): 1,
  ('листьев', 'pcorr'): 1,
  ('стручков', 'incorr'): 1,
  ('опал', 'incorr'): 1},
 (136, 'весело', 'весело'): {('весело', 'corr'): 21,
  ('nan', 'incorr'): 6,
  ('белыми', 'pcorr'): 4,
  ('искаженными', 'pcorr'): 3,
  ('веселыми', 'corr'): 2,
  ('радостно', 'corr'): 1,
  ('злыми', 'pcorr'): 1,
  ('улыбками', 'incorr'): 1,
  ('покоробленными', 'pcorr'): 1},
 (137, 'сверкающими', 'блиставим'): {('блестящими', 'corr'): 17,
  ('сверкающими', 'corr'): 7,
  ('nan', 'incorr'): 5,
  ('белыми', 'pcorr'): 4,
  ('блестевшими', 'corr'): 2,
  ('блиставшими', 'corr'): 2,
  ('блистящими', 'corr'): 1,
  ('блестяшими', 'corr'): 1,
  ('ослепительными', 'corr'): 1},
 (138, 'солдат', 'војник'): {('воин', 'corr'): 10,
  ('солдат', 'corr'): 8,
  ('всадник', 'corr'): 7,
  ('nan', 'incorr'): 5,
  ('возница', 'pcorr'): 1,
  ('последний солдат', 'corr'): 1,
  ('сильно', 'incorr'): 1,
  ('солдата', 'corr'): 1,
  ('повозчик', 'pcorr'): 1,
  ('последним', 'incorr'): 1,
  ('всадние', 'corr'): 1,
  ('военачальник', 'pcorr'): 1,
  ('страж', 'corr'): 1,
  ('последний наездник', 'corr'): 1},
 (139, 'трубою', 'трубом'): {('трубой', 'corr'): 19,
  ('nan', 'incorr'): 10,
  ('шпагой', 'pcorr'): 2,
  ('трубою', 'corr'): 1,
  ('торбой', 'incorr'): 1,
  ('кожей', 'pcorr'): 1,
  ('желтой', 'incorr'): 1,
  ('булавой', 'pcorr'): 1,
  ('трупе', 'incorr'): 1,
  ('толпой', 'pcorr'): 1,
  ('саблей', 'pcorr'): 1,
  ('рогой', 'incorr'): 1},
 (140, 'морща', 'мрштећи'): {('морща', 'corr'): 12,
  ('nan', 'incorr'): 7,
  ('хмуря', 'corr'): 4,
  ('морщась', 'corr'): 2,
  ('намхмурив', 'corr'): 1,
  ('кривя', 'corr'): 1,
  ('хмурясь', 'corr'): 1,
  ('моршив', 'corr'): 1,
  ('сморщив', 'corr'): 1,
  ('отряхивая', 'pcorr'): 1,
  ('щуря', 'pcorr'): 1,
  ('сморщивая', 'corr'): 1,
  ('с', 'incorr'): 1,
  ('скривив', 'corr'): 1,
  ('морщивший', 'corr'): 1,
  ('нахмуривший', 'pcorr'): 1,
  ('нахмурив', 'pcorr'): 1,
  ('закрывая', 'pcorr'): 1,
  ('пряча', 'pcorr'): 1},
 (141, 'двинулся', 'кренуо'): {('двинулся', 'corr'): 9,
  ('nan', 'incorr'): 7,
  ('пошел', 'corr'): 6,
  ('двигался', 'corr'): 5,
  ('повернулся', 'pcorr'): 2,
  ('поскакал', 'pcorr'): 2,
  ('пошёл', 'corr'): 2,
  ('поехал', 'pcorr'): 1,
  ('перекатывался', 'incorr'): 1,
  ('прошел', 'corr'): 1,
  ('повернул', 'pcorr'): 1,
  ('наклонился', 'incorr'): 1,
  ('ринулся', 'pcorr'): 1,
  ('направился', 'corr'): 1},
 (142, 'двинулся', 'дошли'): {('шли', 'corr'): 11,
  ('пошли', 'corr'): 8,
  ('nan', 'incorr'): 5,
  ('шел', 'corr'): 3,
  ('пришли', 'corr'): 2,
  ('двинулся', 'corr'): 1,
  ('следовали', 'corr'): 1,
  ('дошли', 'pcorr'): 1,
  ('вышел', 'pcorr'): 1,
  ('двинулись', 'corr'): 1,
  ('плелись', 'corr'): 1,
  ('шагали', 'corr'): 1,
  ('последовали', 'corr'): 1,
  ('прошли', 'corr'): 1,
  ('пешком шли', 'corr'): 1,
  ('последовал', 'corr'): 1},
 (20, 'пустому', 'празним'): {('пустому', 'corr'): 12,
  ('nan', 'incorr'): 7,
  ('парадному', 'pcorr'): 2,
  ('празному', 'incorr'): 2,
  ('праздничному', 'incorr'): 2,
  ('просторному', 'pcorr'): 2,
  ('коридору', 'pcorr'): 1,
  ('спокойному', 'pcorr'): 1,
  ('сухому', 'pcorr'): 1,
  ('обычному', 'pcorr'): 1,
  ('темному', 'pcorr'): 1,
  ('короткому', 'pcorr'): 1,
  ('длинному', 'pcorr'): 1,
  ('праздному', 'incorr'): 1,
  ('узкому', 'pcorr'): 1,
  ('другому', 'pcorr'): 1,
  ('праздниму', 'incorr'): 1,
  ('тихому', 'pcorr'): 1},
 (21, 'коридору', 'ходником'): {('коридору', 'corr'): 18,
  ('nan', 'incorr'): 5,
  ('переходу', 'pcorr'): 2,
  ('пути', 'pcorr'): 2,
  ('проходу', 'pcorr'): 2,
  ('корридору', 'corr'): 2,
  ('тихому', 'incorr'): 1,
  ('проулку', 'pcorr'): 1,
  ('полу', 'pcorr'): 1,
  ('ходнику', 'incorr'): 1,
  ('холодку', 'incorr'): 1,
  ('переулку', 'pcorr'): 1,
  ('месту', 'pcorr'): 1,
  ('холлу', 'corr'): 1},
 (22, 'здании', 'згради'): {('nan', 'incorr'): 10,
  ('кабинете', 'pcorr'): 7,
  ('доме', 'corr'): 4,
  ('здании', 'corr'): 3,
  ('столе', 'incorr'): 3,
  ('помещении', 'pcorr'): 2,
  ('кабинету', 'pcorr'): 1,
  ('устройстве', 'pcorr'): 1,
  ('зале', 'pcorr'): 1,
  ('строение', 'corr'): 1,
  ('здании. иван сам', 'corr'): 1,
  ('месте', 'pcorr'): 1,
  ('кухне', 'pcorr'): 1,
  ('сооружении', 'corr'): 1,
  ('громаде', 'corr'): 1,
  ('складе', 'pcorr'): 1},
 (23, 'стеклянные', 'стаклене'): {('стеклянные', 'corr'): 23,
  ('nan', 'incorr'): 4,
  ('витрины', 'incorr'): 2,
  ('застекленные', 'corr'): 2,
  ('застеклённые', 'corr'): 2,
  ('комоды', 'incorr'): 1,
  ('стеклянные ветрины', 'corr'): 1,
  ('маленькие', 'pcorr'): 1,
  ('стеклянные витрины', 'corr'): 1,
  ('небольшие', 'pcorr'): 1,
  ('стекляные', 'corr'): 1},
 (24, 'инструментами', 'инструментима'): {('инструментами', 'corr'): 24,
  ('nan', 'incorr'): 8,
  ('ручками', 'pcorr'): 4,
  ('узорами', 'pcorr'): 1,
  ('ложками', 'pcorr'): 1,
  ('приборами', 'pcorr'): 1},
 (25, 'кресла', 'фотеље'): {('nan', 'incorr'): 10,
  ('кресла', 'corr'): 6,
  ('предметы', 'pcorr'): 3,
  ('части', 'pcorr'): 2,
  ('устройства', 'pcorr'): 2,
  ('конструкции', 'pcorr'): 2,
  ('детали', 'pcorr'): 1,
  ('фотографии', 'incorr'): 1,
  ('в фотоателье', 'incorr'): 1,
  ('обородованы', 'incorr'): 1,
  ('фитиля', 'pcorr'): 1,
  ('фонари', 'pcorr'): 1,
  ('там', 'incorr'): 1,
  ('они', 'incorr'): 1,
  ('в этом ателье', 'incorr'): 1,
  ('встроены в кресла', 'corr'): 1,
  ('здесь', 'incorr'): 1,
  ('приборы', 'pcorr'): 1,
  ('фото', 'incorr'): 1,
  ('отелье', 'incorr'): 1},
 (26, 'колпаками', 'абажурима'): {('абажурами', 'corr'): 27,
  ('nan', 'incorr'): 6,
  ('блёстками', 'pcorr'): 1,
  ('спиралями', 'pcorr'): 1,
  ('абаружами', 'corr'): 1,
  ('абожуром', 'corr'): 1,
  ('колпаками', 'corr'): 1,
  ('абажуром', 'corr'): 1},
 (27, 'провода', 'жице'): {('nan', 'incorr'): 12,
  ('провода', 'corr'): 9,
  ('лампы', 'pcorr'): 3,
  ('плиты', 'pcorr'): 3,
  ('горелки', 'pcorr'): 2,
  ('зажигалки', 'incorr'): 2,
  ('микроскопы', 'pcorr'): 1,
  ('щипцы', 'pcorr'): 1,
  ('катушки', 'pcorr'): 1,
  ('жице', 'incorr'): 1,
  ('устройства', 'pcorr'): 1,
  ('иглы', 'pcorr'): 1,
  ('лампочки', 'pcorr'): 1,
  ('джинсы', 'incorr'): 1},
 (28, 'принялись', 'позабавило'): {('nan', 'incorr'): 10,
  ('взялись', 'corr'): 7,
  ('было', 'incorr'): 3,
  ('наблюдали', 'pcorr'): 2,
  ('стояли', 'pcorr'): 2,
  ('встречали', 'pcorr'): 1,

In [20]:
def morph_comparer(set_ru, set_cg, orpho):
    
    def compare_morphemes(ru_list, cg_list, morpheme_type):

        scores = []
        pairs = []

        if not ru_list and not cg_list:
            return {'scores': scores, 'pairs': pairs}

        if not ru_list:
            cg_combined = ''.join(cg_list)
            scores.append(fast_Levenstein('', cg_combined))
            pairs.append(('', cg_combined))
            return {'scores': scores, 'pairs': pairs}

        if not cg_list:
            ru_combined = ''.join(ru_list)
            scores.append(fast_Levenstein(ru_combined, ''))
            pairs.append((ru_combined, ''))
            return {'scores': scores, 'pairs': pairs}

        if len(ru_list) == len(cg_list):
            for ru_elem, cg_elem in zip(ru_list, cg_list):
                scores.append(fast_Levenstein(ru_elem, cg_elem))
                pairs.append((ru_elem, cg_elem))
            return {'scores': scores, 'pairs': pairs}

        if morpheme_type in ['SUFF', 'PREF']:
            return {'scores': ['HANDCHECK'], 'pairs': [ru_list, cg_list]}

    result = {}

    ru_dict = ast.literal_eval(set_ru)
    cg_dict = ast.literal_eval(set_cg)

    if orpho == 'latin':
        if isinstance(cg_dict, dict):
            for key in cg_dict:
                cg_dict[key] = [transliterate(el, 'l') for el in cg_dict[key]]

    morpheme_types = ['PREF', 'ROOT', 'LINK', 'SUFF', 'END', 'POSTFIX']
    not_link = 0

    for morpheme_type in morpheme_types:

        ru_list = []
        cg_list = []

        if isinstance(ru_dict, dict) and isinstance(cg_dict, dict):
            ru_list = ru_dict.get(morpheme_type, [])
            cg_list = cg_dict.get(morpheme_type, [])

        if not ru_list and not cg_list:
            continue

        if morpheme_type == 'ROOT' and len(ru_list) > len(cg_list) and len(cg_list) != 0:
            not_link = 1
            if 'LINK' in ru_dict.keys():
                ru_root = ru_list[0] + ru_dict['LINK'][0] + ru_list[1]
            else:
                ru_root = ru_list[0] + ru_list[1]
            result[morpheme_type] = {'scores': [fast_Levenstein(ru_root, cg_list[0])], 'pairs': [(ru_root, cg_list[0])]}
            continue

        if morpheme_type == 'ROOT' and len(cg_list) > len(ru_list) and len(ru_list) != 0:
            not_link = 1
            if 'LINK' in cg_dict.keys():
                cg_root = cg_list[0] + cg_dict['LINK'][0] + cg_list[1]
            else:
                cg_root = cg_list[0] + cg_list[1]
            result[morpheme_type] = {'scores': [fast_Levenstein(ru_list[0], cg_root)], 'pairs': [(ru_list[0], cg_root)]}
            continue

        if not not_link:
            result[morpheme_type] = compare_morphemes(ru_list, cg_list, morpheme_type)

    return result

In [21]:
def cognate_stats(answer_set, russian_true, language, language_dict, orpho, num_type):
    true_cognates = {}
    part_cognates = {}
    for _, row in answer_set.iterrows():
        test_id = row['test_id']
        answer_no = row['answer_no']
        user_answer = str(row['answer']).lower().strip()
        correctness = row['correctness']
        code_ans = (user_answer, correctness)
        morphs_ans = row['morphemic_parse']

        correct_row = russian_true[
            (russian_true['test_id'] == test_id) &
            (russian_true['answer_no'] == answer_no)
            ]
        original_row = language[
            (language['test_id'] == test_id) &
            (language['answer_no'] == answer_no)
            ]

        if not correct_row.empty:
            correct_answer = str(correct_row.iloc[0]['answer']).strip()
            original_answer = str(original_row.iloc[0]['answer']).strip()
            correct_morph = str(correct_row.iloc[0]['morphemic_parse']).strip()
            original_morph = str(original_row.iloc[0]['morphemic_parse']).strip()
            code = (int(f'{test_id}{answer_no}'), correct_answer, original_answer)
            if float(original_row.iloc[0]['cognate']) != 0:
                if float(original_row.iloc[0]['cognate']) == 1:
                    if code not in true_cognates.keys():
                        true_cognates[code] = {}
                        true_cognates[code]['morph_comparison'] = morph_comparer(correct_morph, original_morph, orpho)
                        true_cognates[code]['overall_stats'] = {}
                        true_cognates[code]['word_stats'] = {}

                elif code not in part_cognates.keys():
                    part_cognates[code] = {}
                    part_cognates[code]['morph_comparison'] = morph_comparer(correct_morph, original_morph, orpho)
                    part_cognates[code]['overall_stats'] = {}
                    part_cognates[code]['word_stats'] = {}

        num_ans = 0
        for key in language_dict[code]:
            num_ans += language_dict[code][key]

        if float(original_row.iloc[0]['cognate']) == 1:
            if correctness not in true_cognates[code]['overall_stats'].keys():
                counter = 0
                for key in language_dict[code]:
                    if key[1] == correctness:
                        counter += language_dict[code][key]
                true_cognates[code]['overall_stats'][correctness] = counter / num_ans
                if correctness == 'incorr':
                    mistakes_control = num_type[code[0]]['mistakes']
                    if mistakes_control != 0:
                        explained_mistakes = (mistakes_control - true_cognates[code]['overall_stats'][
                            correctness]) / mistakes_control
                    else:
                        explained_mistakes = 0 - true_cognates[code]['overall_stats'][correctness]
                    true_cognates[code]['overall_stats']['explained_mistakes'] = explained_mistakes

            if code_ans not in true_cognates[code]['word_stats'].keys():
                true_cognates[code]['word_stats'][code_ans] = (
                morph_comparer(morphs_ans, original_morph, orpho), language_dict[code][code_ans] / num_ans)

        elif float(original_row.iloc[0]['cognate']) == 0.5:
            if correctness not in part_cognates[code]['overall_stats'].keys():
                counter = 0
                for key in language_dict[code]:
                    if key[1] == correctness:
                        counter += language_dict[code][key]
                part_cognates[code]['overall_stats'][correctness] = counter / num_ans
                if correctness == 'incorr':
                    mistakes_control = num_type[code[0]]['mistakes']
                    if mistakes_control != 0:
                        explained_mistakes = (mistakes_control - part_cognates[code]['overall_stats'][
                            correctness]) / mistakes_control
                    else:
                        explained_mistakes = 0 - part_cognates[code]['overall_stats'][correctness]
                    part_cognates[code]['overall_stats']['explained_mistakes'] = explained_mistakes
            if code_ans not in part_cognates[code]['word_stats'].keys():
                part_cognates[code]['word_stats'][code_ans] = (
                morph_comparer(morphs_ans, original_morph, orpho), language_dict[code][code_ans] / num_ans)

    for key in true_cognates:
        for el in true_cognates[key]:
            if el == 'overall_stats':
                true_cognates[key][el] = dict(
                    sorted(true_cognates[key][el].items(), key=lambda item: item[1], reverse=True))
            elif el == 'word_stats':
                true_cognates[key][el] = dict(
                    sorted(true_cognates[key][el].items(), key=lambda item: item[1][1], reverse=True))

    for key in part_cognates:
        for el in part_cognates[key]:
            if el == 'overall_stats':
                part_cognates[key][el] = dict(
                    sorted(part_cognates[key][el].items(), key=lambda item: item[1], reverse=True))
            elif el == 'word_stats':
                part_cognates[key][el] = dict(
                    sorted(part_cognates[key][el].items(), key=lambda item: item[1][1], reverse=True))

    return true_cognates, part_cognates

In [22]:
ukr_stats = cognate_stats(ukrainian_ans, russian_true, ukrainian_true, ukr_cognates, 'cyr', num_type)
ukr_stats

({(10,
   'повернулся',
   'повернувся'): {'morph_comparison': {'PREF': {'scores': [0.0],
     'pairs': [('по', 'по')]},
    'ROOT': {'scores': [0.0], 'pairs': [('вер', 'вер')]},
    'SUFF': {'scores': [0.0, 0.0, 1.0],
     'pairs': [('н', 'н'), ('у', 'у'), ('л', 'в')]},
    'POSTFIX': {'scores': [0.0],
     'pairs': [('ся', 'ся')]}}, 'overall_stats': {'corr': 0.9473684210526315,
    'pcorr': 0.05263157894736842}, 'word_stats': {('повернулся',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('по', 'по')]},
      'ROOT': {'scores': [0.0], 'pairs': [('вер', 'вер')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['ну', 'л'], ['н', 'у', 'в']]},
      'POSTFIX': {'scores': [0.0], 'pairs': [('ся', 'ся')]}},
     0.9210526315789473),
    ('развернулся',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('раз', 'по')]},
      'ROOT': {'scores': [0.0], 'pairs': [('вер', 'вер')]},
      'SUFF': {'scores': [0.0, 0.0, 1.0],
       'pairs': [('н', 'н'), ('у', 'у'), ('л', 'в')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.02631578947368421),
    ('вернулся',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'по')]},
      'ROOT': {'scores': [0.0], 'pairs': [('вер', 'вер')]},
      'SUFF': {'scores': [0.0, 0.0, 1.0],
       'pairs': [('н', 'н'), ('у', 'у'), ('л', 'в')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.02631578947368421),
    ('пошёл',
     'pcorr'): ({'PREF': {'scores': [0.0], 'pairs': [('по', 'по')]},
      'ROOT': {'scores': [2.2], 'pairs': [('шё', 'вер')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['л'], ['н', 'у', 'в']]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'ся')]}}, 0.02631578947368421)}},
  (12,
   'шашек',
   'шашок'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('шаш', 'шаш')]},
    'SUFF': {'scores': [1.0],
     'pairs': [('ек', 'ок')]}}, 'overall_stats': {'corr': 0.6052631578947368,
    'incorr': 0.21052631578947367,
    'pcorr': 0.18421052631578946,
    'explained_mistakes': -2.0877192982456143}, 'word_stats': {('шашек',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('шаш', 'шаш')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ек', 'ок')]}},
     0.3684210526315789),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ок')]}}, 0.18421052631578946),
    ('досок',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('досок', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ок')]}}, 0.13157894736842105),
    ('плиток',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('плит', 'шаш')]},
      'SUFF': {'scores': [0.0],
       'pairs': [('ок', 'ок')]}}, 0.13157894736842105),
    ('шашок',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('шаш', 'шаш')]},
      'SUFF': {'scores': [0.0],
       'pairs': [('ок', 'ок')]}}, 0.05263157894736842),
    ('цветов',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('цвет', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ок')]},
      'END': {'scores': [2.0], 'pairs': [('ов', '')]}}, 0.02631578947368421),
    ('плит',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('плит', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ок')]}}, 0.02631578947368421),
    ('каамней',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('каам', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('н', 'ок')]},
      'END': {'scores': [2.0], 'pairs': [('ей', '')]}}, 0.02631578947368421),
    ('шапок',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('шапок', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ок')]}}, 0.02631578947368421),
    ('узоров',
     'corr'): ({'ROOT': {'scores': [3.6], 'pairs': [('узор', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ок')]},
      'END': {'scores': [2.0], 'pairs': [('ов', '')]}}, 0.02631578947368421)}},
  (13,
   'спиною',
   'спиною'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('спин', 'спин')]},
    'END': {'scores': [0.0],
     'pairs': [('ою',
       'ою')]}}, 'overall_stats': {'corr': 1.0}, 'word_stats': {('спиной',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('спин', 'спин')]},
      'END': {'scores': [1.0], 'pairs': [('ой', 'ою')]}},
     0.7894736842105263),
    ('спиною',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('спин', 'спин')]},
      'END': {'scores': [0.0],
       'pairs': [('ою', 'ою')]}}, 0.21052631578947367)}},
  (14,
   'финики',
   'фініки'): {'morph_comparison': {'ROOT': {'scores': [0.4],
     'pairs': [('финик', 'фінік')]},
    'END': {'scores': [0.0],
     'pairs': [('и', 'и')]}}, 'overall_stats': {'corr': 0.8421052631578947,
    'explained_mistakes': 0.7482837528604119,
    'incorr': 0.13157894736842105,
    'pcorr': 0.02631578947368421}, 'word_stats': {('финики',
     'corr'): ({'ROOT': {'scores': [0.4], 'pairs': [('финик', 'фінік')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]}}, 0.8157894736842105),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'фінік')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.07894736842105263),
    ('финикийцы',
     'incorr'): ({'ROOT': {'scores': [1.4], 'pairs': [('финики', 'фінік')]},
      'SUFF': {'scores': [2.0], 'pairs': [('йц', '')]},
      'END': {'scores': [1.0], 'pairs': [('ы', 'и')]}}, 0.02631578947368421),
    ('камни',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('камн', 'фінік')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]}}, 0.02631578947368421),
    ('финик',
     'corr'): ({'ROOT': {'scores': [0.4], 'pairs': [('финик', 'фінік')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02631578947368421),
    ('думая',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('дум', 'фінік')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ая', '')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02631578947368421)}},
  (16,
   'вырвался',
   'вирвався'): {'morph_comparison': {'PREF': {'scores': [1.0],
     'pairs': [('вы', 'ви')]},
    'ROOT': {'scores': [0.0], 'pairs': [('рв', 'рв')]},
    'SUFF': {'scores': [0.0, 1.0], 'pairs': [('а', 'а'), ('л', 'в')]},
    'POSTFIX': {'scores': [0.0],
     'pairs': [('ся', 'ся')]}}, 'overall_stats': {'corr': 0.8947368421052632,
    'explained_mistakes': 0.768421052631579,
    'pcorr': 0.07894736842105263,
    'incorr': 0.02631578947368421}, 'word_stats': {('вырвался',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('вы', 'ви')]},
      'ROOT': {'scores': [0.0], 'pairs': [('рв', 'рв')]},
      'SUFF': {'scores': [0.0, 1.0], 'pairs': [('а', 'а'), ('л', 'в')]},
      'POSTFIX': {'scores': [0.0], 'pairs': [('ся', 'ся')]}},
     0.868421052631579),
    ('выбрался',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('вы', 'ви')]},
      'ROOT': {'scores': [2.0], 'pairs': [('бр', 'рв')]},
      'SUFF': {'scores': [0.0, 1.0], 'pairs': [('а', 'а'), ('л', 'в')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.05263157894736842),
    ('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'ви')]},
      'ROOT': {'scores': [2.0], 'pairs': [('', 'рв')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ав')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'ся')]}}, 0.02631578947368421),
    ('вырываясь',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('вы', 'ви')]},
      'ROOT': {'scores': [1.0], 'pairs': [('рыв', 'рв')]},
      'SUFF': {'scores': [0.0, 1.0], 'pairs': [('а', 'а'), ('я', 'в')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('сь', 'ся')]}}, 0.02631578947368421),
    ('вырывается',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('вы', 'ви')]},
      'ROOT': {'scores': [1.0], 'pairs': [('рыв', 'рв')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а'], ['а', 'в']]},
      'END': {'scores': [2.0], 'pairs': [('ет', '')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.02631578947368421)}},
  (110,
   'знал',
   'знав'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('зна', 'зна')]},
    'SUFF': {'scores': [1.0],
     'pairs': [('л', 'в')]}}, 'overall_stats': {'corr': 0.9210526315789473,
    'pcorr': 0.07894736842105263}, 'word_stats': {('знал',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('зна', 'зна')]},
      'SUFF': {'scores': [1.0], 'pairs': [('л', 'в')]}}, 0.9210526315789473),
    ('зная',
     'pcorr'): ({'ROOT': {'scores': [0.0], 'pairs': [('зна', 'зна')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'в')]},
      'END': {'scores': [1.0], 'pairs': [('я', '')]}}, 0.05263157894736842),
    ('узнав',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('у', '')]},
      'ROOT': {'scores': [0.0], 'pairs': [('зна', 'зна')]},
      'SUFF': {'scores': [0.0],
       'pairs': [('в', 'в')]}}, 0.02631578947368421)}},
  (112,
   'дорогу',
   'дорогу'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('дорог', 'дорог')]},
    'END': {'scores': [0.0],
     'pairs': [('у', 'у')]}}, 'overall_stats': {'corr': 0.9473684210526315,
    'explained_mistakes': 0.22807017543859648,
    'incorr': 0.05263157894736842}, 'word_stats': {('дорогу',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('дорог', 'дорог')]},
      'END': {'scores': [0.0], 'pairs': [('у', 'у')]}}, 0.9473684210526315),
    ('заход',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('за', '')]},
      'ROOT': {'scores': [4.0], 'pairs': [('ход', 'дорог')]},
      'END': {'scores': [1.0], 'pairs': [('', 'у')]}}, 0.02631578947368421),
    ('мероприятие',
     'incorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('мероприя', 'дорог')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ти', '')]},
      'END': {'scores': [1.0], 'pairs': [('е', 'у')]}}, 0.02631578947368421)}},
  (113,
   'осужденных',
   'засуджених'): {'morph_comparison': {'PREF': {'scores': [2.0],
     'pairs': [('о', 'за')]},
    'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'судж')]},
    'SUFF': {'scores': [1.0], 'pairs': [('енн', 'ен')]},
    'END': {'scores': [1.0],
     'pairs': [('ых', 'их')]}}, 'overall_stats': {'corr': 0.7105263157894737,
    'explained_mistakes': 0.5913312693498453,
    'incorr': 0.15789473684210525,
    'pcorr': 0.13157894736842105}, 'word_stats': {('осужденных',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('о', 'за')]},
      'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'судж')]},
      'SUFF': {'scores': [1.0], 'pairs': [('енн', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('ых', 'их')]}},
     0.3684210526315789),
    ('осуждённых',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('о', 'за')]},
      'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'судж')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ён', 'н'], ['ен']]},
      'END': {'scores': [1.0], 'pairs': [('ых', 'их')]}}, 0.13157894736842105),
    ('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'за')]},
      'ROOT': {'scores': [4.0], 'pairs': [('', 'судж')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [2.0], 'pairs': [('', 'их')]}}, 0.10526315789473684),
    ('видеть',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'за')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вид', 'судж')]},
      'SUFF': {'scores': [1.0], 'pairs': [('е', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('ть', 'их')]}}, 0.05263157894736842),
    ('преследователей',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'за')]},
      'ROOT': {'scores': [6.0], 'pairs': [('преслед', 'судж')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ова', 'тел'], ['ен']]},
      'END': {'scores': [1.6], 'pairs': [('ей', 'их')]}}, 0.05263157894736842),
    ('видеть осужденных', 'corr'): ({}, 0.05263157894736842),
    ('подсудимых',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('под', 'за')]},
      'ROOT': {'scores': [1.0], 'pairs': [('суд', 'судж')]},
      'SUFF': {'scores': [1.6], 'pairs': [('им', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('ых', 'их')]}}, 0.02631578947368421),
    ('казни осужденных', 'pcorr'): ({}, 0.02631578947368421),
    ('засуженных',
     'pcorr'): ({'PREF': {'scores': [0.0], 'pairs': [('за', 'за')]},
      'ROOT': {'scores': [1.0], 'pairs': [('суж', 'судж')]},
      'SUFF': {'scores': [1.0], 'pairs': [('енн', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('ых', 'их')]}}, 0.02631578947368421),
    ('казни',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'за')]},
      'ROOT': {'scores': [4.0], 'pairs': [('казн', 'судж')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('и', 'их')]}}, 0.02631578947368421),
    ('других осужденных', 'corr'): ({}, 0.02631578947368421),
    ('значит осужденных', 'corr'): ({}, 0.02631578947368421),
    ('осужденный',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('о', 'за')]},
      'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'судж')]},
      'SUFF': {'scores': [1.0], 'pairs': [('енн', 'ен')]},
      'END': {'scores': [2.0], 'pairs': [('ый', 'их')]}}, 0.02631578947368421),
    ('байни осужденных', 'corr'): ({}, 0.02631578947368421),
    ('виновных',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'за')]},
      'ROOT': {'scores': [4.0], 'pairs': [('вин', 'судж')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ов', 'н', 'ы'], ['ен']]},
      'END': {'scores': [1.0],
       'pairs': [('х', 'их')]}}, 0.02631578947368421)}},
  (114,
   'глашатаев',
   'глашатаїв'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('глаш', 'глаш')]},
    'SUFF': {'scores': [0.0, 0.0], 'pairs': [('ат', 'ат'), ('а', 'а')]},
    'END': {'scores': [1.0],
     'pairs': [('ев', 'їв')]}}, 'overall_stats': {'corr': 0.9473684210526315,
    'explained_mistakes': 0.8345864661654135,
    'incorr': 0.02631578947368421,
    'pcorr': 0.02631578947368421}, 'word_stats': {('глашатаев',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('глаш', 'глаш')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('ат', 'ат'), ('а', 'а')]},
      'END': {'scores': [1.0], 'pairs': [('ев', 'їв')]}},
     0.7368421052631579),
    ('глашатых',
     'corr'): ({'ROOT': {'scores': [2.0], 'pairs': [('глашат', 'глаш')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'ата')]},
      'END': {'scores': [2.0], 'pairs': [('ых', 'їв')]}}, 0.13157894736842105),
    ('глашатая',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('глаш', 'глаш')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ат'], ['ат', 'а']]},
      'END': {'scores': [2.0], 'pairs': [('ая', 'їв')]}}, 0.05263157894736842),
    ('вренных',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('врен', 'глаш')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н'], ['ат', 'а']]},
      'END': {'scores': [2.0], 'pairs': [('ых', 'їв')]}}, 0.02631578947368421),
    ('хулиганов',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('хулиган', 'глаш')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'ата')]},
      'END': {'scores': [1.0], 'pairs': [('ов', 'їв')]}}, 0.02631578947368421),
    ('глашатаи',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('глаш', 'глаш')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('ат', 'ат'), ('а', 'а')]},
      'END': {'scores': [1.2],
       'pairs': [('и', 'їв')]}}, 0.02631578947368421)}},
  (115,
   'греческом',
   'грецькою'): {'morph_comparison': {'ROOT': {'scores': [0.6],
     'pairs': [('греч', 'грець')]},
    'SUFF': {'scores': [2.0], 'pairs': [('еск', 'к')]},
    'END': {'scores': [1.0],
     'pairs': [('ом', 'ою')]}}, 'overall_stats': {'corr': 0.9210526315789473,
    'explained_mistakes': 0.8345864661654135,
    'pcorr': 0.05263157894736842,
    'incorr': 0.02631578947368421}, 'word_stats': {('греческом',
     'corr'): ({'ROOT': {'scores': [0.6], 'pairs': [('греч', 'грець')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('ом', 'ою')]}},
     0.7368421052631579),
    ('греческих',
     'corr'): ({'ROOT': {'scores': [0.6], 'pairs': [('греч', 'грець')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'к')]},
      'END': {'scores': [2.0], 'pairs': [('их', 'ою')]}}, 0.13157894736842105),
    ('грецком',
     'pcorr'): ({'ROOT': {'scores': [0.0], 'pairs': [('грец', 'грець')]},
      'SUFF': {'scores': [0.0], 'pairs': [('к', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('ом', 'ою')]}}, 0.05263157894736842),
    ('грецском',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('грец', 'грець')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('ом', 'ою')]}}, 0.02631578947368421),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'грець')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ою')]}}, 0.02631578947368421),
    ('греческом наречии', 'corr'): ({}, 0.02631578947368421)}},
  (117,
   'весело',
   'весело'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('весел', 'весел')]},
    'END': {'scores': [0.0],
     'pairs': [('о', 'о')]}}, 'overall_stats': {'corr': 0.9736842105263158,
    'explained_mistakes': 0.4210526315789474,
    'incorr': 0.02631578947368421}, 'word_stats': {('весело',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('весел', 'весел')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.9473684210526315),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'весел')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.02631578947368421),
    ('радостно',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('рад', 'весел')]},
      'SUFF': {'scores': [4.0], 'pairs': [('остн', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.02631578947368421)}},
  (119,
   'солдат',
   'солдат'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('солдат',
       'солдат')]}}, 'overall_stats': {'corr': 1.0}, 'word_stats': {('солдат',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('солдат', 'солдат')]}},
     0.9736842105263158),
    ('содат',
     'corr'): ({'ROOT': {'scores': [2.6], 'pairs': [('сод', 'солдат')]},
      'SUFF': {'scores': [2.0],
       'pairs': [('ат', '')]}}, 0.02631578947368421)}},
  (120,
   'значком',
   'значком'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('знач', 'знач')]},
    'SUFF': {'scores': [0.0], 'pairs': [('к', 'к')]},
    'END': {'scores': [0.0],
     'pairs': [('ом', 'ом')]}}, 'overall_stats': {'corr': 0.9210526315789473,
    'explained_mistakes': 0.7327935222672065,
    'incorr': 0.07894736842105263}, 'word_stats': {('значком',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('знач', 'знач')]},
      'SUFF': {'scores': [0.0], 'pairs': [('к', 'к')]},
      'END': {'scores': [0.0], 'pairs': [('ом', 'ом')]}},
     0.868421052631579),
    ('знаком',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('знак', 'знач')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [0.0], 'pairs': [('ом', 'ом')]}}, 0.05263157894736842),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('', 'знач')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ом')]}}, 0.05263157894736842),
    ('майданом',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('майдан', 'знач')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [0.0],
       'pairs': [('ом', 'ом')]}}, 0.02631578947368421)}},
  (122,
   'вылетела',
   'вилетіла'): {'morph_comparison': {'PREF': {'scores': [1.0],
     'pairs': [('вы', 'ви')]},
    'ROOT': {'scores': [0.0], 'pairs': [('лет', 'лет')]},
    'SUFF': {'scores': [0.6, 0.0], 'pairs': [('е', 'і'), ('л', 'л')]},
    'END': {'scores': [0.0],
     'pairs': [('а', 'а')]}}, 'overall_stats': {'corr': 0.7631578947368421,
    'pcorr': 0.13157894736842105,

In [23]:
bel_stats = cognate_stats(belarus_ans, russian_true, belarus_true, bel_cognates, 'cyr', num_type)
bel_stats

({(10,
   'повернулся',
   'завярнуўся'): {'morph_comparison': {'PREF': {'scores': [2.0],
     'pairs': [('по', 'за')]},
    'ROOT': {'scores': [0.6], 'pairs': [('вер', 'вяр')]},
    'SUFF': {'scores': [0.0, 0.0, 1.0],
     'pairs': [('н', 'н'), ('у', 'у'), ('л', 'ў')]},
    'POSTFIX': {'scores': [0.0],
     'pairs': [('ся', 'ся')]}}, 'overall_stats': {'corr': 0.7631578947368421,
    'explained_mistakes': 0.6691729323308271,
    'pcorr': 0.18421052631578946,
    'incorr': 0.05263157894736842}, 'word_stats': {('развернулся',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('раз', 'за')]},
      'ROOT': {'scores': [0.6], 'pairs': [('вер', 'вяр')]},
      'SUFF': {'scores': [0.0, 0.0, 1.0],
       'pairs': [('н', 'н'), ('у', 'у'), ('л', 'ў')]},
      'POSTFIX': {'scores': [0.0], 'pairs': [('ся', 'ся')]}},
     0.4473684210526316),
    ('повернулся',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'за')]},
      'ROOT': {'scores': [0.6], 'pairs': [('вер', 'вяр')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['ну', 'л'], ['н', 'у', 'ў']]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.2631578947368421),
    ('обернулся',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('о', 'за')]},
      'ROOT': {'scores': [1.6], 'pairs': [('бер', 'вяр')]},
      'SUFF': {'scores': [0.0, 0.0, 1.0],
       'pairs': [('н', 'н'), ('у', 'у'), ('л', 'ў')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.07894736842105263),
    ('завернулся',
     'incorr'): ({'PREF': {'scores': [0.0], 'pairs': [('за', 'за')]},
      'ROOT': {'scores': [0.6], 'pairs': [('вер', 'вяр')]},
      'SUFF': {'scores': [0.0, 0.0, 1.0],
       'pairs': [('н', 'н'), ('у', 'у'), ('л', 'ў')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.05263157894736842),
    ('оглянулся',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('о', 'за')]},
      'ROOT': {'scores': [3.0], 'pairs': [('гля', 'вяр')]},
      'SUFF': {'scores': [0.0, 0.0, 1.0],
       'pairs': [('н', 'н'), ('у', 'у'), ('л', 'ў')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.05263157894736842),
    ('завернул',
     'pcorr'): ({'PREF': {'scores': [0.0], 'pairs': [('за', 'за')]},
      'ROOT': {'scores': [0.6], 'pairs': [('вер', 'вяр')]},
      'SUFF': {'scores': [0.0, 0.0, 1.0],
       'pairs': [('н', 'н'), ('у', 'у'), ('л', 'ў')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'ся')]}}, 0.02631578947368421),
    ('равзвернулся',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'за')]},
      'ROOT': {'scores': [4.6],
       'pairs': [('равзвер', 'вяр')]}}, 0.02631578947368421),
    ('завернулся в плащ', 'pcorr'): ({}, 0.02631578947368421),
    ('отвернулся',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('от', 'за')]},
      'ROOT': {'scores': [0.6], 'pairs': [('вер', 'вяр')]},
      'SUFF': {'scores': [0.0, 0.0, 1.0],
       'pairs': [('н', 'н'), ('у', 'у'), ('л', 'ў')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.02631578947368421)}},
  (11,
   'ступеням',
   'прыступак'): {'morph_comparison': {'PREF': {'scores': [3.0],
     'pairs': [('', 'пры')]},
    'ROOT': {'scores': [2.0], 'pairs': [('ступен', 'ступ')]},
    'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
    'END': {'scores': [2.0],
     'pairs': [('ям', '')]}}, 'overall_stats': {'pcorr': 0.5263157894736842,
    'corr': 0.34210526315789475,
    'incorr': 0.13157894736842105,
    'explained_mistakes': -0.44736842105263147}, 'word_stats': {('ступеням',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [2.0], 'pairs': [('ступен', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ям', '')]}},
     0.23684210526315788),
    ('помосту',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'пры')]},
      'ROOT': {'scores': [4.0], 'pairs': [('мост', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [1.0], 'pairs': [('у', '')]}}, 0.13157894736842105),
    ('nan',
     'incorr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [4.0], 'pairs': [('', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]}}, 0.10526315789473684),
    ('крыльцу',
     'pcorr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [4.0], 'pairs': [('крыль', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ц', 'ак')]},
      'END': {'scores': [1.0], 'pairs': [('у', '')]}}, 0.07894736842105263),
    ('преступнику',
     'pcorr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [3.0], 'pairs': [('преступ', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ник', 'ак')]},
      'END': {'scores': [1.0], 'pairs': [('у', '')]}}, 0.07894736842105263),
    ('приступку',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('при', 'пры')]},
      'ROOT': {'scores': [0.0], 'pairs': [('ступ', 'ступ')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', 'ак')]},
      'END': {'scores': [1.0], 'pairs': [('у', '')]}}, 0.05263157894736842),
    ('лестнице',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [4.0], 'pairs': [('лест', 'ступ')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ниц', 'ак')]},
      'END': {'scores': [1.0], 'pairs': [('е', '')]}}, 0.05263157894736842),
    ('пристани',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('при', 'пры')]},
      'ROOT': {'scores': [2.0], 'pairs': [('ста', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('н', 'ак')]},
      'END': {'scores': [1.0], 'pairs': [('и', '')]}}, 0.05263157894736842),
    ('тупику',
     'pcorr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [1.0], 'pairs': [('туп', 'ступ')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ик', 'ак')]},
      'END': {'scores': [1.0], 'pairs': [('у', '')]}}, 0.02631578947368421),
    ('причалу',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('при', 'пры')]},
      'ROOT': {'scores': [4.0], 'pairs': [('чал', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [1.0], 'pairs': [('у', '')]}}, 0.02631578947368421),
    ('дверям',
     'pcorr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [4.0], 'pairs': [('двер', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ям', '')]}}, 0.02631578947368421),
    ('помосту и ступеням', 'corr'): ({}, 0.02631578947368421),
    ('воротам',
     'pcorr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [4.6], 'pairs': [('ворот', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ам', '')]}}, 0.02631578947368421),
    ('ступенькам',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [0.0], 'pairs': [('ступ', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еньк', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ам', '')]}}, 0.02631578947368421),
    ('приступкам',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('при', 'пры')]},
      'ROOT': {'scores': [0.0], 'pairs': [('ступ', 'ступ')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ам', '')]}}, 0.02631578947368421),
    ('обрыву',
     'pcorr'): ({'PREF': {'scores': [3.0], 'pairs': [('об', 'пры')]},
      'ROOT': {'scores': [4.0], 'pairs': [('рыв', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [1.0], 'pairs': [('у', '')]}}, 0.02631578947368421)}},
  (12,
   'шашек',
   'шашак'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('шаш', 'шаш')]},
    'SUFF': {'scores': [1.0],
     'pairs': [('ек', 'ак')]}}, 'overall_stats': {'corr': 0.6842105263157895,
    'pcorr': 0.23684210526315788,
    'incorr': 0.07894736842105263,
    'explained_mistakes': -0.15789473684210528}, 'word_stats': {('шашек',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('шаш', 'шаш')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ек', 'ак')]}},
     0.18421052631578946),
    ('плиток',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('плит', 'шаш')]},
      'SUFF': {'scores': [1.0],
       'pairs': [('ок', 'ак')]}}, 0.13157894736842105),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]}}, 0.07894736842105263),
    ('досок',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('досок', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]}}, 0.07894736842105263),
    ('деталей',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('детал', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ей', '')]}}, 0.05263157894736842),
    ('мозаик',
     'corr'): ({'ROOT': {'scores': [3.6], 'pairs': [('моза', 'шаш')]},
      'SUFF': {'scores': [1.0],
       'pairs': [('ик', 'ак')]}}, 0.05263157894736842),
    ('кусочков',
     'corr'): ({'ROOT': {'scores': [2.6], 'pairs': [('кус', 'шаш')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['оч', 'к'], ['ак']]},
      'END': {'scores': [2.0], 'pairs': [('ов', '')]}}, 0.02631578947368421),
    ('кусочков мозаики', 'corr'): ({}, 0.02631578947368421),
    ('мазаик',
     'pcorr'): ({'ROOT': {'scores': [1.6], 'pairs': [('маз', 'шаш')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['а', 'ик'], ['ак']]}}, 0.02631578947368421),
    ('фрагментов мозаики', 'corr'): ({}, 0.02631578947368421),
    ('квадратов мозаики', 'corr'): ({}, 0.02631578947368421),
    ('мозаичного',
     'pcorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('моза', 'шаш')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ичн', 'ак')]},
      'END': {'scores': [3.0], 'pairs': [('ого', '')]}}, 0.02631578947368421),
    ('пазлов мазиики', 'corr'): ({}, 0.02631578947368421),
    ('плит мозаики', 'corr'): ({}, 0.02631578947368421),
    ('клеток',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('клет', 'шаш')]},
      'SUFF': {'scores': [1.0],
       'pairs': [('ок', 'ак')]}}, 0.02631578947368421),
    ('плиток мозаики', 'corr'): ({}, 0.02631578947368421),
    ('камней мозаики', 'corr'): ({}, 0.02631578947368421),
    ('узоров',
     'corr'): ({'ROOT': {'scores': [3.6], 'pairs': [('узор', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ов', '')]}}, 0.02631578947368421),
    ('квадратов',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('квадр', 'шаш')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ат', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ов', '')]}}, 0.02631578947368421),
    ('шашек мозаичного', 'corr'): ({}, 0.02631578947368421),
    ('мазаечного',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('мазаеч', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('н', 'ак')]},
      'END': {'scores': [3.0], 'pairs': [('ого', '')]}}, 0.02631578947368421),
    ('частей',
     'pcorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('част', 'шаш')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ей', '')]}}, 0.02631578947368421)}},
  (14,
   'финики',
   'фiнiкi'): {'morph_comparison': {'ROOT': {'scores': [0.4],
     'pairs': [('финик', 'фiнiк')]},
    'END': {'scores': [0.2],
     'pairs': [('и', 'i')]}}, 'overall_stats': {'corr': 0.868421052631579,
    'explained_mistakes': 0.7986270022883295,
    'incorr': 0.10526315789473684,
    'pcorr': 0.02631578947368421}, 'word_stats': {('финики',
     'corr'): ({'ROOT': {'scores': [0.4], 'pairs': [('финик', 'фiнiк')]},
      'END': {'scores': [0.2], 'pairs': [('и', 'i')]}}, 0.868421052631579),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'фiнiк')]},
      'END': {'scores': [1.0], 'pairs': [('', 'i')]}}, 0.05263157894736842),
    ('фантики',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('фант', 'фiнiк')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ик', '')]},
      'END': {'scores': [0.2], 'pairs': [('и', 'i')]}}, 0.02631578947368421),
    ('а также', 'incorr'): ({}, 0.02631578947368421),
    ('думая',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('дум', 'фiнiк')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ая', '')]},
      'END': {'scores': [1.0], 'pairs': [('', 'i')]}}, 0.02631578947368421)}},
  (16,
   'вырвался',
   'вырваўся'): {'morph_comparison': {'PREF': {'scores': [0.0],
     'pairs': [('вы', 'вы')]},
    'ROOT': {'scores': [0.0], 'pairs': [('рв', 'рв')]},
    'SUFF': {'scores': [0.0, 1.0], 'pairs': [('а', 'а'), ('л', 'ў')]},
    'POSTFIX': {'scores': [0.0],
     'pairs': [('ся', 'ся')]}}, 'overall_stats': {'corr': 0.9210526315789473,
    'explained_mistakes': 0.768421052631579,
    'pcorr': 0.05263157894736842,
    'incorr': 0.02631578947368421}, 'word_stats': {('вырвался',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [0.0], 'pairs': [('рв', 'рв')]},
      'SUFF': {'scores': [0.0, 1.0], 'pairs': [('а', 'а'), ('л', 'ў')]},
      'POSTFIX': {'scores': [0.0], 'pairs': [('ся', 'ся')]}},
     0.7894736842105263),
    ('вырвавшийся',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [0.0], 'pairs': [('рв', 'рв')]},
      'SUFF': {'scores': [0.0, 1.5], 'pairs': [('а', 'а'), ('вш', 'ў')]},
      'END': {'scores': [2.0], 'pairs': [('ий', '')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.02631578947368421),
    ('вывернулся',
     'pcorr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вер', 'рв')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['а', 'ў']]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.02631578947368421),
    ('и вырвался', 'corr'): ({}, 0.02631578947368421),
    ('вырывался',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [1.0], 'pairs': [('рыв', 'рв')]},
      'SUFF': {'scores': [0.0, 1.0], 'pairs': [('а', 'а'), ('л', 'ў')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.02631578947368421),
    ('вырываясь',
     'pcorr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [1.0], 'pairs': [('рыв', 'рв')]},
      'SUFF': {'scores': [0.0, 1.0], 'pairs': [('а', 'а'), ('я', 'ў')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('сь', 'ся')]}}, 0.02631578947368421),
    ('вырывается',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [1.0], 'pairs': [('рыв', 'рв')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а'], ['а', 'ў']]},
      'END': {'scores': [2.0], 'pairs': [('ет', '')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.02631578947368421),
    ('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'вы')]},
      'ROOT': {'scores': [2.0], 'pairs': [('', 'рв')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'аў')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'ся')]}}, 0.02631578947368421),
    ('вырваться',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [0.0], 'pairs': [('рв', 'рв')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а'], ['а', 'ў']]},
      'END': {'scores': [2.0], 'pairs': [('ть', '')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('ся', 'ся')]}}, 0.02631578947368421)}},
  (17,
   'веревки',
   'вяроўкi'): {'morph_comparison': {'ROOT': {'scores': [2.1],
     'pairs': [('верев', 'вяроў')]},
    'SUFF': {'scores': [0.0], 'pairs': [('к', 'к')]},
    'END': {'scores': [0.2],
     'pairs': [('и', 'i')]}}, 'overall_stats': {'corr': 0.5526315789473685,
    'pcorr': 0.34210526315789475,
    'incorr': 0.10526315789473684,
    'explained_mistakes': -3.6315789473684204}, 'word_stats': {('веревки',
     'corr'): ({'ROOT': {'scores': [2.1], 'pairs': [('верев', 'вяроў')]},
      'SUFF': {'scores': [0.0], 'pairs': [('к', 'к')]},
      'END': {'scores': [0.2], 'pairs': [('и', 'i')]}},
     0.42105263157894735),
    ('варежки',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('вареж', 'вяроў')]},
      'SUFF': {'scores': [0.0], 'pairs': [('к', 'к')]},
      'END': {'scores': [0.2], 'pairs': [('и', 'i')]}}, 0.10526315789473684),
    ('оковы',
     'pcorr'): ({'ROOT': {'scores': [3.5], 'pairs': [('оков', 'вяроў')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('ы', 'i')]}}, 0.10526315789473684),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'вяроў')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('', 'i')]}}, 0.07894736842105263),
    ('верёвки',
     'corr'): ({'ROOT': {'scores': [2.1], 'pairs': [('верёв', 'вяроў')]},
      'SUFF': {'scores': [0.0], 'pairs': [('к', 'к')]},
      'END': {'scores': [0.2], 'pairs': [('и', 'i')]}}, 0.07894736842105263),
    ('кожу',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('кож', 'вяроў')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('у', 'i')]}}, 0.02631578947368421),
    ('наручники',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('на', '')]},
      'ROOT': {'scores': [3.6], 'pairs': [('руч', 'вяроў')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ник', 'к')]},
      'END': {'scores': [0.2], 'pairs': [('и', 'i')]}}, 0.02631578947368421),
    ('рубашку',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('рубаш', 'вяроў')]},
      'SUFF': {'scores': [0.0], 'pairs': [('к', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('у', 'i')]}}, 0.02631578947368421),
    ('рукава',
     'pcorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('рук', 'вяроў')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ав', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'i')]}}, 0.02631578947368421),
    ('верёвку',
     'corr'): ({'ROOT': {'scores': [2.1], 'pairs': [('верёв', 'вяроў')]},
      'SUFF': {'scores': [0.0], 'pairs': [('к', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('у', 'i')]}}, 0.02631578947368421),
    ('верев и', 'corr'): ({}, 0.02631578947368421),
    ('ветровку',
     'pcorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('ветр', 'вяроў')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ов', 'к'], ['к']]},
      'END': {'scores': [1.0], 'pairs': [('у', 'i')]}}, 0.02631578947368421),
    ('штанишки',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('штан', 'вяроў')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ишк', 'к')]},
      'END': {'scores': [0.2], 'pairs': [('и', 'i')]}}, 0.02631578947368421)}},
  (111,
   'ступеням',
   'прыступак'): {'morph_comparison': {'PREF': {'scores': [3.0],
     'pairs': [('', 'пры')]},
    'ROOT': {'scores': [2.0], 'pairs': [('ступен', 'ступ')]},
    'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
    'END': {'scores': [2.0],
     'pairs': [('ям', '')]}}, 'overall_stats': {'corr': 0.3684210526315789,
    'pcorr': 0.34210526315789475,
    'incorr': 0.2894736842105263,
    'explained_mistakes': -1.5473684210526317}, 'word_stats': {('ступеням',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'пры')]},
      'ROOT': {'scores': [2.0], 'pairs': [('ступен', 'ступ')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ак')]},
      'END': {'scores': [2.0], 'pairs': [('ям', '')]}},
     0.23684210526315788),
    ('приступкам',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('при', 'пры')]},
      'ROOT': {'scores': [0.0], 'pairs': [('ступ', 'ступ')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', 'ак')]},

In [24]:
cz_stats = cognate_stats(czech_ans, russian_true, czech_true, cz_cognates, 'latin', num_type)
cz_stats

({(11,
   'ступеням',
   'stupňům'): {'morph_comparison': {'ROOT': {'scores': [1.0],
     'pairs': [('ступен', 'ступн')]},
    'END': {'scores': [1.0],
     'pairs': [('ям', 'ум')]}}, 'overall_stats': {'corr': 0.7567567567567568,
    'explained_mistakes': 0.4054054054054054,
    'pcorr': 0.1891891891891892,
    'incorr': 0.05405405405405406}, 'word_stats': {('ступеням',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('ступен', 'ступн')]},
      'END': {'scores': [1.0], 'pairs': [('ям', 'ум')]}},
     0.6486486486486487),
    ('ступенькам',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('ступ', 'ступн')]},
      'SUFF': {'scores': [4.0], 'pairs': [('еньк', '')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ум')]}}, 0.05405405405405406),
    ('дороге',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('дорог', 'ступн')]},
      'END': {'scores': [2.0], 'pairs': [('е', 'ум')]}}, 0.05405405405405406),
    ('замку',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('зам', 'ступн')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [1.0], 'pairs': [('у', 'ум')]}}, 0.05405405405405406),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'ступн')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ум')]}}, 0.05405405405405406),
    ('ступенька',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('ступ', 'ступн')]},
      'SUFF': {'scores': [4.0], 'pairs': [('еньк', '')]},
      'END': {'scores': [2.0], 'pairs': [('а', 'ум')]}}, 0.02702702702702703),
    ('лестнице',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('лест', 'ступн')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ниц', '')]},
      'END': {'scores': [2.0], 'pairs': [('е', 'ум')]}}, 0.02702702702702703),
    ('доиу',
     'pcorr'): ({'ROOT': {'scores': [4.2], 'pairs': [('дои', 'ступн')]},
      'END': {'scores': [1.0], 'pairs': [('у', 'ум')]}}, 0.02702702702702703),
    ('трибуне',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('трибун', 'ступн')]},
      'END': {'scores': [2.0], 'pairs': [('е', 'ум')]}}, 0.02702702702702703),
    ('месту',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('мест', 'ступн')]},
      'END': {'scores': [1.0],
       'pairs': [('у', 'ум')]}}, 0.02702702702702703)}},
  (111,
   'ступеням',
   'stupňům'): {'morph_comparison': {'ROOT': {'scores': [1.0],
     'pairs': [('ступен', 'ступн')]},
    'END': {'scores': [1.0],
     'pairs': [('ям', 'ум')]}}, 'overall_stats': {'corr': 0.5135135135135135,
    'pcorr': 0.3783783783783784,
    'incorr': 0.10810810810810811,
    'explained_mistakes': 0.04864864864864856}, 'word_stats': {('ступеням',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('ступен', 'ступн')]},
      'END': {'scores': [1.0], 'pairs': [('ям', 'ум')]}},
     0.40540540540540543),
    ('воротам',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('ворот', 'ступн')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ум')]}}, 0.13513513513513514),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'ступн')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ум')]}}, 0.08108108108108109),
    ('уровням',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('у', '')]},
      'ROOT': {'scores': [4.6], 'pairs': [('ров', 'ступн')]},
      'SUFF': {'scores': [1.0], 'pairs': [('н', '')]},
      'END': {'scores': [1.0], 'pairs': [('ям', 'ум')]}}, 0.08108108108108109),
    ('ступенькам',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('ступ', 'ступн')]},
      'SUFF': {'scores': [4.0], 'pairs': [('еньк', '')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ум')]}}, 0.05405405405405406),
    ('стенам',
     'pcorr'): ({'ROOT': {'scores': [2.0], 'pairs': [('стен', 'ступн')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ум')]}}, 0.05405405405405406),
    ('стражам',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('страж', 'ступн')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ум')]}}, 0.02702702702702703),
    ('уровнем',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('у', '')]},
      'ROOT': {'scores': [4.6], 'pairs': [('ров', 'ступн')]},
      'SUFF': {'scores': [1.0], 'pairs': [('н', '')]},
      'END': {'scores': [1.0], 'pairs': [('ем', 'ум')]}}, 0.02702702702702703),
    ('столбам',
     'pcorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('столб', 'ступн')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ум')]}}, 0.02702702702702703),
    ('лестницам',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('лест', 'ступн')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ниц', '')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ум')]}}, 0.02702702702702703),
    ('ступеням злодеев', 'corr'): ({}, 0.02702702702702703),
    ('помостам',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', '')]},
      'ROOT': {'scores': [4.6], 'pairs': [('мост', 'ступн')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ум')]}}, 0.02702702702702703),
    ('крестам',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('крест', 'ступн')]},
      'END': {'scores': [1.0],
       'pairs': [('ам', 'ум')]}}, 0.02702702702702703)}},
  (113,
   'осужденных',
   'odsouzenci'): {'morph_comparison': {'PREF': {'scores': [1.0],
     'pairs': [('о', 'од')]},
    'ROOT': {'scores': [2.6], 'pairs': [('сужд', 'соуз')]},
    'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['енн'], ['ен', 'ц']]},
    'END': {'scores': [2.0],
     'pairs': [('ых', 'и')]}}, 'overall_stats': {'incorr': 0.4594594594594595,
    'corr': 0.32432432432432434,
    'pcorr': 0.21621621621621623,
    'explained_mistakes': -0.18918918918918928}, 'word_stats': {('осужденных',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'од')]},
      'ROOT': {'scores': [2.6], 'pairs': [('сужд', 'соуз')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['енн'], ['ен', 'ц']]},
      'END': {'scores': [2.0], 'pairs': [('ых', 'и')]}},
     0.1891891891891892),
    ('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.0], 'pairs': [('', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.16216216216216217),
    ('осуждённых',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'од')]},
      'ROOT': {'scores': [2.6], 'pairs': [('сужд', 'соуз')]},
      'SUFF': {'scores': [0.2, 1.0], 'pairs': [('ён', 'ен'), ('н', 'ц')]},
      'END': {'scores': [2.0], 'pairs': [('ых', 'и')]}}, 0.08108108108108109),
    ('отсюда',
     'incorr'): ({'PREF': {'scores': [0.6], 'pairs': [('от', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('сюд', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'и')]}}, 0.05405405405405406),
    ('происхрдящее',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('оис', 'од')]},
      'ROOT': {'scores': [5.0],
       'pairs': [('прхрд', 'соуз')]}}, 0.02702702702702703),
    ('его',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.6], 'pairs': [('его', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('больше',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('больш', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [0.6], 'pairs': [('е', 'и')]}}, 0.02702702702702703),
    ('людей',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.0], 'pairs': [('люд', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [0.8], 'pairs': [('ей', 'и')]}}, 0.02702702702702703),
    ('но солнце', 'pcorr'): ({}, 0.02702702702702703),
    ('глазами',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('глаз', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [2.0], 'pairs': [('ами', 'и')]}}, 0.02702702702702703),
    ('другого',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('друг', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [3.0], 'pairs': [('ого', 'и')]}}, 0.02702702702702703),
    ('толпу',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('толп', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('у', 'и')]}}, 0.02702702702702703),
    ('заимочек',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.6], 'pairs': [('заим', 'соуз')]},
      'SUFF': {'scores': [2.0, 2.0], 'pairs': [('оч', 'ен'), ('ек', 'ц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('приговорённых',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('при', 'од')]},
      'ROOT': {'scores': [3.6], 'pairs': [('говор', 'соуз')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ённ'], ['ен', 'ц']]},
      'END': {'scores': [2.0], 'pairs': [('ых', 'и')]}}, 0.02702702702702703),
    ('опасность',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.6], 'pairs': [('опас', 'соуз')]},
      'SUFF': {'scores': [1.0, 3.0], 'pairs': [('н', 'ен'), ('ост', 'ц')]},
      'END': {'scores': [0.0], 'pairs': [('ь', 'и')]}}, 0.02702702702702703),
    ('узника',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [2.6], 'pairs': [('уз', 'соуз')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ник'], ['ен', 'ц']]},
      'END': {'scores': [1.0], 'pairs': [('а', 'и')]}}, 0.02702702702702703),
    ('однако',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [5.0], 'pairs': [('однак', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('о', 'и')]}}, 0.02702702702702703),
    ('...',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.0], 'pairs': [('', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('иешуа',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.0], 'pairs': [('иеш', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [2.0], 'pairs': [('уа', 'и')]}}, 0.02702702702702703),
    ('заусенцы',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.2], 'pairs': [('заусен', 'соуз')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ц'], ['ен', 'ц']]},
      'END': {'scores': [1.0], 'pairs': [('ы', 'и')]}}, 0.02702702702702703),
    ('остального',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.5], 'pairs': [('осталь', 'соуз')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н'], ['ен', 'ц']]},
      'END': {'scores': [3.0], 'pairs': [('ого', 'и')]}}, 0.02702702702702703),
    ('никого',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [5.0], 'pairs': [('никого', 'соуз')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('остальных',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.5], 'pairs': [('осталь', 'соуз')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н'], ['ен', 'ц']]},
      'END': {'scores': [2.0],
       'pairs': [('ых', 'и')]}}, 0.02702702702702703)}},
  (115,
   'греческом',
   'řecky'): {'morph_comparison': {'ROOT': {'scores': [2.6],
     'pairs': [('греч', 'ржец')]},
    'SUFF': {'scores': [2.0], 'pairs': [('еск', 'цк')]},
    'END': {'scores': [2.0],
     'pairs': [('ом', 'ы')]}}, 'overall_stats': {'corr': 0.40540540540540543,
    'incorr': 0.35135135135135137,
    'pcorr': 0.24324324324324326,
    'explained_mistakes': -1.2084942084942087}, 'word_stats': {('греческом',
     'corr'): ({'ROOT': {'scores': [2.6], 'pairs': [('греч', 'ржец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'ы')]}},
     0.3783783783783784),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('', 'ржец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'цк')]},
      'END': {'scores': [1.0], 'pairs': [('', 'ы')]}}, 0.1891891891891892),
    ('других',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('друг', 'ржец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('их', 'ы')]}}, 0.08108108108108109),
    ('ржецком',
     'incorr'): ({'ROOT': {'scores': [0.0], 'pairs': [('ржец', 'ржец')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'ы')]}}, 0.08108108108108109),
    ('ржевском',
     'incorr'): ({'ROOT': {'scores': [1.0], 'pairs': [('рже', 'ржец')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['в', 'ск'], ['цк']]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'ы')]}}, 0.02702702702702703),
    ('но',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('но', 'ржец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'цк')]},
      'END': {'scores': [1.0], 'pairs': [('', 'ы')]}}, 0.02702702702702703),
    ('русском',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('рус', 'ржец')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'ы')]}}, 0.02702702702702703),
    ('рижском',
     'incorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('риж', 'ржец')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'ы')]}}, 0.02702702702702703),
    ('шумершских',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('шумерш', 'ржец')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('их', 'ы')]}}, 0.02702702702702703),
    ('местных',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('мест', 'ржец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('н', 'цк')]},
      'END': {'scores': [1.0], 'pairs': [('ых', 'ы')]}}, 0.02702702702702703),
    ('греческий',
     'corr'): ({'ROOT': {'scores': [2.6], 'pairs': [('греч', 'ржец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('ий', 'ы')]}}, 0.02702702702702703),
    ('грубых',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('груб', 'ржец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'цк')]},
      'END': {'scores': [1.0], 'pairs': [('ых', 'ы')]}}, 0.02702702702702703),
    ('еврейском',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('еврей', 'ржец')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'ы')]}}, 0.02702702702702703),
    ('иностранных',
     'pcorr'): ({'ROOT': {'scores': [8.0],
       'pairs': [('иностран', 'ржец')]}}, 0.02702702702702703)}},
  (116,
   'труба',
   'troubení'): {'morph_comparison': {'ROOT': {'scores': [1.6],
     'pairs': [('труб', 'троуб')]},
    'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
    'END': {'scores': [1.0],
     'pairs': [('а', 'и')]}}, 'overall_stats': {'incorr': 0.5945945945945946,
    'pcorr': 0.24324324324324326,
    'corr': 0.16216216216216217,
    'explained_mistakes': -1.1801801801801806}, 'word_stats': {('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}},
     0.35135135135135137),
    ('труба',
     'corr'): ({'ROOT': {'scores': [1.6], 'pairs': [('труб', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'и')]}}, 0.13513513513513514),
    ('толпа',
     'pcorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('толп', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'и')]}}, 0.08108108108108109),
    ('кто-то',
     'incorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('ктот', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('о', 'и')]}}, 0.02702702702702703),
    ('голос',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('голос', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('так',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('так', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('приближаваяся',
     'incorr'): ({'PREF': {'scores': [3.0], 'pairs': [('при', '')]},
      'ROOT': {'scores': [5.0], 'pairs': [('ближ', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ав', 'ен')]},
      'END': {'scores': [2.0], 'pairs': [('ая', 'и')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.02702702702702703),
    ('который',
     'incorr'): ({'ROOT': {'scores': [5.5], 'pairs': [('который', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('шум',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('шум', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('гудок',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('гуд', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ок', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('удар',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('удар', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('приблизившись',
     'incorr'): ({'PREF': {'scores': [3.0], 'pairs': [('при', '')]},
      'ROOT': {'scores': [5.0], 'pairs': [('близ', 'троуб')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['и', 'вши'], ['ен']]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('сь', '')]}}, 0.02702702702702703),
    ('ропот',
     'pcorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('ропот', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('труба (?)',
     'corr'): ({'ROOT': {'scores': [1.6], 'pairs': [('труб', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'и')]}}, 0.02702702702702703),
    ('цокот',
     'incorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('цок', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('от', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('лошадь',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('лошадь', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('...',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'троуб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.02702702702702703),
    ('приближение',
     'incorr'): ({'PREF': {'scores': [3.0], 'pairs': [('при', '')]},

In [25]:
pol_stats = cognate_stats(polish_ans, russian_true, polish_true, pol_cognates, 'latin', num_type)
pol_stats

({(10,
   'повернулся',
   'odwrócił'): {'morph_comparison': {'PREF': {'scores': [2.0],
     'pairs': [('по', 'од')]},
    'ROOT': {'scores': [3.0], 'pairs': [('вер', 'вруц')]},
    'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н', 'у', 'л'], ['и', 'л']]},
    'POSTFIX': {'scores': [2.0],
     'pairs': [('ся', '')]}}, 'overall_stats': {'corr': 0.5277777777777778,
    'pcorr': 0.3333333333333333,
    'incorr': 0.1388888888888889,
    'explained_mistakes': 0.12698412698412692}, 'word_stats': {('повернулся',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вер', 'вруц')]},
      'SUFF': {'scores': [2.0, 0.0], 'pairs': [('ну', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [2.0], 'pairs': [('ся', '')]}},
     0.3055555555555556),
    ('развернулся',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('раз', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вер', 'вруц')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['и', 'л']]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.1111111111111111),
    ('оглянулся',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'од')]},
      'ROOT': {'scores': [4.0], 'pairs': [('гля', 'вруц')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['и', 'л']]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.08333333333333333),
    ('встал',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('в', 'од')]},
      'ROOT': {'scores': [4.0], 'pairs': [('ст', 'вруц')]},
      'SUFF': {'scores': [1.0, 0.0],
       'pairs': [('а', 'и'), ('л', 'л')]}}, 0.05555555555555555),
    ('обернулся',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'од')]},
      'ROOT': {'scores': [4.0], 'pairs': [('бер', 'вруц')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['и', 'л']]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.05555555555555555),
    ('отвернулся',
     'corr'): ({'PREF': {'scores': [0.6], 'pairs': [('от', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вер', 'вруц')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['и', 'л']]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.05555555555555555),
    ('подумал',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('дум', 'вруц')]},
      'SUFF': {'scores': [1.0, 0.0],
       'pairs': [('а', 'и'), ('л', 'л')]}}, 0.027777777777777776),
    ('откинул это', 'incorr'): ({}, 0.027777777777777776),
    ('взял',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вз', 'вруц')]},
      'SUFF': {'scores': [1.0, 0.0],
       'pairs': [('я', 'и'), ('л', 'л')]}}, 0.027777777777777776),
    ('прикрыл глаза', 'pcorr'): ({}, 0.027777777777777776),
    ('открыл дверь', 'pcorr'): ({}, 0.027777777777777776),
    ('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.0], 'pairs': [('', 'вруц')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ил')]}}, 0.027777777777777776),
    ('поверил в это', 'incorr'): ({}, 0.027777777777777776),
    ('одбросил',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.6], 'pairs': [('одброс', 'вруц')]},
      'SUFF': {'scores': [0.0, 0.0],
       'pairs': [('и', 'и'), ('л', 'л')]}}, 0.027777777777777776),
    ('повернулся назад', 'corr'): ({}, 0.027777777777777776),
    ('одумался',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('дум', 'вруц')]},
      'SUFF': {'scores': [1.0, 0.0], 'pairs': [('а', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.027777777777777776),
    ('оглядел его', 'pcorr'): ({}, 0.027777777777777776),
    ('вздохнул',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('вз', 'од')]},
      'ROOT': {'scores': [3.6], 'pairs': [('дох', 'вруц')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['и', 'л']]}}, 0.027777777777777776)}},
  (12,
   'шашек',
   'szachownicę'): {'morph_comparison': {'ROOT': {'scores': [1.0],
     'pairs': [('шаш', 'шах')]},
    'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ек'], ['ов', 'ниц']]},
    'END': {'scores': [2.0],
     'pairs': [('', 'ен')]}}, 'overall_stats': {'pcorr': 0.6944444444444444,
    'corr': 0.19444444444444445,
    'incorr': 0.1111111111111111,
    'explained_mistakes': -0.6296296296296297}, 'word_stats': {('камней',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('камн', 'шах')]},
      'SUFF': {'scores': [5.0], 'pairs': [('', 'овниц')]},
      'END': {'scores': [1.0], 'pairs': [('ей', 'ен')]}},
     0.19444444444444445),
    ('досок',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('досок', 'шах')]},
      'SUFF': {'scores': [5.0], 'pairs': [('', 'овниц')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ен')]}}, 0.1111111111111111),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'шах')]},
      'SUFF': {'scores': [5.0], 'pairs': [('', 'овниц')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ен')]}}, 0.1111111111111111),
    ('листьев',
     'pcorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('листь', 'шах')]},
      'SUFF': {'scores': [5.0], 'pairs': [('', 'овниц')]},
      'END': {'scores': [1.0], 'pairs': [('ев', 'ен')]}}, 0.1111111111111111),
    ('камушков',
     'pcorr'): ({'ROOT': {'scores': [2.0], 'pairs': [('кам', 'шах')]},
      'SUFF': {'scores': [1.6, 3.0], 'pairs': [('уш', 'ов'), ('к', 'ниц')]},
      'END': {'scores': [2.0], 'pairs': [('ов', 'ен')]}}, 0.08333333333333333),
    ('узоров',
     'corr'): ({'ROOT': {'scores': [3.6], 'pairs': [('узор', 'шах')]},
      'SUFF': {'scores': [5.0], 'pairs': [('', 'овниц')]},
      'END': {'scores': [2.0], 'pairs': [('ов', 'ен')]}}, 0.08333333333333333),
    ('шахматного',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('шахмат', 'шах')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н'], ['ов', 'ниц']]},
      'END': {'scores': [3.0],
       'pairs': [('ого', 'ен')]}}, 0.05555555555555555),
    ('плиток',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('плит', 'шах')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ок'], ['ов', 'ниц']]},
      'END': {'scores': [2.0], 'pairs': [('', 'ен')]}}, 0.05555555555555555),
    ('шашек',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('шаш', 'шах')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ек'], ['ов', 'ниц']]},
      'END': {'scores': [2.0], 'pairs': [('', 'ен')]}}, 0.05555555555555555),
    ('шахмат',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('шахмат', 'шах')]},
      'SUFF': {'scores': [5.0], 'pairs': [('', 'овниц')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ен')]}}, 0.027777777777777776),
    ('пятен',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('пят', 'шах')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ен'], ['ов', 'ниц']]},
      'END': {'scores': [2.0], 'pairs': [('', 'ен')]}}, 0.027777777777777776),
    ('цветов',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('цвет', 'шах')]},
      'SUFF': {'scores': [5.0], 'pairs': [('', 'овниц')]},
      'END': {'scores': [2.0],
       'pairs': [('ов', 'ен')]}}, 0.027777777777777776),
    ('половиц',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('пол', 'шах')]},
      'SUFF': {'scores': [0.0, 1.0], 'pairs': [('ов', 'ов'), ('иц', 'ниц')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ен')]}}, 0.027777777777777776),
    ('перил и', 'pcorr'): ({}, 0.027777777777777776)}},
  (15,
   'чудо',
   'cud'): {'morph_comparison': {'ROOT': {'scores': [0.6],
     'pairs': [('чуд', 'цуд')]},
    'END': {'scores': [1.0],
     'pairs': [('о', '')]}}, 'overall_stats': {'corr': 0.75,
    'incorr': 0.19444444444444445,
    'explained_mistakes': 0.1444444444444444,
    'pcorr': 0.05555555555555555}, 'word_stats': {('чудо',
     'corr'): ({'ROOT': {'scores': [0.6], 'pairs': [('чуд', 'цуд')]},
      'END': {'scores': [1.0], 'pairs': [('о', '')]}}, 0.6666666666666666),
    ('nan', 'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'цуд')]}},
     0.08333333333333333),
    ('воочию',
     'incorr'): ({'ROOT': {'scores': [3.2], 'pairs': [('вооч', 'цуд')]},
      'SUFF': {'scores': [1.0], 'pairs': [('и', '')]},
      'END': {'scores': [1.0], 'pairs': [('ю', '')]}}, 0.027777777777777776),
    ('то чудо', 'corr'): ({}, 0.027777777777777776),
    ('на яву', 'incorr'): ({}, 0.027777777777777776),
    ('картину',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('картин', 'цуд')]},
      'END': {'scores': [1.0], 'pairs': [('у', '')]}}, 0.027777777777777776),
    ('невозможное',
     'corr'): ({'PREF': {'scores': [5.0], 'pairs': [('невоз', '')]},
      'ROOT': {'scores': [2.6], 'pairs': [('мож', 'цуд')]},
      'SUFF': {'scores': [1.0], 'pairs': [('н', '')]},
      'END': {'scores': [2.0], 'pairs': [('ое', '')]}}, 0.027777777777777776),
    ('человека',
     'pcorr'): ({'ROOT': {'scores': [6.2], 'pairs': [('человек', 'цуд')]},
      'END': {'scores': [1.0], 'pairs': [('а', '')]}}, 0.027777777777777776),
    ('властными',
     'incorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('власт', 'цуд')]},
      'SUFF': {'scores': [1.0], 'pairs': [('н', '')]},
      'END': {'scores': [3.0], 'pairs': [('ыми', '')]}}, 0.027777777777777776),
    ('то', 'incorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('то', 'цуд')]}},
     0.027777777777777776),
    ('это чудо', 'corr'): ({}, 0.027777777777777776)}},
  (16,
   'вырвался',
   'wyrwał'): {'morph_comparison': {'PREF': {'scores': [0.0],
     'pairs': [('вы', 'вы')]},
    'ROOT': {'scores': [0.0], 'pairs': [('рв', 'рв')]},
    'SUFF': {'scores': [0.0, 0.0], 'pairs': [('а', 'а'), ('л', 'л')]},
    'POSTFIX': {'scores': [2.0],
     'pairs': [('ся', '')]}}, 'overall_stats': {'corr': 0.75,
    'explained_mistakes': 0.5111111111111111,
    'pcorr': 0.19444444444444445,
    'incorr': 0.05555555555555555}, 'word_stats': {('вырвался',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [0.0], 'pairs': [('рв', 'рв')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('а', 'а'), ('л', 'л')]},
      'POSTFIX': {'scores': [2.0], 'pairs': [('ся', '')]}},
     0.5833333333333334),
    ('выбрался',
     'pcorr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [2.0], 'pairs': [('бр', 'рв')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('а', 'а'), ('л', 'л')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.08333333333333333),
    ('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'вы')]},
      'ROOT': {'scores': [2.0], 'pairs': [('', 'рв')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ал')]}}, 0.05555555555555555),
    ('который вырвался', 'corr'): ({}, 0.05555555555555555),
    ('вырвал',
     'pcorr'): ({'PREF': {'scores': [0.0], 'pairs': [('вы', 'вы')]},
      'ROOT': {'scores': [0.0], 'pairs': [('рв', 'рв')]},
      'SUFF': {'scores': [0.0, 0.0],
       'pairs': [('а', 'а'), ('л', 'л')]}}, 0.05555555555555555),
    ('который вырван', 'pcorr'): ({}, 0.027777777777777776),
    ('вырвал  рак', 'corr'): ({}, 0.027777777777777776),
    ('и который вырвал себя', 'corr'): ({}, 0.027777777777777776),
    ('бежит',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'вы')]},
      'ROOT': {'scores': [3.0], 'pairs': [('беж', 'рв')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ал')]},
      'END': {'scores': [2.0], 'pairs': [('ит', '')]}}, 0.027777777777777776),
    ('и который вырвался', 'corr'): ({}, 0.027777777777777776),
    ('и который вырвался.', 'corr'): ({}, 0.027777777777777776)}},
  (112,
   'дорогу',
   'drogę'): {'morph_comparison': {'ROOT': {'scores': [1.5],
     'pairs': [('дорог', 'дрог')]},
    'END': {'scores': [2.0],
     'pairs': [('у', 'ен')]}}, 'overall_stats': {'corr': 0.9166666666666666,
    'explained_mistakes': 0.5925925925925926,
    'pcorr': 0.05555555555555555,
    'incorr': 0.027777777777777776}, 'word_stats': {('дорогу',
     'corr'): ({'ROOT': {'scores': [1.5], 'pairs': [('дорог', 'дрог')]},
      'END': {'scores': [2.0], 'pairs': [('у', 'ен')]}}, 0.8888888888888888),
    ('лестницу',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('лест', 'дрог')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ниц', '')]},
      'END': {'scores': [2.0], 'pairs': [('у', 'ен')]}}, 0.027777777777777776),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('', 'дрог')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ен')]}}, 0.027777777777777776),
    ('улицу',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('улиц', 'дрог')]},
      'END': {'scores': [2.0], 'pairs': [('у', 'ен')]}}, 0.027777777777777776),
    ('площадь',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('площадь', 'дрог')]},
      'END': {'scores': [2.0],
       'pairs': [('', 'ен')]}}, 0.027777777777777776)}},
  (115,
   'греческом',
   'grecku'): {'morph_comparison': {'ROOT': {'scores': [0.6],
     'pairs': [('греч', 'грец')]},
    'SUFF': {'scores': [2.0], 'pairs': [('еск', 'цк')]},
    'END': {'scores': [1.6],
     'pairs': [('ом', 'у')]}}, 'overall_stats': {'corr': 0.8333333333333334,
    'explained_mistakes': 0.4761904761904762,
    'pcorr': 0.08333333333333333,
    'incorr': 0.08333333333333333}, 'word_stats': {('греческом',
     'corr'): ({'ROOT': {'scores': [0.6], 'pairs': [('греч', 'грец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'цк')]},
      'END': {'scores': [1.6], 'pairs': [('ом', 'у')]}}, 0.8333333333333334),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('', 'грец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'цк')]},
      'END': {'scores': [1.0], 'pairs': [('', 'у')]}}, 0.05555555555555555),
    ('арабском',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('араб', 'грец')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'цк')]},
      'END': {'scores': [1.6], 'pairs': [('ом', 'у')]}}, 0.027777777777777776),
    ('древних',
     'pcorr'): ({'ROOT': {'scores': [2.0], 'pairs': [('древ', 'грец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('н', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('их', 'у')]}}, 0.027777777777777776),
    ('грецком',
     'pcorr'): ({'ROOT': {'scores': [0.0], 'pairs': [('грец', 'грец')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', 'цк')]},
      'END': {'scores': [1.6], 'pairs': [('ом', 'у')]}}, 0.027777777777777776),
    ('жаргоне',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('жаргон', 'грец')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'цк')]},
      'END': {'scores': [1.0],
       'pairs': [('е', 'у')]}}, 0.027777777777777776)}},
  (116,
   'труба',
   'trąbki'): {'morph_comparison': {'ROOT': {'scores': [1.6],
     'pairs': [('труб', 'тромб')]},
    'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
    'END': {'scores': [1.0],
     'pairs': [('а', 'и')]}}, 'overall_stats': {'corr': 0.3611111111111111,
    'incorr': 0.3333333333333333,
    'pcorr': 0.3055555555555556,
    'explained_mistakes': -0.22222222222222224}, 'word_stats': {('труба',
     'corr'): ({'ROOT': {'scores': [1.6], 'pairs': [('труб', 'тромб')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'и')]}},
     0.2777777777777778),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'тромб')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.2222222222222222),
    ('женщина',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('жен', 'тромб')]},
      'SUFF': {'scores': [3.0], 'pairs': [('щин', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'и')]}}, 0.08333333333333333),
    ('веселый',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('весел', 'тромб')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [1.2], 'pairs': [('ый', 'и')]}}, 0.05555555555555555),
    ('на площадь выбежала женщина', 'incorr'): ({}, 0.027777777777777776),
    ('голос торговки', 'pcorr'): ({}, 0.027777777777777776),
    ('девушка',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('дев', 'тромб')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['уш', 'к'], ['к']]},
      'END': {'scores': [1.0], 'pairs': [('а', 'и')]}}, 0.027777777777777776),
    ('весёлый голос', 'pcorr'): ({}, 0.027777777777777776),
    ('голос трубы', 'corr'): ({}, 0.027777777777777776),
    ('трубы',
     'corr'): ({'ROOT': {'scores': [1.6], 'pairs': [('труб', 'тромб')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('ы', 'и')]}}, 0.027777777777777776),
    ('гул',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('гул', 'тромб')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.027777777777777776),
    ('ржанье',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('рж', 'тромб')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а', 'нь'], ['к']]},
      'END': {'scores': [0.6], 'pairs': [('е', 'и')]}}, 0.027777777777777776),
    ('звук повозки', 'pcorr'): ({}, 0.027777777777777776),
    ('ржач',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('рж', 'тромб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ач', 'к')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.027777777777777776),
    ('веселым голосом', 'pcorr'): ({}, 0.027777777777777776),
    ('звук трубы', 'corr'): ({}, 0.027777777777777776),
    ('гоготанье',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('гогот', 'тромб')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а', 'нь'], ['к']]},
      'END': {'scores': [0.6],
       'pairs': [('е', 'и')]}}, 0.027777777777777776)}},
  (117,
   'весело',
   'wesoły'): {'morph_comparison': {'ROOT': {'scores': [1.0],
     'pairs': [('весел', 'весол')]},
    'END': {'scores': [1.0],
     'pairs': [('о', 'ы')]}}, 'overall_stats': {'pcorr': 0.3888888888888889,
    'corr': 0.3611111111111111,
    'incorr': 0.25,
    'explained_mistakes': -4.499999999999999}, 'word_stats': {('весело',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('весел', 'весол')]},
      'END': {'scores': [1.0], 'pairs': [('о', 'ы')]}},
     0.3333333333333333),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'весол')]},
      'END': {'scores': [1.0], 'pairs': [('', 'ы')]}}, 0.19444444444444445),
    ('громко',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('гром', 'весол')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [1.0], 'pairs': [('о', 'ы')]}}, 0.19444444444444445),
    ('отрывисто',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('от', '')]},
      'ROOT': {'scores': [5.0], 'pairs': [('рыв', 'весол')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ист', '')]},
      'END': {'scores': [1.0], 'pairs': [('о', 'ы')]}}, 0.05555555555555555),
    ('звонко',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('звон', 'весол')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [1.0], 'pairs': [('о', 'ы')]}}, 0.027777777777777776),
    ('требовательно',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('треб', 'весол')]},
      'SUFF': {'scores': [8.0], 'pairs': [('овательн', '')]},
      'END': {'scores': [1.0], 'pairs': [('о', 'ы')]}}, 0.027777777777777776),
    ('робко',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('роб', 'весол')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [1.0], 'pairs': [('о', 'ы')]}}, 0.027777777777777776),
    ('рвано',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('рв', 'весол')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ан', '')]},

In [26]:
bg_stats = cognate_stats(bulgarian_ans, russian_true, bulgarian_true, bg_cognates, 'cyr', num_type)
bg_stats

({(10,
   'повернулся',
   'обърна'): {'morph_comparison': {'PREF': {'scores': [2.0],
     'pairs': [('по', 'об')]},
    'ROOT': {'scores': [2.0], 'pairs': [('вер', 'ър')]},
    'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н', 'у', 'л'], ['н']]},
    'END': {'scores': [1.0], 'pairs': [('', 'а')]},
    'POSTFIX': {'scores': [2.0],
     'pairs': [('ся', '')]}}, 'overall_stats': {'pcorr': 0.4594594594594595,
    'corr': 0.40540540540540543,
    'explained_mistakes': 0.15057915057915053,
    'incorr': 0.13513513513513514}, 'word_stats': {('обернулся',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'об')]},
      'ROOT': {'scores': [2.0], 'pairs': [('бер', 'ър')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н', 'у', 'л'], ['н']]},
      'END': {'scores': [1.0], 'pairs': [('', 'а')]},
      'POSTFIX': {'scores': [2.0], 'pairs': [('ся', '')]}},
     0.32432432432432434),
    ('повернулся',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'об')]},
      'ROOT': {'scores': [2.0], 'pairs': [('вер', 'ър')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ну', 'л'], ['н']]},
      'END': {'scores': [1.0], 'pairs': [('', 'а')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.32432432432432434),
    ('развернулся',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('раз', 'об')]},
      'ROOT': {'scores': [2.0], 'pairs': [('вер', 'ър')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н', 'у', 'л'], ['н']]},
      'END': {'scores': [1.0], 'pairs': [('', 'а')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.08108108108108109),
    ('оглянулся',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('гля', 'ър')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н', 'у', 'л'], ['н']]},
      'END': {'scores': [1.0], 'pairs': [('', 'а')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.05405405405405406),
    ('встал',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('в', 'об')]},
      'ROOT': {'scores': [2.0], 'pairs': [('ст', 'ър')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а', 'л'], ['н']]},
      'END': {'scores': [1.0], 'pairs': [('', 'а')]}}, 0.05405405405405406),
    ('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'об')]},
      'ROOT': {'scores': [2.0], 'pairs': [('', 'ър')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'н')]},
      'END': {'scores': [1.0], 'pairs': [('', 'а')]}}, 0.05405405405405406),
    ('прошелся туда и обратно по подиуму', 'incorr'): ({},
     0.02702702702702703),
    ('василий',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'об')]},
      'ROOT': {'scores': [5.0], 'pairs': [('васил', 'ър')]},
      'SUFF': {'scores': [1.0], 'pairs': [('и', 'н')]},
      'END': {'scores': [1.0], 'pairs': [('й', 'а')]}},
     0.02702702702702703),
    ('прыгнул с обрыва', 'incorr'): ({}, 0.02702702702702703),
    ('огляделся',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'об')]},
      'ROOT': {'scores': [4.0], 'pairs': [('гляд', 'ър')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['е', 'л'], ['н']]},
      'END': {'scores': [1.0], 'pairs': [('', 'а')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.02702702702702703)}},
  (11,
   'ступеням',
   'стъпалата'): {'morph_comparison': {'ROOT': {'scores': [3.0],
     'pairs': [('ступен', 'стъпал')]},
    'END': {'scores': [3.0],
     'pairs': [('ям',
       'ата')]}}, 'overall_stats': {'incorr': 0.40540540540540543,
    'pcorr': 0.32432432432432434,
    'corr': 0.2702702702702703,
    'explained_mistakes': -3.45945945945946}, 'word_stats': {('nan',
     'incorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ата')]}},
     0.2702702702702703),
    ('ступеням',
     'corr'): ({'ROOT': {'scores': [3.0], 'pairs': [('ступен', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('ям', 'ата')]}}, 0.1891891891891892),
    ('палате',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('палат', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ата')]}}, 0.10810810810810811),
    ('дому',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('дом', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('у', 'ата')]}}, 0.08108108108108109),
    ('площади',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('площад', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('и', 'ата')]}}, 0.05405405405405406),
    ('като',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('кат', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('о', 'ата')]}}, 0.02702702702702703),
    ('собору',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('собор', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('у', 'ата')]}}, 0.02702702702702703),
    ('трибуне',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('трибун', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ата')]}}, 0.02702702702702703),
    ('толпе',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('толп', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ата')]}}, 0.02702702702702703),
    ('ступени',
     'corr'): ({'ROOT': {'scores': [3.0], 'pairs': [('ступ', 'стъпал')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ен', '')]},
      'END': {'scores': [3.0], 'pairs': [('и', 'ата')]}}, 0.02702702702702703),
    ('ступенькам',
     'corr'): ({'ROOT': {'scores': [3.0], 'pairs': [('ступ', 'стъпал')]},
      'SUFF': {'scores': [4.0], 'pairs': [('еньк', '')]},
      'END': {'scores': [2.0],
       'pairs': [('ам', 'ата')]}}, 0.02702702702702703),
    ('храму',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('храм', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('у', 'ата')]}}, 0.02702702702702703),
    ('лестнице',
     'corr'): ({'ROOT': {'scores': [6.0], 'pairs': [('лест', 'стъпал')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ниц', '')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ата')]}}, 0.02702702702702703),
    ('креслу',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('кресл', 'стъпал')]},
      'END': {'scores': [3.0], 'pairs': [('у', 'ата')]}}, 0.02702702702702703),
    ('палатке',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('палат', 'стъпал')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ата')]}}, 0.02702702702702703),
    ('бордюру',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('бордюр', 'стъпал')]},
      'END': {'scores': [3.0],
       'pairs': [('у', 'ата')]}}, 0.02702702702702703)}},
  (15,
   'чудо',
   'чудото'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('чуд', 'чуд')]},
    'END': {'scores': [2.0],
     'pairs': [('о', 'ото')]}}, 'overall_stats': {'corr': 0.7567567567567568,
    'explained_mistakes': 0.4054054054054054,
    'incorr': 0.13513513513513514,
    'pcorr': 0.10810810810810811}, 'word_stats': {('чудо',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('чуд', 'чуд')]},
      'END': {'scores': [2.0], 'pairs': [('о', 'ото')]}},
     0.6486486486486487),
    ('это чудо', 'corr'): ({}, 0.10810810810810811),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'чуд')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ото')]}}, 0.05405405405405406),
    ('отчетливо',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('от', '')]},
      'ROOT': {'scores': [1.6], 'pairs': [('чет', 'чуд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('лив', '')]},
      'END': {'scores': [2.0], 'pairs': [('о', 'ото')]}}, 0.02702702702702703),
    ('смерть',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('смерть', 'чуд')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ото')]}}, 0.02702702702702703),
    ('зрелище',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('зрел', 'чуд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ищ', '')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ото')]}}, 0.02702702702702703),
    ('и инжир', 'incorr'): ({}, 0.02702702702702703),
    ('жизнь',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('жи', 'чуд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('знь', '')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ото')]}}, 0.02702702702702703),
    ('представление',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('п', '')]},
      'ROOT': {'scores': [6.6], 'pairs': [('редставл', 'чуд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ени', '')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ото')]}}, 0.02702702702702703),
    ('то',
     'incorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('то', 'чуд')]},
      'END': {'scores': [3.0],
       'pairs': [('', 'ото')]}}, 0.02702702702702703)}},
  (110,
   'знал',
   'знаеше'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('зна', 'зна')]},
    'SUFF': {'scores': [2.0], 'pairs': [('л', 'еш')]},
    'END': {'scores': [1.0],
     'pairs': [('', 'е')]}}, 'overall_stats': {'corr': 0.8378378378378378,
    'explained_mistakes': 0.4054054054054054,
    'pcorr': 0.13513513513513514,
    'incorr': 0.02702702702702703}, 'word_stats': {('знал',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('зна', 'зна')]},
      'SUFF': {'scores': [2.0], 'pairs': [('л', 'еш')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.8108108108108109),
    ('чувствовал',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('чу', 'зна')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['в', 'ств', 'ов', 'а', 'л'], ['еш']]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.02702702702702703),
    ('предполагал',
     'pcorr'): ({'ROOT': {'scores': [8.0], 'pairs': [('предполаг', 'зна')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а', 'л'], ['еш']]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.02702702702702703),
    ('знает',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('зна', 'зна')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'еш')]},
      'END': {'scores': [1.0], 'pairs': [('ет', 'е')]}}, 0.02702702702702703),
    ('думал',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('дум', 'зна')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а', 'л'], ['еш']]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.02702702702702703),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'зна')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'еш')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.02702702702702703),
    ('услышал',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('у', '')]},
      'ROOT': {'scores': [3.6], 'pairs': [('слыш', 'зна')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а', 'л'], ['еш']]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.02702702702702703),
    ('понял',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('пон', 'зна')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['я', 'л'], ['еш']]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.02702702702702703)}},
  (111,
   'ступеням',
   'стъпала'): {'morph_comparison': {'ROOT': {'scores': [3.0],
     'pairs': [('ступен', 'стъпал')]},
    'END': {'scores': [2.0],
     'pairs': [('ям', 'а')]}}, 'overall_stats': {'pcorr': 0.40540540540540543,
    'corr': 0.35135135135135137,
    'incorr': 0.24324324324324326,
    'explained_mistakes': -1.1405405405405407}, 'word_stats': {('ступеням',
     'corr'): ({'ROOT': {'scores': [3.0], 'pairs': [('ступен', 'стъпал')]},
      'END': {'scores': [2.0], 'pairs': [('ям', 'а')]}},
     0.2702702702702703),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('', 'стъпал')]},
      'END': {'scores': [1.0], 'pairs': [('', 'а')]}}, 0.24324324324324326),
    ('воротам',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('ворот', 'стъпал')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.13513513513513514),
    ('ступенькам',
     'corr'): ({'ROOT': {'scores': [3.0], 'pairs': [('ступ', 'стъпал')]},
      'SUFF': {'scores': [4.0], 'pairs': [('еньк', '')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.05405405405405406),
    ('спускам',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('с', '')]},
      'ROOT': {'scores': [6.0], 'pairs': [('пуск', 'стъпал')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.02702702702702703),
    ('лестницам',
     'corr'): ({'ROOT': {'scores': [6.0], 'pairs': [('лест', 'стъпал')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ниц', '')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.02702702702702703),
    ('колоннам',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('колон', 'стъпал')]},
      'SUFF': {'scores': [1.0], 'pairs': [('н', '')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.02702702702702703),
    ('воротами',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('ворот', 'стъпал')]},
      'END': {'scores': [2.0], 'pairs': [('ами', 'а')]}}, 0.02702702702702703),
    ('входам',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('в', '')]},
      'ROOT': {'scores': [6.0], 'pairs': [('ход', 'стъпал')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.02702702702702703),
    ('дверям',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('двер', 'стъпал')]},
      'END': {'scores': [2.0], 'pairs': [('ям', 'а')]}}, 0.02702702702702703),
    ('залам',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('з', '')]},
      'ROOT': {'scores': [4.0], 'pairs': [('ал', 'стъпал')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.02702702702702703),
    ('стенам',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('стен', 'стъпал')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.02702702702702703),
    ('выходам',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('вы', '')]},
      'ROOT': {'scores': [6.0], 'pairs': [('ход', 'стъпал')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.02702702702702703),
    ('флангам',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('фланг', 'стъпал')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'а')]}}, 0.02702702702702703),
    ('шпалам',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('шпал', 'стъпал')]},
      'END': {'scores': [1.0],
       'pairs': [('ам', 'а')]}}, 0.02702702702702703)}},
  (113,
   'осужденных',
   'осъдените'): {'morph_comparison': {'PREF': {'scores': [0.0],
     'pairs': [('о', 'о')]},
    'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'съд')]},
    'SUFF': {'scores': [1.0], 'pairs': [('енн', 'ен')]},
    'END': {'scores': [3.0],
     'pairs': [('ых',
       'ите')]}}, 'overall_stats': {'incorr': 0.4594594594594595,
    'corr': 0.2702702702702703,
    'pcorr': 0.2702702702702703,
    'explained_mistakes': -0.18918918918918928}, 'word_stats': {('nan',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ите')]}},
     0.13513513513513514),
    ('осужденных',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('о', 'о')]},
      'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'съд')]},
      'SUFF': {'scores': [1.0], 'pairs': [('енн', 'ен')]},
      'END': {'scores': [3.0],
       'pairs': [('ых', 'ите')]}}, 0.13513513513513514),
    ('больше',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [4.0], 'pairs': [('больш', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [2.6], 'pairs': [('е', 'ите')]}}, 0.10810810810810811),
    ('осуждённых',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('о', 'о')]},
      'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'съд')]},
      'SUFF': {'scores': [1.2], 'pairs': [('ённ', 'ен')]},
      'END': {'scores': [3.0],
       'pairs': [('ых', 'ите')]}}, 0.08108108108108109),
    ('толпу',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [4.0], 'pairs': [('толп', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [3.0], 'pairs': [('у', 'ите')]}}, 0.05405405405405406),
    ('что',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('что', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ите')]}}, 0.02702702702702703),
    ('его',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('его', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ите')]}}, 0.02702702702702703),
    ('вече',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('веч', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [2.6], 'pairs': [('е', 'ите')]}}, 0.02702702702702703),
    ('конвой',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [4.0], 'pairs': [('конв', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [3.0],
       'pairs': [('ой', 'ите')]}}, 0.02702702702702703),
    ('врагов',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [4.0], 'pairs': [('враг', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [3.0],
       'pairs': [('ов', 'ите')]}}, 0.02702702702702703),
    ('однако',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [5.0], 'pairs': [('однак', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [3.0], 'pairs': [('о', 'ите')]}}, 0.02702702702702703),
    ('хотя',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [2.6], 'pairs': [('хот', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [2.6], 'pairs': [('я', 'ите')]}}, 0.02702702702702703),
    ('осужденного',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('о', 'о')]},
      'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'съд')]},
      'SUFF': {'scores': [1.0], 'pairs': [('енн', 'ен')]},
      'END': {'scores': [3.0],
       'pairs': [('ого', 'ите')]}}, 0.02702702702702703),
    ('людей',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [2.0], 'pairs': [('люд', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [2.6],
       'pairs': [('ей', 'ите')]}}, 0.02702702702702703),
    ('народ',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [4.0], 'pairs': [('народ', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ите')]}}, 0.02702702702702703),
    ('правду',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [4.0], 'pairs': [('правд', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},
      'END': {'scores': [3.0], 'pairs': [('у', 'ите')]}}, 0.02702702702702703),
    ('окружающих',
     'pcorr'): ({'PREF': {'scores': [0.0], 'pairs': [('о', 'о')]},
      'ROOT': {'scores': [4.0], 'pairs': [('круж', 'съд')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а', 'ющ'], ['ен']]},
      'END': {'scores': [2.0],
       'pairs': [('их', 'ите')]}}, 0.02702702702702703),
    ('отсюда',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('от', 'о')]},
      'ROOT': {'scores': [1.0], 'pairs': [('сюд', 'съд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ен')]},

In [27]:
sb_stats = cognate_stats(serbian_ans, russian_true, serbian_true, sb_cognates, 'cyr', num_type)
sb_stats

({(11,
   'ступеням',
   'степеницама'): {'morph_comparison': {'ROOT': {'scores': [1.0],
     'pairs': [('ступен', 'степен')]},
    'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
    'END': {'scores': [2.0],
     'pairs': [('ям', 'ама')]}}, 'overall_stats': {'corr': 0.525,
    'pcorr': 0.35,
    'incorr': 0.125,
    'explained_mistakes': -0.37499999999999994}, 'word_stats': {('лестнице',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('лест', 'степен')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ниц', 'иц')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ама')]}},
     0.325),
    ('ступеням',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('ступен', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [2.0], 'pairs': [('ям', 'ама')]}}, 0.15),
    ('платформе',
     'pcorr'): ({'ROOT': {'scores': [7.0], 'pairs': [('платформ', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ама')]}}, 0.125),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ама')]}}, 0.125),
    ('помосту',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', '')]},
      'ROOT': {'scores': [6.0], 'pairs': [('мост', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [3.0], 'pairs': [('у', 'ама')]}}, 0.075),
    ('ступенькам',
     'corr'): ({'ROOT': {'scores': [3.0], 'pairs': [('ступ', 'степен')]},
      'SUFF': {'scores': [2.6], 'pairs': [('еньк', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ама')]}}, 0.05),
    ('воротам',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('ворот', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ама')]}}, 0.05),
    ('плаформе',
     'pcorr'): ({'ROOT': {'scores': [7.0], 'pairs': [('плаформ', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ама')]}}, 0.025),
    ('площади',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('площад', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [3.0], 'pairs': [('и', 'ама')]}}, 0.025),
    ('темницам',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('тем', 'степен')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ниц', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ама')]}}, 0.025),
    ('деревне',
     'pcorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('дерев', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('н', 'иц')]},
      'END': {'scores': [3.0], 'pairs': [('е', 'ама')]}}, 0.025)}},
  (15,
   'чудо',
   'чудо'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('чуд', 'чуд')]},
    'END': {'scores': [0.0],
     'pairs': [('о', 'о')]}}, 'overall_stats': {'corr': 0.875,
    'explained_mistakes': 0.5599999999999999,
    'incorr': 0.1,
    'pcorr': 0.025}, 'word_stats': {('чудо',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('чуд', 'чуд')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.875),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'чуд')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.075),
    ('то',
     'incorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('то', 'чуд')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.025),
    ('помилование',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', '')]},
      'ROOT': {'scores': [3.0], 'pairs': [('мил', 'чуд')]},
      'SUFF': {'scores': [5.0], 'pairs': [('овани', '')]},
      'END': {'scores': [1.0], 'pairs': [('е', 'о')]}}, 0.025)}},
  (110,
   'знал',
   'знао'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('зна', 'зна')]},
    'SUFF': {'scores': [1.0],
     'pairs': [('л', 'о')]}}, 'overall_stats': {'corr': 0.875,
    'incorr': 0.075,
    'pcorr': 0.05,
    'explained_mistakes': -0.6499999999999999}, 'word_stats': {('знал',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('зна', 'зна')]},
      'SUFF': {'scores': [1.0], 'pairs': [('л', 'о')]}},
     0.8),
    ('знает',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('зна', 'зна')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'END': {'scores': [2.0], 'pairs': [('ет', '')]}}, 0.075),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'зна')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.075),
    ('понимал',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('поним', 'зна')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['а', 'л'], ['о']]}}, 0.025),
    ('зная',
     'pcorr'): ({'ROOT': {'scores': [0.0], 'pairs': [('зна', 'зна')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'END': {'scores': [1.0], 'pairs': [('я', '')]}}, 0.025)}},
  (111,
   'ступеням',
   'степеницама'): {'morph_comparison': {'ROOT': {'scores': [1.0],
     'pairs': [('ступен', 'степен')]},
    'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
    'END': {'scores': [2.0],
     'pairs': [('ям', 'ама')]}}, 'overall_stats': {'corr': 0.6,
    'pcorr': 0.25,
    'incorr': 0.15,
    'explained_mistakes': -0.32}, 'word_stats': {('лестницам',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('лест', 'степен')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ниц', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ама')]}},
     0.3),
    ('ступеням',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('ступен', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [2.0], 'pairs': [('ям', 'ама')]}}, 0.25),
    ('воротам',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('ворот', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ама')]}}, 0.15),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [3.0], 'pairs': [('', 'ама')]}}, 0.1),
    ('ступенькам',
     'corr'): ({'ROOT': {'scores': [3.0], 'pairs': [('ступ', 'степен')]},
      'SUFF': {'scores': [2.6], 'pairs': [('еньк', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ама')]}}, 0.05),
    ('автобусам',
     'incorr'): ({'ROOT': {'scores': [5.6],
       'pairs': [('автобус', 'степен')]}}, 0.025),
    ('помостьям',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', '')]},
      'ROOT': {'scores': [3.0], 'pairs': [('пмость', 'степен')]}}, 0.025),
    ('столбам у воды', 'pcorr'): ({}, 0.025),
    ('улицам',
     'pcorr'): ({'ROOT': {'scores': [5.2], 'pairs': [('улиц', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ама')]}}, 0.025),
    ('дорогам',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('дорог', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ама')]}}, 0.025),
    ('домам',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('дом', 'степен')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ам', 'ама')]}}, 0.025)}},
  (113,
   'осужденных',
   'осуђенике'): {'morph_comparison': {'PREF': {'scores': [0.0],
     'pairs': [('о', 'о')]},
    'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'суђ')]},
    'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['енн'], ['ен', 'ик']]},
    'END': {'scores': [2.0],
     'pairs': [('ых', 'е')]}}, 'overall_stats': {'incorr': 0.675,
    'corr': 0.275,
    'pcorr': 0.05,
    'explained_mistakes': -0.7470588235294119}, 'word_stats': {('осужденных',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('о', 'о')]},
      'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'суђ')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['енн'], ['ен', 'ик']]},
      'END': {'scores': [2.0], 'pairs': [('ых', 'е')]}},
     0.225),
    ('больше',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.6], 'pairs': [('больш', 'суђ')]},
      'SUFF': {'scores': [4.0], 'pairs': [('', 'еник')]},
      'END': {'scores': [0.0], 'pairs': [('е', 'е')]}}, 0.175),
    ('nan',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('', 'суђ')]},
      'SUFF': {'scores': [4.0], 'pairs': [('', 'еник')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.15),
    ('выше',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('выш', 'суђ')]},
      'SUFF': {'scores': [4.0], 'pairs': [('', 'еник')]},
      'END': {'scores': [0.0], 'pairs': [('е', 'е')]}}, 0.1),
    ('ничего',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [6.0], 'pairs': [('ничего', 'суђ')]},
      'SUFF': {'scores': [4.0], 'pairs': [('', 'еник')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.075),
    ('это',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('это', 'суђ')]},
      'SUFF': {'scores': [4.0], 'pairs': [('', 'еник')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.025),
    ('повешения',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('по', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('веш', 'суђ')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ени'], ['ен', 'ик']]},
      'END': {'scores': [0.6], 'pairs': [('я', 'е')]}}, 0.025),
    ('отступников',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('от', 'о')]},
      'ROOT': {'scores': [2.0], 'pairs': [('ступ', 'суђ')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ник'], ['ен', 'ик']]},
      'END': {'scores': [2.0], 'pairs': [('ов', 'е')]}}, 0.025),
    ('внизу',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('в', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('низ', 'суђ')]},
      'SUFF': {'scores': [4.0], 'pairs': [('', 'еник')]},
      'END': {'scores': [1.0], 'pairs': [('у', 'е')]}}, 0.025),
    ('но',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [2.6], 'pairs': [('но', 'суђ')]},
      'SUFF': {'scores': [4.0], 'pairs': [('', 'еник')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.025),
    ('его',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('его', 'суђ')]},
      'SUFF': {'scores': [4.0], 'pairs': [('', 'еник')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.025),
    ('преступника',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [5.0], 'pairs': [('преступ', 'суђ')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ник'], ['ен', 'ик']]},
      'END': {'scores': [1.0], 'pairs': [('а', 'е')]}}, 0.025),
    ('тем более', 'incorr'): ({}, 0.025),
    ('дальше',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.0], 'pairs': [('даль', 'суђ')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ш'], ['ен', 'ик']]},
      'END': {'scores': [0.0], 'pairs': [('е', 'е')]}}, 0.025),
    ('осужденного',
     'corr'): ({'PREF': {'scores': [0.0], 'pairs': [('о', 'о')]},
      'ROOT': {'scores': [2.0], 'pairs': [('сужд', 'суђ')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['енн'], ['ен', 'ик']]},
      'END': {'scores': [3.0], 'pairs': [('ого', 'е')]}}, 0.025),
    ('казнь',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'о')]},
      'ROOT': {'scores': [3.6], 'pairs': [('казнь', 'суђ')]},
      'SUFF': {'scores': [4.0], 'pairs': [('', 'еник')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.025)}},
  (115,
   'греческом',
   'грчком'): {'morph_comparison': {'ROOT': {'scores': [1.0],
     'pairs': [('греч', 'грч')]},
    'SUFF': {'scores': [2.0], 'pairs': [('еск', 'к')]},
    'END': {'scores': [0.0],
     'pairs': [('ом', 'ом')]}}, 'overall_stats': {'corr': 0.85,
    'explained_mistakes': 0.3714285714285714,
    'incorr': 0.1,
    'pcorr': 0.05}, 'word_stats': {('греческом',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('греч', 'грч')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'к')]},
      'END': {'scores': [0.0], 'pairs': [('ом', 'ом')]}},
     0.825),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'грч')]},
      'SUFF': {'scores': [1.0], 'pairs': [('', 'к')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ом')]}}, 0.1),
    ('грческих',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('грч', 'грч')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'к')]},
      'END': {'scores': [2.0], 'pairs': [('их', 'ом')]}}, 0.025),
    ('армянском',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('армян', 'грч')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'к')]},
      'END': {'scores': [0.0], 'pairs': [('ом', 'ом')]}}, 0.025),
    ('еврейском',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('еврей', 'грч')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'к')]},
      'END': {'scores': [0.0], 'pairs': [('ом', 'ом')]}}, 0.025)}},
  (116,
   'труба',
   'трубе'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('труб', 'труб')]},
    'END': {'scores': [1.0],
     'pairs': [('а', 'е')]}}, 'overall_stats': {'corr': 0.65,
    'explained_mistakes': 0.26666666666666655,
    'incorr': 0.2,
    'pcorr': 0.15}, 'word_stats': {('труба',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('труб', 'труб')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'е')]}}, 0.275),
    ('звук трубы', 'corr'): ({}, 0.25),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('', 'труб')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.125),
    ('трубы',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('труб', 'труб')]},
      'END': {'scores': [1.0], 'pairs': [('ы', 'е')]}}, 0.05),
    ('звук труб', 'corr'): ({}, 0.05),
    ('не спеша', 'incorr'): ({}, 0.025),
    ('приближался',
     'incorr'): ({'PREF': {'scores': [3.0], 'pairs': [('при', '')]},
      'ROOT': {'scores': [4.0], 'pairs': [('ближ', 'труб')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ал', '')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]},
      'POSTFIX': {'scores': [2.0], 'pairs': [('ся', '')]}}, 0.025),
    ('крик',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('крик', 'труб')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.025),
    ('запела труба', 'corr'): ({}, 0.025),
    ('так же', 'incorr'): ({}, 0.025),
    ('крики',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('крик', 'труб')]},
      'END': {'scores': [0.6], 'pairs': [('и', 'е')]}}, 0.025),
    ('звук',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('звук', 'труб')]},
      'END': {'scores': [1.0], 'pairs': [('', 'е')]}}, 0.025),
    ('трубный звук', 'pcorr'): ({}, 0.025),
    ('толпы',
     'pcorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('толп', 'труб')]},
      'END': {'scores': [1.0], 'pairs': [('ы', 'е')]}}, 0.025),
    ('крикунья',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('крик', 'труб')]},
      'SUFF': {'scores': [3.0], 'pairs': [('унь', '')]},
      'END': {'scores': [0.6], 'pairs': [('я', 'е')]}}, 0.025)}},
  (117,
   'весело',
   'весело'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('весел', 'весел')]},
    'END': {'scores': [0.0],
     'pairs': [('о', 'о')]}}, 'overall_stats': {'corr': 0.8,
    'incorr': 0.125,
    'pcorr': 0.075,
    'explained_mistakes': -1.75}, 'word_stats': {('весело',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('весел', 'весел')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.75),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'весел')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.1),
    ('громко',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('гром', 'весел')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.05),
    ('радостно',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('рад', 'весел')]},
      'SUFF': {'scores': [4.0], 'pairs': [('остн', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.05),
    ('радостная',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('рад', 'весел')]},
      'SUFF': {'scores': [4.0], 'pairs': [('остн', '')]},
      'END': {'scores': [2.0], 'pairs': [('ая', 'о')]}}, 0.025),
    ('тихо',
     'pcorr'): ({'ROOT': {'scores': [4.2], 'pairs': [('тих', 'весел')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.025)}},
  (121,
   'остановились',
   'зауставили'): {'morph_comparison': {'PREF': {'scores': [3.0],
     'pairs': [('', 'зау')]},
    'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},
    'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
    'END': {'scores': [0.0], 'pairs': [('и', 'и')]},
    'POSTFIX': {'scores': [2.0],
     'pairs': [('сь', '')]}}, 'overall_stats': {'incorr': 0.45,
    'corr': 0.35,
    'pcorr': 0.2,
    'explained_mistakes': -0.8}, 'word_stats': {('nan',
     'incorr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'зау')]},
      'ROOT': {'scores': [4.0], 'pairs': [('', 'став')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ил')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}},
     0.35),
    ('остановились',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'зау')]},
      'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]},
      'POSTFIX': {'scores': [2.0], 'pairs': [('сь', '')]}}, 0.2),
    ('остановился',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'зау')]},
      'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]},
      'POSTFIX': {'scores': [2.0], 'pairs': [('ся', '')]}}, 0.075),
    ('заговорили',
     'pcorr'): ({'PREF': {'scores': ['HANDCHECK'],
       'pairs': [['за'], ['за', 'у']]},
      'ROOT': {'scores': [5.0], 'pairs': [('говор', 'став')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]}}, 0.05),
    ('проехали',
     'pcorr'): ({'PREF': {'scores': ['HANDCHECK'],
       'pairs': [['про'], ['за', 'у']]},
      'ROOT': {'scores': [4.0], 'pairs': [('ех', 'став')]},
      'SUFF': {'scores': [1.0, 0.0], 'pairs': [('а', 'и'), ('л', 'л')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]}}, 0.025),
    ('пошел',
     'pcorr'): ({'PREF': {'scores': ['HANDCHECK'],
       'pairs': [['по'], ['за', 'у']]},
      'ROOT': {'scores': [4.0], 'pairs': [('ше', 'став')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['л'], ['и', 'л']]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.025),
    ('установилию',
     'pcorr'): ({'PREF': {'scores': ['HANDCHECK'],
       'pairs': [['у'], ['за', 'у']]},
      'ROOT': {'scores': [4.0], 'pairs': [('становил', 'став')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['и'], ['и', 'л']]},
      'END': {'scores': [1.0], 'pairs': [('ю', 'и')]}}, 0.025),
    ('полиции',
     'incorr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'зау')]},
      'ROOT': {'scores': [6.0], 'pairs': [('полици', 'став')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ил')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]}}, 0.025),
    ('остановились.',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('', 'зау')]},
      'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},

In [28]:
sk_stats = cognate_stats(slovak_ans, russian_true, slovak_true, sk_cognates, 'latin', num_type)
sk_stats

({(10,
   'повернулся',
   'sa obrátil'): {'morph_comparison': {'PREF': {'scores': [2.0],
     'pairs': [('по', 'об')]},
    'ROOT': {'scores': [3.0], 'pairs': [('вер', 'рат')]},
    'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['н', 'у', 'л'], ['и', 'л']]},
    'POSTFIX': {'scores': [1.0],
     'pairs': [('ся', 'са')]}}, 'overall_stats': {'corr': 0.5217391304347826,
    'pcorr': 0.30434782608695654,
    'incorr': 0.17391304347826086,
    'explained_mistakes': -0.09316770186335402}, 'word_stats': {('повернулся',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вер', 'рат')]},
      'SUFF': {'scores': [2.0, 0.0], 'pairs': [('ну', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [1.0], 'pairs': [('ся', 'са')]}},
     0.2898550724637681),
    ('обернулся',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('бер', 'рат')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['и', 'л']]},
      'POSTFIX': {'scores': [1.0],
       'pairs': [('ся', 'са')]}}, 0.2318840579710145),
    ('развернулся',
     'corr'): ({'PREF': {'scores': [3.0], 'pairs': [('раз', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вер', 'рат')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['и', 'л']]},
      'POSTFIX': {'scores': [1.0],
       'pairs': [('ся', 'са')]}}, 0.15942028985507245),
    ('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('', 'рат')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ил')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'са')]}}, 0.043478260869565216),
    ('обратился',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'об')]},
      'ROOT': {'scores': [2.0], 'pairs': [('обрат', 'рат')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [1.0],
       'pairs': [('ся', 'са')]}}, 0.028985507246376812),
    ('повернул',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вер', 'рат')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['и', 'л']]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'са')]}}, 0.028985507246376812),
    ('сообразил',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'об')]},
      'ROOT': {'scores': [5.0], 'pairs': [('сообраз', 'рат')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'са')]}}, 0.028985507246376812),
    ('осмотрелся',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'об')]},
      'ROOT': {'scores': [4.0], 'pairs': [('смотр', 'рат')]},
      'SUFF': {'scores': [0.6, 0.0], 'pairs': [('е', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [1.0],
       'pairs': [('ся', 'са')]}}, 0.028985507246376812),
    ('оглянулся',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('гля', 'рат')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['н', 'у', 'л'], ['и', 'л']]},
      'POSTFIX': {'scores': [1.0],
       'pairs': [('ся', 'са')]}}, 0.014492753623188406),
    ('обратился к скрещенной трибуне', 'incorr'): ({}, 0.014492753623188406),
    ('обратил',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'об')]},
      'ROOT': {'scores': [2.0], 'pairs': [('обрат', 'рат')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'са')]}}, 0.014492753623188406),
    ('вышел',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('вы', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('ше', 'рат')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['л'], ['и', 'л']]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'са')]}}, 0.014492753623188406),
    ('спустился',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('с', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('пуст', 'рат')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [1.0],
       'pairs': [('ся', 'са')]}}, 0.014492753623188406),
    ('повернулся(развернулся)',
     'corr'): ({'PREF': {'scores': ['HANDCHECK'],
       'pairs': [['по', 'раз'], ['об']]},
      'ROOT': {'scores': [5.0],
       'pairs': [('верлся', 'рат')]}}, 0.014492753623188406),
    ('заметил',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('за', 'об')]},
      'ROOT': {'scores': [2.0], 'pairs': [('мет', 'рат')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'са')]}}, 0.014492753623188406),
    ('посмотрел',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'об')]},
      'ROOT': {'scores': [4.0], 'pairs': [('смотр', 'рат')]},
      'SUFF': {'scores': [0.6, 0.0], 'pairs': [('е', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'са')]}}, 0.014492753623188406),
    ('повернуля',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вер', 'рат')]},
      'SUFF': {'scores': [1.0, 1.0], 'pairs': [('н', 'и'), ('ул', 'л')]},
      'END': {'scores': [1.0], 'pairs': [('я', '')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'са')]}}, 0.014492753623188406),
    ('взял',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('вз', 'рат')]},
      'SUFF': {'scores': [1.0, 0.0], 'pairs': [('я', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('', 'са')]}}, 0.014492753623188406),
    ('собрался',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('со', 'об')]},
      'ROOT': {'scores': [3.0], 'pairs': [('бр', 'рат')]},
      'SUFF': {'scores': [1.0, 0.0], 'pairs': [('а', 'и'), ('л', 'л')]},
      'POSTFIX': {'scores': [1.0],
       'pairs': [('ся', 'са')]}}, 0.014492753623188406)}},
  (113,
   'осужденных',
   'odsúdenci'): {'morph_comparison': {'PREF': {'scores': [1.0],
     'pairs': [('о', 'од')]},
    'ROOT': {'scores': [1.0], 'pairs': [('сужд', 'суд')]},
    'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['енн'], ['ен', 'ц']]},
    'END': {'scores': [2.0],
     'pairs': [('ых', 'и')]}}, 'overall_stats': {'corr': 0.5072463768115942,
    'incorr': 0.30434782608695654,
    'explained_mistakes': 0.21227621483375952,
    'pcorr': 0.18840579710144928}, 'word_stats': {('осужденных',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'од')]},
      'ROOT': {'scores': [1.0], 'pairs': [('сужд', 'суд')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['енн'], ['ен', 'ц']]},
      'END': {'scores': [2.0], 'pairs': [('ых', 'и')]}}, 0.2753623188405797),
    ('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('', 'суд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.10144927536231885),
    ('осуждённых',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'од')]},
      'ROOT': {'scores': [1.0], 'pairs': [('сужд', 'суд')]},
      'SUFF': {'scores': ['HANDCHECK'],
       'pairs': [['ён', 'н', 'ы'], ['ен', 'ц']]},
      'END': {'scores': [1.0], 'pairs': [('х', 'и')]}}, 0.08695652173913043),
    ('каторжников',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [5.6], 'pairs': [('каторж', 'суд')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ник'], ['ен', 'ц']]},
      'END': {'scores': [2.0], 'pairs': [('ов', 'и')]}}, 0.08695652173913043),
    ('заключенных',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [5.6], 'pairs': [('заключ', 'суд')]},
      'SUFF': {'scores': [1.0, 1.0], 'pairs': [('енн', 'ен'), ('ы', 'ц')]},
      'END': {'scores': [1.0], 'pairs': [('х', 'и')]}}, 0.043478260869565216),
    ('отсюда',
     'incorr'): ({'PREF': {'scores': [0.6], 'pairs': [('от', 'од')]},
      'ROOT': {'scores': [1.0], 'pairs': [('сюд', 'суд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'и')]}}, 0.043478260869565216),
    ('заключённых',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [5.6], 'pairs': [('заключ', 'суд')]},
      'SUFF': {'scores': [1.2, 1.0], 'pairs': [('ённ', 'ен'), ('ы', 'ц')]},
      'END': {'scores': [1.0], 'pairs': [('х', 'и')]}}, 0.028985507246376812),
    ('их',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [3.0], 'pairs': [('их', 'суд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.028985507246376812),
    ('каторжники',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [5.6], 'pairs': [('каторж', 'суд')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['ник'], ['ен', 'ц']]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]}}, 0.028985507246376812),
    ('осужденного',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'од')]},
      'ROOT': {'scores': [1.0], 'pairs': [('сужд', 'суд')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['енн'], ['ен', 'ц']]},
      'END': {'scores': [3.0],
       'pairs': [('ого', 'и')]}}, 0.028985507246376812),
    ('людей',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [2.0], 'pairs': [('люд', 'суд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [0.8], 'pairs': [('ей', 'и')]}}, 0.014492753623188406),
    ('судей',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [0.0], 'pairs': [('суд', 'суд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [0.8], 'pairs': [('ей', 'и')]}}, 0.014492753623188406),
    ('подсудимых',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('под', 'од')]},
      'ROOT': {'scores': [0.0], 'pairs': [('суд', 'суд')]},
      'SUFF': {'scores': ['HANDCHECK'], 'pairs': [['им'], ['ен', 'ц']]},
      'END': {'scores': [2.0], 'pairs': [('ых', 'и')]}}, 0.014492753623188406),
    ('теперь',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [5.0], 'pairs': [('теперь', 'суд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.014492753623188406),
    ('однако',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [4.6], 'pairs': [('однак', 'суд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('о', 'и')]}}, 0.014492753623188406),
    ('очевидцы?',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [5.0],
       'pairs': [('очевид', 'суд')]}}, 0.014492753623188406),
    ('осужденные уже исчезли из поля видимости', 'corr'): ({},
     0.014492753623188406),
    ('осуждённого',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', 'од')]},
      'ROOT': {'scores': [1.0], 'pairs': [('сужд', 'суд')]},
      'SUFF': {'scores': [0.2, 1.0], 'pairs': [('ён', 'ен'), ('н', 'ц')]},
      'END': {'scores': [3.0],
       'pairs': [('ого', 'и')]}}, 0.014492753623188406),
    ('поэтому',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('по', 'од')]},
      'ROOT': {'scores': [2.6], 'pairs': [('эт', 'суд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [3.0],
       'pairs': [('ому', 'и')]}}, 0.014492753623188406),
    ('боль',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'од')]},
      'ROOT': {'scores': [2.6], 'pairs': [('боль', 'суд')]},
      'SUFF': {'scores': [3.0], 'pairs': [('', 'енц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.014492753623188406),
    ('отступили',
     'incorr'): ({'PREF': {'scores': [0.6], 'pairs': [('от', 'од')]},
      'ROOT': {'scores': [2.0], 'pairs': [('ступ', 'суд')]},
      'SUFF': {'scores': [1.6, 1.0], 'pairs': [('и', 'ен'), ('л', 'ц')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]}}, 0.014492753623188406),
    ('к сожалению', 'incorr'): ({}, 0.014492753623188406),
    ('кто вокруг', 'incorr'): ({}, 0.014492753623188406),
    ('одним глазом', 'incorr'): ({}, 0.014492753623188406),
    ('трибуну за хребтом', 'pcorr'): ({}, 0.014492753623188406),
    ('успокоился',
     'incorr'): ({'PREF': {'scores': [1.6], 'pairs': [('у', 'од')]},
      'ROOT': {'scores': [3.6], 'pairs': [('споко', 'суд')]},
      'SUFF': {'scores': [1.6, 1.0], 'pairs': [('и', 'ен'), ('л', 'ц')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.014492753623188406),
    ('но из за болезни', 'incorr'): ({}, 0.014492753623188406)}},
  (115,
   'греческом',
   'grécky'): {'morph_comparison': {'ROOT': {'scores': [2.6],
     'pairs': [('греч', 'грэцк')]},
    'SUFF': {'scores': [2.0], 'pairs': [('еск', 'цк')]},
    'END': {'scores': [2.0],
     'pairs': [('ом', 'ы')]}}, 'overall_stats': {'corr': 0.8260869565217391,
    'explained_mistakes': 0.3623188405797101,
    'incorr': 0.10144927536231885,
    'pcorr': 0.07246376811594203}, 'word_stats': {('греческом',
     'corr'): ({'ROOT': {'scores': [2.6], 'pairs': [('греч', 'грэцк')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'ы')]}}, 0.7101449275362319),
    ('греческих',
     'corr'): ({'ROOT': {'scores': [2.6], 'pairs': [('греч', 'грэцк')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('их', 'ы')]}}, 0.10144927536231885),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'грэцк')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'цк')]},
      'END': {'scores': [1.0], 'pairs': [('', 'ы')]}}, 0.07246376811594203),
    ('грецких',
     'pcorr'): ({'ROOT': {'scores': [2.0], 'pairs': [('грец', 'грэцк')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('их', 'ы')]}}, 0.028985507246376812),
    ('грецком',
     'pcorr'): ({'ROOT': {'scores': [2.0], 'pairs': [('грец', 'грэцк')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'ы')]}}, 0.014492753623188406),
    ('арамейских',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('арамей', 'грэцк')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('их', 'ы')]}}, 0.014492753623188406),
    ('герцек',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('герцек', 'грэцк')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'цк')]},
      'END': {'scores': [1.0], 'pairs': [('', 'ы')]}}, 0.014492753623188406),
    ('жаргоне',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('жаргон', 'грэцк')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'цк')]},
      'END': {'scores': [1.0], 'pairs': [('е', 'ы')]}}, 0.014492753623188406),
    ('греческим',
     'corr'): ({'ROOT': {'scores': [2.6], 'pairs': [('греч', 'грэцк')]},
      'SUFF': {'scores': [2.0], 'pairs': [('еск', 'цк')]},
      'END': {'scores': [2.0], 'pairs': [('им', 'ы')]}}, 0.014492753623188406),
    ('славянских',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('славян', 'грэцк')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ск', 'цк')]},
      'END': {'scores': [2.0],
       'pairs': [('их', 'ы')]}}, 0.014492753623188406)}},
  (117,
   'весело',
   'veselo'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('весел', 'весел')]},
    'END': {'scores': [0.0],
     'pairs': [('о', 'о')]}}, 'overall_stats': {'corr': 0.7971014492753623,
    'pcorr': 0.13043478260869565,
    'incorr': 0.07246376811594203,
    'explained_mistakes': -0.5942028985507246}, 'word_stats': {('весело',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('весел', 'весел')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}},
     0.7681159420289855),
    ('громко',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('гром', 'весел')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.07246376811594203),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'весел')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.057971014492753624),
    ('звонко',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('звон', 'весел')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.014492753623188406),
    ('задорно',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('за', '')]},
      'ROOT': {'scores': [5.0], 'pairs': [('дор', 'весел')]},
      'SUFF': {'scores': [1.0], 'pairs': [('н', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.014492753623188406),
    ('тихо',
     'pcorr'): ({'ROOT': {'scores': [4.2], 'pairs': [('тих', 'весел')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.014492753623188406),
    ('хрипло',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('хрип', 'весел')]},
      'SUFF': {'scores': [1.0], 'pairs': [('л', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.014492753623188406),
    ('сильно',
     'pcorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('силь', 'весел')]},
      'SUFF': {'scores': [1.0], 'pairs': [('н', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.014492753623188406),
    ('резко',
     'pcorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('рез', 'весел')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.014492753623188406),
    ('аплодировал',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('аплод', 'весел')]},
      'SUFF': {'scores': [6.0], 'pairs': [('ировал', '')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.014492753623188406)}},
  (121,
   'остановились',
   'sa zastavili'): {'morph_comparison': {'PREF': {'scores': [2.0],
     'pairs': [('', 'за')]},
    'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},
    'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
    'END': {'scores': [0.0], 'pairs': [('и', 'и')]},
    'POSTFIX': {'scores': [0.0],
     'pairs': [('сь',
       'са')]}}, 'overall_stats': {'incorr': 0.43478260869565216,
    'corr': 0.391304347826087,
    'pcorr': 0.17391304347826086,
    'explained_mistakes': -0.7391304347826086}, 'word_stats': {('nan',
     'incorr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'за')]},
      'ROOT': {'scores': [4.0], 'pairs': [('', 'став')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ил')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]},
      'POSTFIX': {'scores': [2.0], 'pairs': [('', 'са')]}},
     0.391304347826087),
    ('остановились',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'за')]},
      'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]},
      'POSTFIX': {'scores': [0.0],
       'pairs': [('сь', 'са')]}}, 0.30434782608695654),
    ('остановился',
     'corr'): ({'PREF': {'scores': [2.0], 'pairs': [('', 'за')]},
      'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]},
      'POSTFIX': {'scores': [1.0],
       'pairs': [('ся', 'са')]}}, 0.043478260869565216),
    ('встали',

In [29]:
sn_stats = cognate_stats(slovene_ans, russian_true, slovene_true, sn_cognates, 'latin', num_type)
sn_stats

({(11,
   'ступеням',
   'stopnicam'): {'morph_comparison': {'ROOT': {'scores': [1.6],
     'pairs': [('ступен', 'стопн')]},
    'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
    'END': {'scores': [1.0],
     'pairs': [('ям', 'ам')]}}, 'overall_stats': {'corr': 0.6216216216216216,
    'pcorr': 0.1891891891891892,
    'incorr': 0.1891891891891892,
    'explained_mistakes': -1.0810810810810811}, 'word_stats': {('лестнице',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('лест', 'стопн')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ниц', 'иц')]},
      'END': {'scores': [2.0], 'pairs': [('е', 'ам')]}},
     0.32432432432432434),
    ('ступеням',
     'corr'): ({'ROOT': {'scores': [1.6], 'pairs': [('ступен', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ям', 'ам')]}}, 0.21621621621621623),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ам')]}}, 0.10810810810810811),
    ('ступенькам',
     'corr'): ({'ROOT': {'scores': [1.6], 'pairs': [('ступ', 'стопн')]},
      'SUFF': {'scores': [2.6], 'pairs': [('еньк', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.05405405405405406),
    ('воротам',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('ворот', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.05405405405405406),
    ('дворцу',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('двор', 'стопн')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ц', 'иц')]},
      'END': {'scores': [2.0], 'pairs': [('у', 'ам')]}}, 0.05405405405405406),
    ('горе',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('гор', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [2.0], 'pairs': [('е', 'ам')]}}, 0.02702702702702703),
    ('сходням',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('с', '')]},
      'ROOT': {'scores': [4.0], 'pairs': [('ход', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('н', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ям', 'ам')]}}, 0.02702702702702703),
    ('себе',
     'incorr'): ({'ROOT': {'scores': [3.6], 'pairs': [('себе', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ам')]}}, 0.02702702702702703),
    ('гостям',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('гост', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ям', 'ам')]}}, 0.02702702702702703),
    ('стенам',
     'pcorr'): ({'ROOT': {'scores': [2.0], 'pairs': [('стен', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.02702702702702703),
    ('нему',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('нему', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ам')]}}, 0.02702702702702703),
    ('стопницам',
     'incorr'): ({'ROOT': {'scores': [1.0], 'pairs': [('стоп', 'стопн')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ниц', 'иц')]},
      'END': {'scores': [0.0],
       'pairs': [('ам', 'ам')]}}, 0.02702702702702703)}},
  (15,
   'чудо',
   'čudo'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('чуд', 'чуд')]},
    'END': {'scores': [0.0],
     'pairs': [('о', 'о')]}}, 'overall_stats': {'corr': 0.8108108108108109,
    'explained_mistakes': 0.4054054054054054,
    'incorr': 0.13513513513513514,
    'pcorr': 0.05405405405405406}, 'word_stats': {('чудо',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('чуд', 'чуд')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.8108108108108109),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('', 'чуд')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.05405405405405406),
    ('видели',
     'incorr'): ({'ROOT': {'scores': [2.0], 'pairs': [('вид', 'чуд')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ел', '')]},
      'END': {'scores': [1.0], 'pairs': [('и', 'о')]}}, 0.02702702702702703),
    ('это',
     'incorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('это', 'чуд')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.02702702702702703),
    ('казнь',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('казнь', 'чуд')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.02702702702702703),
    ('войну',
     'pcorr'): ({'ROOT': {'scores': [2.6], 'pairs': [('вой', 'чуд')]},
      'SUFF': {'scores': [1.0], 'pairs': [('н', '')]},
      'END': {'scores': [0.6], 'pairs': [('у', 'о')]}}, 0.02702702702702703),
    ('всё то', 'incorr'): ({}, 0.02702702702702703)}},
  (111,
   'ступеням',
   'stopnicam'): {'morph_comparison': {'ROOT': {'scores': [1.6],
     'pairs': [('ступен', 'стопн')]},
    'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
    'END': {'scores': [1.0],
     'pairs': [('ям', 'ам')]}}, 'overall_stats': {'corr': 0.5135135135135135,
    'pcorr': 0.32432432432432434,
    'incorr': 0.16216216216216217,
    'explained_mistakes': -0.42702702702702716}, 'word_stats': {('ступеням',
     'corr'): ({'ROOT': {'scores': [1.6], 'pairs': [('ступен', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ям', 'ам')]}},
     0.3783783783783784),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ам')]}}, 0.13513513513513514),
    ('лестницам',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('лест', 'стопн')]},
      'SUFF': {'scores': [1.0], 'pairs': [('ниц', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.10810810810810811),
    ('воротам',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('ворот', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.10810810810810811),
    ('дверям',
     'pcorr'): ({'ROOT': {'scores': [4.6], 'pairs': [('двер', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [1.0], 'pairs': [('ям', 'ам')]}}, 0.08108108108108109),
    ('ступенькам',
     'corr'): ({'ROOT': {'scores': [1.6], 'pairs': [('ступ', 'стопн')]},
      'SUFF': {'scores': [2.6], 'pairs': [('еньк', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.02702702702702703),
    ('тратуарам',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('тратуар', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.02702702702702703),
    ('стенам',
     'pcorr'): ({'ROOT': {'scores': [2.0], 'pairs': [('стен', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.02702702702702703),
    ('колоннам',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('колон', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('н', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.02702702702702703),
    ('мостам',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('мост', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.02702702702702703),
    ('местам',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('мест', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [0.0], 'pairs': [('ам', 'ам')]}}, 0.02702702702702703),
    ('столбам',
     'pcorr'): ({'ROOT': {'scores': [2.0], 'pairs': [('столб', 'стопн')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'иц')]},
      'END': {'scores': [0.0],
       'pairs': [('ам', 'ам')]}}, 0.02702702702702703)}},
  (115,
   'греческом',
   'grščini'): {'morph_comparison': {'ROOT': {'scores': [1.0],
     'pairs': [('греч', 'гршч')]},
    'SUFF': {'scores': [2.6], 'pairs': [('еск', 'ин')]},
    'END': {'scores': [2.0],
     'pairs': [('ом', 'и')]}}, 'overall_stats': {'corr': 0.6486486486486487,
    'pcorr': 0.21621621621621623,
    'explained_mistakes': 0.15057915057915053,
    'incorr': 0.13513513513513514}, 'word_stats': {('греческом',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('греч', 'гршч')]},
      'SUFF': {'scores': [2.6], 'pairs': [('еск', 'ин')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'и')]}}, 0.5675675675675675),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('', 'гршч')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ин')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.13513513513513514),
    ('греческих',
     'corr'): ({'ROOT': {'scores': [1.0], 'pairs': [('греч', 'гршч')]},
      'SUFF': {'scores': [2.6], 'pairs': [('еск', 'ин')]},
      'END': {'scores': [1.0], 'pairs': [('их', 'и')]}}, 0.08108108108108109),
    ('иностранных',
     'pcorr'): ({'ROOT': {'scores': [7.0],
       'pairs': [('иностран', 'гршч')]}}, 0.05405405405405406),
    ('арамейских',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('арамей', 'гршч')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ск', 'ин')]},
      'END': {'scores': [1.0], 'pairs': [('их', 'и')]}}, 0.02702702702702703),
    ('латинском',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('латин', 'гршч')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ск', 'ин')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'и')]}}, 0.02702702702702703),
    ('египетском',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('египет', 'гршч')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ск', 'ин')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'и')]}}, 0.02702702702702703),
    ('разных',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('раз', 'гршч')]},
      'SUFF': {'scores': [1.0], 'pairs': [('н', 'ин')]},
      'END': {'scores': [2.0], 'pairs': [('ых', 'и')]}}, 0.02702702702702703),
    ('городском',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('город', 'гршч')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ск', 'ин')]},
      'END': {'scores': [2.0], 'pairs': [('ом', 'и')]}}, 0.02702702702702703),
    ('других',
     'pcorr'): ({'ROOT': {'scores': [3.0], 'pairs': [('друг', 'гршч')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ин')]},
      'END': {'scores': [1.0],
       'pairs': [('их', 'и')]}}, 0.02702702702702703)}},
  (116,
   'труба',
   'trobento'): {'morph_comparison': {'ROOT': {'scores': [3.6],
     'pairs': [('труб', 'тробент')]},
    'END': {'scores': [1.0],
     'pairs': [('а', 'о')]}}, 'overall_stats': {'corr': 0.3783783783783784,
    'incorr': 0.35135135135135137,
    'pcorr': 0.2702702702702703,
    'explained_mistakes': -0.28828828828828845}, 'word_stats': {('nan',
     'incorr'): ({'ROOT': {'scores': [7.0], 'pairs': [('', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}},
     0.35135135135135137),
    ('труба',
     'corr'): ({'ROOT': {'scores': [3.6], 'pairs': [('труб', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'о')]}}, 0.21621621621621623),
    ('треск',
     'pcorr'): ({'ROOT': {'scores': [4.0], 'pairs': [('треск', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.05405405405405406),
    ('труб',
     'corr'): ({'ROOT': {'scores': [3.6], 'pairs': [('труб', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.05405405405405406),
    ('трубу',
     'corr'): ({'ROOT': {'scores': [3.6], 'pairs': [('труб', 'тробент')]},
      'END': {'scores': [0.6], 'pairs': [('у', 'о')]}}, 0.02702702702702703),
    ('свист',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('свист', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.02702702702702703),
    ('конница',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('кон', 'тробент')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ниц', '')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'о')]}}, 0.02702702702702703),
    ('колесница',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('колес', 'тробент')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ниц', '')]},
      'END': {'scores': [1.0], 'pairs': [('а', 'о')]}}, 0.02702702702702703),
    ('рёв',
     'pcorr'): ({'ROOT': {'scores': [5.2], 'pairs': [('рёв', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.02702702702702703),
    ('трубы',
     'corr'): ({'ROOT': {'scores': [3.6], 'pairs': [('труб', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('ы', 'о')]}}, 0.02702702702702703),
    ('гул',
     'pcorr'): ({'ROOT': {'scores': [6.6], 'pairs': [('гул', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.02702702702702703),
    ('ржание',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('рж', 'тробент')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ани', '')]},
      'END': {'scores': [1.0], 'pairs': [('е', 'о')]}}, 0.02702702702702703),
    ('рожком',
     'corr'): ({'ROOT': {'scores': [5.0], 'pairs': [('рож', 'тробент')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [1.0], 'pairs': [('ом', 'о')]}}, 0.02702702702702703),
    ('звук трубы', 'corr'): ({}, 0.02702702702702703),
    ('шум',
     'pcorr'): ({'ROOT': {'scores': [6.6], 'pairs': [('шум', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.02702702702702703),
    ('крик',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('крик', 'тробент')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.02702702702702703)}},
  (117,
   'весело',
   'veselo'): {'morph_comparison': {'ROOT': {'scores': [0.0],
     'pairs': [('весел', 'весел')]},
    'END': {'scores': [0.0],
     'pairs': [('о', 'о')]}}, 'overall_stats': {'corr': 0.7837837837837838,
    'incorr': 0.10810810810810811,
    'pcorr': 0.10810810810810811,
    'explained_mistakes': -1.3783783783783785}, 'word_stats': {('весело',
     'corr'): ({'ROOT': {'scores': [0.0], 'pairs': [('весел', 'весел')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}},
     0.7837837837837838),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('', 'весел')]},
      'END': {'scores': [1.0], 'pairs': [('', 'о')]}}, 0.10810810810810811),
    ('неистово',
     'pcorr'): ({'PREF': {'scores': [2.0], 'pairs': [('не', '')]},
      'ROOT': {'scores': [3.6], 'pairs': [('ист', 'весел')]},
      'SUFF': {'scores': [2.0], 'pairs': [('ов', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.02702702702702703),
    ('громко',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('гром', 'весел')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.02702702702702703),
    ('робко',
     'pcorr'): ({'ROOT': {'scores': [5.0], 'pairs': [('роб', 'весел')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [0.0], 'pairs': [('о', 'о')]}}, 0.02702702702702703),
    ('оглушающе',
     'pcorr'): ({'PREF': {'scores': [1.0], 'pairs': [('о', '')]},
      'ROOT': {'scores': [5.0], 'pairs': [('глуш', 'весел')]},
      'SUFF': {'scores': [3.0], 'pairs': [('ающ', '')]},
      'END': {'scores': [1.0], 'pairs': [('е', 'о')]}}, 0.02702702702702703)}},
  (120,
   'значком',
   'znamenjem'): {'morph_comparison': {'ROOT': {'scores': [4.0],
     'pairs': [('знач', 'знаменй')]},
    'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
    'END': {'scores': [1.0],
     'pairs': [('ом',
       'ем')]}}, 'overall_stats': {'explained_mistakes': 0.6340956340956341,
    'pcorr': 0.5675675675675675,
    'corr': 0.32432432432432434,
    'incorr': 0.10810810810810811}, 'word_stats': {('знаменем',
     'pcorr'): ({'ROOT': {'scores': [1.0], 'pairs': [('знамен', 'знаменй')]},
      'END': {'scores': [0.0], 'pairs': [('ем', 'ем')]}}, 0.5135135135135135),
    ('знаком',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('знак', 'знаменй')]},
      'END': {'scores': [1.0], 'pairs': [('ом', 'ем')]}}, 0.10810810810810811),
    ('божьим знаменем', 'corr'): ({}, 0.08108108108108109),
    ('значком',
     'corr'): ({'ROOT': {'scores': [4.0], 'pairs': [('знач', 'знаменй')]},
      'SUFF': {'scores': [1.0], 'pairs': [('к', '')]},
      'END': {'scores': [1.0], 'pairs': [('ом', 'ем')]}}, 0.08108108108108109),
    ('боевым знаком', 'corr'): ({}, 0.05405405405405406),
    ('nan',
     'incorr'): ({'ROOT': {'scores': [7.0], 'pairs': [('', 'знаменй')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ем')]}}, 0.05405405405405406),
    ('свечой',
     'pcorr'): ({'ROOT': {'scores': [5.6], 'pairs': [('свеч', 'знаменй')]},
      'END': {'scores': [2.0], 'pairs': [('ой', 'ем')]}}, 0.02702702702702703),
    ('прокуратор',
     'incorr'): ({'ROOT': {'scores': [7.0], 'pairs': [('прокур', 'знаменй')]},
      'SUFF': {'scores': [4.0], 'pairs': [('атор', '')]},
      'END': {'scores': [2.0], 'pairs': [('', 'ем')]}}, 0.02702702702702703),
    ('спицей',
     'incorr'): ({'ROOT': {'scores': [6.2], 'pairs': [('спиц', 'знаменй')]},
      'END': {'scores': [1.0], 'pairs': [('ей', 'ем')]}}, 0.02702702702702703),
    ('ломом',
     'pcorr'): ({'ROOT': {'scores': [6.0], 'pairs': [('лом', 'знаменй')]},
      'END': {'scores': [1.0],
       'pairs': [('ом', 'ем')]}}, 0.02702702702702703)}},
  (121,
   'остановились',
   'ustavili'): {'morph_comparison': {'PREF': {'scores': [1.0],
     'pairs': [('', 'у')]},
    'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},
    'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
    'END': {'scores': [0.0], 'pairs': [('и', 'и')]},
    'POSTFIX': {'scores': [2.0],
     'pairs': [('сь', '')]}}, 'overall_stats': {'corr': 0.5675675675675675,
    'incorr': 0.35135135135135137,
    'pcorr': 0.08108108108108109,
    'explained_mistakes': -0.4054054054054055}, 'word_stats': {('остановились',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'у')]},
      'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]},
      'POSTFIX': {'scores': [2.0], 'pairs': [('сь', '')]}},
     0.4864864864864865),
    ('nan',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'у')]},
      'ROOT': {'scores': [4.0], 'pairs': [('', 'став')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ил')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]}}, 0.13513513513513514),
    ('поставили',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'у')]},
      'ROOT': {'scores': [2.0], 'pairs': [('постав', 'став')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'END': {'scores': [0.0], 'pairs': [('и', 'и')]}}, 0.05405405405405406),
    ('остановился',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'у')]},
      'ROOT': {'scores': [3.0], 'pairs': [('останов', 'став')]},
      'SUFF': {'scores': [0.0, 0.0], 'pairs': [('и', 'и'), ('л', 'л')]},
      'END': {'scores': [1.0], 'pairs': [('', 'и')]},
      'POSTFIX': {'scores': [2.0],
       'pairs': [('ся', '')]}}, 0.02702702702702703),
    ('охраны',
     'incorr'): ({'PREF': {'scores': [0.6], 'pairs': [('о', 'у')]},
      'ROOT': {'scores': [3.0], 'pairs': [('хран', 'став')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ил')]},
      'END': {'scores': [1.0], 'pairs': [('ы', 'и')]}}, 0.02702702702702703),
    ('короля',
     'incorr'): ({'PREF': {'scores': [1.0], 'pairs': [('', 'у')]},
      'ROOT': {'scores': [5.0], 'pairs': [('корол', 'став')]},
      'SUFF': {'scores': [2.0], 'pairs': [('', 'ил')]},
      'END': {'scores': [1.0], 'pairs': [('я', 'и')]}}, 0.02702702702702703),
    ('встали',
     'corr'): ({'PREF': {'scores': [1.0], 'pairs': [('в', 'у')]},

In [30]:
import pandas as pd
import numpy as np

def dict_to_dataframe(data):
    rows = []
    
    for key, value in data.items():
        row = {
            'pair': f"{key[0]}, '{key[1]}', '{key[2]}'"
        }
        
        overall = value.get('overall_stats', {})
        row['explained_mistakes'] = overall.get('explained_mistakes', 0.0)
        
        morph = value.get('morph_comparison', {})
        morph_categories = ['PREF', 'ROOT', 'LINK', 'SUFF', 'END', 'POSTFIX']
        
        for category in morph_categories:
            if category in morph:
                row[category] = morph[category].get('scores', [0.0])
            else:
                row[category] = [0.0]
        
        rows.append(row)
    
    df = pd.DataFrame(rows)
    
    columns_order = ['pair'] + morph_categories + ['explained_mistakes']
    df = df[columns_order]
    
    return df

ukr_true_df = dict_to_dataframe(ukr_stats[0])
ukr_true_df

,pair,PREF,ROOT,LINK,SUFF,END,POSTFIX,explained_mistakes
0,"10, 'повернулся', 'повернувся'",[0.0],[0.0],[0.0],"[0.0, 0.0, 1.0]",[0.0],[0.0],0.000000
1,"12, 'шашек', 'шашок'",[0.0],[0.0],[0.0],[1.0],[0.0],[0.0],-2.087719
2,"13, 'спиною', 'спиною'",[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],0.000000
3,"14, 'финики', 'фініки'",[0.0],[0.4],[0.0],[0.0],[0.0],[0.0],0.748284
4,"16, 'вырвался', 'вирвався'",[1.0],[0.0],[0.0],"[0.0, 1.0]",[0.0],[0.0],0.768421
...,...,...,...,...,...,...,...,...
121,"630, 'заговорил', 'заговорив'",[0.0],[0.0],[0.0],"[0.0, 1.0]",[0.0],[0.0],0.000000
122,"631, 'присутствовал', 'присутній'",[0.0],[3.0],[0.0],[HANDCHECK],[2.0],[0.0],0.000000
123,"632, 'балконе', 'балконі'",[0.0],[0.0],[0.0],[0.0],[0.6],[0.0],0.867868
124,"633, 'тайно', 'таємно'",[0.0],[2.0],[0.0],[0.0],[0.0],[0.0],0.817048
125,"634, 'секрет', 'секрет'",[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],0.908524

In [31]:
ukr_true_df.to_csv(
    'ukr_true.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)

In [32]:
bel_true_df = dict_to_dataframe(bel_stats[0])
bel_true_df.to_csv(
    'bel_true.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)

cz_true_df = dict_to_dataframe(cz_stats[0])
cz_true_df.to_csv(
    'cz_true.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
pol_true_df = dict_to_dataframe(pol_stats[0])
pol_true_df.to_csv(
    'pol_true.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
bg_true_df = dict_to_dataframe(bg_stats[0])
bg_true_df.to_csv(
    'bg_true.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
sn_true_df = dict_to_dataframe(sn_stats[0])
sn_true_df.to_csv(
    'sn_true.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
sk_true_df = dict_to_dataframe(sk_stats[0])
sk_true_df.to_csv(
    'sk_true.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
sb_true_df = dict_to_dataframe(sb_stats[0])
sb_true_df.to_csv(
    'sb_true.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)

In [33]:
import pandas as pd
import numpy as np

def alternate_to_dataframe(data):
    rows = []
    
    for key, value in data.items():
        code = key[0]
        original = key[2]
        overall = value.get('overall_stats', {})
        explained_mistakes = overall.get('explained_mistakes', 0.0)
        for key1, value1 in value['word_stats'].items():
            row = {
                'pair': f"{code}, '{key1[0]}', '{original}'"
            }
            row['explained_mistakes'] = explained_mistakes
            morph = value1[0]
            morph_categories = ['PREF', 'ROOT', 'LINK', 'SUFF', 'END', 'POSTFIX']
            
            for category in morph_categories:
                if category in morph:
                    row[category] = morph[category].get('scores', [0.0])
                else:
                    row[category] = [0.0]
            
            rows.append(row)
    
    df = pd.DataFrame(rows)
    
    columns_order = ['pair'] + morph_categories + ['explained_mistakes']
    df = df[columns_order]
    
    return df

ukr_part1_df = alternate_to_dataframe(ukr_stats[1])
ukr_part1_df

,pair,PREF,ROOT,LINK,SUFF,END,POSTFIX,explained_mistakes
0,"11, 'ступенькам', 'сходинок'",[1.0],[3.6],[0.0],[HANDCHECK],[2.0],[0.0],-1.605263
1,"11, 'nan', 'сходинок'",[1.0],[3.0],[0.0],[4.0],[0.0],[0.0],-1.605263
2,"11, 'ступеням', 'сходинок'",[1.0],[5.6],[0.0],[4.0],[2.0],[0.0],-1.605263
3,"11, 'сходням', 'сходинок'",[0.0],[0.0],[0.0],[HANDCHECK],[2.0],[0.0],-1.605263
4,"11, 'лестнице', 'сходинок'",[1.0],[3.6],[0.0],[HANDCHECK],[1.0],[0.0],-1.605263
...,...,...,...,...,...,...,...,...
788,"628, 'прилипли', 'понахилялися'",[HANDCHECK],[2.0],[0.0],[HANDCHECK],[0.0],[2.0],-1.972973
789,"628, 'граждане', 'понахилялися'",[4.0],[4.6],[0.0],[HANDCHECK],[0.6],[2.0],-1.972973
790,"628, 'nan', 'понахилялися'",[4.0],[3.0],[0.0],[2.0],[1.0],[2.0],-1.972973
791,"628, 'что понаехали', 'понахилялися'",[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],-1.972973
792,"628, 'прижавшись', 'понахилялися'",[HANDCHECK],[3.0],[0.0],[HANDCHECK],[1.0],[0.0],-1.972973

In [34]:
ukr_part1_df.to_csv(
    'ukr_part11.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)

bel_part1_df = alternate_to_dataframe(bel_stats[1])
bel_part1_df.to_csv(
    'bel_part11.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)

In [35]:
bg_part1_df = alternate_to_dataframe(bg_stats[1])
bg_part1_df.to_csv(
    'bg_part11.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
pol_part1_df = alternate_to_dataframe(pol_stats[1])
pol_part1_df.to_csv(
    'pol_part11.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
cz_part1_df = alternate_to_dataframe(cz_stats[1])
cz_part1_df.to_csv(
    'cz_part11.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
sb_part1_df = alternate_to_dataframe(sb_stats[1])
sb_part1_df.to_csv(
    'sb_part11.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
sn_part1_df = alternate_to_dataframe(sn_stats[1])
sn_part1_df.to_csv(
    'sn_part11.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)
sk_part1_df = alternate_to_dataframe(sk_stats[1])
sk_part1_df.to_csv(
    'sk_part11.csv',
    index=False,
    encoding='utf-8',
    sep=',',
    header=True
)

In [36]:
def transform_morpheme_dataframe(filepath):
    
    df = pd.read_csv(filepath)

    def safe_eval_list(val, default_len=3):
        if pd.isna(val) or val == '' or val == '[]':
            return [0] * default_len
        try:
            if isinstance(val, str):
                val = val.replace("'", '"')
                parsed = ast.literal_eval(val)
                if isinstance(parsed, list):
                    return parsed + [0] * (default_len - len(parsed))
                else:
                    return [parsed] + [0] * (default_len - 1)
            elif isinstance(val, list):
                return val + [0] * (default_len - len(val))
            else:
                return [val] + [0] * (default_len - 1)
        except:
            return [0] * default_len
    
    def safe_eval_single(val):
        if pd.isna(val) or val == '' or val == '[]':
            return 0
        try:
            if isinstance(val, str):
                val = val.replace("'", '"')
                parsed = ast.literal_eval(val)
                if isinstance(parsed, list):
                    return parsed[0] if parsed else 0
                else:
                    return parsed
            else:
                return val
        except:
            return 0
    
    new_data = []
    
    for idx, row in df.iterrows():
        new_row = {
            'pair': row['pair'],
            'explained_mistakes': row['explained_mistakes']
        }
        
        pref_list = safe_eval_list(row['PREF'], 2)
        new_row['PREF1'] = pref_list[0]
        new_row['PREF2'] = pref_list[1]
        
        root_list = safe_eval_list(row['ROOT'], 2)
        new_row['ROOT1'] = root_list[0]
        new_row['ROOT2'] = root_list[1]

        new_row['LINK'] = safe_eval_single(row['LINK'])
        
        suff_list = safe_eval_list(row['SUFF'], 3)
        new_row['SUFF1'] = suff_list[0]
        new_row['SUFF2'] = suff_list[1]
        new_row['SUFF3'] = suff_list[2]
        
        new_row['END'] = safe_eval_single(row['END'])
        
        new_row['POSTFIX'] = safe_eval_single(row['POSTFIX'])
        
        new_data.append(new_row)
    
    new_df = pd.DataFrame(new_data)
    
    columns_order = ['pair', 'PREF1', 'PREF2', 'ROOT1', 'ROOT2', 'LINK', 
                     'SUFF1', 'SUFF2', 'SUFF3', 'END', 'POSTFIX', 
                     'explained_mistakes']
    new_df = new_df[columns_order]
    
    return new_df